import type { RawTerm } from "../types";

export const aestheticTerms: RawTerm[] = [
  {
    slug: "aesthetic", term: "Aesthetic", pron: "es-THET-ik", pos: "noun", cat: "aesthetic",
    year: 2014, pop: 74, trend: 1, status: "mainstream",
    def: "A named visual and emotional style treated as an identity you can adopt wholesale, complete with palette, wardrobe, soundtrack and implied way of living.",
    eli: "A named look and mood you can choose for yourself, like a theme for your whole life.",
    org: "Tumblr repurposed the philosophical term in the mid-2010s. Pinterest and TikTok industrialised it, and the Aesthetics Wiki now catalogues thousands of named styles.",
    ex: ["The whole flat is committed to one aesthetic.", "Naming an aesthetic is the first step to selling it."],
    rel: ["core-suffix", "moodboard", "vibe"], tags: ["tumblr", "identity", "style"],
  },
  {
    slug: "core-suffix", term: "-core", pron: "kor", pos: "suffix", cat: "aesthetic",
    year: 2013, pop: 69, trend: 4, status: "mainstream",
    def: "A productive suffix converting almost any noun into a named aesthetic, as in cottagecore or goblincore. Attaches to anything and remains instantly legible.",
    eli: "An ending you can add to almost any word to invent a new style, like cottagecore.",
    org: "Borrowed from hardcore via music genre names such as mumblecore and normcore. Tumblr generalised it around 2013 and TikTok accelerated production to several new cores a month.",
    ex: ["Someone has coined stationerycore and it already has forty thousand posts.", "The suffix is more productive than almost anything else in current English."],
    rel: ["aesthetic", "cottagecore", "normcore"], tags: ["morphology", "tumblr", "suffix"],
  },
  {
    slug: "cottagecore", term: "Cottagecore", pron: "KOT-ij-kor", pos: "noun", cat: "aesthetic",
    year: 2018, pop: 58, trend: -5, status: "mainstream",
    def: "An aesthetic of idealised rural self-sufficiency: baking, gardening, linen and soft light. A fantasy of slowness rather than a description of farm labour.",
    eli: "A style based on a dreamy version of country life, with baking, flowers and old-fashioned clothes.",
    org: "Named on Tumblr around 2018 and exploded during the 2020 lockdowns, when the appeal of an imagined outdoors was self-explanatory. Its queer readings were central from the start.",
    ex: ["Peak cottagecore: sourdough, a wicker basket and no mention of rent.", "Cottagecore is escapism and knows it."],
    rel: ["core-suffix", "goblincore", "aesthetic"], tags: ["tumblr", "rural", "escapism"],
  },
  {
    slug: "dark-academia", term: "Dark academia", pron: "dark ak-uh-DEE-mee-uh", pos: "noun", cat: "aesthetic",
    year: 2019, pop: 55, trend: -3, status: "mainstream",
    def: "An aesthetic of old universities, tweed, candlelight and classical literature, drawing heavily on a romanticised and often exclusionary vision of scholarship.",
    eli: "A style based on old universities, libraries and studying by candlelight.",
    org: "Coalesced on Tumblr around 2019, drawing on Donna Tartt's The Secret History. Its critics point out that it aestheticises institutions many people were kept out of.",
    ex: ["Dark academia is a mood board about a reading list.", "Light academia is the same thing with better weather."],
    rel: ["aesthetic", "core-suffix", "cottagecore"], tags: ["tumblr", "books", "university"],
  },
  {
    slug: "normcore", term: "Normcore", pron: "NORM-kor", pos: "noun", cat: "aesthetic",
    year: 2013, pop: 41, trend: -4, status: "classic",
    def: "Deliberately unremarkable clothing worn as a stance, on the argument that refusing to signal is itself a signal.",
    eli: "Dressing in deliberately boring ordinary clothes on purpose, as a statement.",
    org: "Coined by trend forecasting group K-Hole in a 2013 report, where it originally meant social adaptability rather than plain clothing. The fashion press misread it and the misreading won.",
    ex: ["Normcore was a misunderstood report that became a real trend.", "Plain trainers and a fleece, priced like a statement."],
    rel: ["core-suffix", "aesthetic", "quiet-luxury"], tags: ["fashion", "2013", "irony"],
  },
  {
    slug: "y2k", term: "Y2K aesthetic", pron: "why-too-KAY", pos: "noun", cat: "aesthetic",
    year: 2019, pop: 63, trend: -2, status: "mainstream",
    def: "A revival of late-1990s and early-2000s design: chrome, translucent plastic, low-rise silhouettes and optimistic futurism.",
    eli: "A style copying the shiny, plastic, futuristic look of around the year 2000.",
    org: "Revived on Tumblr and TikTok from 2019, on the usual twenty-year nostalgia cycle. The name comes from the millennium bug, which is unrelated to the visual style.",
    ex: ["Translucent gadgets are back and it is entirely Y2K.", "The nostalgia cycle runs about twenty years, reliably."],
    rel: ["frutiger-aero", "vaporwave", "aesthetic"], tags: ["nostalgia", "2000s", "design"],
  },
  {
    slug: "frutiger-aero", term: "Frutiger Aero", pron: "FROO-tig-ur AIR-oh", pos: "noun", cat: "aesthetic",
    year: 2017, pop: 34, trend: 12, status: "rising",
    def: "The glossy, skeuomorphic design language of roughly 2004 to 2013: water droplets, glass buttons, tropical fish and unbounded technological optimism.",
    eli: "The shiny glass-and-water look computers had in the late 2000s.",
    org: "Named retroactively by design historians online, after the Frutiger typeface and Windows Aero. Its revival is driven by nostalgia for a period when technology still felt optimistic.",
    ex: ["Gradients, bubbles and a leaf. Pure Frutiger Aero.", "The style was named years after it ended, by people who missed it."],
    rel: ["y2k", "aesthetic", "vaporwave"], tags: ["design", "skeuomorphism", "nostalgia"],
  },
  {
    slug: "vaporwave", term: "Vaporwave", pron: "VAY-pur-wayv", pos: "noun", cat: "aesthetic",
    year: 2011, pop: 46, trend: -1, status: "classic",
    def: "A music and visual genre built from slowed 1980s corporate muzak, Greek statuary, early computer graphics and Japanese text, framed as critique of consumer capitalism.",
    eli: "A style using slowed-down old mall music and 1990s computer graphics, often as a joke about shopping culture.",
    org: "Emerged around 2011 on Bandcamp and Tumblr. Its politics were ambiguous enough that it was absorbed into advertising within a few years, which some consider the point proven.",
    ex: ["A marble bust, a palm tree and a slowed saxophone. Vaporwave.", "It criticised the mall and then got used to sell things in one."],
    rel: ["y2k", "frutiger-aero", "aesthetic"], tags: ["music", "tumblr", "critique"],
  },
  {
    slug: "liminal-space", term: "Liminal space", pron: "LIM-in-ul spays", pos: "noun", cat: "aesthetic",
    year: 2019, pop: 57, trend: 5, status: "rising",
    def: "A transitional place photographed while empty, producing unease because it is designed for people and contains none: corridors, stairwells, empty pools.",
    eli: "A photo of an empty place that is normally full of people, which feels strange and slightly wrong.",
    org: "From anthropology, where liminality names an in-between state in a ritual. Image boards applied it to empty architecture around 2019, producing an enormous photography genre.",
    ex: ["An empty shopping centre at 4am is a liminal space.", "The unease comes from absence, not from anything present."],
    rel: ["backrooms", "weirdcore", "cursed-image"], tags: ["photography", "unease", "architecture"],
  },
  {
    slug: "backrooms", term: "The Backrooms", pron: "thuh BAK-roomz", pos: "noun", cat: "aesthetic",
    year: 2019, pop: 52, trend: 2, status: "mainstream",
    def: "A collaborative horror setting of endless yellow office rooms with humming lights, expanded by thousands of contributors from a single image.",
    eli: "A made-up scary place of endless empty yellow rooms, invented from one photo online.",
    org: "Began with a 2019 4chan thread asking for unsettling images. One reply described falling out of reality into the rooms, and the setting grew from that single caption.",
    ex: ["The Backrooms started as one photo and one paragraph.", "It is the clearest example of collaborative worldbuilding online."],
    rel: ["liminal-space", "creepypasta", "weirdcore"], tags: ["horror", "4chan", "worldbuilding"],
  },
  {
    slug: "weirdcore", term: "Weirdcore", pron: "WEERD-kor", pos: "noun", cat: "aesthetic",
    year: 2020, pop: 38, trend: 4, status: "niche",
    def: "An aesthetic of low-quality amateur photography edited with crude overlays and text, engineered to produce nostalgia for a childhood that never happened.",
    eli: "Blurry old-looking photos edited to feel like a strange half-remembered dream.",
    org: "Named on Tumblr and TikTok around 2020, closely related to dreamcore. Its deliberate technical crudeness is the point: polish would destroy the effect.",
    ex: ["A blurry photo of a corridor with arrows drawn on it. Weirdcore.", "It manufactures nostalgia for memories you do not have."],
    rel: ["liminal-space", "backrooms", "aesthetic"], tags: ["tumblr", "nostalgia", "unease"],
  },
  {
    slug: "goblincore", term: "Goblincore", pron: "GOB-lin-kor", pos: "noun", cat: "aesthetic",
    year: 2019, pop: 36, trend: -2, status: "niche",
    def: "An aesthetic celebrating mud, moss, snails, bones and hoarded shiny objects. Explicitly framed as the messy answer to cottagecore's tidiness.",
    eli: "A style that loves mud, mushrooms, bugs and collecting odd little treasures.",
    org: "Emerged on Tumblr around 2019 as a deliberate counter to cottagecore, and was quickly adopted as an aesthetic by neurodivergent and queer users who found the tidy version alienating.",
    ex: ["Pockets full of interesting rocks. Goblincore.", "Cottagecore with the dirt left in."],
    rel: ["cottagecore", "core-suffix", "aesthetic"], tags: ["tumblr", "nature", "counterculture"],
  },
  {
    slug: "clean-girl", term: "Clean girl", pron: "kleen gurl", pos: "noun", cat: "aesthetic",
    year: 2022, pop: 54, trend: -6, status: "mainstream",
    def: "An aesthetic of minimal makeup, slicked hair, gold hoops and visible expensive simplicity. Criticised for repackaging looks long stigmatised on Black and Latina women.",
    eli: "A style of looking effortlessly neat and natural, which actually takes a lot of expensive products.",
    org: "Named on TikTok in 2022. Critics noted immediately that the slicked bun and hoops had been called unprofessional on women of colour for decades before being marketed as clean.",
    ex: ["Clean girl needs about nine products to look like none.", "The critique arrived roughly a fortnight after the trend."],
    rel: ["quiet-luxury", "aesthetic", "old-money"], tags: ["beauty", "tiktok", "criticism"],
  },
  {
    slug: "quiet-luxury", term: "Quiet luxury", pron: "KWY-ut LUK-shur-ee", pos: "noun", cat: "aesthetic",
    year: 2022, pop: 51, trend: -4, status: "mainstream",
    def: "Expensive clothing without visible branding, legible as wealth only to people who already recognise the cut. Also called stealth wealth or old money.",
    eli: "Very expensive clothes with no logos, so only people who know can tell.",
    org: "Named around 2022 and amplified by the television series Succession. It is a recurring cycle: conspicuous logos and inconspicuous quality alternate roughly every decade.",
    ex: ["No logo, four figures, quiet luxury.", "The point is being unreadable to almost everyone."],
    rel: ["clean-girl", "normcore", "old-money"], tags: ["fashion", "wealth", "television"],
  },
  {
    slug: "corecore", term: "Corecore", pron: "KOR-kor", pos: "noun", cat: "aesthetic",
    year: 2022, pop: 33, trend: 3, status: "niche",
    def: "A video collage of unrelated clips set to melancholy music, assembled to evoke a diffuse feeling about modern life. A commentary on aesthetic naming itself.",
    eli: "Videos made of many unrelated clips stitched together with sad music to make you feel something.",
    org: "Emerged on TikTok in late 2022 as a reaction to the endless invention of cores. Often described as the first genuinely internet-native art movement of the decade.",
    ex: ["Nine seconds of unrelated clips and a piano loop. Corecore.", "It is a parody of aesthetic naming that became an aesthetic."],
    rel: ["core-suffix", "aesthetic", "brainrot"], tags: ["tiktok", "video", "meta"],
  },
  {
    slug: "moodboard", term: "Moodboard", pron: "MOOD-bord", pos: "noun", cat: "aesthetic",
    year: 2010, pop: 48, trend: 1, status: "classic",
    def: "A collage of images assembled to communicate a feeling rather than a plan. Now used for personal identity as often as for design briefs.",
    eli: "A collection of pictures put together to show a feeling or style.",
    org: "A long-standing design and fashion practice that Pinterest turned into a mass activity after 2010. Its use for self-description rather than project planning is the newer part.",
    ex: ["The moodboard is nine photos and a colour swatch.", "People now moodboard their year rather than plan it."],
    rel: ["aesthetic", "core-suffix", "vibe"], tags: ["pinterest", "design", "identity"],
  },
  {
    slug: "old-money", term: "Old money", pron: "ohld MUN-ee", pos: "noun", cat: "aesthetic",
    year: 2022, pop: 47, trend: -3, status: "mainstream",
    def: "An aesthetic imitating inherited wealth: understated tailoring, tennis clubs, no logos. A costume of a class position rather than the position itself.",
    eli: "Dressing to look like your family has been rich for generations.",
    org: "Named on TikTok around 2022 alongside quiet luxury. The irony noted repeatedly is that the aesthetic is consumed mainly by people buying fast fashion versions of it.",
    ex: ["Old money aesthetic, brand new credit agreement.", "It is cosplay about inheritance."],
    rel: ["quiet-luxury", "clean-girl", "aesthetic"], tags: ["fashion", "class", "tiktok"],
  },
  {
    slug: "indie-sleaze", term: "Indie sleaze", pron: "IN-dee sleez", pos: "noun", cat: "aesthetic",
    year: 2021, pop: 34, trend: 2, status: "niche",
    def: "A revival of late-2000s party aesthetics: harsh flash photography, American Apparel, visible mess. Explicitly a reaction against curated feeds.",
    eli: "A style copying messy late-2000s party photos taken with a bright camera flash.",
    org: "Named retroactively around 2021 by people too young to have attended. Its appeal is that it predates the polished influencer image, which is precisely what it rejects.",
    ex: ["Indie sleaze is a rebellion against good lighting.", "Nobody called it indie sleaze at the time."],
    rel: ["y2k", "aesthetic", "normcore"], tags: ["nostalgia", "2000s", "photography"],
  },
  {
    slug: "coquette", term: "Coquette", pron: "koh-KET", pos: "noun", cat: "aesthetic",
    year: 2021, pop: 42, trend: -3, status: "mainstream",
    def: "An aesthetic of bows, lace, pastels and deliberate girlishness, drawing on Rococo portraiture and 1960s styling.",
    eli: "A very girly style full of bows, lace and soft pink colours.",
    org: "Named on TikTok around 2021, descended from earlier Tumblr nymphet imagery whose sources were widely criticised. The current version has been largely detached from that history.",
    ex: ["A bow on every available surface. Coquette.", "The lineage is more complicated than the pastels suggest."],
    rel: ["clean-girl", "aesthetic", "core-suffix"], tags: ["fashion", "tiktok", "girlhood"],
  },
  {
    slug: "gorpcore", term: "Gorpcore", pron: "GORP-kor", pos: "noun", cat: "aesthetic",
    year: 2017, pop: 33, trend: 2, status: "niche",
    def: "Technical outdoor clothing worn in cities with no intention of going outdoors: fleeces, hiking shoes, waterproof shells as everyday wear.",
    eli: "Wearing serious hiking gear around town even though you are not going hiking.",
    org: "Coined by writer Jason Chen in 2017, from GORP, the American acronym for trail mix. It marked the point at which performance clothing became fashion rather than equipment.",
    ex: ["Full alpine kit for a trip to the corner shop. Gorpcore.", "The jacket is rated for conditions it will never see."],
    rel: ["normcore", "core-suffix", "quiet-luxury"], tags: ["fashion", "outdoors", "2017"],
  },
  {
    slug: "dreamcore", term: "Dreamcore", pron: "DREEM-kor", pos: "noun", cat: "aesthetic",
    year: 2020, pop: 31, trend: 3, status: "niche",
    def: "An aesthetic imitating the logic of dreams: familiar settings rendered slightly wrong, with soft focus and impossible geometry.",
    eli: "Images that look like a dream, with normal places that feel subtly wrong.",
    org: "Named on Tumblr and TikTok around 2020 alongside weirdcore. Where weirdcore aims for unease, dreamcore aims for a gentler disorientation.",
    ex: ["A corridor that keeps going. Dreamcore.", "Weirdcore unsettles, dreamcore floats."],
    rel: ["weirdcore", "liminal-space", "aesthetic"], tags: ["tumblr", "dreams", "unease"],
  },
  {
    slug: "mob-wife", term: "Mob wife", pron: "mob wyfe", pos: "noun", cat: "aesthetic",
    year: 2024, pop: 36, trend: -9, status: "fading",
    def: "An aesthetic of fur coats, heavy gold, dark sunglasses and visible expense, defined explicitly against the restraint of clean girl.",
    eli: "A loud, glamorous style with big fur coats and lots of gold jewellery.",
    org: "Named on TikTok in January 2024 as a direct reaction to clean girl. The speed of the swing between the two is a good illustration of how aesthetic cycles now run.",
    ex: ["Clean girl was over the week mob wife arrived.", "Two opposite aesthetics inside eighteen months."],
    rel: ["clean-girl", "quiet-luxury", "aesthetic"], tags: ["fashion", "tiktok", "2024"],
  },
  {
    slug: "blokecore", term: "Blokecore", pron: "BLOHK-kor", pos: "noun", cat: "aesthetic",
    year: 2022, pop: 29, trend: -2, status: "niche",
    def: "Retro football shirts, plain jeans and terrace trainers worn as fashion. Named from British slang, and adopted mainly outside Britain.",
    eli: "Wearing old football shirts and plain jeans as a fashion look.",
    org: "Named on TikTok around 2022. British observers noted with some amusement that the look was simply how a great many men had always dressed, now priced accordingly.",
    ex: ["A 1998 away shirt is now a fashion item.", "In Britain this is not a look, it is Saturday."],
    rel: ["gorpcore", "normcore", "core-suffix"], tags: ["fashion", "football", "british"],
  },
  {
    slug: "whimsigoth", term: "Whimsigoth", pron: "WIM-zee-goth", pos: "noun", cat: "aesthetic",
    year: 2022, pop: 27, trend: 3, status: "niche",
    def: "A style blending 1990s mystical imagery with soft gothic elements: velvet, crescent moons, tarot, dark florals.",
    eli: "A gentle witchy style with velvet, moons and tarot cards.",
    org: "Named by Evan Collins of the Consumer Aesthetics Research Institute around 2022, part of a broader project cataloguing and dating unnamed twentieth-century design movements.",
    ex: ["Velvet, moons and a tarot deck. Whimsigoth.", "Named retroactively by people who catalogue design eras properly."],
    rel: ["cottagecore", "dark-academia", "aesthetic"], tags: ["fashion", "1990s", "occult"],
  },
  {
    slug: "aesthetics-wiki", term: "Aesthetics Wiki", pron: "es-THET-iks WIK-ee", pos: "noun", cat: "aesthetic",
    year: 2019, pop: 31, trend: 5, status: "rising",
    def: "A community reference cataloguing named visual styles, with entries covering palette, history and adjacent movements. The closest thing the practice has to a standards body.",
    eli: "A fan-run encyclopedia listing every named internet style and what it looks like.",
    org: "Founded in 2019 and grown to thousands of entries. Its existence is itself evidence of how systematically internet aesthetics are now named and classified.",
    ex: ["Thousands of documented aesthetics and more each week.", "Someone is doing the taxonomy properly, for free."],
    rel: ["aesthetic", "core-suffix", "moodboard"], tags: ["reference", "wiki", "taxonomy"],
  },
  {
    slug: "skeuomorphism", term: "Skeuomorphism", pron: "skyoo-oh-MOR-fiz-um", pos: "noun", cat: "aesthetic",
    year: 2012, pop: 38, trend: 4, status: "classic",
    def: "Design that imitates the appearance of physical objects: leather stitching, paper textures, three-dimensional buttons. Replaced by flat design, and now partly returning.",
    eli: "Designs that look like real objects, such as an app made to look like a leather notebook.",
    org: "An old architectural term, applied to software interfaces during the 2013 argument over iOS 7's flat redesign. The pendulum has since swung part of the way back.",
    ex: ["The notes app with fake torn paper was peak skeuomorphism.", "Flat design won, then quietly reintroduced shadows."],
    rel: ["frutiger-aero", "y2k", "aesthetic"], tags: ["design", "interfaces", "history"],
  },
  {
    slug: "e-girl", term: "E-girl", pron: "EE-gurl", pos: "noun", cat: "aesthetic",
    year: 2019, pop: 56, trend: -6, status: "fading",
    def: "An aesthetic combining alternative fashion, anime-influenced makeup with heart drawings under the eyes, and a persona cultivated for gaming and short-video platforms.",
    eli: "A style mixing edgy fashion with anime-style makeup, like little hearts drawn under the eyes, popular on gaming and video apps.",
    org: "Emerged from gaming-adjacent internet culture around 2019, spreading rapidly through TikTok, and closely paired from the start with its male counterpart, e-boy.",
    ex: ["Full e-girl makeup for a stream that four people watched.", "The e-girl aesthetic borrowed heavily from 2000s emo and scene styles."],
    rel: ["e-boy", "vsco-girl", "alt"], tags: ["tiktok", "fashion", "2019"],
  },
  {
    slug: "e-boy", term: "E-boy", pron: "EE-boy", pos: "noun", cat: "aesthetic",
    year: 2019, pop: 45, trend: -7, status: "fading",
    def: "The male counterpart to the e-girl aesthetic, combining chain necklaces, painted nails and a moody, skater-adjacent style cultivated for short-video platforms.",
    eli: "A style for guys with chain necklaces, painted nails and a moody skater look, popular on video apps.",
    org: "Rose alongside e-girl aesthetics in 2019 through the same gaming and TikTok communities, borrowing heavily from skater and emo fashion of the 2000s.",
    ex: ["E-boy hair takes more product than it looks like it should.", "The e-boy aesthetic peaked and faded within about two years."],
    rel: ["e-girl", "soft-boy", "alt"], tags: ["tiktok", "fashion", "2019"],
  },
  {
    slug: "vsco-girl", term: "VSCO girl", pron: "VIS-koh gurl", pos: "noun", cat: "aesthetic",
    year: 2019, pop: 48, trend: -12, status: "fading",
    def: "A 2019 aesthetic built around scrunchies, metal straws, oversized t-shirts and a laid-back, environmentally conscious presentation, named after the photo-editing app used to style its photos.",
    eli: "A 2019 style involving scrunchies, metal straws and big t-shirts, named after a photo-editing app popular for the look's signature filters.",
    org: "Named after the VSCO photography app in 2019, the aesthetic became one of the fastest rise-and-fall trend cycles TikTok had produced up to that point.",
    ex: ["The scrunchie collection was peak VSCO girl.", "VSCO girl lasted about one summer before the internet moved on entirely."],
    rel: ["e-girl", "clean-girl", "sksksk"], tags: ["tiktok", "2019", "fashion"],
  },
  {
    slug: "coastal-grandmother", term: "Coastal grandmother", pron: "KOHST-ul GRAN-muth-ur", pos: "noun", cat: "aesthetic",
    year: 2022, pop: 40, trend: -3, status: "fading",
    def: "An aesthetic centred on neutral linen clothing, beachside interiors and an unhurried, affluent lifestyle, evoking a relaxed retirement rather than an actual grandmother's wardrobe.",
    eli: "A calm, beachy style with lots of linen and neutral colours, meant to look like an easy, comfortable, well-off retirement.",
    org: "Named on TikTok in 2022, inspired partly by imagined film aesthetics of wealthy seaside living, and notable for making an aspirational lifestyle out of visible relaxation.",
    ex: ["The whole rental was decorated in coastal grandmother, right down to the linen napkins.", "Coastal grandmother is quiet luxury with a cardigan on."],
    rel: ["quiet-luxury", "old-money", "clean-girl"], tags: ["tiktok", "2022", "lifestyle"],
  },
  {
    slug: "light-academia", term: "Light academia", pron: "lyt ak-uh-DEE-mee-uh", pos: "noun", cat: "aesthetic",
    year: 2020, pop: 33, trend: -2, status: "niche",
    def: "A softer, brighter counterpart to dark academia, keeping the scholarly, vintage-inspired styling but trading dark tones for cream, beige and pastel palettes.",
    eli: "A brighter, softer version of the dark academia look, keeping the old-fashioned, studious style but with lighter colours.",
    org: "Formed by direct contrast to dark academia once that aesthetic was established on Tumblr and TikTok, offering the same literary mood without the gothic tone.",
    ex: ["Light academia if dark academia ever saw actual sunlight.", "Same tweed, entirely different colour palette."],
    rel: ["dark-academia", "aesthetic", "clean-girl"], tags: ["tumblr", "aesthetic", "fashion"],
  },
  {
    slug: "alt", term: "Alt", pron: "alt", pos: "adjective", cat: "aesthetic",
    year: 2015, pop: 47, trend: -1, status: "mainstream",
    def: "Short for alternative, describing a broad, loosely defined identity built around non-mainstream fashion, music taste and online presentation, encompassing e-girl, goth and grunge-adjacent styles under one umbrella.",
    eli: "Short for alternative, a general label for someone into non-mainstream fashion and music, covering lots of different specific styles.",
    org: "Long used offline for alternative music and fashion scenes, the label was absorbed into a single broad online identity category from around 2015 as platforms flattened many older subcultures into one another.",
    ex: ["The alt tag on that app covers about six different aesthetics at once.", "Alt used to mean something more specific before the internet broadened it."],
    rel: ["e-girl", "e-boy", "indie-sleaze"], tags: ["identity", "fashion", "music"],
  },
];
