import type { RawTerm } from "../types";

export const aiTerms: RawTerm[] = [
  {
    slug: "agentic", term: "Agentic", pron: "ay-JEN-tik", pos: "adjective", cat: "ai",
    year: 2024, pop: 81, trend: 38, status: "rising",
    def: "Describing an AI system that plans multi-step work, calls tools and acts on the results in a loop, rather than answering a single question and stopping.",
    eli: "An AI that does not just answer once. It makes a plan, uses tools, checks what happened, and keeps going until the job is done.",
    org: "Moved from research vocabulary into product marketing during 2024 and 2025, as tool use and long-running loops became standard model capabilities.",
    ex: ["The agentic version runs the tests itself and fixes what fails.", "Every roadmap this year has the word agentic somewhere on it."],
    rel: ["vibe-coding", "rag", "prompt-engineering"], tags: ["agents", "tools", "2025"],
  },
  {
    slug: "ai-slop", term: "AI slop", pron: "AY-EYE slop", pos: "noun", cat: "ai",
    year: 2024, pop: 86, trend: 27, status: "rising",
    def: "Mass-produced generated content published for volume rather than value, recognisable by its uniform tone, generic imagery and absence of specific detail.",
    eli: "Cheap articles and pictures made by AI in huge numbers to fill up websites, not because anyone wanted to read them.",
    org: "\"Slop\" was adopted from animal feed by online communities in 2024 as generated filler flooded search results, stock libraries and social feeds.",
    ex: ["Page one of the results is entirely AI slop.", "You can spot the slop by the hands and the adjectives."],
    rel: ["hallucination", "model-collapse", "dead-internet-theory"], tags: ["content", "quality", "search"],
  },
  {
    slug: "context-window", term: "Context window", pron: "KON-tekst WIN-doh", pos: "noun", cat: "ai",
    year: 2023, pop: 75, trend: 9, status: "mainstream",
    def: "The maximum amount of text, measured in tokens, that a model can consider at once. Everything outside it is invisible to the model unless retrieved and reinserted.",
    eli: "How much an AI can hold in its head at one time. Anything past that limit is simply not there for it.",
    org: "Standard machine-learning terminology that entered general use after 2023, when competing labs began advertising window sizes as a headline feature.",
    ex: ["The whole repository does not fit in the context window, so we retrieve the relevant files.", "It forgot the earlier instruction because it fell out of the context window."],
    rel: ["token", "rag", "hallucination"], tags: ["llm", "architecture", "limits"],
  },
  {
    slug: "dead-internet-theory", term: "Dead internet theory", pron: "ded IN-tur-net THEER-ee", pos: "noun", cat: "ai",
    year: 2021, pop: 71, trend: 19, status: "rising",
    def: "The claim that most online activity is now automated, leaving a web where bots post for other bots. Overstated as literal fact, but increasingly cited as a description of how feeds feel.",
    eli: "The idea that a lot of the internet is machines talking to machines, and fewer real people than it looks like.",
    org: "Posted on the Agora Road forum in 2021 as a conspiracy theory. Generated content and bot networks after 2023 gave the underlying worry mainstream credibility.",
    ex: ["Every reply was identical praise. Dead internet theory hours.", "It is not literally true, but the comment sections make the case."],
    rel: ["ai-slop", "model-collapse", "algorithm"], tags: ["bots", "conspiracy", "feeds"],
  },
  {
    slug: "hallucination", term: "Hallucination", pron: "huh-loo-si-NAY-shun", pos: "noun", cat: "ai",
    year: 2022, pop: 87, trend: 4, status: "mainstream",
    def: "Output from a language model that is fluent and confident but factually wrong or fabricated. A failure of grounding rather than a failure of grammar.",
    eli: "When an AI makes something up and says it in a very sure voice, so it sounds true even though it is not.",
    org: "Adapted from earlier image-captioning research and applied to text models after 2022. The metaphor is contested - some researchers prefer \"confabulation\" as more accurate.",
    ex: ["It cited three papers and two of them were hallucinations.", "Always check the citations. Hallucination rate is not zero."],
    rel: ["rag", "context-window", "ai-slop"], tags: ["reliability", "llm", "safety"],
  },
  {
    slug: "jailbreak", term: "Jailbreak", pron: "JAYL-brayk", pos: "noun", cat: "ai",
    year: 2022, pop: 62, trend: 7, status: "niche",
    def: "A prompt crafted to make a model ignore its own safety guidelines, typically by wrapping the request in fiction, role-play or a false claim of authority.",
    eli: "A trick question designed to talk an AI out of following its own rules.",
    org: "Borrowed from phone modification culture and applied to chatbots in 2022. It remains an active area of security research on both sides.",
    ex: ["The jailbreak worked for a week and then the model was patched.", "Red teams write jailbreaks so the safety team can close them."],
    rel: ["prompt-engineering", "hallucination", "agentic"], tags: ["safety", "security", "llm"],
  },
  {
    slug: "model-collapse", term: "Model collapse", pron: "MOD-ul kuh-LAPS", pos: "noun", cat: "ai",
    year: 2023, pop: 47, trend: 15, status: "niche",
    def: "Degradation that occurs when models are trained largely on the output of earlier models, gradually losing the rare cases present in original human data.",
    eli: "If AI keeps learning from other AI instead of from real people, it slowly forgets the unusual things and gets blander.",
    org: "Described in research published in 2023 and 2024, and quickly folded into wider arguments about generated content flooding the open web.",
    ex: ["Filtering training data matters more once the web is full of slop.", "Model collapse is the long-term version of the slop problem."],
    rel: ["ai-slop", "dead-internet-theory", "hallucination"], tags: ["training", "research", "quality"],
  },
  {
    slug: "prompt-engineering", term: "Prompt engineering", pron: "prompt en-jin-EER-ing", pos: "noun", cat: "ai",
    year: 2020, pop: 85, trend: -10, status: "mainstream",
    def: "The practice of structuring instructions, examples and context so a model produces reliable output. Closer to specification writing than to programming.",
    eli: "Learning how to ask an AI for things in a way that gets you a good answer instead of a vague one.",
    org: "Named around 2020 after GPT-3 showed that phrasing changed results dramatically. As models improved, the emphasis shifted from clever wording to supplying the right context.",
    ex: ["Half of prompt engineering is deciding what to leave out.", "We moved the prompt into version control like any other source file."],
    rel: ["context-window", "jailbreak", "agentic"], tags: ["llm", "practice", "workflow"],
  },
  {
    slug: "rag", term: "RAG", pron: "rag", pos: "abbreviation", cat: "ai",
    year: 2020, pop: 63, trend: 12, status: "niche",
    def: "Retrieval-augmented generation: fetching relevant documents from a data source and placing them in the prompt, so answers are grounded in real material rather than model memory.",
    eli: "Giving the AI the right pages to read before it answers, so it quotes real information instead of guessing.",
    org: "Introduced in a 2020 research paper from Facebook AI Research and turned into standard product architecture once companies wanted models to answer from their own documents.",
    ex: ["Support answers improved once we put the help centre behind RAG.", "RAG reduces hallucination but does not remove it."],
    rel: ["hallucination", "context-window", "agentic"], tags: ["architecture", "search", "llm"],
  },
  {
    slug: "token", term: "Token", pron: "TOH-kun", pos: "noun", cat: "ai",
    year: 2020, pop: 68, trend: 6, status: "mainstream",
    def: "The unit a language model reads and writes. Tokens are fragments of text - often a short word or part of a longer one - and they are what usage and pricing are measured in.",
    eli: "AI does not read whole words. It reads little pieces, and each piece is a token. Longer text means more tokens.",
    org: "Inherited from computational linguistics, where tokenisation has always meant splitting text into units. It became a consumer-facing word once API pricing was quoted per token.",
    ex: ["A page of English is roughly 750 tokens.", "We cut the prompt in half and the token bill followed."],
    rel: ["context-window", "prompt-engineering", "hallucination"], tags: ["llm", "pricing", "nlp"],
  },
  {
    slug: "vibe-coding", term: "Vibe coding", pron: "VYBE KOH-ding", pos: "noun", cat: "ai",
    year: 2025, pop: 89, trend: 33, status: "rising",
    def: "Building software by describing intent to a model and accepting its output largely unreviewed, judging the result by whether it appears to work rather than by reading the code.",
    eli: "Making an app by telling an AI what you want and trusting what it writes, without checking every line yourself.",
    org: "Named by Andrej Karpathy in early 2025 to describe a mode of working where you \"fully give in to the vibes\" and forget the code exists. Adopted enthusiastically and criticised just as fast.",
    ex: ["The prototype was vibe coded in an evening and rewritten properly in a week.", "Vibe coding is fine until something breaks and nobody knows why."],
    rel: ["agentic", "ai-slop", "prompt-engineering"], tags: ["software", "workflow", "2025"],
  },
  {
    slug: "transformer", term: "Transformer", pron: "trans-FOR-mur", pos: "noun", cat: "ai",
    year: 2017, pop: 64, trend: 3, status: "mainstream",
    def: "The neural network architecture underlying nearly all current language models, built on an attention mechanism that weighs every token against every other.",
    eli: "The design that modern AI models are built on, which lets them consider how every word relates to every other word.",
    org: "Introduced in the 2017 Google paper Attention Is All You Need. Replacing sequential processing with parallel attention is what made training at current scale practical.",
    ex: ["Almost everything since 2018 is a transformer variant.", "The architecture is eight years old and still dominant."],
    rel: ["token", "context-window", "scaling-laws"], tags: ["architecture", "research", "google"],
  },
  {
    slug: "diffusion", term: "Diffusion model", pron: "di-FYOO-zhun", pos: "noun", cat: "ai",
    year: 2020, pop: 55, trend: 4, status: "mainstream",
    def: "An image generation method that learns to reverse a gradual noising process, starting from static and denoising step by step into a picture.",
    eli: "An image AI that starts with random static and slowly cleans it up into a picture.",
    org: "Built on 2015 research and made practical in 2020. It displaced GANs as the dominant approach to image generation because it trains far more stably.",
    ex: ["The whole image is denoised from static in about thirty steps.", "Diffusion won because GANs were miserable to train."],
    rel: ["deepfake", "ai-slop", "multimodal"], tags: ["images", "research", "generation"],
  },
  {
    slug: "deepfake", term: "Deepfake", pron: "DEEP-fayk", pos: "noun", cat: "ai",
    year: 2017, pop: 78, trend: 9, status: "mainstream",
    def: "Synthetic video or audio depicting a real person doing or saying something they did not. Increasingly a legal category as well as a technical one.",
    eli: "A fake video or voice recording of a real person, made by AI.",
    org: "Named after a Reddit user who posted face-swapped videos in 2017. Legislation followed in many jurisdictions, particularly targeting non-consensual and election-related use.",
    ex: ["The audio deepfake fooled the finance team into a transfer.", "Detection consistently lags generation."],
    rel: ["diffusion", "dead-internet-theory", "catfishing"], tags: ["video", "fraud", "law"],
  },
  {
    slug: "alignment", term: "Alignment", pron: "uh-LYNE-munt", pos: "noun", cat: "ai",
    year: 2015, pop: 58, trend: 7, status: "rising",
    def: "The problem of making an AI system pursue what its operators actually intend, including cases the specification never anticipated.",
    eli: "Making sure an AI does what people actually want, not just what they literally asked for.",
    org: "Formalised as a research field in the mid-2010s, though the underlying concern about specifying goals precisely goes back to Norbert Wiener in 1960.",
    ex: ["The model optimised the metric and ignored the point. Alignment problem.", "Specification is harder than optimisation."],
    rel: ["guardrails", "jailbreak", "agi"], tags: ["safety", "research", "philosophy"],
  },
  {
    slug: "agi", term: "AGI", pron: "ay-jee-EYE", pos: "abbreviation", cat: "ai",
    year: 2007, pop: 72, trend: 11, status: "rising",
    def: "Artificial general intelligence: a system matching human capability across essentially all cognitive tasks. There is no agreed definition or test, which is central to most disputes about it.",
    eli: "An AI that could do basically any thinking task a person can. Nobody agrees on how we would know it had arrived.",
    org: "Popularised by Ben Goertzel and Shane Legg around 2007 to distinguish broad capability from narrow systems. Definitions now vary enough that headlines about it frequently talk past each other.",
    ex: ["Every AGI timeline argument is a definitions argument.", "The word does a lot of fundraising work."],
    rel: ["alignment", "benchmark", "scaling-laws"], tags: ["research", "contested", "philosophy"],
  },
  {
    slug: "benchmark", term: "Benchmark", pron: "BENCH-mark", pos: "noun", cat: "ai",
    year: 2018, pop: 60, trend: 5, status: "mainstream",
    def: "A standard test set used to compare models. Benchmark contamination, where test data leaks into training data, makes many published scores hard to interpret.",
    eli: "A standard exam for AI models. If the answers leaked into training, the score means little.",
    org: "Long-standing in computer science, but central to public AI discourse since 2018. Saturation and contamination have repeatedly forced the field to design harder tests.",
    ex: ["Ninety-two percent on a benchmark that may be in the training set.", "Benchmarks measure benchmarks, not always capability."],
    rel: ["agi", "scaling-laws", "open-weights"], tags: ["evaluation", "research", "measurement"],
  },
  {
    slug: "open-weights", term: "Open weights", pron: "OH-pun wayts", pos: "noun", cat: "ai",
    year: 2023, pop: 54, trend: 12, status: "rising",
    def: "A model whose trained parameters are downloadable, allowing local use and modification. Distinct from open source, since training data and code are usually withheld.",
    eli: "An AI model you can download and run yourself, though you still cannot see what it was trained on.",
    org: "Became a live distinction after 2023, when several labs released weights without releasing data or training code. The Open Source Initiative published a definition to settle the confusion.",
    ex: ["Open weights, closed data, contested licence.", "Downloadable is not the same as open source."],
    rel: ["distillation", "benchmark", "open-source"], tags: ["licensing", "release", "contested"],
  },
  {
    slug: "chain-of-thought", term: "Chain of thought", pron: "chayn uv thawt", pos: "noun", cat: "ai",
    year: 2022, pop: 57, trend: 8, status: "rising",
    def: "Having a model produce intermediate reasoning steps before an answer, which measurably improves accuracy on multi-step problems.",
    eli: "Getting an AI to show its working, which makes it get more answers right.",
    org: "Named in a 2022 Google Research paper showing that simply asking a model to think step by step improved results. It became a foundation for later reasoning-focused models.",
    ex: ["Chain of thought turned a wrong answer into a right one.", "The visible reasoning is not necessarily the actual computation."],
    rel: ["prompt-engineering", "agentic", "transformer"], tags: ["prompting", "reasoning", "research"],
  },
  {
    slug: "clanker", term: "Clanker", pron: "KLANK-ur", pos: "noun", cat: "ai",
    year: 2024, pop: 59, trend: 28, status: "rising",
    def: "A dismissive term for a robot or AI system, used when automated service fails or when generated content is obvious. Adopted as a joke rather than a serious slur.",
    eli: "A rude nickname for robots and AI, used when they get things wrong.",
    org: "Taken from Star Wars: The Clone Wars, where clone troopers use it for battle droids. It spread widely in 2024 and 2025 as automated customer service and generated content became unavoidable.",
    ex: ["Forty minutes arguing with a clanker before reaching a person.", "Every caption ends with an em dash. Clanker wrote it."],
    rel: ["ai-slop", "dead-internet-theory", "agentic"], tags: ["star-wars", "2025", "backlash"],
  },
  {
    slug: "fine-tuning", term: "Fine-tuning", pron: "fyne TYOO-ning", pos: "noun", cat: "ai",
    year: 2018, pop: 52, trend: 2, status: "mainstream",
    def: "Continuing training on a smaller specific dataset to specialise an existing model, far cheaper than training from scratch.",
    eli: "Taking a general AI model and training it a bit more on your own examples so it fits your task.",
    org: "Standard transfer-learning practice that became central after 2018, when pretrained language models made starting from scratch unnecessary for most applications.",
    ex: ["Fine-tuned on ten thousand support tickets.", "Most people who want fine-tuning actually want retrieval."],
    rel: ["rag", "distillation", "open-weights"], tags: ["training", "practice", "transfer"],
  },
  {
    slug: "distillation", term: "Distillation", pron: "dis-til-AY-shun", pos: "noun", cat: "ai",
    year: 2015, pop: 46, trend: 9, status: "rising",
    def: "Training a smaller model to reproduce a larger one's outputs, capturing much of the capability at a fraction of the running cost.",
    eli: "Training a small AI to copy a big one, so it is cheaper to run but nearly as good.",
    org: "Formalised in a 2015 paper by Hinton, Vinyals and Dean. It became commercially and legally contentious after 2024, when distilling from competitors' outputs became widespread.",
    ex: ["A distilled model at a twentieth of the cost.", "Whether distilling a rival's outputs is permitted is now a licensing question."],
    rel: ["fine-tuning", "open-weights", "benchmark"], tags: ["training", "efficiency", "licensing"],
  },
  {
    slug: "embedding", term: "Embedding", pron: "em-BED-ing", pos: "noun", cat: "ai",
    year: 2013, pop: 48, trend: 4, status: "mainstream",
    def: "A representation of text or images as a list of numbers, positioned so that similar meanings sit close together. The basis of semantic search.",
    eli: "Turning words into numbers arranged so that similar meanings end up near each other.",
    org: "Word2vec in 2013 made the idea famous, with its demonstration that king minus man plus woman lands near queen. Modern embeddings work on whole passages rather than single words.",
    ex: ["Search by embedding finds the answer even when no word matches.", "Similarity in embedding space is not the same as relevance."],
    rel: ["rag", "transformer", "token"], tags: ["search", "representation", "research"],
  },
  {
    slug: "guardrails", term: "Guardrails", pron: "GARD-raylz", pos: "noun", cat: "ai",
    year: 2022, pop: 55, trend: 6, status: "mainstream",
    def: "Constraints placed around a model's behaviour, through training, filtering or system instructions, to keep outputs within acceptable bounds.",
    eli: "The rules and filters that stop an AI from saying or doing certain things.",
    org: "Became standard product vocabulary after 2022, as conversational models reached the public. The term is deliberately reassuring, which is part of why critics dislike it.",
    ex: ["The guardrails held for everything except the obvious case.", "Guardrails are layered, not singular."],
    rel: ["alignment", "jailbreak", "red-teaming"], tags: ["safety", "product", "moderation"],
  },
  {
    slug: "red-teaming", term: "Red teaming", pron: "red TEE-ming", pos: "noun", cat: "ai",
    year: 2022, pop: 47, trend: 8, status: "rising",
    def: "Deliberately attacking your own system to find failures before others do, borrowed directly from security and military practice.",
    eli: "Paying people to try to break your own AI so you can fix the problems first.",
    org: "A Cold War military exercise term, adopted by computer security and then by AI labs from around 2022. It is now a formal requirement in several regulatory frameworks.",
    ex: ["The red team found nine jailbreaks in a fortnight.", "Red teaming is only useful if the findings get fixed."],
    rel: ["jailbreak", "guardrails", "alignment"], tags: ["safety", "security", "practice"],
  },
  {
    slug: "scaling-laws", term: "Scaling laws", pron: "SKAY-ling lawz", pos: "noun", cat: "ai",
    year: 2020, pop: 44, trend: 5, status: "mainstream",
    def: "Empirical relationships showing how model performance improves predictably with more parameters, data and compute. The basis of the case for building larger models.",
    eli: "The finding that AI models get predictably better as you make them bigger and feed them more data.",
    org: "Published by OpenAI in 2020 and refined by DeepMind's Chinchilla paper in 2022, which showed most models were badly undertrained for their size.",
    ex: ["The scaling laws predicted the jump before anyone measured it.", "Chinchilla changed how the compute budget gets spent."],
    rel: ["transformer", "benchmark", "agi"], tags: ["research", "compute", "prediction"],
  },
  {
    slug: "multimodal", term: "Multimodal", pron: "mul-tee-MOH-dul", pos: "adjective", cat: "ai",
    year: 2021, pop: 53, trend: 7, status: "rising",
    def: "Describing a model that handles more than one kind of input or output, such as text alongside images, audio or video, within a single system.",
    eli: "An AI that can handle pictures, sound and text together instead of just one of them.",
    org: "Became a standard product category after 2021, as image and text models converged. The practical shift was being able to point a camera at something and ask about it.",
    ex: ["Multimodal means you can photograph the error message.", "Text-only models now look like a transitional stage."],
    rel: ["transformer", "diffusion", "agentic"], tags: ["capability", "product", "vision"],
  },
  {
    slug: "mcp", term: "MCP", pron: "em-see-PEE", pos: "abbreviation", cat: "ai",
    year: 2024, pop: 46, trend: 22, status: "rising",
    def: "Model Context Protocol: an open standard for connecting AI assistants to external tools and data sources through a common interface.",
    eli: "A shared standard that lets AI assistants plug into other apps and data without custom code for each one.",
    org: "Published by Anthropic in November 2024 and adopted across the industry through 2025. It addresses the same fragmentation problem that drove earlier integration standards.",
    ex: ["Wrote one MCP server and every client could use it.", "Standards win when writing the adapter once is cheaper than writing it nine times."],
    rel: ["agentic", "api", "rag"], tags: ["standards", "tools", "2025"],
  },
  {
    slug: "ai-boyfriend", term: "AI companion", pron: "AY-EYE kum-PAN-yun", pos: "noun", cat: "ai",
    year: 2023, pop: 51, trend: 13, status: "rising",
    def: "A conversational system used for ongoing companionship or romance. A large consumer category, and an active area of psychological and regulatory concern.",
    eli: "An AI you talk to like a friend or partner, every day.",
    org: "Replika launched in 2017, and the category grew sharply after 2023. A 2023 update that changed one product's behaviour caused widespread distress among users, which made the attachment hard to dismiss.",
    ex: ["The model update changed his personality overnight.", "Whatever you think of it, the attachment is real."],
    rel: ["parasocial", "delulu", "guardrails"], tags: ["companionship", "psychology", "product"],
  },
  {
    slug: "slopsquatting", term: "Slopsquatting", pron: "SLOP-skwot-ing", pos: "noun", cat: "ai",
    year: 2025, pop: 29, trend: 18, status: "rising",
    def: "Registering package names that language models commonly hallucinate, so that developers installing a suggested dependency receive attacker-controlled code.",
    eli: "Attackers publishing fake software packages with the names AI tends to make up, so people install them by mistake.",
    org: "Named in 2025 by analogy with typosquatting, after research showed models invent package names consistently enough for the mistake to be predictable and therefore exploitable.",
    ex: ["The suggested package did not exist until someone registered it.", "A hallucination becomes a supply chain problem once it is reproducible."],
    rel: ["hallucination", "vibe-coding", "red-teaming"], tags: ["security", "supply-chain", "2025"],
  },
  {
    slug: "em-dash-tell", term: "The em dash tell", pron: "em dash tel", pos: "noun", cat: "ai",
    year: 2024, pop: 43, trend: 15, status: "rising",
    def: "Any surface feature taken as evidence that text was machine-generated: certain punctuation habits, particular adjectives, relentlessly balanced sentences.",
    eli: "Little writing habits people use to guess that text was written by an AI.",
    org: "Emerged in 2024 as generated writing became common. The tells are weak evidence individually and have caused a great deal of false accusation, particularly against non-native writers.",
    ex: ["Accused of using AI because of one punctuation mark.", "Detection by vibes has a serious false positive problem."],
    rel: ["ai-slop", "clanker", "hallucination"], tags: ["detection", "writing", "2025"],
  },
  {
    slug: "context-rot", term: "Context rot", pron: "KON-tekst rot", pos: "noun", cat: "ai",
    year: 2025, pop: 27, trend: 20, status: "rising",
    def: "Degradation in a model's performance as a conversation grows long, with earlier instructions effectively losing force even while technically still in the window.",
    eli: "When a long AI conversation slowly gets worse and the model forgets what you told it at the start.",
    org: "Named in 2025 as very large context windows made the gap between what fits and what is actually used obvious. It is why long sessions often benefit from a restart.",
    ex: ["Forty messages in and it has forgotten the format entirely.", "Fitting in the window is not the same as being attended to."],
    rel: ["context-window", "chain-of-thought", "agentic"], tags: ["limits", "practice", "2025"],
  },
  {
    slug: "human-in-the-loop", term: "Human in the loop", pron: "HYOO-mun in thuh loop", pos: "noun", cat: "ai",
    year: 2019, pop: 45, trend: 7, status: "mainstream",
    def: "A design requiring human review before an automated decision takes effect. Effective only if the reviewer has time, context and genuine authority to say no.",
    eli: "Making sure a person checks and approves what the AI decided before anything happens.",
    org: "Machine learning vocabulary that became a governance requirement in frameworks including the EU AI Act. Automation bias, where reviewers approve by default, is the standard failure.",
    ex: ["Human in the loop with four seconds per case is not oversight.", "The loop only works if the human can actually stop it."],
    rel: ["guardrails", "alignment", "agentic"], tags: ["governance", "regulation", "oversight"],
  },
];
