import type { RawTerm } from "../types";

export const animeTerms: RawTerm[] = [
  {
    slug: "weeb", term: "Weeb", pron: "weeb", pos: "noun", cat: "anime",
    year: 2005, pop: 58, trend: -2, status: "classic",
    def: "Someone with an intense enthusiasm for Japanese media, often to the point of affecting Japanese speech. Originally an insult, now largely self-applied.",
    eli: "Someone who is very into anime and Japanese culture. It used to be an insult and is now mostly a joke about yourself.",
    org: "Clipped from weeaboo, a nonsense word from a Perry Bible Fellowship comic that 4chan's word filter substituted for an older slur in 2005. The filter accidentally created the vocabulary.",
    ex: ["Full weeb behaviour: he has opinions about subtitle fonts.", "Reclaimed thoroughly enough that shops sell weeb merchandise."],
    rel: ["otaku", "waifu", "fansub"], tags: ["4chan", "identity", "japan"],
  },
  {
    slug: "otaku", term: "Otaku", pron: "oh-TAH-koo", pos: "noun", cat: "anime",
    year: 1983, pop: 52, trend: 0, status: "classic",
    def: "A person with obsessive interests, particularly in anime and manga. In Japanese the word carries a stigma that the English borrowing largely lost.",
    eli: "Someone deeply obsessed with a hobby, especially anime. In Japan the word is more negative than in English.",
    org: "Coined in Japanese usage by writer Akio Nakamori in 1983, from a formal word for your house used oddly by fans addressing each other. English adopted it neutrally in the 1990s.",
    ex: ["Otaku in the English sense is almost a compliment.", "The Japanese connotation is closer to shut-in than to enthusiast."],
    rel: ["weeb", "doujinshi", "moe"], tags: ["japan", "identity", "fandom"],
  },
  {
    slug: "waifu", term: "Waifu", pron: "WY-foo", pos: "noun", cat: "anime",
    year: 2007, pop: 55, trend: -1, status: "classic",
    def: "A fictional character a fan claims as a spouse, usually with knowing exaggeration. Husbando is the masculine counterpart, formed by the same joke.",
    eli: "A cartoon character someone jokingly calls their wife.",
    org: "From a line in the 2002 anime Azumanga Daioh, in which a character says my waifu in accented English. Imageboards adopted it around 2007.",
    ex: ["Waifu wars in the replies again.", "Husbando was coined by applying the same accent to the other word."],
    rel: ["best-girl", "weeb", "otaku"], tags: ["fandom", "characters", "japan"],
  },
  {
    slug: "best-girl", term: "Best girl", pron: "best gurl", pos: "noun", cat: "anime",
    year: 2010, pop: 47, trend: 0, status: "mainstream",
    def: "A declaration that a particular character is the finest in a series. Rarely a considered judgement and always an invitation to argue.",
    eli: "Saying which character in a show is your favourite, usually to start a friendly argument.",
    org: "Imageboard and forum vocabulary that formalised an existing habit into a contestable title, complete with tournaments and bracket voting.",
    ex: ["Objectively best girl, and I will take questions.", "The best girl bracket ran for six weeks."],
    rel: ["waifu", "ship", "power-scaling"], tags: ["fandom", "debate", "characters"],
  },
  {
    slug: "senpai", term: "Senpai", pron: "SEN-pye", pos: "noun", cat: "anime",
    year: 2012, pop: 49, trend: -4, status: "mainstream",
    def: "A senior colleague or older student. In English it became shorthand for anyone whose attention you want, chiefly through the phrase notice me senpai.",
    eli: "A Japanese word for an older student or colleague, used online to mean someone whose attention you want.",
    org: "A genuine Japanese social term describing a real hierarchy. English internet use flattened it into a joke about unrequited attention around 2012.",
    ex: ["Notice me, senpai.", "The actual senpai and kohai relationship is a workplace structure, not a romance."],
    rel: ["weeb", "waifu", "kawaii"], tags: ["japan", "hierarchy", "loanword"],
  },
  {
    slug: "kawaii", term: "Kawaii", pron: "kuh-WY-ee", pos: "adjective", cat: "anime",
    year: 1970, pop: 56, trend: 0, status: "classic",
    def: "Cute, in a specific Japanese aesthetic sense covering smallness, roundness and vulnerability. A major cultural export, not merely a translation of cute.",
    eli: "The Japanese idea of cuteness, with its own particular style.",
    org: "Emerged as a youth aesthetic in 1970s Japan, spreading through handwriting styles, Sanrio characters and fashion. It became one of Japan's most successful cultural exports.",
    ex: ["The whole stationery aisle is aggressively kawaii.", "Kawaii is a design tradition, not just an adjective."],
    rel: ["moe", "chibi", "uwu"], tags: ["japan", "aesthetic", "design"],
  },
  {
    slug: "moe", term: "Moe", pron: "MOH-eh", pos: "noun", cat: "anime",
    year: 2000, pop: 38, trend: -1, status: "niche",
    def: "A protective affection felt toward a fictional character, and the design vocabulary engineered to produce it. A commercial category as much as a feeling.",
    eli: "The warm protective feeling some characters are designed to make you feel.",
    org: "Japanese fan vocabulary of the late 1990s, literally budding. By the 2000s moe had become an explicit design brief for character artists rather than an accidental effect.",
    ex: ["The character design is pure moe engineering.", "Moe describes an effect on the audience, not a trait of the character."],
    rel: ["kawaii", "waifu", "chibi"], tags: ["japan", "design", "affect"],
  },
  {
    slug: "tsundere", term: "Tsundere", pron: "tsoon-DEH-reh", pos: "noun", cat: "anime",
    year: 2002, pop: 45, trend: -2, status: "classic",
    def: "A character type that is cold or hostile on the surface and affectionate underneath. One of a family of dere archetypes including yandere and kuudere.",
    eli: "A character who acts mean but secretly cares a lot.",
    org: "Japanese fan vocabulary from the early 2000s, blending tsuntsun for aloof and deredere for lovestruck. The taxonomy grew into a whole classification system.",
    ex: ["Textbook tsundere, right down to the it is not like I like you.", "The dere taxonomy has at least a dozen branches."],
    rel: ["yandere", "best-girl", "moe"], tags: ["archetype", "japan", "characters"],
  },
  {
    slug: "yandere", term: "Yandere", pron: "yan-DEH-reh", pos: "noun", cat: "anime",
    year: 2005, pop: 40, trend: 0, status: "niche",
    def: "A character whose affection becomes obsessive and dangerous. Formed from yanderu, to be mentally unwell, plus the same dere ending as tsundere.",
    eli: "A character whose love for someone turns frightening and possessive.",
    org: "Coined in Japanese fan discussion in the mid-2000s as the dere taxonomy expanded. The archetype long predates the label.",
    ex: ["It stops being romantic and becomes yandere around episode six.", "The yandere archetype is a horror trope wearing a romance costume."],
    rel: ["tsundere", "best-girl", "moe"], tags: ["archetype", "japan", "horror"],
  },
  {
    slug: "isekai", term: "Isekai", pron: "ee-SEK-eye", pos: "noun", cat: "anime",
    year: 2012, pop: 57, trend: 6, status: "mainstream",
    def: "A genre in which an ordinary person is transported to another world, usually one resembling a video game. Frequently begins with the protagonist being hit by a truck.",
    eli: "Stories where someone from our world wakes up in a fantasy world, often after an accident.",
    org: "Japanese for other world. The genre existed for decades but exploded after 2012 through web novel platforms, becoming so dominant that competitions began banning it.",
    ex: ["Another isekai where he is overpowered by episode two.", "Truck-kun has become a genre in-joke."],
    rel: ["shonen", "power-scaling", "gacha"], tags: ["genre", "japan", "web-novels"],
  },
  {
    slug: "shonen", term: "Shonen", pron: "SHOH-nen", pos: "noun", cat: "anime",
    year: 1995, pop: 61, trend: 2, status: "classic",
    def: "Manga and anime aimed at teenage boys, characterised by escalating fights, training arcs and friendship. A demographic category, not a genre.",
    eli: "Anime and manga made for teenage boys, usually with fighting and friendship.",
    org: "A Japanese publishing demographic, alongside shojo, seinen and josei. English fandom often treats these as genres, which annoys people who know the distinction.",
    ex: ["Classic shonen structure: tournament, then a training arc.", "Shonen is who it is sold to, not what it is about."],
    rel: ["isekai", "power-scaling", "arc"], tags: ["genre", "publishing", "japan"],
  },
  {
    slug: "power-scaling", term: "Power scaling", pron: "POW-ur SKAY-ling", pos: "noun", cat: "anime",
    year: 2010, pop: 44, trend: 5, status: "mainstream",
    def: "The practice of ranking fictional characters by strength across works, using feats as evidence. An entire argument culture with its own citation norms.",
    eli: "Arguing about which fictional character would win a fight, using examples from the story as proof.",
    org: "Forum and YouTube fandom, formalised through versus debate communities. The rules about what counts as a valid feat are genuinely elaborate.",
    ex: ["The power scaling video is fifty minutes and cites nine chapters.", "Every power scaling argument eventually becomes a definitions argument."],
    rel: ["shonen", "best-girl", "lore"], tags: ["debate", "fandom", "youtube"],
  },
  {
    slug: "fansub", term: "Fansub", pron: "FAN-sub", pos: "noun", cat: "anime",
    year: 1986, pop: 36, trend: -3, status: "classic",
    def: "An unofficial subtitled release produced by volunteers, often with translation notes and elaborate typesetting. The main route anime reached the West before licensing caught up.",
    eli: "Subtitles made by fans for shows that had no official translation.",
    org: "Began with VHS tape trading in the 1980s and moved to digital distribution in the 1990s. Many fansub groups shut down voluntarily once official simulcasts arrived.",
    ex: ["The fansub had four lines of translation notes on screen at once.", "Fansubbing built the audience that legal streaming later sold to."],
    rel: ["scanlation", "sub-vs-dub", "weeb"], tags: ["translation", "piracy", "history"],
  },
  {
    slug: "scanlation", term: "Scanlation", pron: "skan-LAY-shun", pos: "noun", cat: "anime",
    year: 2000, pop: 34, trend: 1, status: "classic",
    def: "Scanned manga translated and re-lettered by volunteers. The print equivalent of fansubbing, with the same ambiguous relationship to licensing.",
    eli: "Comics scanned in and translated by fans instead of by the publisher.",
    org: "A blend of scan and translation, emerging as home scanners became common around 2000. Groups developed conventions for cleaning, redrawing and typesetting that publishers later copied.",
    ex: ["The scanlation was three years ahead of the official release.", "Cleaning and redrawing is more work than the translation."],
    rel: ["fansub", "doujinshi", "mangaka"], tags: ["translation", "manga", "volunteers"],
  },
  {
    slug: "sub-vs-dub", term: "Sub versus dub", pron: "sub VUR-sus dub", pos: "noun", cat: "anime",
    year: 1995, pop: 48, trend: 0, status: "classic",
    def: "The perennial argument over whether anime should be watched subtitled or dubbed. The oldest unresolved dispute in Western anime fandom.",
    eli: "The long-running argument about whether to read subtitles or listen to English voices.",
    org: "Dates to the earliest Western releases, when dubs were often heavily rewritten. Dub quality improved enormously, but the argument continued out of habit.",
    ex: ["Thirty years and the sub versus dub thread still runs weekly.", "Accessibility is the argument that usually ends it."],
    rel: ["fansub", "weeb", "otaku"], tags: ["debate", "translation", "fandom"],
  },
  {
    slug: "sakuga", term: "Sakuga", pron: "sah-KOO-gah", pos: "noun", cat: "anime",
    year: 2010, pop: 31, trend: 4, status: "niche",
    def: "A sequence of unusually high animation quality, and the fan practice of following individual animators by their distinctive style.",
    eli: "A part of an anime that is animated far better than the rest, and the hobby of spotting who drew it.",
    org: "Japanese for drawing pictures. English fandom adopted it around 2010 to name a specialist form of appreciation that credits animators rather than studios.",
    ex: ["That thirty-second cut is pure sakuga.", "Sakuga fandom is the closest anime has to auteur criticism."],
    rel: ["mangaka", "shonen", "arc"], tags: ["animation", "craft", "japan"],
  },
  {
    slug: "mangaka", term: "Mangaka", pron: "MAN-gah-kah", pos: "noun", cat: "anime",
    year: 1998, pop: 39, trend: 1, status: "classic",
    def: "A manga author-artist, typically responsible for story and art together, working to weekly deadlines that are notorious even within publishing.",
    eli: "A person who writes and draws manga, usually doing both jobs themselves.",
    org: "A straightforward Japanese occupational term adopted by English fandom. The working conditions it describes have been the subject of sustained criticism and several high-profile health crises.",
    ex: ["The mangaka draws twenty pages a week with three assistants.", "Serialisation schedules are the industry's open wound."],
    rel: ["scanlation", "doujinshi", "sakuga"], tags: ["manga", "japan", "labour"],
  },
  {
    slug: "doujinshi", term: "Doujinshi", pron: "doh-jin-SHEE", pos: "noun", cat: "anime",
    year: 1975, pop: 33, trend: 1, status: "classic",
    def: "Self-published work, often fan comics using existing characters, sold at conventions. A large parallel economy that publishers mostly tolerate deliberately.",
    eli: "Fan-made comics that people print and sell themselves at conventions.",
    org: "Comiket, founded in Tokyo in 1975, is the largest such event and draws hundreds of thousands of attendees. Several major professional creators started in doujinshi.",
    ex: ["Comiket moves more printed matter in three days than most publishers do in a year.", "The tolerance is strategic: it is where new talent is found."],
    rel: ["mangaka", "fanfic", "scanlation"], tags: ["japan", "publishing", "fandom"],
  },
  {
    slug: "chibi", term: "Chibi", pron: "CHEE-bee", pos: "noun", cat: "anime",
    year: 2000, pop: 41, trend: 0, status: "classic",
    def: "A deliberately shortened art style with an oversized head and tiny body, used for comic or affectionate effect within otherwise realistic work.",
    eli: "Drawing characters small and cute with big heads, usually for funny moments.",
    org: "Japanese for short or small. The style functions grammatically rather than decoratively: switching to chibi signals that a scene is not to be read seriously.",
    ex: ["The argument is played in chibi so you know it is comic.", "It is a register change, not just a cute drawing."],
    rel: ["kawaii", "moe", "sakuga"], tags: ["art", "japan", "style"],
  },
  {
    slug: "arc", term: "Arc", pron: "ark", pos: "noun", cat: "anime",
    year: 2005, pop: 63, trend: 4, status: "mainstream",
    def: "A self-contained stretch of a longer story. Applied to real life, having an arc means going through a phase with a recognisable shape and, ideally, a lesson.",
    eli: "A section of a long story with its own beginning and end. People also use it about phases of their own life.",
    org: "Screenwriting vocabulary that shonen fandom made everyday, since long-running series are structured explicitly as named arcs. Applying it to yourself followed around 2020.",
    ex: ["Currently in my learning-to-cook arc.", "The training arc is a whole structural convention."],
    rel: ["shonen", "era", "canon-event"], tags: ["narrative", "structure", "identity"],
  },
  {
    slug: "cosplay", term: "Cosplay", pron: "KOZ-play", pos: "noun", cat: "anime",
    year: 1984, pop: 66, trend: 2, status: "classic",
    def: "Dressing as a character, treated as a craft discipline covering construction, fabrication and performance rather than simply wearing a costume.",
    eli: "Dressing up as a character from a show, film or game, often making the costume yourself.",
    org: "Coined by Japanese journalist Nobuyuki Takahashi in 1984 after visiting a US science fiction convention, blending costume and play. The practice long predates the word.",
    ex: ["Nine months of build time for one weekend.", "Judged on construction, not on resemblance alone."],
    rel: ["otaku", "doujinshi", "weeb"], tags: ["craft", "conventions", "japan"],
  },
  {
    slug: "seinen", term: "Seinen", pron: "SAY-nen", pos: "noun", cat: "anime",
    year: 1995, pop: 38, trend: 2, status: "classic",
    def: "Manga aimed at adult men, typically slower and more morally ambiguous than shonen. Josei is the corresponding category for adult women.",
    eli: "Manga made for adult men, usually more serious than the teenage kind.",
    org: "A Japanese publishing demographic rather than a genre. English fandom often uses it as a quality marker, which annoys people who know it only describes the intended readership.",
    ex: ["Seinen is a shelf in a shop, not a compliment.", "The same story could run in either magazine with different framing."],
    rel: ["shonen", "mangaka", "isekai"], tags: ["publishing", "japan", "demographic"],
  },
  {
    slug: "filler", term: "Filler", pron: "FIL-ur", pos: "noun", cat: "anime",
    year: 2005, pop: 44, trend: 0, status: "classic",
    def: "Anime episodes with no basis in the source manga, produced to stop the adaptation overtaking its own material. Fan-maintained filler lists are standard reference works.",
    eli: "Episodes made up for the anime that were not in the original comic, often skippable.",
    org: "A structural consequence of adapting a weekly manga into a weekly anime. Long-running series accumulated hundreds of filler episodes and, inevitably, community guides to avoiding them.",
    ex: ["Skip 54 to 61, pure filler.", "The filler list is more carefully maintained than most wikis."],
    rel: ["arc", "shonen", "sakuga"], tags: ["adaptation", "production", "fandom"],
  },
  {
    slug: "op-ed-anime", term: "OP and ED", pron: "oh-PEE and ee-DEE", pos: "abbreviation", cat: "anime",
    year: 2005, pop: 34, trend: 1, status: "niche",
    def: "The opening and ending title sequences, treated as significant works in themselves and often changed several times across a series.",
    eli: "The opening and closing title songs and animations of an anime.",
    org: "A production convention that fandom elevated into a genre of its own. Openings are frequently animated by different teams and analysed independently of the episodes.",
    ex: ["Never skip the OP on this one.", "The ED spoils the entire final arc if you look closely."],
    rel: ["sakuga", "arc", "filler"], tags: ["music", "animation", "convention"],
  },
  {
    slug: "nakama", term: "Nakama", pron: "nah-KAH-mah", pos: "noun", cat: "anime",
    year: 2005, pop: 30, trend: 0, status: "niche",
    def: "Comrades bound by chosen loyalty rather than blood. English fandom treats it as untranslatable, which is contested but tells you how it is used.",
    eli: "A group of friends who are as close as family because they chose each other.",
    org: "A common Japanese word for companion, elevated by One Piece fandom into something more freighted. Translators generally consider the untranslatable framing an overstatement.",
    ex: ["The nakama speech is a structural requirement of the genre.", "It means companion; fandom made it mean more."],
    rel: ["shonen", "arc", "weeb"], tags: ["loanword", "one-piece", "friendship"],
  },
  {
    slug: "gap-moe", term: "Gap moe", pron: "gap MOH-eh", pos: "noun", cat: "anime",
    year: 2010, pop: 24, trend: 1, status: "niche",
    def: "Appeal generated by a contrast between how a character seems and how they behave: the intimidating one who likes knitting.",
    eli: "When a character is charming because they are the opposite of what you expected.",
    org: "Japanese fan vocabulary naming a specific mechanism within moe. The precision of the taxonomy is characteristic of the scene.",
    ex: ["Gap moe is why the terrifying one bakes.", "The contrast is the whole device."],
    rel: ["moe", "tsundere", "chibi"], tags: ["archetype", "japan", "characters"],
  },
  {
    slug: "cour", term: "Cour", pron: "koor", pos: "noun", cat: "anime",
    year: 2010, pop: 26, trend: 1, status: "niche",
    def: "A production block of roughly twelve or thirteen episodes, aligned to a Japanese broadcast quarter. Series are commissioned in cours, not in seasons.",
    eli: "A block of about twelve anime episodes, matching one three-month broadcast season.",
    org: "From the French cours, adopted into Japanese scheduling vocabulary and then into English fandom. It explains why so many series stop abruptly at episode twelve.",
    ex: ["One cour, twelve episodes, no ending.", "Split cour means a gap and then more."],
    rel: ["filler", "arc", "seinen"], tags: ["production", "scheduling", "japan"],
  },
  {
    slug: "power-creep", term: "Power creep", pron: "POW-ur kreep", pos: "noun", cat: "anime",
    year: 2012, pop: 35, trend: 2, status: "mainstream",
    def: "The tendency of long-running series and games to escalate capability until earlier threats become trivial and stakes stop registering.",
    eli: "When each new enemy or character is stronger than the last, until the old ones seem pointless.",
    org: "Trading card game vocabulary, where each set had to outsell the last, applied to shonen and to gacha games. Both face the same structural pressure.",
    ex: ["The first arc villain could not survive the current opening credits.", "Escalation is easier to write than tension."],
    rel: ["shonen", "power-scaling", "gacha"], tags: ["design", "narrative", "escalation"],
  },
];
