import type { RawTerm } from "../types";

export const datingTerms: RawTerm[] = [
  {
    slug: "ghosting", term: "Ghosting", pron: "GOHST-ing", pos: "noun", cat: "dating",
    year: 2015, pop: 88, trend: 0, status: "mainstream",
    def: "Ending a relationship by ceasing all contact without explanation, leaving the other person to infer what happened.",
    eli: "Disappearing on someone completely instead of telling them it is over.",
    org: "Named around 2015 as dating apps made low-cost disappearance easy. The behaviour is old; what changed is that there is now no shared social network to make it costly.",
    ex: ["Three months of daily messages, then nothing. Ghosted.", "Recruiters ghost candidates as routinely as anyone ghosts a date."],
    rel: ["slow-fade", "orbiting", "zombieing"], tags: ["apps", "endings", "communication"],
  },
  {
    slug: "slow-fade", term: "Slow fade", pron: "sloh fayd", pos: "noun", cat: "dating",
    year: 2016, pop: 52, trend: 1, status: "mainstream",
    def: "Gradually reducing contact until the relationship expires, so that neither party has to say it is over. Ghosting spread across several weeks.",
    eli: "Slowly replying less and less until the relationship quietly ends.",
    org: "Named alongside ghosting as the vocabulary of app-era endings expanded. Some argue it is kinder than ghosting; others that the ambiguity makes it worse.",
    ex: ["Replies went from minutes to days to never. Slow fade.", "The slow fade lets you avoid the conversation and the guilt."],
    rel: ["ghosting", "breadcrumbing", "dry-texting"], tags: ["apps", "endings", "avoidance"],
  },
  {
    slug: "breadcrumbing", term: "Breadcrumbing", pron: "BRED-krum-ing", pos: "noun", cat: "dating",
    year: 2016, pop: 57, trend: 3, status: "mainstream",
    def: "Giving someone just enough intermittent attention to keep them interested, without any intention of committing.",
    eli: "Sending someone occasional messages to keep them hoping, without ever meaning to take it further.",
    org: "From the fairy-tale trail of crumbs. The pattern maps precisely onto intermittent reinforcement, which is the most durable conditioning schedule known.",
    ex: ["One story reply a fortnight is breadcrumbing.", "Breadcrumbing works because unpredictable rewards are the hardest to give up."],
    rel: ["benching", "orbiting", "slow-fade"], tags: ["apps", "manipulation", "attention"],
  },
  {
    slug: "benching", term: "Benching", pron: "BENCH-ing", pos: "noun", cat: "dating",
    year: 2016, pop: 42, trend: 0, status: "mainstream",
    def: "Keeping someone in reserve as a fallback option while pursuing others, from the sporting practice of naming substitutes.",
    eli: "Keeping someone waiting as a backup while you see other people.",
    org: "Coined in a 2016 New York magazine piece cataloguing app-era behaviours. The sports metaphor makes the hierarchy explicit in a way earlier vocabulary did not.",
    ex: ["Benched for four months and told he was busy.", "Everyone on the roster is being benched by someone."],
    rel: ["breadcrumbing", "roster", "cushioning"], tags: ["apps", "hierarchy", "reserve"],
  },
  {
    slug: "orbiting", term: "Orbiting", pron: "OR-bit-ing", pos: "noun", cat: "dating",
    year: 2018, pop: 47, trend: 2, status: "mainstream",
    def: "Cutting off direct contact while continuing to watch and react to someone's posts, staying visible without engaging.",
    eli: "Someone who stops talking to you but keeps watching all your stories.",
    org: "Named in 2018, describing a behaviour only possible once platforms made passive observation both easy and visible through read receipts and viewer lists.",
    ex: ["Has not replied since March but watches every story. Orbiting.", "Orbiting exists because the platform tells you who is looking."],
    rel: ["ghosting", "haunting", "zombieing"], tags: ["apps", "watching", "instagram"],
  },
  {
    slug: "zombieing", term: "Zombieing", pron: "ZOM-bee-ing", pos: "noun", cat: "dating",
    year: 2017, pop: 40, trend: 1, status: "mainstream",
    def: "Reappearing without explanation after having ghosted, usually with a casual message pretending no absence occurred.",
    eli: "Someone who disappeared on you suddenly messaging again as if nothing happened.",
    org: "Named around 2017 as the natural sequel to ghosting. The opening message is almost always a single lowercase word.",
    ex: ["Ghosted in January, zombied in November with a hey stranger.", "The zombie always resurfaces when their other option falls through."],
    rel: ["ghosting", "orbiting", "haunting"], tags: ["apps", "return", "avoidance"],
  },
  {
    slug: "love-bombing", term: "Love bombing", pron: "luv BOM-ing", pos: "noun", cat: "dating",
    year: 2017, pop: 66, trend: 7, status: "rising",
    def: "Overwhelming someone with attention and affection early on, creating rapid attachment that is later withdrawn. A recognised coercive-control tactic, not merely enthusiasm.",
    eli: "Showering someone with attention very fast to make them attached, then taking it away.",
    org: "Originally described recruitment practices in high-control groups in the 1970s. Applied to intimate relationships and popularised online after 2017, sometimes loosely.",
    ex: ["Four dates in and he was planning a holiday. Love bombing.", "Enthusiasm becomes love bombing when the withdrawal arrives."],
    rel: ["negging", "red-flag", "breadcrumbing"], tags: ["manipulation", "psychology", "warning"],
  },
  {
    slug: "negging", term: "Negging", pron: "NEG-ing", pos: "noun", cat: "dating",
    year: 2005, pop: 44, trend: -3, status: "classic",
    def: "Delivering a backhanded compliment intended to lower someone's confidence and make their approval feel more valuable to obtain.",
    eli: "Giving someone an insult disguised as a compliment to make them want your approval.",
    org: "Pickup-artist vocabulary popularised by Neil Strauss's 2005 book The Game. The term outlived the subculture and is now used mainly to name the tactic critically.",
    ex: ["You are pretty for someone who does not try is a neg.", "Negging is named far more often than it is attempted now."],
    rel: ["love-bombing", "red-flag", "pick-me"], tags: ["manipulation", "pickup", "criticism"],
  },
  {
    slug: "catfishing", term: "Catfishing", pron: "KAT-fish-ing", pos: "noun", cat: "dating",
    year: 2010, pop: 72, trend: 1, status: "classic",
    def: "Maintaining a fake online identity to deceive someone into a relationship, using stolen photographs and an invented biography.",
    eli: "Pretending to be someone else online, with fake photos, to trick someone into a relationship.",
    org: "From the 2010 documentary Catfish and the television series that followed. The name comes from an anecdote in the film about catfish keeping cod active in transit.",
    ex: ["Reverse image search ended the catfishing in four seconds.", "Refusing every video call for a year is the classic sign."],
    rel: ["kittenfishing", "sockpuppet", "red-flag"], tags: ["deception", "identity", "television"],
  },
  {
    slug: "kittenfishing", term: "Kittenfishing", pron: "KIT-un-fish-ing", pos: "noun", cat: "dating",
    year: 2017, pop: 33, trend: 0, status: "niche",
    def: "Mild self-misrepresentation on a dating profile: old photographs, adjusted height, a job title with some optimism. Catfishing at low intensity.",
    eli: "Making yourself look a bit better than you really are on a dating profile.",
    org: "Coined by Hinge in 2017 as a deliberately gentler counterpart to catfishing, naming the ordinary exaggeration almost everyone commits.",
    ex: ["Photos from 2015 and a two-inch height adjustment. Kittenfishing.", "Kittenfishing is normal, which is why it needed a softer word."],
    rel: ["catfishing", "swipe", "talking-stage"], tags: ["apps", "profiles", "honesty"],
  },
  {
    slug: "swipe", term: "Swipe", pron: "swype", pos: "verb", cat: "dating",
    year: 2012, pop: 79, trend: -1, status: "classic",
    def: "To accept or reject a profile with a directional gesture. The interaction that reshaped dating into a sorting task performed at speed.",
    eli: "Flicking a dating profile left or right to say no or yes.",
    org: "Introduced by Tinder in 2012. The mechanic borrowed from card sorting and turned partner selection into something closer to triage, with well-documented effects on behaviour.",
    ex: ["Two hundred swipes and one conversation.", "The swipe made rejection frictionless in both directions."],
    rel: ["kittenfishing", "talking-stage", "roster"], tags: ["apps", "tinder", "interface"],
  },
  {
    slug: "talking-stage", term: "Talking stage", pron: "TAWK-ing stayj", pos: "noun", cat: "dating",
    year: 2019, pop: 68, trend: 8, status: "rising",
    def: "The period of sustained conversation before anything is defined, which may last months and may never resolve into a relationship.",
    eli: "The long period of messaging someone before you are actually together.",
    org: "Emerged in the late 2010s to name a stage that dating apps effectively invented, sitting between matching and dating with no agreed rules or endpoint.",
    ex: ["Six weeks in the talking stage and no plans made.", "The talking stage is where most app connections quietly expire."],
    rel: ["situationship", "dtr", "swipe"], tags: ["apps", "stages", "ambiguity"],
  },
  {
    slug: "dtr", term: "DTR", pron: "dee-tee-AR", pos: "abbreviation", cat: "dating",
    year: 2010, pop: 41, trend: 2, status: "mainstream",
    def: "Define the relationship: the explicit conversation about what two people are to each other, widely dreaded and frequently postponed.",
    eli: "The talk where you decide what you actually are to each other.",
    org: "Campus vocabulary from the 2000s that spread online as undefined arrangements became the norm. The situationship is what happens when the DTR never occurs.",
    ex: ["Finally had the DTR after eight months.", "Avoiding the DTR is itself an answer."],
    rel: ["talking-stage", "situationship", "hard-launch"], tags: ["conversation", "commitment", "apps"],
  },
  {
    slug: "hard-launch", term: "Hard launch", pron: "hard lawnch", pos: "noun", cat: "dating",
    year: 2021, pop: 58, trend: 4, status: "mainstream",
    def: "Announcing a relationship publicly and unambiguously, with a face and usually a caption. The counterpart to the soft launch.",
    eli: "Openly posting that you are with someone, showing their face.",
    org: "Borrowed from product marketing alongside soft launch. The pairing formalised what had been an informal sequence of hints followed by confirmation.",
    ex: ["Soft launched in March, hard launched at the wedding.", "The hard launch is the point of no return for the group chat."],
    rel: ["soft-launch", "dtr", "situationship"], tags: ["instagram", "announcement", "public"],
  },
  {
    slug: "roster", term: "Roster", pron: "ROS-tur", pos: "noun", cat: "dating",
    year: 2016, pop: 45, trend: 2, status: "mainstream",
    def: "The set of people someone is casually seeing at once, managed with the vocabulary of team selection. Rotation is the equivalent term.",
    eli: "The group of people someone is dating at the same time.",
    org: "Sports metaphor that spread with app dating, where seeing several people simultaneously became both normal and administratively demanding.",
    ex: ["Cut the roster down to two and immediately felt calmer.", "Managing a roster is a scheduling problem before it is a romantic one."],
    rel: ["benching", "cushioning", "swipe"], tags: ["apps", "multiple", "sports"],
  },
  {
    slug: "cushioning", term: "Cushioning", pron: "KUSH-un-ing", pos: "noun", cat: "dating",
    year: 2017, pop: 36, trend: 0, status: "niche",
    def: "Maintaining flirtatious contact with others while in a relationship, so that a breakup would have a soft landing rather than a hard one.",
    eli: "Keeping other people interested while you are with someone, just in case.",
    org: "Named in the 2017 wave of dating vocabulary. It describes hedging rather than cheating, which is precisely why it needed its own word.",
    ex: ["Three cushions in the DMs and a partner at home.", "Cushioning is insurance, which is what makes it feel dishonest."],
    rel: ["benching", "roster", "breadcrumbing"], tags: ["apps", "hedging", "commitment"],
  },
  {
    slug: "cuffing-season", term: "Cuffing season", pron: "KUF-ing SEE-zun", pos: "noun", cat: "dating",
    year: 2011, pop: 54, trend: 0, status: "classic",
    def: "The colder months, when people are said to seek short-term relationships for warmth and company, ending them around spring.",
    eli: "The winter months when people are more likely to want a relationship.",
    org: "African American Vernacular English, from being handcuffed to someone. App data does show measurable seasonal spikes, so the folk theory has some support.",
    ex: ["Cuffing season starts the week the clocks change.", "Every dating app runs a cuffing season campaign now."],
    rel: ["roster", "talking-stage", "swipe"], tags: ["seasonal", "aave", "apps"],
  },
  {
    slug: "left-on-read", term: "Left on read", pron: "left on red", pos: "phrase", cat: "dating",
    year: 2014, pop: 76, trend: 2, status: "mainstream",
    def: "Having a message visibly seen and not answered. Only possible because platforms report when a message has been opened.",
    eli: "When someone reads your message and does not reply, and you can see that they read it.",
    org: "Created by read receipts, which turned silence into a documented event. The feature manufactured an entire category of social injury that did not previously exist.",
    ex: ["Left on read for eleven hours.", "Turning off read receipts is a whole personality decision."],
    rel: ["dry-texting", "ghosting", "slow-fade"], tags: ["messaging", "receipts", "silence"],
  },
  {
    slug: "dry-texting", term: "Dry texting", pron: "dry TEKS-ting", pos: "noun", cat: "dating",
    year: 2019, pop: 61, trend: 5, status: "rising",
    def: "Replying with minimal effort, such as one-word answers that end conversations rather than continuing them. Technically a response, functionally a refusal.",
    eli: "Replying with very short boring answers so the conversation dies.",
    org: "Named on TikTok around 2019. It describes the middle ground between engagement and silence that read receipts made newly legible.",
    ex: ["Three days of lol and ok. Dry texting.", "Dry texting is ghosting with extra steps."],
    rel: ["left-on-read", "slow-fade", "ick"], tags: ["messaging", "effort", "tiktok"],
  },
  {
    slug: "pocketing", term: "Pocketing", pron: "POK-it-ing", pos: "noun", cat: "dating",
    year: 2019, pop: 34, trend: 1, status: "niche",
    def: "Keeping a partner away from your friends and family, so the relationship exists in isolation. Also called stashing.",
    eli: "Dating someone but never introducing them to anyone you know.",
    org: "Named around 2019. It is usually a sign of ambivalence rather than secrecy, which is why it is more common than outright hiding.",
    ex: ["Eight months and she has not met a single friend. Pocketing.", "Pocketing is what happens when someone will not decide."],
    rel: ["hard-launch", "cushioning", "situationship"], tags: ["isolation", "commitment", "apps"],
  },
  {
    slug: "monkey-branching", term: "Monkey branching", pron: "MUN-kee BRANCH-ing", pos: "noun", cat: "dating",
    year: 2018, pop: 30, trend: 0, status: "niche",
    def: "Securing the next relationship before leaving the current one, never letting go of one branch until holding another.",
    eli: "Lining up the next partner before ending things with the current one.",
    org: "Relationship-advice forums of the late 2010s. The image is of a monkey swinging without ever being unsupported.",
    ex: ["New relationship announced nine days later. Monkey branching.", "Cushioning is the preparation, monkey branching is the execution."],
    rel: ["cushioning", "benching", "roster"], tags: ["overlap", "forums", "endings"],
  },
  {
    slug: "curving", term: "Curving", pron: "KUR-ving", pos: "noun", cat: "dating",
    year: 2017, pop: 32, trend: 0, status: "niche",
    def: "Deflecting someone's interest politely and indefinitely rather than rejecting them outright, so the hint is never quite explicit.",
    eli: "Turning someone down gently and vaguely instead of saying no clearly.",
    org: "Named around 2017 as a softer sibling of ghosting. It keeps the door nominally open, which is either kindness or cowardice depending on who is describing it.",
    ex: ["Curved every invitation for a month without once saying no.", "A clear no is kinder than a long curve."],
    rel: ["breadcrumbing", "slow-fade", "dry-texting"], tags: ["rejection", "avoidance", "apps"],
  },
  {
    slug: "haunting", term: "Haunting", pron: "HAWNT-ing", pos: "noun", cat: "dating",
    year: 2018, pop: 31, trend: 0, status: "niche",
    def: "Lingering at the edge of someone's online life after a relationship ends: liking old posts, appearing in viewer lists, never messaging.",
    eli: "An ex who never messages but keeps showing up in your notifications.",
    org: "Named alongside orbiting and zombieing in the 2018 wave. All three describe presence without contact, which platforms made possible and then made visible.",
    ex: ["Liked a photo from 2019 at 2am. Haunting.", "The notification is the whole message."],
    rel: ["orbiting", "zombieing", "ghosting"], tags: ["exes", "watching", "instagram"],
  },
  {
    slug: "paperclipping", term: "Paperclipping", pron: "PAY-pur-klip-ing", pos: "noun", cat: "dating",
    year: 2019, pop: 26, trend: 0, status: "niche",
    def: "Resurfacing periodically to remind someone you exist, with no intention of meeting. Named after the Microsoft Office assistant that appeared uninvited.",
    eli: "Someone who pops up now and then just to be noticed, then disappears again.",
    org: "Coined in 2019, naming Clippy as the archetype of unwanted periodic reappearance. It is zombieing on a schedule.",
    ex: ["Paperclipped every four months for two years.", "It looks like a hi, and it is really a notification."],
    rel: ["zombieing", "breadcrumbing", "haunting"], tags: ["apps", "attention", "microsoft"],
  },
  {
    slug: "group-chat-consult", term: "Group chat consult", pron: "groop chat KON-sult", pos: "noun", cat: "dating",
    year: 2021, pop: 38, trend: 3, status: "niche",
    def: "The practice of screenshotting a message thread into a group chat for collective interpretation before replying.",
    eli: "Sending a screenshot of your messages to friends so they can help you decide what to say.",
    org: "A behaviour as old as group messaging, named informally in the 2020s as dating advice content made the practice visible and slightly self-conscious.",
    ex: ["Four friends spent an hour parsing one full stop.", "No reply is ever sent unread by committee."],
    rel: ["left-on-read", "dry-texting", "talking-stage"], tags: ["messaging", "friends", "advice"],
  },
  {
    slug: "soft-ghosting", term: "Soft ghosting", pron: "soft GOHST-ing", pos: "noun", cat: "dating",
    year: 2019, pop: 36, trend: 2, status: "niche",
    def: "Reacting to messages without replying to them, so contact is technically maintained while conversation is refused.",
    eli: "Liking someone's message instead of answering it, so you have not quite ignored them.",
    org: "Named once platforms added message reactions, which created a way of acknowledging without engaging. It is the smallest possible unit of avoidance.",
    ex: ["Liked the message and never answered it. Soft ghosting.", "The reaction button made a new category of rudeness possible."],
    rel: ["left-on-read", "ghosting", "curving"], tags: ["messaging", "avoidance", "reactions"],
  },
  {
    slug: "situationship-fatigue", term: "Situationship fatigue", pron: "sit-choo-AY-shun-ship fuh-TEEG", pos: "noun", cat: "dating",
    year: 2023, pop: 34, trend: 6, status: "rising",
    def: "Exhaustion with undefined arrangements, cited in surveys as a reason younger users are leaving dating apps for in-person meeting.",
    eli: "Being tired of relationships that are never properly defined.",
    org: "Named around 2023 as app usage fell among younger users for the first time. Run clubs and hobby groups being reframed as dating venues is a direct consequence.",
    ex: ["Deleted the apps and joined a run club. Situationship fatigue.", "The apps' own research shows the same trend."],
    rel: ["situationship", "talking-stage", "swipe"], tags: ["apps", "burnout", "2023"],
  },
  {
    slug: "fwb", term: "FWB", pron: "ef-dub-ul-yoo-BEE", pos: "abbreviation", cat: "dating",
    year: 1997, pop: 56, trend: 1, status: "classic",
    def: "Friends with benefits: a relationship combining friendship with a physical component, explicitly without the commitment or exclusivity of romantic partnership.",
    eli: "Two friends who are also physically involved, without being in an official relationship.",
    org: "In casual use since at least the 1990s, the abbreviation spread widely once dating-app profiles needed a compact way to state relationship intentions upfront.",
    ex: ["Started as FWB, ended up something more complicated.", "Put FWB in the bio and save everyone the conversation."],
    rel: ["situationship", "talking-stage", "dtr"], tags: ["relationships", "abbreviation", "classic"],
  },
  {
    slug: "himbo", term: "Himbo", pron: "HIM-boh", pos: "noun", cat: "dating",
    year: 1988, pop: 52, trend: 3, status: "mainstream",
    def: "An attractive man who is kind, uncomplicated and not especially sharp, treated as an entirely positive archetype rather than an insult.",
    eli: "A sweet, good-looking guy who is not that clever, described warmly rather than as a put-down.",
    org: "A blend of him and bimbo coined in the late 1980s, revived enthusiastically online after 2018 as fictional and real himbos were celebrated as a refreshingly low-drama ideal.",
    ex: ["He is a certified himbo and the internet adores him for it.", "Himbo energy: strong, gentle, occasionally cannot open a jar."],
    rel: ["soft-boy", "wife-guy", "clean-girl"], tags: ["archetype", "compliment", "internet"],
  },
  {
    slug: "soft-boy", term: "Soft boy", pron: "soft boy", pos: "noun", cat: "dating",
    year: 2017, pop: 44, trend: -2, status: "fading",
    def: "A man who cultivates a sensitive, emotionally literate public persona, sometimes sincerely and sometimes as a calculated method of attracting attention.",
    eli: "A guy who presents himself as very sensitive and in touch with his feelings, sometimes genuinely and sometimes as a tactic.",
    org: "Named on Twitter around 2017 as dating-app profiles increasingly performed vulnerability, with critics arguing the persona was often more strategic than sincere.",
    ex: ["Soft boy bio, questionable follow-through.", "Hard to tell a soft boy from someone who is actually just soft."],
    rel: ["himbo", "performative", "nonchalant"], tags: ["archetype", "dating-apps", "criticism"],
  },
  {
    slug: "wife-guy", term: "Wife guy", pron: "wyf gy", pos: "noun", cat: "dating",
    year: 2017, pop: 43, trend: -1, status: "mainstream",
    def: "A man whose public persona is built substantially around being married, constantly referencing his wife, which becomes suspicious to online audiences if the marriage later ends badly.",
    eli: "A man who talks about his wife constantly online as his whole personality, which people get suspicious of if the marriage falls apart.",
    org: "Named on Twitter around 2017 after several prominent wife guys were revealed to have behaved badly toward the wives they publicly celebrated, turning the label faintly ironic.",
    ex: ["Every wife guy makes people nervous for the wife.", "Being a wife guy is fine until it becomes your entire brand."],
    rel: ["himbo", "performative", "parasocial"], tags: ["twitter", "archetype", "irony"],
  },
  {
    slug: "gaslighting", term: "Gaslighting", pron: "GAS-lyt-ing", pos: "noun", cat: "dating",
    year: 1944, pop: 79, trend: 6, status: "mainstream",
    def: "Manipulating someone into doubting their own memory, perception or judgement, over time, in order to gain control over them.",
    eli: "Making someone doubt their own memory or sanity on purpose, so they rely on you instead of trusting themselves.",
    org: "Named after a 1938 stage play and its 1944 film adaptation, in which a husband manipulates his wife into believing she is losing her mind. The term entered clinical vocabulary decades later and general internet use heavily after 2016.",
    ex: ["Insisting the argument never happened is textbook gaslighting.", "Gaslighting is one of the most overused and most under-understood words online."],
    rel: ["love-bombing", "negging", "red-flag"], tags: ["manipulation", "psychology", "warning"],
  },
  {
    slug: "trauma-dumping", term: "Trauma dumping", pron: "TRAW-muh DUMP-ing", pos: "noun", cat: "dating",
    year: 2019, pop: 46, trend: 8, status: "rising",
    def: "Sharing distressing personal history with someone, often early in a relationship or with a stranger, without regard for whether they are prepared to receive it.",
    eli: "Telling someone heavy, personal problems without checking whether they are in a position to hear them.",
    org: "Distinguished from healthy vulnerability by therapists and popularised online around 2019, as a way of naming oversharing that burdens rather than builds trust.",
    ex: ["First date, full childhood history. That is trauma dumping.", "There is a difference between opening up and trauma dumping."],
    rel: ["love-bombing", "menty-b", "soft-boy"], tags: ["boundaries", "psychology", "communication"],
  },
  {
    slug: "future-faking", term: "Future faking", pron: "FYOO-chur FAY-king", pos: "noun", cat: "dating",
    year: 2018, pop: 41, trend: 5, status: "mainstream",
    def: "Making confident promises about a shared future, such as moving in together or meeting family, with no real intention of following through, in order to secure someone's continued investment.",
    eli: "Making big promises about the future of a relationship that never actually happen, just to keep someone interested.",
    org: "Named in relationship psychology writing around 2018 to describe a manipulation tactic distinct from ordinary hopeful planning, identifiable mainly by the pattern of promises never materialising.",
    ex: ["Two years of future faking and still no actual plans.", "Future faking works because it is genuinely hard to prove intent."],
    rel: ["love-bombing", "situationship", "breadcrumbing"], tags: ["manipulation", "psychology", "warning"],
  },
  {
    slug: "micro-cheating", term: "Micro-cheating", pron: "MY-kroh-CHEET-ing", pos: "noun", cat: "dating",
    year: 2018, pop: 39, trend: 3, status: "mainstream",
    def: "A small act that crosses an implicit boundary of a committed relationship without technically being infidelity, such as maintaining a flirtatious secret conversation.",
    eli: "A small thing that is not quite cheating but still crosses a line in a relationship, like secretly flirting with someone else.",
    org: "Named in relationship writing around 2018 to capture behaviour that feels like a betrayal without meeting the traditional definition of cheating, and remains genuinely contested as a category.",
    ex: ["Keeping the ex's messages hidden might count as micro-cheating.", "What counts as micro-cheating varies enormously between couples."],
    rel: ["gaslighting", "red-flag", "situationship"], tags: ["boundaries", "relationships", "debate"],
  },
  {
    slug: "dating-app-fatigue", term: "Dating app fatigue", pron: "DAY-ting ap fuh-TEEG", pos: "noun", cat: "dating",
    year: 2019, pop: 48, trend: 4, status: "mainstream",
    def: "Exhaustion and disillusionment from prolonged use of dating apps, characterised by declining effort, repeated small disappointments and a sense that the process has become a chore.",
    eli: "Feeling worn out and unenthusiastic about dating apps after using them for a long time without much luck.",
    org: "Named in dating and technology writing around 2019 as apps matured from a novelty into a years-long default experience for many single people, with genuine surveyed burnout to match.",
    ex: ["Deleted the apps again, dating app fatigue finally won.", "Dating app fatigue is basically its own stage of modern dating."],
    rel: ["swipe", "talking-stage", "situationship"], tags: ["apps", "burnout", "modern-dating"],
  },
  {
    slug: "textationship", term: "Textationship", pron: "tekst-AY-shun-ship", pos: "noun", cat: "dating",
    year: 2015, pop: 34, trend: 2, status: "niche",
    def: "A connection sustained almost entirely through text messages, with frequent, intimate conversation but little or no in-person contact.",
    eli: "A relationship that happens mostly over text, with barely any actual meetups.",
    org: "A blend of texting and relationship coined in the mid-2010s once smartphone messaging made it possible to sustain something that felt like intimacy without ever meeting.",
    ex: ["Six months of a textationship and we have met twice.", "A textationship can feel closer than it actually is."],
    rel: ["talking-stage", "situationship", "left-on-read"], tags: ["apps", "texting", "modern-dating"],
  },
  {
    slug: "rebound", term: "Rebound", pron: "REE-bownd", pos: "noun", cat: "dating",
    year: 1980, pop: 60, trend: 0, status: "classic",
    def: "A relationship entered soon after a breakup, largely to cope with the loss rather than out of genuine interest in the new person.",
    eli: "Dating someone new right after a breakup mostly to feel better, not because you are really that into them.",
    org: "Standard English for decades, borrowed from the basketball sense of recovering a missed shot, applied to relationships as a coping-focused rather than connection-focused pairing.",
    ex: ["Three weeks post-breakup and already dating. Classic rebound.", "Being someone's rebound rarely ends well for the rebound."],
    rel: ["situationship", "delusionship", "hard-launch"], tags: ["relationships", "breakups", "classic"],
  },
];
