import type { RawTerm } from "../types";

export const discourseTerms: RawTerm[] = [
  {
    slug: "troll", term: "Troll", pron: "trohl", pos: "noun", cat: "discourse",
    year: 1992, pop: 79, trend: -1, status: "classic",
    def: "Someone who posts provocatively to elicit an emotional reaction rather than to communicate. Do not feed the troll advises that a reaction is the reward.",
    eli: "Someone who says annoying things online just to get a reaction.",
    org: "From trolling for fish, meaning to trail bait, not from the creature. Attested on Usenet by 1992, where trolling for newbies was a recognised sport.",
    ex: ["Nine replies in and it is clearly a troll.", "Do not feed the troll is still the only reliable advice."],
    rel: ["concern-troll", "flame-war", "ragebait"], tags: ["usenet", "provocation", "classic"],
  },
  {
    slug: "concern-troll", term: "Concern troll", pron: "kun-SURN trohl", pos: "noun", cat: "discourse",
    year: 2006, pop: 48, trend: 2, status: "classic",
    def: "Someone who opposes a position while claiming to be a worried supporter of it, so that objections appear to come from inside the group.",
    eli: "Someone who pretends to be on your side so their criticism sounds more convincing.",
    org: "Named in political blogging around 2006. The accusation is hard to falsify, which is both its usefulness and its main danger.",
    ex: ["As someone who agrees with you, but is this wise? Concern troll.", "Calling every critic a concern troll ends the conversation early."],
    rel: ["troll", "sealioning", "bad-faith"], tags: ["politics", "blogging", "rhetoric"],
  },
  {
    slug: "sealioning", term: "Sealioning", pron: "SEE-ly-un-ing", pos: "noun", cat: "discourse",
    year: 2014, pop: 42, trend: 3, status: "mainstream",
    def: "Pursuing someone with relentless polite requests for evidence, so that the exhausting volume is the attack while each individual question looks reasonable.",
    eli: "Wearing someone down by endlessly asking polite questions until they give up.",
    org: "From a 2014 Wondermark comic by David Malki, in which a sea lion follows a couple demanding they justify a remark. The name stuck immediately.",
    ex: ["Forty civil questions in one thread is sealioning.", "The politeness is what makes it hard to name."],
    rel: ["concern-troll", "gish-gallop", "bad-faith"], tags: ["rhetoric", "comics", "harassment"],
  },
  {
    slug: "bad-faith", term: "Bad faith", pron: "bad fayth", pos: "noun", cat: "discourse",
    year: 2015, pop: 58, trend: 4, status: "mainstream",
    def: "Arguing without any intention of being persuaded or of representing your own position honestly. Good faith is the assumption most moderation policies ask people to extend first.",
    eli: "Arguing when you do not really mean it and will never change your mind.",
    org: "A philosophical and legal term that became everyday internet vocabulary in the mid-2010s, as distinguishing sincere from insincere disagreement became a practical necessity.",
    ex: ["This is a bad-faith reading and you know it.", "Assume good faith until the evidence is overwhelming."],
    rel: ["steelman", "strawman", "sealioning"], tags: ["rhetoric", "moderation", "philosophy"],
  },
  {
    slug: "strawman", term: "Strawman", pron: "STRAW-man", pos: "noun", cat: "discourse",
    year: 1990, pop: 62, trend: 0, status: "classic",
    def: "A distorted, weaker version of someone's argument, attacked in place of what they actually said.",
    eli: "Arguing against a made-up weaker version of what someone said, instead of what they really said.",
    org: "A named fallacy long before the internet, but online argument made it one of the most cited. The image is of a training dummy stuffed with straw.",
    ex: ["Nobody said that. Pure strawman.", "The strawman is easier to beat, which is the whole appeal."],
    rel: ["steelman", "bad-faith", "motte-and-bailey"], tags: ["fallacy", "rhetoric", "argument"],
  },
  {
    slug: "steelman", term: "Steelman", pron: "STEEL-man", pos: "verb", cat: "discourse",
    year: 2011, pop: 39, trend: 3, status: "mainstream",
    def: "To restate an opposing argument in its strongest form before answering it. The deliberate inverse of a strawman.",
    eli: "Making someone else's argument as strong as possible before you disagree with it.",
    org: "Coined in rationalist blogging around 2011 as a corrective to strawmanning. Critics note it can become a way of arguing with a position nobody actually holds.",
    ex: ["Let me steelman the other side first.", "Steelmanning is slower and almost always more useful."],
    rel: ["strawman", "bad-faith", "good-faith"], tags: ["rhetoric", "rationalism", "argument"],
  },
  {
    slug: "whataboutism", term: "Whataboutism", pron: "wot-uh-BOWT-iz-um", pos: "noun", cat: "discourse",
    year: 1974, pop: 55, trend: 2, status: "classic",
    def: "Answering a criticism by pointing to someone else's misconduct rather than addressing the charge. A deflection, though sometimes a genuine consistency argument.",
    eli: "Answering a criticism by saying but what about that other bad thing.",
    org: "Named in the 1970s to describe Soviet responses to Western criticism, and revived heavily after 2014. The distinction between deflection and a fair charge of hypocrisy is genuinely contested.",
    ex: ["Straight to whataboutism in the second reply.", "Sometimes it is deflection and sometimes it is a real double standard."],
    rel: ["strawman", "bad-faith", "gish-gallop"], tags: ["politics", "fallacy", "cold-war"],
  },
  {
    slug: "gish-gallop", term: "Gish gallop", pron: "gish GAL-up", pos: "noun", cat: "discourse",
    year: 1994, pop: 36, trend: 4, status: "niche",
    def: "Overwhelming an opponent with a rapid flood of claims, more than can be answered in the time available, so that unrebutted points appear to stand.",
    eli: "Making so many claims at once that nobody can possibly answer them all.",
    org: "Named by Eugenie Scott after creationist debater Duane Gish. It exploits an asymmetry: asserting takes seconds, refuting takes minutes.",
    ex: ["Thirty claims in ninety seconds. Classic Gish gallop.", "The format rewards volume over accuracy."],
    rel: ["sealioning", "whataboutism", "bad-faith"], tags: ["debate", "rhetoric", "asymmetry"],
  },
  {
    slug: "poes-law", term: "Poe's law", pron: "pohz law", pos: "noun", cat: "discourse",
    year: 2005, pop: 44, trend: 2, status: "classic",
    def: "Without a clear signal of intent, a parody of an extreme view is indistinguishable from a sincere statement of it.",
    eli: "Online, a joke about an extreme opinion looks exactly like someone who really means it.",
    org: "Formulated by Nathan Poe on a creationism forum in 2005. It is the strongest practical argument for tone indicators, which solve precisely this problem.",
    ex: ["Poe's law: nobody can tell whether that account is serious.", "The comment section proved Poe's law within four replies."],
    rel: ["tone-indicator", "godwins-law", "troll"], tags: ["parody", "law", "forums"],
  },
  {
    slug: "brigading", term: "Brigading", pron: "bri-GAY-ding", pos: "noun", cat: "discourse",
    year: 2013, pop: 51, trend: 3, status: "mainstream",
    def: "Coordinated mass participation from one community into another, to vote down, report or overwhelm a target. Prohibited on most platforms and hard to prove.",
    eli: "When a group organises to swarm someone else's post all at once.",
    org: "Reddit vocabulary formalised around 2013, when the site began restricting links between subreddits precisely to reduce it.",
    ex: ["Three hundred comments in an hour from one subreddit. Brigading.", "Platforms ban brigading and struggle to detect it."],
    rel: ["dogpiling", "sockpuppet", "mod"], tags: ["reddit", "coordination", "moderation"],
  },
  {
    slug: "dogpiling", term: "Dogpiling", pron: "DOG-pyle-ing", pos: "noun", cat: "discourse",
    year: 2015, pop: 53, trend: 4, status: "mainstream",
    def: "A large uncoordinated crowd responding critically to one person at once, so that a proportionate individual reaction becomes an overwhelming collective one.",
    eli: "When hundreds of people all criticise the same person at the same time.",
    org: "Named as quote-posting made pile-ons frictionless. Unlike brigading it requires no organisation, only reach, which makes it harder to moderate.",
    ex: ["One bad joke and eight thousand quote posts. Dogpiling.", "Everyone thinks they are one reply and they are one of thousands."],
    rel: ["brigading", "ratio", "cancelled"], tags: ["scale", "twitter", "harassment"],
  },
  {
    slug: "cancelled", term: "Cancelled", pron: "KAN-suld", pos: "adjective", cat: "discourse",
    year: 2017, pop: 74, trend: -6, status: "mainstream",
    def: "Subjected to mass public withdrawal of support after a disclosure. What counts as cancellation, and whether it durably works, is heavily contested.",
    eli: "When lots of people publicly stop supporting someone because of something they said or did.",
    org: "Black Twitter usage from around 2015, from a joke about cancelling a person like a television show. It became a political flashpoint from 2019 onward.",
    ex: ["Cancelled on Monday, touring again by August.", "The word does far too many jobs to survive a serious argument."],
    rel: ["dogpiling", "callout-post", "milkshake-duck"], tags: ["accountability", "twitter", "contested"],
  },
  {
    slug: "callout-post", term: "Callout post", pron: "KAWL-owt pohst", pos: "noun", cat: "discourse",
    year: 2014, pop: 46, trend: -2, status: "mainstream",
    def: "A long public post detailing someone's alleged wrongdoing, usually with screenshots, intended to inform a shared community.",
    eli: "A long public post accusing someone of doing something wrong, with screenshots as proof.",
    org: "Tumblr and fandom vocabulary of the mid-2010s. The format spread to every platform, along with persistent arguments about accuracy and proportionality.",
    ex: ["Nine screenshots and a two-thousand-word callout post.", "Callout posts document, they do not adjudicate."],
    rel: ["receipts", "cancelled", "dogpiling"], tags: ["tumblr", "accountability", "fandom"],
  },
  {
    slug: "milkshake-duck", term: "Milkshake duck", pron: "MILK-shayk duk", pos: "noun", cat: "discourse",
    year: 2016, pop: 40, trend: 0, status: "classic",
    def: "Someone who becomes beloved online and is then revealed to have a serious flaw, usually within about a day of going viral.",
    eli: "Someone the internet loves one day and discovers something terrible about the next.",
    org: "From a June 2016 tweet by Australian cartoonist Ben Ward, imagining a duck that drinks milkshakes and is then revealed as racist. It named a pattern everyone had noticed.",
    ex: ["Viral on Tuesday, milkshake ducked on Wednesday.", "The turnaround gets faster every year."],
    rel: ["cancelled", "callout-post", "clout"], tags: ["virality", "twitter", "pattern"],
  },
  {
    slug: "streisand-effect", term: "Streisand effect", pron: "STRY-zand i-FEKT", pos: "noun", cat: "discourse",
    year: 2005, pop: 57, trend: 2, status: "classic",
    def: "The way an attempt to suppress information draws far more attention to it than leaving it alone would have.",
    eli: "Trying to hide something online usually makes many more people look at it.",
    org: "Named by Mike Masnick in 2005 after Barbra Streisand sued to remove an aerial photograph of her house, which had been downloaded six times before the lawsuit and hundreds of thousands after.",
    ex: ["The takedown notice was the best publicity it ever had.", "Legal threats to a forum are a reliable Streisand effect."],
    rel: ["dogpiling", "wayback-machine", "receipts"], tags: ["censorship", "law", "attention"],
  },
  {
    slug: "echo-chamber", term: "Echo chamber", pron: "EK-oh CHAYM-bur", pos: "noun", cat: "discourse",
    year: 2001, pop: 63, trend: 1, status: "classic",
    def: "A space where a belief is amplified by repetition and rarely challenged. The filter bubble is the algorithmic version, produced by personalisation rather than by choice.",
    eli: "A group where everyone already agrees, so the same ideas keep bouncing back.",
    org: "Media-criticism vocabulary applied to blogs in the early 2000s. Eli Pariser's 2011 book The Filter Bubble named the version created by recommendation systems.",
    ex: ["The feed is an echo chamber with better graphics.", "Research on how strong the effect actually is remains genuinely mixed."],
    rel: ["algorithm", "rabbit-hole", "dead-internet-theory"], tags: ["media", "algorithms", "politics"],
  },
  {
    slug: "rabbit-hole", term: "Rabbit hole", pron: "RAB-it hohl", pos: "noun", cat: "discourse",
    year: 2018, pop: 66, trend: 3, status: "mainstream",
    def: "A chain of recommendations leading progressively further into a niche. Neutral when it ends in obscure hobbies, and the subject of serious research when it ends elsewhere.",
    eli: "Following one video or link to the next until you are somewhere very strange.",
    org: "From Alice in Wonderland, applied to recommendation systems from around 2018 as researchers began studying how autoplay shapes what people see next.",
    ex: ["Three hours down a rabbit hole about canal locks.", "The rabbit hole is a design outcome, not an accident."],
    rel: ["echo-chamber", "algorithm", "doomscrolling"], tags: ["recommendation", "youtube", "research"],
  },
  {
    slug: "hot-take", term: "Hot take", pron: "hot tayk", pos: "noun", cat: "discourse",
    year: 2013, pop: 59, trend: -2, status: "mainstream",
    def: "A deliberately provocative opinion produced quickly, valued for speed and heat rather than for accuracy. The take economy is what rewards it.",
    eli: "A bold opinion posted fast, made to get attention rather than to be right.",
    org: "Sports journalism vocabulary of the early 2010s, where being first mattered more than being correct. Twitter generalised it and then made it slightly shameful.",
    ex: ["Hot take: the sequel was better and I will not elaborate.", "The take economy rewards being wrong loudly and quickly."],
    rel: ["ragebait", "ratio", "clout"], tags: ["journalism", "twitter", "opinion"],
  },
  {
    slug: "subtweet", term: "Subtweet", pron: "SUB-tweet", pos: "noun", cat: "discourse",
    year: 2012, pop: 61, trend: -1, status: "classic",
    def: "A post about someone that does not name or tag them, so the target may recognise themselves while the author retains deniability.",
    eli: "Posting about someone without naming them, so only they know it is about them.",
    org: "Twitter vocabulary from around 2012, formed from subliminal and tweet. The behaviour is far older; AIM away messages did the same job.",
    ex: ["That is a subtweet and everyone in the group chat knows it.", "Vaguebooking is the same manoeuvre on a different platform."],
    rel: ["vaguepost", "away-message", "shade"], tags: ["twitter", "indirect", "conflict"],
  },
  {
    slug: "vaguepost", term: "Vaguepost", pron: "VAYG-pohst", pos: "noun", cat: "discourse",
    year: 2011, pop: 43, trend: 0, status: "mainstream",
    def: "A deliberately unspecific post about distress or conflict, inviting concern without disclosing anything. Vaguebooking is the Facebook-specific form.",
    eli: "Posting something sad and vague so people ask what is wrong.",
    org: "Named on Facebook and Tumblr in the early 2010s. It sits in the gap between wanting attention and not wanting to explain, which is why it irritates people so reliably.",
    ex: ["Cannot believe some people. Textbook vaguepost.", "Someone always replies asking if they are okay, which is the point."],
    rel: ["subtweet", "shade", "callout-post"], tags: ["facebook", "tumblr", "attention"],
  },
  {
    slug: "notes-app-apology", term: "Notes app apology", pron: "nohts ap uh-POL-uh-jee", pos: "noun", cat: "discourse",
    year: 2017, pop: 47, trend: 1, status: "mainstream",
    def: "A public apology posted as a screenshot of plain text, a format so standard that the screenshot itself now signals what is coming.",
    eli: "An apology posted as a photo of text typed in a phone notes app.",
    org: "Became the default celebrity apology format in the mid-2010s because character limits forced it. The form is now so recognisable it undermines the sincerity it aims for.",
    ex: ["The notes app screenshot appeared within nine hours.", "You can tell how bad it is by the font size."],
    rel: ["cancelled", "callout-post", "receipts"], tags: ["celebrity", "format", "apology"],
  },
  {
    slug: "tone-policing", term: "Tone policing", pron: "tohn puh-LEES-ing", pos: "noun", cat: "discourse",
    year: 2012, pop: 41, trend: 0, status: "mainstream",
    def: "Dismissing an argument because of how angrily it was expressed rather than engaging with its content.",
    eli: "Ignoring what someone said because they said it angrily.",
    org: "Feminist and anti-racist blogging vocabulary of the early 2010s. Critics note that manner sometimes genuinely matters, which keeps the term contested.",
    ex: ["Answering the anger and not the point is tone policing.", "It is a real pattern and also a convenient shield."],
    rel: ["bad-faith", "strawman", "callout-post"], tags: ["blogging", "rhetoric", "contested"],
  },
  {
    slug: "block", term: "Block", pron: "blok", pos: "verb", cat: "discourse",
    year: 2008, pop: 72, trend: 4, status: "classic",
    def: "To prevent an account from seeing or contacting you. Distinct from muting, which hides them from you while leaving them able to see you.",
    eli: "Stopping someone from seeing or contacting you online.",
    org: "A basic platform feature that became a social act with its own etiquette. Block lists, block parties and mass-blocking tools turned it into a collective practice.",
    ex: ["Blocked, and my timeline improved immediately.", "Mute is for peace, block is for a message."],
    rel: ["timeout", "mod", "dogpiling"], tags: ["moderation", "boundaries", "platforms"],
  },
  {
    slug: "doxxing", term: "Doxxing", pron: "DOKS-ing", pos: "noun", cat: "discourse",
    year: 2001, pop: 64, trend: 3, status: "classic",
    def: "Publishing someone's private identifying information without consent, typically to expose them to harassment. Prohibited by every major platform and illegal in many places.",
    eli: "Publishing someone's real name, address or workplace so strangers can harass them.",
    org: "From dropping docs, hacker vocabulary of the 1990s. It moved from feuds between hackers into general online conflict during the 2000s.",
    ex: ["The thread was removed for doxxing within minutes.", "Doxxing turns an argument into a safety problem."],
    rel: ["swatting", "brigading", "opsec"], tags: ["harassment", "privacy", "safety"],
  },
  {
    slug: "good-faith", term: "Good faith", pron: "good fayth", pos: "noun", cat: "discourse",
    year: 2005, pop: 47, trend: 2, status: "classic",
    def: "The assumption that another person means what they say and is open to persuasion. Wikipedia made assume good faith a formal editing policy.",
    eli: "Believing that the person you disagree with is being honest, at least until they prove otherwise.",
    org: "A legal and ethical term adopted as a governance principle by Wikipedia in the mid-2000s. It works well as a default and badly as an absolute rule.",
    ex: ["Assume good faith, but stop assuming it after the fourth time.", "Good faith is a starting position, not a life sentence."],
    rel: ["bad-faith", "steelman", "sealioning"], tags: ["wikipedia", "moderation", "policy"],
  },
  {
    slug: "motte-and-bailey", term: "Motte and bailey", pron: "MOT and BAY-lee", pos: "noun", cat: "discourse",
    year: 2005, pop: 33, trend: 4, status: "niche",
    def: "Advancing a controversial claim, then retreating to a nearly unarguable version when challenged, and returning to the strong claim once the challenge passes.",
    eli: "Making a bold claim, and when questioned, pretending you only meant something obvious.",
    org: "Named by philosopher Nicholas Shackel in 2005, after a castle design with an indefensible courtyard and a fortified mound to retreat to.",
    ex: ["The strong claim in the headline, the weak one in the correction.", "Motte and bailey is hard to spot in a single exchange."],
    rel: ["strawman", "bad-faith", "whataboutism"], tags: ["fallacy", "philosophy", "rhetoric"],
  },
  {
    slug: "swatting", term: "Swatting", pron: "SWOT-ing", pos: "noun", cat: "discourse",
    year: 2008, pop: 51, trend: 2, status: "classic",
    def: "Making a false emergency report to send armed police to someone's address. It has caused deaths and is prosecuted as a serious crime in many jurisdictions.",
    eli: "Lying to the police so armed officers are sent to someone's home as an attack.",
    org: "Named by the FBI around 2008 after SWAT teams. It became a recognised hazard of live streaming, since the broadcast confirms in real time that the call worked.",
    ex: ["The stream cut out mid-sentence and the reason was swatting.", "Several jurisdictions passed specific anti-swatting statutes after fatalities."],
    rel: ["doxxing", "opsec", "brigading"], tags: ["harassment", "crime", "streaming"],
  },
  {
    slug: "opsec", term: "OPSEC", pron: "OP-sek", pos: "abbreviation", cat: "discourse",
    year: 2014, pop: 43, trend: 5, status: "mainstream",
    def: "Operational security: the practice of not revealing information that lets someone identify or locate you. Online it usually means managing what your posts leak by accident.",
    eli: "Being careful not to accidentally reveal details that let strangers find you.",
    org: "A Vietnam-era military term, adopted by hackers and then by ordinary users as harassment made incidental detail dangerous. Reflections, window views and metadata are the classic leaks.",
    ex: ["Posted a photo with the street sign visible. Bad opsec.", "Good opsec is mostly about what you do not post."],
    rel: ["doxxing", "swatting", "block"], tags: ["privacy", "safety", "military"],
  },
  {
    slug: "ban-evasion", term: "Ban evasion", pron: "ban i-VAY-zhun", pos: "noun", cat: "discourse",
    year: 2010, pop: 35, trend: 1, status: "mainstream",
    def: "Returning to a platform on a new account after being removed. Usually detected by writing style and behaviour rather than by technical identifiers.",
    eli: "Making a new account to come back after being banned.",
    org: "A standing moderation problem since forums existed. Platforms respond with device and network fingerprinting, which catches the careless and rarely the determined.",
    ex: ["Same posting hours, same three typos. Ban evasion.", "You cannot ban a person, only an account."],
    rel: ["sockpuppet", "block", "mod"], tags: ["moderation", "enforcement", "detection"],
  },
  {
    slug: "bot", term: "Bot", pron: "bot", pos: "noun", cat: "discourse",
    year: 1993, pop: 76, trend: 6, status: "classic",
    def: "An automated account. The accusation that someone is a bot is now a routine way of dismissing an opponent, which makes the word less useful than it was.",
    eli: "An automated account run by software instead of a person.",
    org: "IRC bots date to the early 1990s and were mostly helpful. The word soured as spam, astroturfing and influence operations made automation adversarial by default.",
    ex: ["Nine identical replies from accounts made last Tuesday. Bots.", "Calling a person a bot ends the conversation without answering it."],
    rel: ["astroturfing", "sockpuppet", "dead-internet-theory"], tags: ["automation", "irc", "manipulation"],
  },
  {
    slug: "discourse-noun", term: "The discourse", pron: "thuh DIS-kors", pos: "noun", cat: "discourse",
    year: 2017, pop: 54, trend: 2, status: "mainstream",
    def: "The current online argument, treated as a single weather system that everyone is subject to whether or not they participate.",
    eli: "Whatever the internet is collectively arguing about right now.",
    org: "Borrowed with heavy irony from critical theory. The definite article does the work: it is not a discourse but the discourse, as though only one is running at a time.",
    ex: ["I am not engaging with the discourse today.", "The discourse has moved on and nobody was persuaded."],
    rel: ["hot-take", "dogpiling", "ratio"], tags: ["twitter", "irony", "argument"],
  },
  {
    slug: "read", term: "Read", pron: "reed", pos: "noun", cat: "discourse",
    year: 1990, pop: 42, trend: 0, status: "classic",
    def: "A precise and public criticism of someone, delivered openly rather than by implication. Shade is its indirect counterpart; a read is meant to be recognised.",
    eli: "A sharp, direct insult that names exactly what is wrong.",
    org: "Ballroom vocabulary documented in Paris Is Burning, which distinguishes reading from shade explicitly. Reading requires accuracy, which is what separates it from an insult.",
    ex: ["That was not shade, that was a read.", "A good read is admired even by the person receiving it."],
    rel: ["shade", "gagged", "callout-post"], tags: ["ballroom", "criticism", "drag"],
  },
  {
    slug: "context-collapse", term: "Context collapse", pron: "KON-tekst kuh-LAPS", pos: "noun", cat: "discourse",
    year: 2011, pop: 38, trend: 6, status: "rising",
    def: "What happens when a message written for one audience reaches every other one at once, so a joke among friends is read by strangers as a statement.",
    eli: "When something you said for your friends is seen by everyone, and it sounds completely different.",
    org: "Named by researchers including danah boyd and Alice Marwick around 2011. It explains most viral misunderstanding better than bad faith does.",
    ex: ["Nine followers saw the joke, nine million saw the screenshot.", "The post did not change; the audience did."],
    rel: ["dogpiling", "subtweet", "milkshake-duck"], tags: ["research", "audience", "virality"],
  },
  {
    slug: "nutpicking", term: "Nutpicking", pron: "NUT-pik-ing", pos: "noun", cat: "discourse",
    year: 2006, pop: 29, trend: 3, status: "niche",
    def: "Selecting the least defensible member of a group and presenting them as representative, which is trivially easy on any platform of sufficient size.",
    eli: "Finding the silliest person on the other side and pretending everyone there is like them.",
    org: "Coined in political blogging around 2006. Scale makes it effortless: any group of a million people contains someone saying something indefensible right now.",
    ex: ["Quoting an account with nine followers as proof of a movement.", "At scale, nutpicking is always available."],
    rel: ["strawman", "dogpiling", "bad-faith"], tags: ["rhetoric", "politics", "scale"],
  },
  {
    slug: "sanewashing", term: "Sanewashing", pron: "SAYN-wosh-ing", pos: "noun", cat: "discourse",
    year: 2020, pop: 34, trend: 12, status: "rising",
    def: "Reporting or paraphrasing an incoherent statement in a tidier form than it was made, so the summary is more reasonable than the original.",
    eli: "Making someone's confusing statement sound more sensible than it actually was when you repeat it.",
    org: "Emerged around 2020 in media criticism, becoming widely used by 2024. It names a real editorial problem: cleaning up a quote for clarity can change what it reported.",
    ex: ["The headline was coherent; the transcript was not.", "Paraphrase is an editorial act, not a neutral one."],
    rel: ["nutpicking", "hot-take", "context-collapse"], tags: ["media", "reporting", "2024"],
  },
  {
    slug: "third-rail", term: "Third rail", pron: "TUCH-ing thuh thurd rayl", pos: "noun", cat: "discourse",
    year: 2015, pop: 26, trend: 1, status: "niche",
    def: "Raising a topic a community treats as non-negotiable, where any position other than the accepted one draws immediate and disproportionate response.",
    eli: "Bringing up the one subject a group refuses to argue about calmly.",
    org: "American political vocabulary, from the electrified rail on a railway, applied to online communities where certain topics reliably end constructive discussion.",
    ex: ["Mentioned the licence change and touched the third rail.", "Every community has one, and newcomers find it by accident."],
    rel: ["dogpiling", "flame-war", "gatekeep"], tags: ["community", "taboo", "politics"],
  },
];
