import type { RawTerm } from "../types";

export const fandomTerms: RawTerm[] = [
  {
    slug: "bias", term: "Bias", pron: "BY-us", pos: "noun", cat: "fandom",
    year: 2011, pop: 60, trend: 2, status: "niche",
    def: "A fan's favourite member of a group. A bias wrecker is the member who keeps threatening to displace them.",
    eli: "Your favourite person in a band. A bias wrecker is the one who almost makes you change your mind.",
    org: "From K-pop fandom in English-speaking communities in the early 2010s, calqued from Korean fan vocabulary and now standard across group fandoms.",
    ex: ["He was my bias for a year and then the b-side happened.", "Bias wrecker behaviour in every single fancam."],
    rel: ["stan", "fancam", "otp"], tags: ["kpop", "fandom"],
  },
  {
    slug: "era", term: "Era", pron: "EER-uh", pos: "noun", cat: "fandom",
    year: 2022, pop: 77, trend: -4, status: "mainstream",
    def: "A distinct chapter in someone's life or output, named and framed as though it were an album cycle. Applied to ordinary people as readily as to artists.",
    eli: "A phase you are in, described like a musician's new album with its own look and mood.",
    org: "Music-industry vocabulary for a release cycle, generalised by Taylor Swift fandom and then by TikTok around 2022 into a way of narrating everyday change.",
    ex: ["In my leaving-the-house-on-time era.", "That was the sourdough era and we do not discuss it."],
    rel: ["canon-event", "lore", "stan"], tags: ["identity", "music", "tiktok"],
  },
  {
    slug: "fancam", term: "Fancam", pron: "FAN-kam", pos: "noun", cat: "fandom",
    year: 2020, pop: 53, trend: -3, status: "niche",
    def: "A close-focus performance video following one member of a group. Reposting fancams under unrelated conversations became a recognised derailing tactic.",
    eli: "A video zoomed in on one performer. Fans post them under random conversations to change the subject.",
    org: "A long-standing K-pop practice that reached general Twitter in 2020, when fandoms used mass fancam posting to flood hostile hashtags.",
    ex: ["Someone dropped a fancam under the press release and the thread never recovered.", "The fancam has more views than the official video."],
    rel: ["bias", "stan", "ratio"], tags: ["kpop", "twitter", "video"],
  },
  {
    slug: "gatekeep", term: "Gatekeep", pron: "GAYT-keep", pos: "verb", cat: "fandom",
    year: 2015, pop: 64, trend: -2, status: "mainstream",
    def: "To restrict access to a community or interest by demanding proof of credentials, usually to preserve a sense of scarcity or authenticity.",
    eli: "Making people prove they are real fans before you let them join in, so the group stays small.",
    org: "From sociology by way of Tumblr in the mid-2010s, and cemented by the 2021 \"gatekeep, gaslight, girlboss\" formula that satirised it.",
    ex: ["Naming three songs is not a personality test. Stop gatekeeping.", "Some gatekeeping is just a small venue trying to stay a small venue."],
    rel: ["normie", "stan", "cringe"], tags: ["community", "authenticity"],
  },
  {
    slug: "headcanon", term: "Headcanon", pron: "HED-kan-un", pos: "noun", cat: "fandom",
    year: 2009, pop: 56, trend: 3, status: "niche",
    def: "A fan's personal interpretation of a character or story that the official work never confirms, held sincerely while being acknowledged as unofficial.",
    eli: "Something you decide is true about a character even though the book or show never actually says it.",
    org: "Formed on LiveJournal and Tumblr in the late 2000s from \"canon\", the body of officially established fact.",
    ex: ["My headcanon is that he never learned to drive.", "Half the fandom treats that headcanon as canon now."],
    rel: ["lore", "otp", "canon-event"], tags: ["tumblr", "fanfiction", "interpretation"],
  },
  {
    slug: "otp", term: "OTP", pron: "oh-tee-PEE", pos: "abbreviation", cat: "fandom",
    year: 2005, pop: 52, trend: -1, status: "niche",
    def: "\"One true pairing\": the romantic pairing a fan is most committed to, defended against all competing interpretations.",
    eli: "The two characters you most want to end up together, and you will argue with anyone who disagrees.",
    org: "Standard in fanfiction communities by the mid-2000s, inherited from the shipping vocabulary of 1990s mailing lists.",
    ex: ["The finale respected the OTP, which almost never happens.", "Two OTPs, one fandom, endless argument."],
    rel: ["headcanon", "bias", "stan"], tags: ["shipping", "fanfiction"],
  },
  {
    slug: "stan", term: "Stan", pron: "stan", pos: "noun", cat: "fandom",
    year: 2000, pop: 85, trend: 1, status: "mainstream",
    def: "An intensely devoted fan, and the organised communities such fans form. Used as a verb meaning to support something wholeheartedly and publicly.",
    eli: "A super fan who follows everything an artist does and defends them online.",
    org: "From the 2000 Eminem song about an obsessive letter-writer. The word softened over two decades from warning to self-description, and entered dictionaries in 2017.",
    ex: ["The stans found the deleted post in about six minutes.", "I stan a functional public transport system."],
    rel: ["bias", "parasocial", "glazing"], tags: ["music", "fandom", "community"],
  },
  {
    slug: "ship", term: "Ship", pron: "ship", pos: "verb", cat: "fandom",
    year: 1996, pop: 72, trend: 2, status: "classic",
    def: "To want two characters to be in a relationship. A ship is the pairing itself, usually named by blending the two names together.",
    eli: "Wanting two characters to get together, and the name fans give that pairing.",
    org: "Clipped from relationshipper, coined in X-Files newsgroups around 1996 to distinguish fans focused on the romance from those focused on the plot.",
    ex: ["I ship them and the show does not, which is the usual arrangement.", "The ship name is a portmanteau by convention."],
    rel: ["otp", "canon", "fanfic"], tags: ["usenet", "relationships", "x-files"],
  },
  {
    slug: "canon", term: "Canon", pron: "KAN-un", pos: "noun", cat: "fandom",
    year: 1990, pop: 68, trend: 1, status: "classic",
    def: "The body of officially established facts in a fictional world. What counts as canon is itself frequently disputed, particularly across adaptations.",
    eli: "The things that officially happened in a story, according to the creators.",
    org: "Borrowed from biblical scholarship via Sherlock Holmes fandom, which used it from the 1910s to distinguish Conan Doyle's stories from imitations.",
    ex: ["The film is not canon and the argument has run for years.", "Canon, headcanon and fanon are three different things."],
    rel: ["headcanon", "retcon", "ship"], tags: ["fiction", "authority", "sherlock"],
  },
  {
    slug: "retcon", term: "Retcon", pron: "RET-kon", pos: "noun", cat: "fandom",
    year: 1988, pop: 49, trend: 0, status: "classic",
    def: "Retroactive continuity: revising established facts so that past events acquire a new meaning. Distinct from a simple contradiction, which is just an error.",
    eli: "Changing what already happened in a story so it means something different now.",
    org: "Comics vocabulary, coined in the late 1980s as long-running serials accumulated contradictions. The best retcons reframe rather than erase.",
    ex: ["The retcon made three earlier issues better.", "A contradiction is a mistake, a retcon is a decision."],
    rel: ["canon", "lore", "headcanon"], tags: ["comics", "continuity", "writing"],
  },
  {
    slug: "fanfic", term: "Fanfiction", pron: "FAN-fik-shun", pos: "noun", cat: "fandom",
    year: 1965, pop: 71, trend: 3, status: "classic",
    def: "Fiction written by fans using existing characters or settings. A vast body of work with its own genres, conventions and critical vocabulary.",
    eli: "Stories fans write using characters from books, films or shows they love.",
    org: "The modern practice dates to Star Trek fanzines in the 1960s. Online archives industrialised it, and the community's tagging systems are more sophisticated than most commercial ones.",
    ex: ["The fanfic has more words than the source novel.", "Several bestsellers began as filed-off fanfiction."],
    rel: ["ao3", "au", "slow-burn"], tags: ["writing", "star-trek", "community"],
  },
  {
    slug: "ao3", term: "AO3", pron: "ay-oh-THREE", pos: "abbreviation", cat: "fandom",
    year: 2009, pop: 58, trend: 5, status: "mainstream",
    def: "Archive of Our Own, a nonprofit fanfiction archive run by its users, notable for a tagging system maintained by volunteer wranglers.",
    eli: "A huge fan-run website for fanfiction, with an unusually good system for tagging stories.",
    org: "Launched in 2009 by the Organization for Transformative Works, founded after commercial hosts repeatedly deleted fan work. It won a Hugo Award in 2019.",
    ex: ["The tag wranglers do work most companies would pay a team for.", "A Hugo Award for an archive was a first."],
    rel: ["fanfic", "au", "enemies-to-lovers"], tags: ["archive", "nonprofit", "tagging"],
  },
  {
    slug: "au", term: "AU", pron: "ay-YOO", pos: "abbreviation", cat: "fandom",
    year: 1995, pop: 47, trend: 2, status: "classic",
    def: "Alternate universe: fanfiction placing established characters in a different setting, such as a coffee shop or a modern city, to test what is essential about them.",
    eli: "Fan stories that put the same characters in a completely different world or job.",
    org: "Fanzine vocabulary formalised online in the 1990s. The coffee shop AU became such a standard that it functions as a genre with its own expectations.",
    ex: ["Coffee shop AU is practically a literary form.", "AUs are character studies with the plot removed."],
    rel: ["fanfic", "ao3", "headcanon"], tags: ["writing", "genre", "archive"],
  },
  {
    slug: "enemies-to-lovers", term: "Enemies to lovers", pron: "EN-uh-meez tuh LUV-urz", pos: "noun", cat: "fandom",
    year: 2015, pop: 62, trend: 8, status: "rising",
    def: "A romance structure in which antagonism converts into attraction. One of the most requested tropes in fanfiction and, increasingly, in published romance.",
    eli: "A love story where two people start out hating each other.",
    org: "An ancient plot structure that fandom tagging turned into a searchable category. BookTok made the trope-first way of choosing books mainstream after 2020.",
    ex: ["Filtered by enemies to lovers and slow burn.", "Tropes as search terms changed how romance is published."],
    rel: ["slow-burn", "ao3", "fanfic"], tags: ["romance", "tropes", "booktok"],
  },
  {
    slug: "slow-burn", term: "Slow burn", pron: "sloh burn", pos: "noun", cat: "fandom",
    year: 2010, pop: 51, trend: 4, status: "mainstream",
    def: "A romance that develops over a very long span, where the delay is the appeal. In fanfiction it can mean two hundred thousand words before anything happens.",
    eli: "A love story that takes a very long time to actually happen, on purpose.",
    org: "Fanfiction tag vocabulary that spread into mainstream publishing. The tag exists because readers want to choose pacing deliberately, not despite it.",
    ex: ["Slow burn, three hundred thousand words, worth it.", "The tag is a promise about pacing, not plot."],
    rel: ["enemies-to-lovers", "fanfic", "ao3"], tags: ["romance", "pacing", "tropes"],
  },
  {
    slug: "comeback", term: "Comeback", pron: "KUM-bak", pos: "noun", cat: "fandom",
    year: 2012, pop: 46, trend: 1, status: "mainstream",
    def: "In K-pop, any new release by a group, regardless of whether they have been away. A full production cycle with a concept, choreography and coordinated fan campaign.",
    eli: "A K-pop group releasing new music, treated as a big planned event even if they never went away.",
    org: "Korean industry vocabulary carried into English by international fandom. The word confuses newcomers precisely because no absence is implied.",
    ex: ["Comeback in three weeks and the fandom has a spreadsheet.", "They released in March and the June release is still a comeback."],
    rel: ["bias", "stan", "era"], tags: ["kpop", "industry", "release"],
  },
  {
    slug: "bias-wrecker", term: "Bias wrecker", pron: "BY-us REK-ur", pos: "noun", cat: "fandom",
    year: 2014, pop: 34, trend: 0, status: "niche",
    def: "The group member who threatens to displace your declared favourite. Naming one is a way of admitting your loyalty is under strain.",
    eli: "The band member who keeps making you wonder whether they should be your favourite instead.",
    org: "K-pop fandom vocabulary from the mid-2010s. It exists because bias is treated as a commitment, which makes wavering something that needs its own word.",
    ex: ["He was a bias wrecker for a year and then just became the bias.", "The vocabulary treats fandom as monogamy."],
    rel: ["bias", "stan", "comeback"], tags: ["kpop", "fandom", "loyalty"],
  },
  {
    slug: "fanon", term: "Fanon", pron: "FAN-on", pos: "noun", cat: "fandom",
    year: 2002, pop: 32, trend: 1, status: "niche",
    def: "Interpretations so widely shared within a fandom that newcomers assume they are official. The collective version of headcanon.",
    eli: "Ideas fans agree on so much that people forget they were never in the actual story.",
    org: "Coined by blending fan and canon in early 2000s fandom. Fanon frequently outlives and outweighs canon, particularly for details the source material never specified.",
    ex: ["That character trait is fanon and has been for fifteen years.", "Half of what people remember is fanon."],
    rel: ["headcanon", "canon", "lore"], tags: ["interpretation", "community", "fanfiction"],
  },
  {
    slug: "shipping-war", term: "Shipping war", pron: "SHIP-ing wor", pos: "noun", cat: "fandom",
    year: 1998, pop: 38, trend: 0, status: "classic",
    def: "Sustained conflict between fans of competing romantic pairings. Among the oldest recurring forms of internet argument, with a documented history going back to Usenet.",
    eli: "A long argument between fans who want different characters to end up together.",
    org: "The X-Files newsgroups of the late 1990s produced the first documented shipping wars, complete with the vocabulary that fandom still uses.",
    ex: ["The shipping war outlasted the show by a decade.", "It was fought on newsgroups before it was fought anywhere else."],
    rel: ["ship", "otp", "canon"], tags: ["conflict", "usenet", "x-files"],
  },
  {
    slug: "spoiler", term: "Spoiler", pron: "SPOY-lur", pos: "noun", cat: "fandom",
    year: 1971, pop: 74, trend: 0, status: "classic",
    def: "Information about a plot development that a reader has not reached. The etiquette around them is old, elaborate and permanently disputed.",
    eli: "Telling someone what happens in a story before they get there.",
    org: "The word appears in a 1971 National Lampoon article. Usenet developed the first formal countermeasures, and every platform has rebuilt them since.",
    ex: ["Untagged spoilers in the thread title is a hostile act.", "The statute of limitations argument recurs annually."],
    rel: ["spoiler-tag", "canon", "rot13"], tags: ["etiquette", "usenet", "narrative"],
  },
  {
    slug: "lightstick", term: "Lightstick", pron: "LYTE-stik", pos: "noun", cat: "fandom",
    year: 2013, pop: 29, trend: 1, status: "niche",
    def: "An official illuminated fan accessory, often synchronised by Bluetooth so an arena becomes a single controlled display.",
    eli: "A glowing stick fans wave at K-pop concerts, which can be controlled to light up the whole arena in patterns.",
    org: "K-pop concert culture from the early 2010s. Networked control turned the audience into part of the production, which is a genuine innovation in live performance.",
    ex: ["The whole arena changed colour on cue.", "The audience is lighting equipment now."],
    rel: ["comeback", "fancam", "stan"], tags: ["kpop", "concerts", "technology"],
  },
  {
    slug: "standom", term: "Standom", pron: "STAN-dum", pos: "noun", cat: "fandom",
    year: 2017, pop: 36, trend: 0, status: "mainstream",
    def: "The organised world of stan communities, considered collectively. Distinguished from fandom by intensity, coordination and a willingness to mobilise.",
    eli: "The whole world of super-fan communities and how they organise.",
    org: "Formed from stan plus fandom around 2017, once stan Twitter had developed enough shared structure to need a collective noun.",
    ex: ["Standom mobilised faster than the press office.", "It has its own economy, journalism and law enforcement."],
    rel: ["stan", "fancam", "parasocial"], tags: ["community", "twitter", "organisation"],
  },
  {
    slug: "beta-reader", term: "Beta reader", pron: "BAY-tuh REE-dur", pos: "noun", cat: "fandom",
    year: 1998, pop: 27, trend: 1, status: "niche",
    def: "A volunteer who reads a draft and gives feedback before publication. Fanfiction communities built a functioning editorial culture with no money involved.",
    eli: "Someone who reads a story before it is published and helps make it better.",
    org: "Borrowed from software beta testing, in use in fanfiction circles by the late 1990s. Many professional writers first learned to take editorial notes this way.",
    ex: ["Three beta readers and a britpicker on a fanfic.", "It is a functioning editorial system running entirely on goodwill."],
    rel: ["fanfic", "ao3", "au"], tags: ["writing", "editing", "volunteers"],
  },
  {
    slug: "multi", term: "Multi", pron: "MUL-tee", pos: "noun", cat: "fandom",
    year: 2015, pop: 28, trend: 0, status: "niche",
    def: "Someone who follows several groups or fandoms at once, rather than committing exclusively to one. Occasionally treated as disloyalty by the more intense.",
    eli: "A fan who follows several bands or shows instead of just one.",
    org: "K-pop fandom vocabulary, where exclusive loyalty was the assumed default. The word exists because the alternative needed naming.",
    ex: ["Multi with a main, which is the diplomatic answer.", "It needed a word because loyalty was assumed."],
    rel: ["bias", "stan", "standom"], tags: ["kpop", "loyalty", "identity"],
  },
  {
    slug: "fan-service", term: "Fan service", pron: "fan SUR-vis", pos: "noun", cat: "fandom",
    year: 1998, pop: 42, trend: 0, status: "classic",
    def: "Material included to please the audience rather than to serve the story: a cameo, a callback, a shot that exists purely for the people who care.",
    eli: "Things put in a story just to make fans happy, not because the plot needs them.",
    org: "Anime criticism vocabulary that spread to film and television. It carries a mild charge of indulgence, though defenders point out that pleasing the audience is not a crime.",
    ex: ["The final act was ninety percent fan service and everyone was delighted.", "The criticism is about proportion, not existence."],
    rel: ["canon", "retcon", "lore"], tags: ["criticism", "anime", "narrative"],
  },
  {
    slug: "hyperfixation", term: "Hyperfixation", pron: "HY-pur-fik-SAY-shun", pos: "noun", cat: "fandom",
    year: 2019, pop: 47, trend: 8, status: "rising",
    def: "An intense, absorbing and often temporary focus on one interest. Used clinically in ADHD and autism contexts, and colloquially for any consuming enthusiasm.",
    eli: "Being so interested in one thing that you think about almost nothing else for a while.",
    org: "Clinical vocabulary that spread through neurodivergent communities on Tumblr and TikTok after 2019. Casual use has broadened it, which some find useful and others find flattening.",
    ex: ["Current hyperfixation is eighteenth-century canal engineering.", "The clinical and casual senses have drifted apart."],
    rel: ["brainworms", "roman-empire", "standom"], tags: ["neurodivergence", "interest", "tiktok"],
  },
  {
    slug: "blorbo", term: "Blorbo", pron: "BLOR-boh", pos: "noun", cat: "fandom",
    year: 2021, pop: 32, trend: 4, status: "niche",
    def: "A deliberately silly placeholder name for a favourite character, used to avoid the earnestness of saying so directly.",
    eli: "A joke word for your favourite character, used so you do not have to sound too serious about it.",
    org: "Coined on Tumblr in 2021. Its nonsense quality is functional: it lets people express attachment while signalling awareness that the attachment is disproportionate.",
    ex: ["My blorbo from my shows.", "The silliness is a defence against being earnest."],
    rel: ["fanon", "headcanon", "hyperfixation"], tags: ["tumblr", "irony", "characters"],
  },
];
