import type { RawTerm } from "../types";

export const gamingTerms: RawTerm[] = [
  {
    slug: "clutch", term: "Clutch", pron: "kluch", pos: "adjective", cat: "gaming",
    year: 2004, pop: 74, trend: 2, status: "classic",
    def: "Performing well precisely when the stakes are highest, especially when winning from a position that looked lost. Used as both adjective and verb.",
    eli: "Doing something brilliant at the very last moment when everyone thought you were going to lose.",
    org: "Borrowed from American sports commentary, where a clutch player delivers under pressure. Counter-Strike and Valorant made it standard vocabulary online.",
    ex: ["One versus four and he clutched it.", "Clutch fix. The deploy went out with nine seconds to spare."],
    rel: ["gg", "tilt", "sweaty"], tags: ["pressure", "esports", "sports"],
  },
  {
    slug: "gg", term: "GG", pron: "jee-JEE", pos: "interjection", cat: "gaming",
    year: 1998, pop: 80, trend: 0, status: "classic",
    def: "Short for \"good game\", said at the end of a match as a gesture of sportsmanship. Outside games it marks the moment something is decisively over.",
    eli: "What players say when a game finishes, to be polite. People now say it about anything that has clearly ended.",
    org: "Standard etiquette in competitive PC gaming since the late 1990s, spread by StarCraft and Quake ladders and carried into every chat window since.",
    ex: ["GG, well played, rematch in ten.", "Server went down during the demo. GG."],
    rel: ["clutch", "tilt", "meta"], tags: ["etiquette", "esports", "classic"],
  },
  {
    slug: "grind", term: "Grind", pron: "grynd", pos: "noun", cat: "gaming",
    year: 1999, pop: 78, trend: 1, status: "classic",
    def: "Repetitive effort undertaken for slow, guaranteed progress rather than enjoyment. In games it means farming levels or currency; outside them, any long unglamorous stretch of work.",
    eli: "Doing the same boring task again and again because it slowly gets you what you want.",
    org: "Standard vocabulary in massively multiplayer games from the late 1990s, where progression was explicitly time-gated. Hustle culture borrowed it wholesale.",
    ex: ["Forty hours of grind for one cosmetic item.", "Back on the grind after two weeks away."],
    rel: ["sweaty", "hustle-culture", "lock-in"], tags: ["progression", "work-crossover"],
  },
  {
    slug: "meta", term: "Meta", pron: "MET-uh", pos: "noun", cat: "gaming",
    year: 1995, pop: 84, trend: 2, status: "classic",
    def: "The set of strategies currently considered strongest in a game, as determined by the community rather than the designers. Shifts with every balance patch.",
    eli: "The way most good players agree is the best way to play right now. It changes whenever the game gets updated.",
    org: "Short for \"metagame\", used in trading card games from the 1990s and adopted by every competitive title since. Backronymed by players as \"most effective tactic available\".",
    ex: ["That build was meta for two weeks and then got nerfed.", "Playing off-meta is fine until you have to explain it to the team."],
    rel: ["nerf", "sweaty", "gg"], tags: ["strategy", "esports", "balance"],
  },
  {
    slug: "nerf", term: "Nerf", pron: "nurf", pos: "verb", cat: "gaming",
    year: 1997, pop: 76, trend: 1, status: "classic",
    def: "To weaken something in an update in order to restore balance. Its opposite is to buff. Widely used outside games for any change that quietly reduces value.",
    eli: "When the people who make a game make something less powerful because it was winning too much.",
    org: "From the foam Nerf toy brand, used by Ultima Online players in 1997 to complain that a weapon had been made harmlessly soft.",
    ex: ["They nerfed the shotgun and the whole meta shifted overnight.", "The free tier got nerfed again this quarter."],
    rel: ["meta", "gg", "grind"], tags: ["balance", "patches", "design"],
  },
  {
    slug: "speedrun", term: "Speedrun", pron: "SPEED-run", pos: "noun", cat: "gaming",
    year: 1994, pop: 72, trend: 3, status: "classic",
    def: "A recorded attempt to finish a game as quickly as possible under agreed rules, often exploiting bugs. Also used figuratively for doing anything at unreasonable speed.",
    eli: "Finishing a game as fast as humanly possible, using every shortcut and glitch, and timing yourself against everyone else.",
    org: "Formalised by Doom players sharing demo files in 1994, and now a large community with verification boards, categories and annual charity marathons.",
    ex: ["The any-percent world record is under four minutes.", "He speedran the onboarding and broke three things."],
    rel: ["grind", "clutch", "gg"], tags: ["competition", "community", "records"],
  },
  {
    slug: "sweaty", term: "Sweaty", pron: "SWET-ee", pos: "adjective", cat: "gaming",
    year: 2012, pop: 67, trend: 5, status: "mainstream",
    def: "Describing a player who brings maximum competitive effort to a context where others are playing casually. Neither purely praise nor purely insult.",
    eli: "Trying extremely hard in a game that other people are just playing for fun.",
    org: "Console shooter lobbies in the early 2010s, from the image of someone concentrating hard enough to sweat. It shares ancestry with \"tryhard\".",
    ex: ["It is a party game and he brought a sweaty loadout.", "Casual night turned sweaty in about four minutes."],
    rel: ["tilt", "meta", "grind"], tags: ["effort", "lobbies"],
  },
  {
    slug: "tilt", term: "Tilt", pron: "tilt", pos: "noun", cat: "gaming",
    year: 2003, pop: 69, trend: 4, status: "classic",
    def: "A state of frustration in which emotion overrides judgement and performance degrades further, producing a spiral of increasingly poor decisions.",
    eli: "Getting so annoyed after losing that you play worse, lose again, and get even more annoyed.",
    org: "From pinball, where tilting the machine forfeited the ball. Poker players adopted it, and online games made it the standard word for competitive frustration.",
    ex: ["I am on tilt, I should stop playing.", "Two bad reviews and the whole team tilted."],
    rel: ["crash-out", "clutch", "sweaty"], tags: ["psychology", "poker", "esports"],
  },
  {
    slug: "buff", term: "Buff", pron: "buf", pos: "verb", cat: "gaming",
    year: 1999, pop: 63, trend: 0, status: "classic",
    def: "To strengthen something in an update, the counterpart to a nerf. As a noun, a temporary beneficial effect applied to a character.",
    eli: "Making something in a game stronger, the opposite of a nerf.",
    org: "Massively multiplayer game vocabulary of the late 1990s, from buffing meaning to polish. Both senses, the patch change and the temporary effect, coexist without confusion.",
    ex: ["They buffed the shotgun and the meta shifted back.", "Coffee is just a real-life buff."],
    rel: ["nerf", "meta", "patch-notes"], tags: ["balance", "mmo", "design"],
  },
  {
    slug: "smurf", term: "Smurf", pron: "smurf", pos: "noun", cat: "gaming",
    year: 1996, pop: 51, trend: 2, status: "classic",
    def: "A secondary account used by a skilled player to compete against beginners, ruining the matchmaking the ranking system was built to provide.",
    eli: "A good player using a new account to play against beginners and win easily.",
    org: "Named in 1996, when two top Warcraft II players made new accounts called PapaSmurf and Smurfette because nobody would play them under their real names.",
    ex: ["Level four account with perfect aim. Obvious smurf.", "Smurfing is the main complaint in every ranked ladder."],
    rel: ["elo-hell", "sweaty", "stream-sniping"], tags: ["matchmaking", "competitive", "warcraft"],
  },
  {
    slug: "elo-hell", term: "Elo hell", pron: "EE-loh hel", pos: "noun", cat: "gaming",
    year: 2011, pop: 42, trend: -1, status: "mainstream",
    def: "The belief that a player is trapped at a rank below their ability by bad teammates. Statistically dubious over large samples, and universally believed.",
    eli: "The feeling that you are stuck at a low rank because your teammates keep losing, not you.",
    org: "Named after the Elo rating system devised for chess by Arpad Elo. Analysis of large match datasets consistently shows individual skill dominates over enough games.",
    ex: ["Convinced he is in elo hell after nine hundred games.", "If you are there for a thousand matches, it is not the teammates."],
    rel: ["smurf", "tilt", "skill-issue"], tags: ["ranking", "chess", "psychology"],
  },
  {
    slug: "gacha", term: "Gacha", pron: "GAH-chuh", pos: "noun", cat: "gaming",
    year: 2010, pop: 56, trend: 6, status: "mainstream",
    def: "A monetisation model where players pay for randomised character or item draws. Pity systems guarantee a result after a set number of failures.",
    eli: "Paying for a random prize in a game, hoping to get the character you want.",
    org: "Named after Japanese gashapon capsule toy machines. Mobile gacha games became one of the largest revenue categories in the industry, and prompted regulation in several countries.",
    ex: ["Two hundred pulls and still no pity trigger.", "Several countries now require disclosed drop rates."],
    rel: ["loot-box", "battle-pass", "grind"], tags: ["monetisation", "japan", "mobile"],
  },
  {
    slug: "loot-box", term: "Loot box", pron: "loot boks", pos: "noun", cat: "gaming",
    year: 2010, pop: 54, trend: -2, status: "mainstream",
    def: "A purchasable container yielding random rewards. The subject of gambling investigations in multiple jurisdictions, with several outright bans.",
    eli: "A paid mystery box in a game that gives you random items.",
    org: "Spread from Asian free-to-play games into Western titles around 2010. Belgium ruled them a form of gambling in 2018, and several publishers withdrew them from that market.",
    ex: ["The backlash over paid loot boxes reshaped the industry.", "Belgium banned them outright and the sky did not fall."],
    rel: ["gacha", "battle-pass", "grind"], tags: ["monetisation", "regulation", "gambling"],
  },
  {
    slug: "battle-pass", term: "Battle pass", pron: "BAT-ul pas", pos: "noun", cat: "gaming",
    year: 2013, pop: 58, trend: 1, status: "mainstream",
    def: "A seasonal progression track offering rewards for play, sold as a fixed-price alternative to random purchases. It converts spending into an attendance requirement.",
    eli: "A season pass in a game that gives you rewards for playing a lot.",
    org: "Introduced by Dota 2 in 2013 and made universal by Fortnite. It answered the loot box backlash by replacing randomness with obligation.",
    ex: ["Bought the battle pass and now the game is a second job.", "Fixed price, unfixed time cost."],
    rel: ["loot-box", "gacha", "grind"], tags: ["monetisation", "seasons", "fortnite"],
  },
  {
    slug: "griefing", term: "Griefing", pron: "GREEF-ing", pos: "noun", cat: "gaming",
    year: 1999, pop: 47, trend: 0, status: "classic",
    def: "Playing to ruin other people's experience rather than to win, by blocking, sabotaging or destroying within the rules the game allows.",
    eli: "Playing a game just to annoy other players instead of trying to win.",
    org: "Named in massively multiplayer games of the late 1990s. Because griefing usually stays inside the rules, it is a design problem before it is a moderation one.",
    ex: ["Blocked the only doorway for an hour. Pure griefing.", "You cannot ban your way out of a design flaw."],
    rel: ["troll", "afk", "camping"], tags: ["mmo", "moderation", "design"],
  },
  {
    slug: "camping", term: "Camping", pron: "KAMP-ing", pos: "noun", cat: "gaming",
    year: 1996, pop: 49, trend: -1, status: "classic",
    def: "Remaining in one advantageous position rather than moving, effective and near-universally resented. Spawn camping, attacking players as they respawn, is the least forgiven form.",
    eli: "Hiding in one good spot and waiting instead of moving around.",
    org: "First-person shooter vocabulary from the Quake era of the mid-1990s. The tension between effective and enjoyable play has never been resolved.",
    ex: ["Camped the same corner for the whole match.", "Spawn camping is where the arguments actually start."],
    rel: ["griefing", "meta", "sweaty"], tags: ["shooters", "tactics", "etiquette"],
  },
  {
    slug: "ragequit", term: "Ragequit", pron: "RAYJ-kwit", pos: "verb", cat: "gaming",
    year: 2004, pop: 57, trend: 0, status: "classic",
    def: "To leave a game abruptly out of anger rather than because it has ended. Extended to walking out of any activity in visible frustration.",
    eli: "Quitting a game in the middle because you are too annoyed to keep playing.",
    org: "Online multiplayer vocabulary of the early 2000s. Many games now penalise it explicitly, since one player leaving ruins the match for everyone remaining.",
    ex: ["Ragequit at two minutes down and cost everyone the match.", "Ragequit the spreadsheet and went for a walk."],
    rel: ["tilt", "crash-out", "malding"], tags: ["anger", "multiplayer", "etiquette"],
  },
  {
    slug: "aggro", term: "Aggro", pron: "AG-roh", pos: "noun", cat: "gaming",
    year: 1999, pop: 43, trend: 0, status: "classic",
    def: "The attention of hostile enemies, tracked as a value that determines who they attack. Pulling aggro means becoming the target, deliberately or catastrophically.",
    eli: "How much the enemies in a game want to attack you specifically.",
    org: "Massively multiplayer vocabulary from EverQuest onward, clipped from aggravation. It gave group play its role structure: someone has to hold aggro so everyone else can work.",
    ex: ["Pulled aggro on the whole room by sneezing.", "Attracted aggro from the entire comment section."],
    rel: ["griefing", "grind", "meta"], tags: ["mmo", "mechanics", "roles"],
  },
  {
    slug: "lag", term: "Lag", pron: "lag", pos: "noun", cat: "gaming",
    year: 1996, pop: 71, trend: 0, status: "classic",
    def: "Delay between an action and its effect, caused by network latency. Rubberbanding is its visible form, where a character snaps back to a previous position.",
    eli: "When a game responds late because your connection is slow.",
    org: "Named in the earliest online shooters and never replaced. It remains the universal excuse, deployed with roughly the same sincerity as a bad referee decision.",
    ex: ["It was lag, obviously.", "Rubberbanding across the map for nine seconds."],
    rel: ["ping", "hitbox", "afk"], tags: ["network", "latency", "excuses"],
  },
  {
    slug: "ping", term: "Ping", pron: "ping", pos: "noun", cat: "gaming",
    year: 1983, pop: 59, trend: 1, status: "classic",
    def: "Round-trip network latency in milliseconds. Also a verb meaning to contact someone briefly, which is now its dominant sense in workplaces.",
    eli: "How long it takes a message to reach a server and come back. Also means giving someone a quick nudge.",
    org: "Written by Mike Muuss in 1983 and named after sonar. Its migration from network diagnostics to office vocabulary is one of the cleaner examples of jargon escaping.",
    ex: ["Forty milliseconds of ping and still blaming the connection.", "Ping me when the document is ready."],
    rel: ["lag", "hitbox", "afk"], tags: ["network", "diagnostics", "workplace"],
  },
  {
    slug: "hitbox", term: "Hitbox", pron: "HIT-boks", pos: "noun", cat: "gaming",
    year: 1998, pop: 41, trend: 0, status: "classic",
    def: "The invisible shape used to determine whether an attack connects, which frequently does not match the visible model. A permanent source of argument.",
    eli: "The invisible shape around a character that decides whether a hit counts.",
    org: "Standard game development vocabulary that players adopted to explain apparent injustice. Mismatch between hitbox and visual model is a real and common design compromise.",
    ex: ["The hitbox is a foot wider than the sword.", "Frame data and hitboxes are how fighting game arguments get settled."],
    rel: ["lag", "meta", "exploit"], tags: ["mechanics", "design", "fighting-games"],
  },
  {
    slug: "exploit", term: "Exploit", pron: "EKS-ployt", pos: "noun", cat: "gaming",
    year: 1999, pop: 48, trend: 1, status: "classic",
    def: "Using a bug for advantage. The line between an exploit and clever play is drawn by developers after the fact, which is why the argument never ends.",
    eli: "Using a glitch in a game to get an unfair advantage.",
    org: "Shared with security vocabulary, where an exploit weaponises a vulnerability. In games the ethics depend entirely on context: speedrunning celebrates what ranked play bans.",
    ex: ["Patched the exploit and invalidated four world records.", "One community's exploit is another's technique."],
    rel: ["speedrun", "hitbox", "griefing"], tags: ["bugs", "ethics", "competitive"],
  },
  {
    slug: "crunch", term: "Crunch", pron: "krunch", pos: "noun", cat: "gaming",
    year: 2004, pop: 54, trend: 3, status: "mainstream",
    def: "Extended mandatory overtime before a game ships. A recurring industrial-relations issue rather than an occasional emergency.",
    eli: "Long forced overtime before a game is released.",
    org: "Named publicly by the 2004 EA Spouse blog post, which described conditions at Electronic Arts and led to lawsuits. The practice and the argument have both continued since.",
    ex: ["Eighteen months of crunch and a third of the studio left after launch.", "Crunch is a scheduling failure sold as dedication."],
    rel: ["live-service", "hustle-culture", "grind"], tags: ["labour", "industry", "burnout"],
  },
  {
    slug: "live-service", term: "Live service", pron: "lyve SUR-vis", pos: "noun", cat: "gaming",
    year: 2015, pop: 51, trend: 2, status: "mainstream",
    def: "A game designed to be updated and monetised indefinitely rather than sold once. Its economics require players to keep returning, which shapes every design decision.",
    eli: "A game that keeps getting updates and keeps asking for money, instead of being finished when you buy it.",
    org: "Became the dominant model in the mid-2010s. Its failure mode is well documented: most live service games are shut down, taking the purchased content with them.",
    ex: ["Servers closed and the game people paid for stopped existing.", "Retention metrics are the design brief."],
    rel: ["battle-pass", "gacha", "crunch"], tags: ["business-model", "industry", "preservation"],
  },
  {
    slug: "permadeath", term: "Permadeath", pron: "PUR-muh-deth", pos: "noun", cat: "gaming",
    year: 1980, pop: 37, trend: 2, status: "classic",
    def: "A rule where death is final and progress is lost. It makes every decision consequential, which is why the design keeps returning despite being unforgiving.",
    eli: "When dying in a game means starting completely over, losing everything.",
    org: "Standard in the 1980 game Rogue and its descendants. Its revival in the 2010s roguelike boom showed that consequence is a design feature, not merely an old limitation.",
    ex: ["Forty hours gone to one mistake.", "Permadeath makes caution meaningful."],
    rel: ["roguelike", "grind", "exploit"], tags: ["design", "roguelike", "consequence"],
  },
  {
    slug: "roguelike", term: "Roguelike", pron: "ROHG-lyke", pos: "noun", cat: "gaming",
    year: 1993, pop: 44, trend: 4, status: "classic",
    def: "A genre defined by procedurally generated levels and permadeath. Roguelite loosens the rules by letting some progress carry between runs.",
    eli: "A game where the levels are randomly built each time and dying means starting again.",
    org: "Named after Rogue and defined at a 1993 Usenet gathering that produced the Berlin Interpretation, a list of genre criteria that fans still argue about.",
    ex: ["Every run is different and every death is total.", "Whether it counts as a roguelike is a thirty-year argument."],
    rel: ["permadeath", "grind", "speedrun"], tags: ["genre", "procedural", "usenet"],
  },
  {
    slug: "cheese", term: "Cheese", pron: "cheez", pos: "verb", cat: "gaming",
    year: 1996, pop: 40, trend: 0, status: "classic",
    def: "To win using a tactic that is effective, unsatisfying and technically permitted. Distinct from an exploit because nothing is broken, only inelegant.",
    eli: "Winning with a cheap trick that works but feels unfair.",
    org: "Fighting game vocabulary from the 1990s, where repeating one move could beat inexperienced opponents. It is a social judgement rather than a rules violation.",
    ex: ["Cheesed the boss with the corner strategy.", "It is not cheating, it is just not fun for anyone else."],
    rel: ["exploit", "meta", "sweaty"], tags: ["tactics", "fighting-games", "etiquette"],
  },
  {
    slug: "backlog", term: "Backlog", pron: "BAK-log", pos: "noun", cat: "gaming",
    year: 2010, pop: 46, trend: 3, status: "mainstream",
    def: "The accumulated pile of purchased and unplayed games. A widely shared and cheerfully acknowledged consequence of frequent discounting.",
    eli: "All the games you bought and never played.",
    org: "Became a standard joke once digital storefronts made impulse purchases frictionless and seasonal sales made them cheap. The pile is bought faster than it can be played.",
    ex: ["Two hundred games in the backlog and I bought three more.", "The sale is the mechanism and the backlog is the result."],
    rel: ["live-service", "battle-pass", "grind"], tags: ["habits", "storefronts", "humour"],
  },
  {
    slug: "toxic", term: "Toxic", pron: "TOK-sik", pos: "adjective", cat: "gaming",
    year: 2010, pop: 68, trend: 1, status: "mainstream",
    def: "Behaving in a hostile, abusive or generally unpleasant way toward other players, particularly after a loss or mistake.",
    eli: "Being mean or nasty to other players, especially after losing.",
    org: "Adopted by competitive gaming communities in the early 2010s from the general English sense of poisonous, describing behaviour that ruins a match's atmosphere for everyone else.",
    ex: ["Muted him after two rounds of toxic chat.", "The community has a genuine toxicity problem in ranked."],
    rel: ["tilt", "ragequit", "griefing"], tags: ["behaviour", "competitive", "chat"],
  },
  {
    slug: "carry", term: "Carry", pron: "KAR-ee", pos: "verb", cat: "gaming",
    year: 2005, pop: 62, trend: 0, status: "classic",
    def: "To perform so far above the rest of a team that you effectively win the match on your own, or a player who reliably does so.",
    eli: "Playing so well that you win the game almost by yourself, dragging your team along.",
    org: "Multiplayer online battle arena vocabulary from the mid-2000s, where certain roles were explicitly designed to become powerful enough late in a match to carry a team to victory.",
    ex: ["He carried that whole game on his own.", "Zero help from the team, hard carry required."],
    rel: ["clutch", "smurf", "meta"], tags: ["performance", "moba", "teamplay"],
  },
  {
    slug: "int", term: "Int", pron: "int", pos: "verb", cat: "gaming",
    year: 2016, pop: 44, trend: 2, status: "mainstream",
    def: "To play recklessly and lose a winnable position on purpose or through obvious carelessness, short for intentionally feeding.",
    eli: "Playing badly on purpose, or so carelessly it looks like you gave up trying to win.",
    org: "Short for intentional feeding, gaming forum shorthand from the mid-2010s for throwing a match, whether out of frustration or genuine bad faith.",
    ex: ["He started inting the moment the scoreline went against him.", "Reported for inting, not just for being bad."],
    rel: ["tilt", "throw", "ragequit"], tags: ["behaviour", "competitive", "moba"],
  },
  {
    slug: "gg-ez", term: "GG EZ", pron: "jee-jee EE-zee", pos: "phrase", cat: "gaming",
    year: 2012, pop: 40, trend: -3, status: "classic",
    def: "A deliberately provocative variant of gg meaning good game easy, said to a defeated opponent as a taunt rather than a courtesy.",
    eli: "A rude version of good game that adds easy, said to rub in a win rather than be polite about it.",
    org: "Emerged in competitive shooter and MOBA chat in the early 2010s as a way to invert the sportsmanship of the original phrase into an insult.",
    ex: ["Won by one point and still had to type gg ez.", "GG ez is a great way to start a rematch request."],
    rel: ["gg", "toxic", "tilt"], tags: ["etiquette", "taunt", "competitive"],
  },
  {
    slug: "one-shot", term: "One-shot", pron: "wun-SHOT", pos: "verb", cat: "gaming",
    year: 1998, pop: 46, trend: 0, status: "classic",
    def: "To kill an opponent with a single hit, regardless of their remaining health, or a weapon capable of doing so.",
    eli: "Killing someone in one hit, no matter how much health they had left.",
    org: "Shooter vocabulary from the sniper-rifle era of late-1990s multiplayer games, where a headshot could end an opponent instantly regardless of skill gap.",
    ex: ["One-shot from across the map, no counterplay possible.", "That boss can one-shot you if you are not paying attention."],
    rel: ["hitbox", "clutch", "camping"], tags: ["shooter", "mechanics", "classic"],
  },
  {
    slug: "respawn", term: "Respawn", pron: "ree-SPAWN", pos: "verb", cat: "gaming",
    year: 1993, pop: 58, trend: -1, status: "classic",
    def: "To reappear in a game after being defeated, usually at a designated point and after a short delay, allowing play to continue.",
    eli: "Coming back into the game after dying, usually at a set spot after waiting a bit.",
    org: "Standard multiplayer shooter vocabulary since the early 1990s, one of the oldest surviving pieces of gaming jargon still used exactly as originally intended.",
    ex: ["Respawn timer felt like an eternity that round.", "Spawn camping means killing people the second they respawn."],
    rel: ["camping", "permadeath", "ping"], tags: ["mechanics", "shooter", "classic"],
  },
  {
    slug: "dlc", term: "DLC", pron: "dee-el-SEE", pos: "abbreviation", cat: "gaming",
    year: 2005, pop: 55, trend: -1, status: "classic",
    def: "Downloadable content: additional material sold or released after a game's initial launch, ranging from cosmetic items to full new story chapters.",
    eli: "Extra content you can buy or download after the main game, like new levels, characters or outfits.",
    org: "Enabled by widespread broadband and online console services from the mid-2000s onward, which made it commercially viable to sell games in ongoing pieces rather than as one finished product.",
    ex: ["The season pass covers all four planned DLC drops.", "Day-one DLC always sparks an argument about whether it should have shipped in the base game."],
    rel: ["live-service", "battle-pass", "microtransaction"], tags: ["monetisation", "industry", "abbreviation"],
  },
  {
    slug: "pay-to-win", term: "Pay-to-win", pron: "pay too win", pos: "adjective", cat: "gaming",
    year: 2010, pop: 60, trend: 3, status: "mainstream",
    def: "Describing a game in which spending real money grants a meaningful competitive advantage over players who do not, undermining the fairness of the contest itself.",
    eli: "A game where paying real money makes you stronger or more likely to win, which most competitive players consider unfair.",
    org: "Named around 2010 as free-to-play mobile and browser games proliferated, distinguishing cosmetic-only monetisation from monetisation that directly affects competitive outcomes.",
    ex: ["The new update quietly made the premium weapon pay-to-win.", "It is free to download and pay-to-win once you actually try to compete."],
    rel: ["microtransaction", "game-whale", "battle-pass"], tags: ["monetisation", "criticism", "mobile"],
  },
  {
    slug: "game-whale", term: "Whale", pron: "wayl", pos: "noun", cat: "gaming",
    year: 2012, pop: 51, trend: 4, status: "mainstream",
    def: "A player who spends a large amount of money on a free-to-play game, generating a disproportionate share of its revenue relative to the number of such players.",
    eli: "A player who spends a lot of real money on a free game, making up most of its earnings even though there are not many of them.",
    org: "Borrowed from casino industry vocabulary for a high-spending gambler, adopted by free-to-play mobile game economics around 2012 once developers began openly discussing spending tiers.",
    ex: ["A single whale can outspend a thousand regular players combined.", "The whole monetisation model is built around a small number of whales."],
    rel: ["microtransaction", "pay-to-win", "battle-pass"], tags: ["monetisation", "economics", "mobile"],
  },
  {
    slug: "microtransaction", term: "Microtransaction", pron: "MY-kroh-tran-zak-shun", pos: "noun", cat: "gaming",
    year: 2007, pop: 57, trend: 1, status: "classic",
    def: "A small in-game purchase, typically for cosmetics, currency or convenience, that individually seems minor but collectively forms a major revenue model.",
    eli: "A small purchase inside a game, like a skin or extra currency, that costs a little but adds up across millions of players.",
    org: "Standard vocabulary in mobile and free-to-play game design from the late 2000s onward, and a frequent target of criticism when it edges toward affecting competitive balance.",
    ex: ["The battle pass is basically forty microtransactions bundled together.", "Cosmetic-only microtransactions are the least controversial version of this model."],
    rel: ["game-whale", "pay-to-win", "dlc"], tags: ["monetisation", "industry", "mobile"],
  },
  {
    slug: "battle-royale", term: "Battle royale", pron: "BAT-ul roy-AL", pos: "noun", cat: "gaming",
    year: 2017, pop: 66, trend: -3, status: "classic",
    def: "A genre in which a large number of players compete on a shrinking map until only one player or team remains, combining scavenging, positioning and combat.",
    eli: "A game type where lots of players fight on a map that keeps getting smaller until only one is left.",
    org: "Popularised by a 2017 game built by a modder who had refined the format across several earlier titles, itself named after a 2000 Japanese film and novel about a forced last-one-standing contest.",
    ex: ["The battle royale genre briefly dominated the entire industry's release schedule.", "A hundred players land, one team survives."],
    rel: ["live-service", "camping", "permadeath"], tags: ["genre", "2017", "multiplayer"],
  },
  {
    slug: "no-scope", term: "No-scope", pron: "noh skohp", pos: "noun", cat: "gaming",
    year: 2007, pop: 39, trend: -2, status: "classic",
    def: "A sniper rifle kill made without using the weapon's zoomed sight, considered a high-skill, high-risk trick shot in first-person shooters.",
    eli: "Killing someone with a sniper rifle without using its zoom, which is much harder and looked down on or celebrated depending on the crowd.",
    org: "First-person shooter vocabulary from the mid-to-late 2000s, when console shooters made trick-shot montages a genuine competitive video genre in their own right.",
    ex: ["Hit a 360 no-scope and immediately had to show everyone the clip.", "No-scope montages were their own YouTube genre for a while."],
    rel: ["gg", "one-shot", "clutch"], tags: ["shooter", "skill", "youtube"],
  },
  {
    slug: "hardstuck", term: "Hardstuck", pron: "HARD-stuk", pos: "adjective", cat: "gaming",
    year: 2015, pop: 47, trend: 3, status: "mainstream",
    def: "Unable to climb past a particular competitive rank despite repeated attempts, implying a plateau in skill rather than a temporary slump.",
    eli: "Stuck at the same rank in a competitive game no matter how many times you try to climb higher.",
    org: "Ranked ladder vocabulary from the mid-2010s, once competitive matchmaking systems made a player's exact rank a persistent, visible number rather than a private statistic.",
    ex: ["Hardstuck the same rank for three seasons straight.", "He blames the team, but he has been hardstuck alone in every game too."],
    rel: ["elo-hell", "tilt", "smurf"], tags: ["ranked", "competitive", "matchmaking"],
  },
  {
    slug: "main", term: "Main", pron: "mayn", pos: "noun", cat: "gaming",
    year: 1999, pop: 54, trend: 0, status: "classic",
    def: "The character, class or strategy a player has chosen as their primary, most-practised option, used as both a noun and a verb.",
    eli: "The character or style you mostly play and are best at.",
    org: "Fighting game vocabulary from the late 1990s, where committing to one character deeply enough to master their full move set was considered essential to real competitive play.",
    ex: ["He mains the same character he picked a decade ago.", "Picking up a new main mid-season is a bold move."],
    rel: ["meta", "smurf", "grind"], tags: ["fighting-games", "identity", "competitive"],
  },
  {
    slug: "wombo-combo", term: "Wombo combo", pron: "WOM-boh KOM-boh", pos: "noun", cat: "gaming",
    year: 2011, pop: 36, trend: -1, status: "niche",
    def: "A spectacular, often lucky-looking sequence of coordinated abilities between teammates that eliminates an opponent in one dramatic chain.",
    eli: "A flashy, team-up move where several players' abilities combine perfectly to take someone out in one go.",
    org: "Named after a 2011 highlight clip whose commentator repeatedly shouted the phrase, which stuck as the standard term for this kind of coordinated multi-ability kill.",
    ex: ["That wombo combo should be in a highlight reel.", "Pure luck, but it looked like a wombo combo."],
    rel: ["clutch", "carry", "meta"], tags: ["moba", "teamplay", "highlight"],
  },
  {
    slug: "cracked", term: "Cracked", pron: "krakt", pos: "adjective", cat: "gaming",
    year: 2018, pop: 49, trend: 5, status: "mainstream",
    def: "Extremely skilled, often to a degree that looks unnatural or unfairly good compared to an average player.",
    eli: "Really, really good at a game, almost unfairly so.",
    org: "Streaming and competitive shooter vocabulary from the late 2010s, describing mechanical skill so far above the norm it prompts genuine suspicion or awe.",
    ex: ["He is cracked at this game, it is honestly frustrating to play against.", "That aim was cracked, no other word for it."],
    rel: ["sweaty", "tryhard", "clutch"], tags: ["skill", "shooter", "streaming"],
  },
  {
    slug: "diff", term: "Diff", pron: "dif", pos: "noun", cat: "gaming",
    year: 2019, pop: 40, trend: 4, status: "mainstream",
    def: "Short for difference, used to attribute a match's outcome to a specific skill gap in one role or lane, as in top diff or jungle diff.",
    eli: "A short way of saying one specific part of the team was clearly better or worse than the opponent, and that decided the game.",
    org: "Competitive online battle arena chat shorthand from the late 2010s, used to assign credit or blame to a specific role rather than the team as a whole.",
    ex: ["Lost that one hard, mid diff the whole game.", "Jungle diff carried us honestly."],
    rel: ["carry", "smurf", "int"], tags: ["moba", "chat", "competitive"],
  },
  {
    slug: "stat-check", term: "Stat check", pron: "stat chek", pos: "noun", cat: "gaming",
    year: 2016, pop: 34, trend: 2, status: "niche",
    def: "A situation decided almost entirely by raw numerical advantage, such as level or gear, rather than by player skill or decision-making.",
    eli: "When a fight is decided just by who has better stats or gear, regardless of who actually plays better.",
    org: "Role-playing and strategy game vocabulary, describing moments when the underlying numbers make the outcome close to inevitable before any actual play begins.",
    ex: ["Ten levels higher, it was a pure stat check.", "Skill matters less once it becomes a stat check."],
    rel: ["grind", "meta", "cheese"], tags: ["mechanics", "rpg", "balance"],
  },
  {
    slug: "boosted", term: "Boosted", pron: "BOOS-tid", pos: "adjective", cat: "gaming",
    year: 2013, pop: 43, trend: 1, status: "mainstream",
    def: "Having reached a rank through someone else's help, such as a higher-skilled player carrying the account, rather than through the player's own ability.",
    eli: "Reaching a high rank because someone else helped or played for you, not because you are actually that good.",
    org: "Ranked matchmaking vocabulary from the early 2010s, used both as a factual account-sharing complaint and as a general insult about someone overestimating their own skill.",
    ex: ["That rank is clearly boosted, watch him play his actual level.", "Boosted accounts get reported constantly."],
    rel: ["smurf", "hardstuck", "carry"], tags: ["ranked", "accusation", "competitive"],
  },
  {
    slug: "throw", term: "Throw", pron: "throh", pos: "verb", cat: "gaming",
    year: 2008, pop: 46, trend: 1, status: "classic",
    def: "To lose a match from a winning position through a bad decision, carelessness or a loss of focus, distinct from inting in that a throw can be an honest mistake rather than a deliberate one.",
    eli: "Losing a game you were clearly winning, because of one bad mistake near the end.",
    org: "Competitive gaming vocabulary from the late 2000s, describing the specific, memorable pain of losing a game that felt already won.",
    ex: ["Ten kills ahead and still found a way to throw it.", "That was not bad luck, that was a throw."],
    rel: ["int", "tilt", "clutch"], tags: ["mistakes", "competitive", "classic"],
  },
];
