import type { RawTerm } from "../types";

export const memeTerms: RawTerm[] = [
  {
    slug: "canon-event", term: "Canon event", pron: "KAN-un ee-VENT", pos: "noun", cat: "meme",
    year: 2023, pop: 66, trend: -12, status: "fading",
    def: "An unpleasant but formative experience treated as unavoidable, and therefore not to be prevented, because it is required for a person to become who they are.",
    eli: "A bad thing that has to happen to you so you grow up. Friends joke that they cannot save you from it.",
    org: "Taken from Spider-Man: Across the Spider-Verse in 2023, where fixed events must not be disrupted. TikTok applied it to bad haircuts and worse relationships within weeks.",
    ex: ["I cannot let you skip this. It is a canon event.", "Getting scammed by a fake ticket site is a canon event."],
    rel: ["lore", "era", "headcanon"], tags: ["film", "growth", "tiktok"],
  },
  {
    slug: "copypasta", term: "Copypasta", pron: "KOP-ee-pah-stuh", pos: "noun", cat: "meme",
    year: 2006, pop: 64, trend: -1, status: "classic",
    def: "A block of text circulated by repeated copying and pasting, usually absurd or overwrought, whose humour comes from its appearance in unexpected places.",
    eli: "A funny chunk of writing people paste into chats over and over until everyone recognises it.",
    org: "Named on 4chan around 2006 by blending \"copy-paste\" with \"pasta\". Reddit and Twitch chat kept the form alive and gave it new classics.",
    ex: ["Someone dropped the entire navy seal copypasta in the standup channel.", "It started as a real review and became copypasta within a week."],
    rel: ["shitpost", "lore", "normie"], tags: ["4chan", "text", "chat"],
  },
  {
    slug: "cursed-image", term: "Cursed image", pron: "KURST IM-ij", pos: "noun", cat: "meme",
    year: 2015, pop: 58, trend: -5, status: "niche",
    def: "A photograph that is unsettling for reasons the viewer cannot articulate, usually because ordinary elements are combined in a way that feels subtly wrong.",
    eli: "A photo where nothing scary is happening but it still makes you feel weird and you cannot explain why.",
    org: "Formalised by Tumblr blogs around 2015 and quickly answered by the gentler \"blessed image\". Both rely on low-quality, contextless photography.",
    ex: ["A man in a suit holding forty balloons in an empty pool is a cursed image.", "Do not open the folder, it is all cursed images."],
    rel: ["shitpost", "deep-fried", "normie"], tags: ["tumblr", "aesthetic", "photography"],
  },
  {
    slug: "deep-fried", term: "Deep-fried", pron: "deep FRYD", pos: "adjective", cat: "meme",
    year: 2015, pop: 49, trend: -7, status: "niche",
    def: "Describing an image degraded on purpose through repeated compression, saturation and contrast, so the visible damage becomes the joke.",
    eli: "A picture saved and re-saved so many times it looks crunchy and broken, and that is exactly the point.",
    org: "Emerged around 2015 as a reaction against polished meme templates, echoing the natural decay of images passed between platforms.",
    ex: ["Deep-fry it until the text is barely legible, then post.", "That logo has been through so many reposts it is deep-fried."],
    rel: ["shitpost", "cursed-image", "copypasta"], tags: ["aesthetic", "images"],
  },
  {
    slug: "lore", term: "Lore", pron: "lor", pos: "noun", cat: "meme",
    year: 2021, pop: 73, trend: 8, status: "mainstream",
    def: "The accumulated backstory attached to a person, account or running joke, treated with the seriousness normally reserved for fiction.",
    eli: "All the background stories about a person or joke that you need to know before the newest joke makes sense.",
    org: "Borrowed from games and fantasy fiction, then applied to real people on Twitter and TikTok around 2021 as a way of framing ordinary lives as continuing narratives.",
    ex: ["You cannot understand that reply without three years of lore.", "New lore dropped about the guy who runs the bakery account."],
    rel: ["canon-event", "headcanon", "parasocial"], tags: ["narrative", "fandom-crossover"],
  },
  {
    slug: "normie", term: "Normie", pron: "NOR-mee", pos: "noun", cat: "meme",
    year: 2012, pop: 55, trend: -9, status: "fading",
    def: "A person outside a given internet subculture, who encounters its material only once it has reached mainstream platforms and lost its original context.",
    eli: "Someone who is not part of an internet group and only hears its jokes long after everyone inside has moved on.",
    org: "Grew out of 4chan and early Reddit in the early 2010s to mark the boundary between insiders and everyone else. Now used more playfully than defensively.",
    ex: ["Once it hits the family group chat it is officially normie.", "I have gone full normie, I only use the default settings."],
    rel: ["cringe", "copypasta", "gatekeep"], tags: ["subculture", "4chan"],
  },
  {
    slug: "ragebait", term: "Ragebait", pron: "RAYJ-bayt", pos: "noun", cat: "meme",
    year: 2015, pop: 82, trend: 14, status: "rising",
    def: "Content engineered to provoke anger so that furious replies and quote-posts push it further through recommendation systems.",
    eli: "Something posted on purpose to make people angry, because angry people share it and that gets the poster attention.",
    org: "Named in the mid-2010s as a sharper cousin of clickbait, once creators worked out that engagement-ranked feeds reward outrage as much as interest.",
    ex: ["Do not quote it, that recipe video is ragebait.", "The headline is ragebait and the article says the opposite."],
    rel: ["ratio", "algorithm", "shitpost"], tags: ["engagement", "manipulation"],
  },
  {
    slug: "shitpost", term: "Shitpost", pron: "SHIT-pohst", pos: "noun", cat: "meme",
    year: 2012, pop: 70, trend: 1, status: "classic",
    def: "A post made with deliberate disregard for quality or relevance, whose value lies in being absurd rather than in communicating anything.",
    eli: "A post made on purpose to be silly and pointless, just because it is funny.",
    org: "Coined on forums in the early 2010s as an insult for low-effort posting, then reclaimed as a craft with its own standards and admired practitioners.",
    ex: ["The account is 90 percent shitposts and 10 percent genuinely useful news.", "Do not overthink it, it is a shitpost."],
    rel: ["copypasta", "ragebait", "deep-fried"], tags: ["humour", "forums"],
  },
  {
    slug: "meme", term: "Meme", pron: "meem", pos: "noun", cat: "meme",
    year: 1976, pop: 95, trend: 0, status: "classic",
    def: "A unit of culture that spreads by imitation. Online it narrowed to mean a shareable joke in a recognisable format, which is a small subset of the original idea.",
    eli: "An idea or joke that spreads by people copying and changing it.",
    org: "Coined by Richard Dawkins in The Selfish Gene in 1976, from the Greek mimeme, as an analogy to the gene. Internet usage narrowed it enormously and Dawkins has said as much.",
    ex: ["The format lasted four days, which is a long life for a meme.", "Dawkins meant something much broader than image macros."],
    rel: ["template", "reaction-image", "dank"], tags: ["dawkins", "theory", "culture"],
  },
  {
    slug: "template", term: "Template", pron: "TEM-playt", pos: "noun", cat: "meme",
    year: 2010, pop: 68, trend: 1, status: "classic",
    def: "A reusable structure with fixed elements and blank slots. The joke lives in what you put in the slots, not in the image itself.",
    eli: "The reusable picture or layout of a meme, where you change the words each time.",
    org: "Image macro culture of the late 2000s formalised the idea. A template's value is precisely that everyone already knows the grammar, so a new caption reads instantly.",
    ex: ["A new template appears and there are ten thousand versions by morning.", "Explaining a template kills it."],
    rel: ["meme", "snowclone", "drake-format"], tags: ["format", "structure", "images"],
  },
  {
    slug: "snowclone", term: "Snowclone", pron: "SNOH-klohn", pos: "noun", cat: "meme",
    year: 2004, pop: 29, trend: 0, status: "niche",
    def: "A phrasal template with swappable slots, such as X is the new Y or if Eskimos have N words for snow. The linguistic equivalent of an image template.",
    eli: "A sentence pattern where you swap in different words to make a new joke.",
    org: "Coined by economist Glen Whitman in 2004 at the suggestion of linguist Geoffrey Pullum, on Language Log. Named after the much-repeated and largely false snow claim.",
    ex: ["In space, no one can hear you X.", "Every snowclone eventually escapes its source."],
    rel: ["template", "meme", "copypasta"], tags: ["linguistics", "language-log", "phrases"],
  },
  {
    slug: "rickroll", term: "Rickroll", pron: "RIK-rohl", pos: "verb", cat: "meme",
    year: 2007, pop: 72, trend: 0, status: "classic",
    def: "To trick someone into clicking a link that leads to the 1987 music video for Never Gonna Give You Up. The internet's most durable bait-and-switch.",
    eli: "Tricking someone into clicking a link that plays an old Rick Astley song.",
    org: "Descended from 4chan's duckroll in 2007, which swapped an image for a duck on wheels. Substituting the Astley video created something that has never entirely stopped working.",
    ex: ["Nearly two decades and people still fall for it.", "The link looked like a document and was not."],
    rel: ["bait", "meme", "copypasta"], tags: ["4chan", "2007", "prank"],
  },
  {
    slug: "doge", term: "Doge", pron: "dohj", pos: "noun", cat: "meme",
    year: 2013, pop: 61, trend: -3, status: "classic",
    def: "A Shiba Inu photograph captioned with ungrammatical inner monologue in Comic Sans: such wow, very meme. Later lent its name to a cryptocurrency.",
    eli: "A famous dog photo with funny broken-English captions floating around it.",
    org: "The photograph is of Kabosu, a rescue dog in Japan, posted by her owner in 2010. The caption style spread in 2013, and Dogecoin followed months later as a joke.",
    ex: ["such internet. very 2013. wow.", "Kabosu died in 2024 and the obituaries were genuine."],
    rel: ["memecoin", "meme", "template"], tags: ["2013", "dogs", "crypto"],
  },
  {
    slug: "pepe", term: "Pepe the Frog", pron: "PEP-ay", pos: "noun", cat: "meme",
    year: 2008, pop: 57, trend: 0, status: "classic",
    def: "A cartoon frog from Matt Furie's comic Boy's Club, adopted as a general-purpose reaction character and now the base for hundreds of Twitch emote variants.",
    eli: "A cartoon frog used to show feelings online, with hundreds of different versions.",
    org: "Created by Matt Furie in 2005 and spread on MySpace and 4chan from 2008. Furie fought a long legal and public campaign against its co-option by extremist groups.",
    ex: ["Most Pepe variants on Twitch are simply emotional vocabulary.", "The artist spent years reclaiming his own character."],
    rel: ["monkas", "sadge", "wojak"], tags: ["4chan", "twitch", "reaction"],
  },
  {
    slug: "wojak", term: "Wojak", pron: "VOY-yak", pos: "noun", cat: "meme",
    year: 2010, pop: 48, trend: -2, status: "classic",
    def: "A crudely drawn bald figure used to represent an everyman, endlessly modified into variants expressing specific social types and moods.",
    eli: "A simple bald cartoon face used to represent an ordinary person feeling something.",
    org: "Posted on a Polish imageboard around 2010, where wojak means soldier. Its infinite variability made it the template for an entire visual taxonomy of online types.",
    ex: ["There is a wojak for every possible state of mind.", "The variants form a whole classification system nobody designed."],
    rel: ["pepe", "gigachad", "npc"], tags: ["imageboards", "poland", "reaction"],
  },
  {
    slug: "gigachad", term: "Gigachad", pron: "GIG-uh-chad", pos: "noun", cat: "meme",
    year: 2017, pop: 55, trend: -4, status: "mainstream",
    def: "A heavily stylised image of an idealised man, used to mark a position as unassailably correct. Almost always ironic, and often self-deprecating.",
    eli: "A picture of an exaggerated strong man used to say someone made an unarguably good choice.",
    org: "From a digitally altered photo series by Russian artist Krista Sudmalis, mistaken for years for a real person or a rendering. The chad and virgin comparison format preceded it.",
    ex: ["Cancelled the subscription and read a book. Gigachad.", "The image was a photography project, not a person."],
    rel: ["wojak", "sigma", "based"], tags: ["imageboards", "irony", "masculinity"],
  },
  {
    slug: "reaction-image", term: "Reaction image", pron: "ree-AK-shun IM-ij", pos: "noun", cat: "meme",
    year: 2007, pop: 62, trend: 1, status: "classic",
    def: "A picture posted in place of a written response, carrying a precise emotional meaning that the community has agreed on over time.",
    eli: "A picture you post instead of typing how you feel.",
    org: "Imageboard practice of the mid-2000s that became universal. Reaction images function as a shared vocabulary: their meaning is conventional, not obvious from the image itself.",
    ex: ["Replied with a single reaction image and won the argument.", "The meaning is agreed, not depicted."],
    rel: ["pepe", "wojak", "emote"], tags: ["imageboards", "vocabulary", "images"],
  },
  {
    slug: "tfw", term: "TFW", pron: "tee-ef-DUB", pos: "abbreviation", cat: "meme",
    year: 2011, pop: 44, trend: -3, status: "classic",
    def: "That feel when. Introduces a specific and usually melancholy situation, paired with a reaction image. MFW, my face when, is the sibling form.",
    eli: "That feeling when. Used to describe a very specific moment, usually a sad or funny one.",
    org: "Imageboard vocabulary of the early 2010s, closely tied to the feels guy wojak. It gave a name to an emotion too precise for existing words.",
    ex: ["tfw the shop closed nine minutes ago", "mfw the meeting could have been an email"],
    rel: ["wojak", "reaction-image", "big-mood"], tags: ["imageboards", "abbreviation", "feeling"],
  },
  {
    slug: "dank", term: "Dank", pron: "dank", pos: "adjective", cat: "meme",
    year: 2013, pop: 39, trend: -8, status: "fading",
    def: "Originally high-quality and obscure, said of memes. Its meaning inverted through irony until it mostly marked memes as deliberately low-quality or old.",
    eli: "A word for memes that first meant really good and then came to mean deliberately bad.",
    org: "Cannabis slang for high-grade product, applied to memes around 2013. Its rapid semantic inversion is a clean example of how irony consumes evaluative slang.",
    ex: ["Dank memes was sincere for roughly eight months.", "By 2016 calling a meme dank was itself the joke."],
    rel: ["meme", "cringe", "normie"], tags: ["irony", "semantics", "2013"],
  },
  {
    slug: "drake-format", term: "Drake format", pron: "drayk FOR-mat", pos: "noun", cat: "meme",
    year: 2015, pop: 58, trend: -5, status: "classic",
    def: "A two-panel template with a rejection above and an endorsement below, from a 2015 music video. Among the most reproduced templates ever made.",
    eli: "The meme with two pictures: one saying no to something and one saying yes to something better.",
    org: "Taken from the video for Hotline Bling in 2015. Its structure is so clear that it needs no explanation in any language, which is why it travelled so far.",
    ex: ["Drake format, but it is about database indexes.", "The template survived the song entirely."],
    rel: ["template", "meme", "distracted-boyfriend"], tags: ["template", "music", "2015"],
  },
  {
    slug: "distracted-boyfriend", term: "Distracted boyfriend", pron: "dis-TRAK-tud BOY-frend", pos: "noun", cat: "meme",
    year: 2017, pop: 54, trend: -6, status: "classic",
    def: "A stock photograph of a man looking at a passing woman while his partner reacts. Used as a three-slot template for temptation and distraction.",
    eli: "The stock photo meme about being tempted by something new while ignoring what you have.",
    org: "A 2015 stock image by Antonio Guillem that went viral as a template in 2017. Its three labelled figures make it unusually flexible.",
    ex: ["Distracted boyfriend, but the new thing is a side project.", "The photographer had no idea what he had made."],
    rel: ["drake-format", "template", "meme"], tags: ["stock-photo", "template", "2017"],
  },
  {
    slug: "galaxy-brain", term: "Galaxy brain", pron: "GAL-uk-see brayn", pos: "noun", cat: "meme",
    year: 2017, pop: 45, trend: 0, status: "mainstream",
    def: "An escalating template where each glowing brain represents a supposedly more enlightened take, the final one being spectacularly stupid.",
    eli: "A meme where ideas get fancier and fancier until the last one is completely silly.",
    org: "Spread in 2017 from an expanding brain image set. The word now works alone as an adjective for overthought reasoning that arrives somewhere absurd.",
    ex: ["Galaxy-brained argument for skipping tests entirely.", "Each panel is more confident and less correct."],
    rel: ["template", "hot-take", "cope"], tags: ["template", "reasoning", "2017"],
  },
  {
    slug: "this-is-fine", term: "This is fine", pron: "this iz fyne", pos: "phrase", cat: "meme",
    year: 2013, pop: 66, trend: 1, status: "classic",
    def: "A dog sitting calmly in a burning room, used for denial in the face of obvious disaster. One of the most widely reproduced comic panels online.",
    eli: "A cartoon dog sitting in a fire saying everything is fine, used when things are clearly not fine.",
    org: "From KC Green's 2013 webcomic Gunshow. Green has noted that the second half of the strip, where the dog melts, is usually cropped out.",
    ex: ["Production is down and the status page says this is fine.", "The cropped version is more optimistic than the original."],
    rel: ["cope", "meme", "reaction-image"], tags: ["webcomic", "denial", "2013"],
  },
  {
    slug: "creepypasta", term: "Creepypasta", pron: "KREE-pee-pah-stuh", pos: "noun", cat: "meme",
    year: 2007, pop: 47, trend: 2, status: "classic",
    def: "A short horror story circulated as if true, written to be pasted between forums. The internet's campfire tale tradition.",
    eli: "A scary story shared online as though it really happened.",
    org: "Formed from copypasta plus creepy, around 2007. The genre produced Slender Man in 2009, which later escaped fiction with serious real-world consequences.",
    ex: ["The best creepypasta reads like a forum post, not a story.", "The format matters: it has to look found, not written."],
    rel: ["copypasta", "backrooms", "scp"], tags: ["horror", "forums", "fiction"],
  },
  {
    slug: "scp", term: "SCP Foundation", pron: "es-see-PEE", pos: "noun", cat: "meme",
    year: 2008, pop: 42, trend: 2, status: "classic",
    def: "A collaborative fiction project written as clinical containment reports about anomalous objects. Thousands of authors, one house style, strictly enforced.",
    eli: "A huge shared horror story written as if it were a secret organisation's filing system.",
    org: "Began with a single 2007 4chan post about a statue, and moved to a dedicated wiki in 2008. The rigid documentary format is what lets thousands of strangers write coherently together.",
    ex: ["Object class Euclid, containment procedures as follows.", "The format is the constraint that makes the collaboration work."],
    rel: ["creepypasta", "backrooms", "lore"], tags: ["collaborative", "horror", "wiki"],
  },
  {
    slug: "stonks", term: "Stonks", pron: "stonks", pos: "noun", cat: "meme",
    year: 2017, pop: 46, trend: -4, status: "classic",
    def: "A deliberate misspelling of stocks, used for financial decisions that are confidently wrong. Also used sincerely, and ironically, in the same sentence.",
    eli: "A joke misspelling of stocks, used when someone makes a very bad money decision confidently.",
    org: "From a 2017 image of a suited figure before a rising chart. It became the standard vocabulary of retail trading humour and peaked during the 2021 meme stock episode.",
    ex: ["Sold at the bottom. Stonks.", "The deliberate misspelling is doing all the tonal work."],
    rel: ["diamond-hands", "memecoin", "galaxy-brain"], tags: ["finance", "irony", "2021"],
  },
  {
    slug: "loss", term: "Loss", pron: "los", pos: "noun", cat: "meme",
    year: 2008, pop: 31, trend: 0, status: "niche",
    def: "A four-panel webcomic abstracted into a recognisable arrangement of lines and shapes, detectable in almost anything once you know the pattern.",
    eli: "A comic simplified down to a pattern of shapes, hidden inside other images as a long-running joke.",
    org: "From a 2008 strip of the webcomic Ctrl+Alt+Del. Its abstraction into pure geometry made it the most elaborate in-joke online, requiring no image, only an arrangement.",
    ex: ["Somebody found Loss in the fire exit signage.", "It survives because it can be encoded in almost anything."],
    rel: ["meme", "template", "shitpost"], tags: ["webcomic", "abstraction", "in-joke"],
  },
  {
    slug: "brainrot-italian", term: "Italian brainrot", pron: "i-TAL-yun BRAYN-rot", pos: "noun", cat: "meme",
    year: 2025, pop: 48, trend: 16, status: "rising",
    def: "A 2025 genre of generated absurd characters with rhyming pseudo-Italian names and short nonsense narrations, spread almost entirely by short video.",
    eli: "Silly AI-made characters with made-up Italian-sounding names that got very popular with kids in 2025.",
    org: "Emerged in early 2025 from generated audio and image tools. It is the clearest example so far of a meme genre that could not exist without generative models.",
    ex: ["He can name forty of them and I cannot name one.", "The first meme genre native to generated media."],
    rel: ["brainrot", "ai-slop", "skibidi"], tags: ["2025", "generative", "gen-alpha"],
  },
  {
    slug: "image-macro", term: "Image macro", pron: "IM-ij MAK-roh", pos: "noun", cat: "meme",
    year: 2004, pop: 44, trend: -2, status: "classic",
    def: "An image with bold white text top and bottom, the dominant meme form of roughly 2007 to 2013. Impact font is its signature.",
    eli: "The old style of meme with a picture and big white text above and below.",
    org: "Named on Something Awful around 2004, where macro referred to a stored shortcut that inserted an image. The format now reads as dated enough to be its own joke.",
    ex: ["Impact font instantly dates a meme to before 2014.", "Everything since is a reaction against the image macro."],
    rel: ["template", "meme", "dank"], tags: ["format", "history", "typography"],
  },
  {
    slug: "bait-and-switch", term: "Bait-and-switch", pron: "bayt and swich", pos: "noun", cat: "meme",
    year: 2007, pop: 36, trend: 0, status: "classic",
    def: "A format promising one thing and delivering another, of which rickrolling is the definitive example. The pleasure is in being caught by something you knew existed.",
    eli: "A joke where a link or video pretends to be one thing and turns out to be another.",
    org: "Formalised by duckrolling and then rickrolling on 4chan in 2007. It survives because the payload can be swapped while the mechanism stays intact.",
    ex: ["Clicked a spreadsheet link and got Rick Astley.", "The mechanism outlives every specific payload."],
    rel: ["rickroll", "bait", "meme"], tags: ["4chan", "prank", "format"],
  },
  {
    slug: "brainworms", term: "Brainworms", pron: "BRAYN-wurmz", pos: "noun", cat: "meme",
    year: 2021, pop: 39, trend: 7, status: "rising",
    def: "An idea lodged so firmly that it distorts everything the holder says. Usually applied affectionately to a harmless fixation, sometimes not.",
    eli: "An idea stuck in someone's head so firmly it affects everything they say.",
    org: "Online usage spread around 2021, distinct from brainrot: brainworms are about one specific idea taking over, brainrot about general degradation.",
    ex: ["He has brainworms about kerning and I respect it.", "Brainrot is the ambient version, brainworms the targeted one."],
    rel: ["brainrot", "rent-free", "roman-empire"], tags: ["obsession", "humour", "2021"],
  },
  {
    slug: "nostalgia-bait", term: "Nostalgia bait", pron: "nos-TAL-juh bayt", pos: "noun", cat: "meme",
    year: 2018, pop: 41, trend: 4, status: "mainstream",
    def: "Content trading entirely on recognition of a past era, requiring no joke beyond the reminder that you remember something.",
    eli: "Posts that only work because they remind you of something from your childhood.",
    org: "Named in the late 2010s as feeds filled with only nineties kids will remember formats. The mechanism is recognition, which is cheaper to produce than humour.",
    ex: ["Remember this? is not a joke, it is a prompt.", "Nostalgia bait is engagement bait with a longer runway."],
    rel: ["engagement-bait", "y2k", "frutiger-aero"], tags: ["nostalgia", "engagement", "format"],
  },
  {
    slug: "absurdist-meme", term: "Absurdist meme", pron: "ab-SURD-ist meem", pos: "noun", cat: "meme",
    year: 2016, pop: 38, trend: 2, status: "mainstream",
    def: "Humour built on incongruity with no punchline to decode, where the absence of a joke is the joke. Also called surreal or anti-humour.",
    eli: "Jokes that are funny because they make no sense and have no real punchline.",
    org: "Emerged as a reaction against explicable image macros around 2016. It rewards audiences fluent enough in the form to recognise when a structure is being subverted.",
    ex: ["No punchline, no reference, and still funny.", "Anti-humour needs an audience that knows the rules being broken."],
    rel: ["shitpost", "ohio", "brainrot"], tags: ["humour", "surreal", "format"],
  },
  {
    slug: "meta-meme", term: "Meta meme", pron: "MET-uh meem", pos: "noun", cat: "meme",
    year: 2015, pop: 34, trend: 1, status: "niche",
    def: "A meme about meme conventions, which requires fluency in the format it comments on. Corecore is a recent example at feature length.",
    eli: "A meme that is a joke about how memes work.",
    org: "A predictable stage in any form's development, arriving once the audience knows the conventions well enough for commentary to land without explanation.",
    ex: ["Three layers of reference and no base joke anywhere.", "It only works for people already fluent."],
    rel: ["corecore", "template", "dank"], tags: ["meta", "humour", "format"],
  },
  {
    slug: "hide-the-pain-harold", term: "Hide the Pain Harold", pron: "hyde thuh payn HAR-uld", pos: "noun", cat: "meme",
    year: 2011, pop: 42, trend: -2, status: "classic",
    def: "A stock photo of an older man smiling with visible discomfort, used to caption situations where someone is putting on a brave face over quiet suffering.",
    eli: "A stock photo of a man smiling in a way that looks like he is actually in pain, used for jokes about hiding how bad something feels.",
    org: "The subject, Andras Arato, a Hungarian stock photo model, discovered his own meme fame around 2011 and later leaned into it, appearing in interviews and even an advert as the character.",
    ex: ["Told the client the launch went great. Hide the Pain Harold face.", "That photo is doing a lot of Hide the Pain Harold work."],
    rel: ["this-is-fine", "cursed-image", "reaction-image"], tags: ["stock-photo", "reaction", "classic"],
  },
  {
    slug: "success-kid", term: "Success Kid", pron: "suk-SES kid", pos: "noun", cat: "meme",
    year: 2007, pop: 40, trend: -3, status: "classic",
    def: "A photo of a toddler clenching a fist with a determined expression, captioned to celebrate a small, hard-won personal victory.",
    eli: "A photo of a baby making a determined fist, used to celebrate a small win.",
    org: "Taken by the child's mother at the beach in 2007 and uploaded to a photo site, where it was discovered and turned into a determination-themed captioning template within a year.",
    ex: ["Parked in one attempt. Success Kid energy.", "The whole week has been a Success Kid moment."],
    rel: ["image-macro", "template", "based"], tags: ["stock-photo", "template", "2000s"],
  },
  {
    slug: "trollface", term: "Trollface", pron: "TROHL-fays", pos: "noun", cat: "meme",
    year: 2008, pop: 38, trend: -6, status: "fading",
    def: "A drawn grinning face used to signal that a post was a deliberate wind-up, marking the moment of the reveal in early rage-comic style stories.",
    eli: "A drawn smiling face used at the end of a joke to say you got tricked on purpose.",
    org: "Drawn by artist Carlos Ramirez in 2008 as part of the same wave of MS Paint rage comics that produced most of that era's reaction faces.",
    ex: ["Posted a fake announcement, ended with the trollface.", "The trollface era of forums has mostly passed."],
    rel: ["rage-comic", "shitpost", "image-macro"], tags: ["rage-comics", "2008", "classic"],
  },
  {
    slug: "rage-comic", term: "Rage comic", pron: "rayj KOM-ik", pos: "noun", cat: "meme",
    year: 2008, pop: 35, trend: -7, status: "fading",
    def: "A crudely drawn multi-panel comic using a stock set of simple faces to tell a short story of everyday frustration, usually ending on a punchline face.",
    eli: "A simply drawn comic strip using a small set of stock faces to tell a quick, relatable, frustrating story.",
    org: "Emerged on 4chan around 2008 from a single comic about a bathroom mishap. The format's deliberately crude style made it easy for anyone to make their own.",
    ex: ["The whole thread turned into rage comics within an hour.", "Rage comics were the format everyone briefly tried making."],
    rel: ["trollface", "image-macro", "greentext"], tags: ["4chan", "format", "2008"],
  },
  {
    slug: "bad-luck-brian", term: "Bad Luck Brian", pron: "bad luk BRY-un", pos: "noun", cat: "meme",
    year: 2012, pop: 34, trend: -8, status: "fading",
    def: "A stock yearbook photo captioned with escalating examples of comically terrible fortune, used to describe someone for whom nothing ever goes right.",
    eli: "A yearbook photo used to caption stories about someone who has the worst possible luck.",
    org: "Submitted to Reddit in 2012 by a friend of the pictured subject, Kyle Craven, whose awkward school photo made the caption format instantly work.",
    ex: ["Missed the flight by two minutes. Bad Luck Brian behaviour.", "His whole week has been Bad Luck Brian."],
    rel: ["success-kid", "image-macro", "template"], tags: ["stock-photo", "reddit", "2012"],
  },
  {
    slug: "philosoraptor", term: "Philosoraptor", pron: "fil-oh-soh-RAP-tur", pos: "noun", cat: "meme",
    year: 2008, pop: 33, trend: -6, status: "fading",
    def: "A drawn dinosaur head captioned with a deceptively simple, mildly troubling philosophical question, used to introduce a piece of stoner logic.",
    eli: "A cartoon dinosaur used to caption a strange but oddly deep-sounding question.",
    org: "One of the original advice-animal image macros from the late 2000s, paired with a clip-art raptor head to deliver questions with the tone of a genuine thought experiment.",
    ex: ["If a screenshot is deleted, did the argument ever happen? Philosoraptor.", "That is a genuinely good philosoraptor question."],
    rel: ["image-macro", "galaxy-brain", "template"], tags: ["image-macro", "2008", "clip-art"],
  },
  {
    slug: "roll-safe", term: "Roll Safe", pron: "rohl sayf", pos: "noun", cat: "meme",
    year: 2016, pop: 46, trend: -2, status: "classic",
    def: "A screengrab of someone tapping their temple while delivering deliberately flawed logic, used to caption a plan so bad it loops back around to sounding clever.",
    eli: "A photo of someone tapping their head while saying advice that sounds smart but is actually a bit silly.",
    org: "Taken from a 2016 British television programme and adopted almost immediately on Black Twitter as the standard format for mock-genius advice.",
    ex: ["Can't fail the exam if you don't take it. Roll Safe.", "That is some real roll safe logic, respectfully."],
    rel: ["galaxy-brain", "philosoraptor", "cope"], tags: ["reaction-image", "2016", "british-tv"],
  },
  {
    slug: "coffin-dance", term: "Coffin dance", pron: "KOF-in dans", pos: "noun", cat: "meme",
    year: 2020, pop: 44, trend: -5, status: "fading",
    def: "A clip of pallbearers dancing while carrying a coffin, overlaid on footage of a minor mishap to comically suggest the outcome could have been fatal.",
    eli: "A funny video of people dancing while carrying a coffin, added to clips of small accidents to joke that it nearly ended badly.",
    org: "Filmed in Ghana years earlier as part of a real, respected dancing pallbearer tradition, the clip was set to a 2020 dance track and became a global reaction meme, somewhat divorced from its original cultural context.",
    ex: ["He nearly walked into the glass door. Coffin dance incoming.", "The coffin dance meme peaked and vanished within about six weeks."],
    rel: ["reaction-image", "this-is-fine", "template"], tags: ["video", "2020", "reaction"],
  },
  {
    slug: "florida-man", term: "Florida Man", pron: "FLOR-id-uh man", pos: "noun", cat: "meme",
    year: 2013, pop: 41, trend: 2, status: "mainstream",
    def: "A recurring joke built from genuine local news headlines describing bizarre crimes and mishaps, all attributed to an unnamed Florida Man due to the state's broad public-records access producing more reported oddities.",
    eli: "A running joke based on real, strange news headlines from Florida, where public records make unusual local stories easy to find and report.",
    org: "A Twitter account launched in 2013 began collecting these headlines, and the format spread as a genre unto itself, eventually inspiring a search-your-birthday game using the pattern.",
    ex: ["Search your birthday plus Florida Man, it never disappoints.", "That headline reads like a Florida Man story from a different state."],
    rel: ["cursed-image", "shitpost", "copypasta"], tags: ["news", "twitter", "genre"],
  },
  {
    slug: "kombucha-girl", term: "Kombucha Girl", pron: "kom-BOO-chuh gurl", pos: "noun", cat: "meme",
    year: 2019, pop: 37, trend: -3, status: "niche",
    def: "A short clip of someone reacting to a first taste of kombucha with visible disgust that resolves into enjoyment, used as a template for any experience that starts badly and improves quickly.",
    eli: "A video of someone making a disgusted face after a sip of a drink that then turns into a happy face, used for anything that seems bad at first but turns out good.",
    org: "Posted to Vine in 2017 and rediscovered on TikTok in 2019, where its clean two-beat structure made it an easy reaction template to reuse.",
    ex: ["My reaction to the first day of the internship was pure Kombucha Girl.", "That plot twist was a Kombucha Girl moment."],
    rel: ["reaction-image", "template", "screaming"], tags: ["vine", "tiktok", "reaction"],
  },
  {
    slug: "waiting-skeleton", term: "Waiting skeleton", pron: "WAY-ting SKEL-i-tun", pos: "noun", cat: "meme",
    year: 2015, pop: 40, trend: -1, status: "classic",
    def: "A stock photo of a skeleton seated at a computer, used to caption anything that requires an unreasonably long or seemingly eternal wait.",
    eli: "A stock photo of a skeleton sitting at a desk, used to joke about waiting for something forever.",
    org: "A stock photography image repurposed as a reaction meme from around 2015, valued for needing almost no explanation to land.",
    ex: ["Waiting skeleton loading, still buffering.", "Me, waiting for a reply to a text I sent three days ago."],
    rel: ["reaction-image", "image-macro", "template"], tags: ["stock-photo", "waiting", "classic"],
  },
  {
    slug: "am-i-the-drama", term: "Am I the drama?", pron: "am eye thuh DRAH-muh", pos: "phrase", cat: "meme",
    year: 2022, pop: 43, trend: 5, status: "mainstream",
    def: "A self-aware riff on Reddit's Am I the Asshole format, used to ask, usually rhetorically, whether the speaker themselves is the source of an ongoing conflict.",
    eli: "A joking way of asking if you are actually the problem in a situation, based on a Reddit format that asks the same question seriously.",
    org: "Adapted from the subreddit format Am I the Asshole, popularised in a knowing, comic register on TikTok and Twitter from around 2022 onward.",
    ex: ["Started the argument, escalated it, then asked if I was the drama.", "Reading the replies, yes, you are the drama."],
    rel: ["discourse-noun", "cancelled", "unserious"], tags: ["reddit", "self-aware", "format"],
  },
  {
    slug: "he-would-never", term: "He would never", pron: "hee wud NEV-ur", pos: "phrase", cat: "meme",
    year: 2019, pop: 39, trend: 3, status: "mainstream",
    def: "An ironic caption paired with a photo of a pet or person appearing to have just done something obviously wrong, insisting on their innocence anyway.",
    eli: "A joke caption saying someone or something would never misbehave, right after a photo showing clear evidence that they did.",
    org: "Spread through pet-account Twitter and Instagram from around 2019, where the gap between the caption's confidence and the photo's evidence was the entire joke.",
    ex: ["Caption: he would never. Photo: the destroyed sofa cushion.", "He would never, except for all the times he clearly has."],
    rel: ["caught-in-4k", "cursed-image", "unserious"], tags: ["pets", "instagram", "irony"],
  },
  {
    slug: "always-has-been", term: "Always has been", pron: "AWL-wayz haz bin", pos: "phrase", cat: "meme",
    year: 2020, pop: 36, trend: -4, status: "fading",
    def: "A two-panel format in which a surprising realisation is met with a gunshot and the flat line always has been, used to mock treating an obvious fact as a sudden discovery.",
    eli: "A meme format where someone realises something obvious and gets shot as a joke, with the caption always has been.",
    org: "Drawn for a 2020 comic strip using generic spacesuit figures and popularised on Reddit and Twitter as a template for deadpan disillusionment jokes.",
    ex: ["Wait, the meetings really could have been emails? Always has been.", "The always-has-been format is basically a punchline generator."],
    rel: ["galaxy-brain", "template", "cope"], tags: ["template", "2020", "reddit"],
  },
];
