import type { RawTerm } from "../types";

export const oldwebTerms: RawTerm[] = [
  {
    slug: "usenet", term: "Usenet", pron: "YOOZ-net", pos: "noun", cat: "oldweb",
    year: 1980, pop: 42, trend: 0, status: "classic",
    def: "A distributed discussion system organised into newsgroups, predating the web. Much of what is now considered internet etiquette was settled there first.",
    eli: "A very old discussion system with topic groups, from before websites existed.",
    org: "Built at Duke University and UNC in 1980 by Tom Truscott, Jim Ellis and Steve Bellovin. Its hierarchy of groups such as comp, rec and alt shaped how online communities organised for decades.",
    ex: ["The convention dates to a Usenet thread from 1993.", "Usenet solved threading before anyone else had the problem."],
    rel: ["eternal-september", "netiquette", "lurker"], tags: ["history", "protocol", "forums"],
  },
  {
    slug: "bbs", term: "BBS", pron: "bee-bee-ES", pos: "abbreviation", cat: "oldweb",
    year: 1978, pop: 35, trend: 0, status: "classic",
    def: "Bulletin board system. A computer you dialled directly by modem to read messages, trade files and play door games, usually one caller at a time.",
    eli: "An old system where you phoned a computer with a modem to leave messages and download files.",
    org: "The first, CBBS, was launched by Ward Christensen and Randy Suess in Chicago in February 1978 during a blizzard. Thousands followed, each a small local world with its own rules.",
    ex: ["He ran a BBS from a spare bedroom for eleven years.", "Long-distance charges shaped which BBS you could afford to call."],
    rel: ["sysop", "usenet", "dial-up"], tags: ["history", "modem", "community"],
  },
  {
    slug: "sysop", term: "Sysop", pron: "SIS-op", pos: "noun", cat: "oldweb",
    year: 1980, pop: 26, trend: 0, status: "classic",
    def: "System operator. The person who ran a bulletin board, combining the roles of host, moderator, technician and, frequently, the only person paying for it.",
    eli: "The person who owned and ran an old dial-up bulletin board.",
    org: "BBS vocabulary. The sysop's absolute authority over a single machine is the direct ancestor of the modern forum admin and the Discord server owner.",
    ex: ["The sysop banned you by unplugging the line.", "Every BBS was exactly as good as its sysop."],
    rel: ["bbs", "mod", "dial-up"], tags: ["history", "moderation", "bbs"],
  },
  {
    slug: "irc", term: "IRC", pron: "eye-ar-SEE", pos: "abbreviation", cat: "oldweb",
    year: 1988, pop: 44, trend: -1, status: "classic",
    def: "Internet Relay Chat. A text chat protocol organised into channels beginning with a hash, still in use and still the model most chat apps copy.",
    eli: "A very old text chat system with channels, which is where the idea of a hashtag topic came from.",
    org: "Written by Jarkko Oikarinen in Finland in 1988. Its channel prefix, nickname system and operator model were inherited almost wholesale by Slack and Discord.",
    ex: ["The project still keeps an IRC channel out of principle.", "IRC had bots and moderation decades before the apps claiming to have invented them."],
    rel: ["bbs", "netiquette", "lurker"], tags: ["history", "chat", "protocol"],
  },
  {
    slug: "netiquette", term: "Netiquette", pron: "NET-ik-et", pos: "noun", cat: "oldweb",
    year: 1983, pop: 31, trend: -2, status: "classic",
    def: "Network etiquette: the informal rules of online conduct, covering quoting, capitalisation, topicality and how much of a previous message to include.",
    eli: "The unwritten manners of being online, like not typing in capitals.",
    org: "Circulated as guides on Usenet from the early 1980s and formalised in RFC 1855 in 1995. Most of it still holds; it simply stopped being taught.",
    ex: ["Trimming quoted text is basic netiquette.", "RFC 1855 reads as either quaint or urgently necessary, depending on the day."],
    rel: ["usenet", "top-posting", "flame-war"], tags: ["etiquette", "history", "rfc"],
  },
  {
    slug: "eternal-september", term: "Eternal September", pron: "i-TUR-nul sep-TEM-bur", pos: "noun", cat: "oldweb",
    year: 1993, pop: 34, trend: 2, status: "classic",
    def: "The permanent state of a community flooded with newcomers who never learn its norms, so that acculturation never completes.",
    eli: "When so many new people keep arriving that a community never gets a chance to teach them how it works.",
    org: "Named on Usenet in 1993, when AOL connected its users to newsgroups. Previously each September brought one wave of students; after AOL the wave never stopped.",
    ex: ["Every platform eventually has its Eternal September.", "The mods gave up somewhere around the third Eternal September."],
    rel: ["usenet", "newbie", "normie"], tags: ["history", "community", "usenet"],
  },
  {
    slug: "flame-war", term: "Flame war", pron: "flaym wor", pos: "noun", cat: "oldweb",
    year: 1981, pop: 47, trend: -1, status: "classic",
    def: "A prolonged hostile argument that consumes a thread. To flame is to post an insulting message; the war is what follows.",
    eli: "A long angry argument online that takes over the whole discussion.",
    org: "MIT and Usenet slang from the early 1980s, where flaming meant speaking with excessive heat. The dynamics described then are unchanged; only the venues differ.",
    ex: ["A question about tab width became a nine-day flame war.", "Do not feed a flame war with corrections."],
    rel: ["troll", "godwins-law", "netiquette"], tags: ["argument", "usenet", "history"],
  },
  {
    slug: "godwins-law", term: "Godwin's law", pron: "GOD-winz law", pos: "noun", cat: "oldweb",
    year: 1990, pop: 40, trend: 0, status: "classic",
    def: "The observation that as an online discussion grows longer, the probability of a Nazi comparison approaches one. Often misquoted as a rule that whoever makes it loses.",
    eli: "The idea that the longer an internet argument goes on, the more likely someone brings up Hitler.",
    org: "Formulated by Mike Godwin on Usenet in 1990 as a deliberate counter-meme, meant to make people think twice before reaching for the comparison rather than to forbid it.",
    ex: ["Fourteen replies before Godwin's law. Respectable.", "Godwin has clarified that some comparisons are warranted."],
    rel: ["flame-war", "poes-law", "usenet"], tags: ["argument", "usenet", "law"],
  },
  {
    slug: "lurker", term: "Lurker", pron: "LUR-kur", pos: "noun", cat: "oldweb",
    year: 1983, pop: 52, trend: 1, status: "classic",
    def: "Someone who reads a community without posting. Long-time lurker, first-time poster is the standard formula for finally breaking cover.",
    eli: "Someone who reads a forum for years without ever posting anything.",
    org: "Usenet vocabulary. Lurking before posting was considered good practice, and guides advised months of reading before a first message.",
    ex: ["Long-time lurker, first-time poster.", "The ratio of lurkers to posters is roughly ninety to one."],
    rel: ["newbie", "netiquette", "usenet"], tags: ["community", "usenet", "behaviour"],
  },
  {
    slug: "rtfm", term: "RTFM", pron: "ar-tee-ef-EM", pos: "abbreviation", cat: "oldweb",
    year: 1979, pop: 37, trend: -2, status: "classic",
    def: "Read the manual, with an expletive in the middle. A blunt instruction to consult documentation before asking, and a signature of early technical culture.",
    eli: "A rude way of telling someone to read the instructions before asking for help.",
    org: "Unix and military documentation culture of the 1970s, carried onto Usenet and into open-source support channels, where it remains contentious.",
    ex: ["The only reply in six hours was RTFM.", "RTFM is not support, it is a way of avoiding it."],
    rel: ["newbie", "flame-war", "netiquette"], tags: ["unix", "support", "abbreviation"],
  },
  {
    slug: "newbie", term: "Newbie", pron: "NOO-bee", pos: "noun", cat: "oldweb",
    year: 1988, pop: 49, trend: -3, status: "classic",
    def: "A newcomer to a community or skill. Noob and n00b are later and more contemptuous forms; newb is the gentler one.",
    eli: "Someone new to a game or community who has not learned how things work yet.",
    org: "Usenet, probably from British military slang for a new recruit. Gaming culture of the 2000s produced the leetspeak variant n00b as a specific insult.",
    ex: ["Be kind, they are a newbie.", "Calling someone a n00b in 2003 was a whole personality."],
    rel: ["lurker", "leet", "eternal-september"], tags: ["community", "gaming", "usenet"],
  },
  {
    slug: "leet", term: "Leet", pron: "leet", pos: "noun", cat: "oldweb",
    year: 1985, pop: 33, trend: -4, status: "classic",
    def: "An alphabet substituting numerals and symbols for letters, as in 1337 for leet and h4x0r for hacker. Originally a filter-evasion device, later a joke.",
    eli: "Writing words with numbers instead of letters, like 1337 instead of leet.",
    org: "BBS and warez culture of the mid-1980s, where substitutions defeated keyword filters on boards. By the 2000s it survived mainly as parody.",
    ex: ["The password was 1337 and it did not help.", "Nobody has written h4x0r sincerely in twenty years."],
    rel: ["newbie", "warez", "bbs"], tags: ["bbs", "warez", "orthography"],
  },
  {
    slug: "warez", term: "Warez", pron: "WAIRZ", pos: "noun", cat: "oldweb",
    year: 1990, pop: 27, trend: -3, status: "fading",
    def: "Pirated software distributed through an organised scene with its own release standards, naming conventions and competitive hierarchy.",
    eli: "Illegally copied software, shared through organised groups with strict rules.",
    org: "BBS culture of the late 1980s. The scene's release conventions, including NFO text files and cracktros, are an entire lost design tradition.",
    ex: ["The NFO files were better designed than the software.", "Warez scene rules were stricter than most workplaces."],
    rel: ["leet", "bbs", "torrent"], tags: ["piracy", "bbs", "scene"],
  },
  {
    slug: "top-posting", term: "Top posting", pron: "top POH-sting", pos: "noun", cat: "oldweb",
    year: 1995, pop: 24, trend: -1, status: "niche",
    def: "Replying above the quoted message rather than beneath the part being answered. Considered poor form on Usenet and standard practice in corporate email.",
    eli: "Putting your reply above the old message instead of underneath it.",
    org: "The argument dates to the mid-1990s and has never been resolved. The canonical objection is phrased as a question about why it is bad, answered above itself.",
    ex: ["A: Because it reverses the order. Q: Why is top posting frowned upon?", "Mailing lists still fight about this weekly."],
    rel: ["netiquette", "usenet", "flame-war"], tags: ["email", "etiquette", "usenet"],
  },
  {
    slug: "geocities", term: "GeoCities", pron: "JEE-oh-sit-eez", pos: "noun", cat: "oldweb",
    year: 1995, pop: 38, trend: 2, status: "classic",
    def: "A free hosting service that organised personal homepages into themed neighbourhoods. Its visual excess became the defining look of the amateur web.",
    eli: "A free website service from the 1990s where anyone could make their own page, usually with tiled backgrounds and animated graphics.",
    org: "Launched in 1994 as Beverly Hills Internet and renamed in 1995. Yahoo bought it for billions and closed it in 2009; archivists rescued roughly a terabyte of it.",
    ex: ["A tiled starfield background and a MIDI file. Peak GeoCities.", "The GeoCities archive is a genuine historical record."],
    rel: ["under-construction", "webring", "guestbook"], tags: ["history", "web1", "hosting"],
  },
  {
    slug: "webring", term: "Webring", pron: "WEB-ring", pos: "noun", cat: "oldweb",
    year: 1994, pop: 29, trend: 4, status: "niche",
    def: "A circular chain of related sites, each linking to the next, letting visitors travel a topic without a search engine. Recently revived by the small-web movement.",
    eli: "A loop of websites about the same topic, each linking to the next one.",
    org: "Devised in the mid-1990s when search was poor and discovery depended on human curation. Personal-site enthusiasts began rebuilding webrings in the 2020s.",
    ex: ["The button at the bottom took you to the next site in the ring.", "Webrings are back, and mostly on Neocities."],
    rel: ["geocities", "blogroll", "under-construction"], tags: ["discovery", "web1", "small-web"],
  },
  {
    slug: "under-construction", term: "Under construction", pron: "UN-dur kun-STRUK-shun", pos: "noun", cat: "oldweb",
    year: 1995, pop: 31, trend: 3, status: "classic",
    def: "An animated roadworks graphic marking an unfinished page. Ubiquitous enough on the 1990s web to become its unofficial emblem.",
    eli: "A little animated digger picture that meant a web page was not finished yet.",
    org: "A GeoCities-era convention that treated the web as a place being built in public. Modern sites hide the same incompleteness rather than announcing it.",
    ex: ["Three of the five links were under construction, permanently.", "The animated GIF was doing a lot of emotional work."],
    rel: ["geocities", "webring", "guestbook"], tags: ["web1", "gif", "nostalgia"],
  },
  {
    slug: "guestbook", term: "Guestbook", pron: "GEST-book", pos: "noun", cat: "oldweb",
    year: 1996, pop: 27, trend: 1, status: "classic",
    def: "A page where visitors left a short message to record that they had been. The ancestor of the comment section, without any expectation of conversation.",
    eli: "A page where visitors signed their name to show they had visited your site.",
    org: "A staple of personal homepages before comments existed. Its purpose was acknowledgement rather than discussion, which is why spam killed it so completely.",
    ex: ["Please sign my guestbook before you leave.", "By 1999 most guestbooks were entirely spam."],
    rel: ["geocities", "hit-counter", "under-construction"], tags: ["web1", "community", "nostalgia"],
  },
  {
    slug: "hit-counter", term: "Hit counter", pron: "hit KOWN-tur", pos: "noun", cat: "oldweb",
    year: 1995, pop: 28, trend: 1, status: "classic",
    def: "A visible odometer showing how many times a page had been loaded, usually rendered as mechanical digits and frequently started at a flattering number.",
    eli: "A little number on a web page showing how many people had visited.",
    org: "A defining feature of the personal web, when traffic was a private curiosity rather than a business metric. Analytics replaced it and hid the number from visitors.",
    ex: ["You are visitor number 000417.", "Everyone started their counter at a thousand."],
    rel: ["guestbook", "geocities", "webring"], tags: ["web1", "metrics", "nostalgia"],
  },
  {
    slug: "dial-up", term: "Dial-up", pron: "DY-ul up", pos: "noun", cat: "oldweb",
    year: 1990, pop: 41, trend: 0, status: "classic",
    def: "Internet access over a telephone line via modem, occupying the phone while connected and announcing itself with a distinctive handshake tone.",
    eli: "Old internet that worked through the phone line, made a strange noise, and stopped anyone calling you.",
    org: "The standard consumer connection through the 1990s. The 56k modem handshake is one of the most recognisable sounds of the decade to anyone who lived through it.",
    ex: ["Someone picked up the phone and killed the download at 94 percent.", "56k warning on that image, be considerate."],
    rel: ["bbs", "56k-warning", "aol"], tags: ["history", "modem", "access"],
  },
  {
    slug: "56k-warning", term: "56k warning", pron: "FIF-tee-siks-kay WOR-ning", pos: "noun", cat: "oldweb",
    year: 1999, pop: 21, trend: 0, status: "fading",
    def: "A courtesy note that a page contained large images and would be painful to load on a dial-up connection.",
    eli: "A warning that a page had big pictures and would take forever on slow internet.",
    org: "Forum etiquette of the late 1990s and early 2000s, when bandwidth was scarce enough that posting a large image without warning was genuinely rude.",
    ex: ["Image heavy, 56k warning.", "The modern equivalent would be warning about autoplaying video."],
    rel: ["dial-up", "netiquette", "hotlinking"], tags: ["etiquette", "bandwidth", "forums"],
  },
  {
    slug: "hotlinking", term: "Hotlinking", pron: "HOT-link-ing", pos: "noun", cat: "oldweb",
    year: 1997, pop: 23, trend: -1, status: "niche",
    def: "Embedding an image hosted on someone else's server, so they pay for the bandwidth. Retaliation traditionally involved swapping the image for something worse.",
    eli: "Using a picture from someone else's website so their server does the work.",
    org: "A constant irritation of the bandwidth-limited web. Server operators built rules to detect it and replace the image, which produced a small genre of revenge graphics.",
    ex: ["He hotlinked the logo and woke up to a very different image.", "Hotlink protection is still a standard hosting setting."],
    rel: ["56k-warning", "netiquette", "geocities"], tags: ["bandwidth", "hosting", "etiquette"],
  },
  {
    slug: "aol", term: "AOL", pron: "ay-oh-EL", pos: "noun", cat: "oldweb",
    year: 1991, pop: 39, trend: 0, status: "classic",
    def: "America Online, the walled-garden service that introduced millions to the internet through CD-ROMs, chat rooms and the greeting You've got mail.",
    eli: "A huge 1990s service that gave many people their first internet, famous for free trial CDs.",
    org: "Its mass mailing of installation discs is still one of the largest physical marketing campaigns ever run. Connecting its users to Usenet in 1993 caused the Eternal September.",
    ex: ["Everyone had a drawer of AOL discs.", "AOL chat rooms taught a generation what moderation was for."],
    rel: ["dial-up", "eternal-september", "away-message"], tags: ["history", "isp", "1990s"],
  },
  {
    slug: "away-message", term: "Away message", pron: "uh-WAY MES-ij", pos: "noun", cat: "oldweb",
    year: 1997, pop: 30, trend: 2, status: "classic",
    def: "A status note shown while you were absent from instant messenger, which quickly became a venue for song lyrics and coded messages aimed at one specific reader.",
    eli: "A message shown when you were away from chat, often used to post song lyrics at someone.",
    org: "An AIM feature intended as a practical courtesy that teenagers immediately repurposed as a broadcast medium. The direct ancestor of the status update.",
    ex: ["The away message was three lines of lyrics and everyone knew who they were for.", "Away messages were subtweeting before Twitter existed."],
    rel: ["aol", "screen-name", "subtweet"], tags: ["aim", "messenger", "status"],
  },
  {
    slug: "screen-name", term: "Screen name", pron: "skreen naym", pos: "noun", cat: "oldweb",
    year: 1995, pop: 32, trend: 0, status: "classic",
    def: "A chosen chat handle, distinct from a real name and often permanent enough to become an identity. The ancestor of the username and the gamertag.",
    eli: "The made-up name you used in old chat programs instead of your real one.",
    org: "AOL and AIM vocabulary. Because screen names could not easily be changed, people carried the same slightly embarrassing teenage handle for years.",
    ex: ["My screen name had four x characters and a number in it.", "Nobody has recovered from their first screen name."],
    rel: ["away-message", "aol", "handle"], tags: ["identity", "aim", "usernames"],
  },
  {
    slug: "necropost", term: "Necropost", pron: "NEK-roh-pohst", pos: "verb", cat: "oldweb",
    year: 2004, pop: 25, trend: 0, status: "niche",
    def: "To reply to a thread that has been inactive for years, pushing it back to the top of the forum. Also called thread necromancy.",
    eli: "Replying to a very old discussion and bringing it back to the top.",
    org: "Forum vocabulary of the mid-2000s. Opinions divide sharply: some boards ban it outright, others note that a real answer is worth more than a tidy index.",
    ex: ["Necroposted a 2009 thread to say he had the same problem.", "Sorry for the necropost, but this is the top search result."],
    rel: ["bump", "op", "sticky"], tags: ["forums", "etiquette", "threads"],
  },
  {
    slug: "bump", term: "Bump", pron: "bump", pos: "verb", cat: "oldweb",
    year: 2002, pop: 44, trend: 0, status: "classic",
    def: "To post a contentless reply purely to return a thread to the top of a list ordered by recent activity.",
    eli: "Replying to your own post just to move it back to the top of the page.",
    org: "Forum vocabulary, often backronymed as bring up my post. Considered acceptable once, rude if repeated, and automated by bots on classified boards.",
    ex: ["bump", "Third bump in an hour is not going to help."],
    rel: ["necropost", "sticky", "op"], tags: ["forums", "etiquette", "threads"],
  },
  {
    slug: "sticky", term: "Sticky", pron: "STIK-ee", pos: "noun", cat: "oldweb",
    year: 2001, pop: 27, trend: 0, status: "classic",
    def: "A thread pinned above all others by a moderator, usually holding rules or a frequently asked question that nobody reads anyway.",
    eli: "A discussion that mods pin to the top of the page so everyone sees it.",
    org: "Standard forum software vocabulary from phpBB and vBulletin, carried into modern platforms as pinned posts and announcement channels.",
    ex: ["It is answered in the sticky.", "Every forum has a sticky nobody has read since 2011."],
    rel: ["bump", "mod", "op"], tags: ["forums", "moderation", "phpbb"],
  },
  {
    slug: "sockpuppet", term: "Sockpuppet", pron: "SOK-pup-it", pos: "noun", cat: "oldweb",
    year: 1993, pop: 41, trend: 3, status: "classic",
    def: "A second account used to support your own arguments, evade a ban or manufacture the appearance of agreement.",
    eli: "A fake extra account someone makes to agree with themselves or dodge a ban.",
    org: "Usenet vocabulary that became a formal policy category on Wikipedia, which developed detection methods and a dedicated investigation process.",
    ex: ["Three accounts, one writing style. Obvious sockpuppet.", "Sockpuppet investigations are a genuine Wikipedia specialism."],
    rel: ["ban-evasion", "astroturfing", "troll"], tags: ["moderation", "deception", "wikipedia"],
  },
  {
    slug: "astroturfing", term: "Astroturfing", pron: "AS-troh-turf-ing", pos: "noun", cat: "oldweb",
    year: 1985, pop: 46, trend: 5, status: "classic",
    def: "Manufacturing the appearance of grassroots support, using paid or coordinated accounts to make a position look popular.",
    eli: "Faking a crowd of ordinary supporters when it is really one organisation paying for it.",
    org: "Coined by US Senator Lloyd Bentsen in 1985, naming the fake grass against real grassroots. It moved online almost immediately and now names a whole industry.",
    ex: ["Two hundred accounts, all created last Tuesday. Astroturfing.", "The reviews were astroturfed and the pattern was obvious."],
    rel: ["sockpuppet", "bot", "dead-internet-theory"], tags: ["manipulation", "politics", "reviews"],
  },
  {
    slug: "thread", term: "Thread", pron: "thred", pos: "noun", cat: "oldweb",
    year: 1984, pop: 79, trend: 2, status: "classic",
    def: "A sequence of messages connected by reply relationships. Threading is the single most-reinvented feature in the history of online communication.",
    eli: "A chain of replies that all belong to the same conversation.",
    org: "Solved on Usenet in the 1980s using message identifiers, then lost and rebuilt by nearly every platform since. Twitter threads, Slack threads and email threads are three incompatible answers to one problem.",
    ex: ["A nine-post thread that should have been one paragraph.", "Every platform rediscovers threading about four years in."],
    rel: ["usenet", "op", "bump"], tags: ["structure", "usenet", "conversation"],
  },
  {
    slug: "handle", term: "Handle", pron: "HAN-dul", pos: "noun", cat: "oldweb",
    year: 1980, pop: 55, trend: 0, status: "classic",
    def: "A chosen name used online. Distinct from a legal name and often more stable, since people carry handles across platforms for decades.",
    eli: "The name you go by online instead of your real name.",
    org: "CB radio vocabulary adopted by BBS culture around 1980. The handle predates the username, the screen name and the gamertag, and outlasted all three as the general term.",
    ex: ["Same handle since 2003, three platforms, one identity.", "Losing a handle to a platform migration is a real bereavement."],
    rel: ["screen-name", "sockpuppet", "bbs"], tags: ["identity", "cb-radio", "usernames"],
  },
  {
    slug: "torrent", term: "Torrent", pron: "TOR-unt", pos: "noun", cat: "oldweb",
    year: 2001, pop: 52, trend: 0, status: "classic",
    def: "A peer-to-peer file distribution method where every downloader also uploads, so popular files get faster as demand rises rather than slower.",
    eli: "A way of sharing files where everyone downloading also helps send pieces to others.",
    org: "BitTorrent was designed by Bram Cohen in 2001. The protocol is content-neutral and widely used for legitimate distribution, including Linux releases and scientific datasets.",
    ex: ["Seeding ratio is a genuine point of honour.", "The protocol solved a hosting problem and inherited a legal one."],
    rel: ["warez", "hotlinking", "dial-up"], tags: ["p2p", "distribution", "piracy"],
  },
  {
    slug: "blogroll", term: "Blogroll", pron: "BLOG-rohl", pos: "noun", cat: "oldweb",
    year: 2002, pop: 27, trend: 3, status: "niche",
    def: "A sidebar list of blogs the author reads, used for discovery before search and feeds took over. A public statement about who you considered peers.",
    eli: "A list of other blogs someone recommended, shown in the sidebar of their site.",
    org: "Standard on blogs from around 2002. It was a human recommendation system, and its disappearance is often cited in arguments about what algorithmic feeds replaced.",
    ex: ["Being added to a blogroll was the whole reward system.", "The blogroll is coming back on personal sites."],
    rel: ["webring", "geocities", "rss"], tags: ["blogging", "discovery", "web2"],
  },
  {
    slug: "rss", term: "RSS", pron: "ar-es-ES", pos: "abbreviation", cat: "oldweb",
    year: 1999, pop: 44, trend: 6, status: "classic",
    def: "A format letting readers subscribe to a site directly, receiving everything published in order, with no ranking and no intermediary.",
    eli: "A way of following websites so you get everything they post, in order, with no algorithm.",
    org: "Standardised around 1999 and widely declared dead after Google Reader closed in 2013. It never actually died, and interest has risen steadily as feed ranking has grown less popular.",
    ex: ["Still reading fifty sites by RSS and no algorithm involved.", "Podcasts are RSS, which most people never realise."],
    rel: ["blogroll", "algorithm", "webring"], tags: ["feeds", "open-web", "subscription"],
  },
  {
    slug: "meatspace", term: "Meatspace", pron: "MEET-spays", pos: "noun", cat: "oldweb",
    year: 1993, pop: 24, trend: -2, status: "fading",
    def: "The physical world, as opposed to cyberspace. Deliberately unglamorous, coined by people who found the offline world the less interesting of the two.",
    eli: "A joking word for the real physical world instead of the internet.",
    org: "Cyberpunk-adjacent vocabulary of the early 1990s. Its decline tracks the collapse of the assumption that online and offline are separate places at all.",
    ex: ["Meeting in meatspace for the first time after nine years.", "The word only makes sense if the two worlds are separate, which they no longer are."],
    rel: ["irl", "handle", "usenet"], tags: ["cyberpunk", "offline", "1990s"],
  },
  {
    slug: "dead-link", term: "Dead link", pron: "ded link", pos: "noun", cat: "oldweb",
    year: 1996, pop: 38, trend: 2, status: "classic",
    def: "A hyperlink whose destination no longer exists. Individually trivial, collectively the slow erasure of the web's ability to cite itself.",
    eli: "A link that no longer goes anywhere because the page is gone.",
    org: "As old as hyperlinks. Studies of legal and academic citation have repeatedly found that a majority of links break within twenty years, which is a serious archival problem.",
    ex: ["Every source in that 2009 article is a dead link now.", "The footnote survives, the evidence does not."],
    rel: ["link-rot", "404", "wayback-machine"], tags: ["archives", "citation", "decay"],
  },
  {
    slug: "greentext", term: "Greentext", pron: "GREEN-tekst", pos: "noun", cat: "oldweb",
    year: 2007, pop: 41, trend: 0, status: "classic",
    def: "A narrative style of short lines each beginning with an angle bracket, rendered green on imageboards. Terse, present tense, and usually building to an anticlimax.",
    eli: "A story told in short lines each starting with a greater-than sign, in green text.",
    org: "An accident of imageboard quoting markup, where a leading angle bracket coloured a line green. Users repurposed the formatting into a genuine literary form with its own conventions.",
    ex: ["be me, forget the whole point of the story", "A formatting quirk became a narrative genre."],
    rel: ["copypasta", "shitpost", "wojak"], tags: ["4chan", "narrative", "formatting"],
  },
  {
    slug: "myspace", term: "MySpace", pron: "MY-spays", pos: "noun", cat: "oldweb",
    year: 2003, pop: 46, trend: 4, status: "classic",
    def: "An early social network letting users heavily customise their profile pages with code, music and layout, and rank a Top 8 list of friends publicly.",
    eli: "An early social media site where you could decorate your own profile page and publicly rank your top eight friends.",
    org: "Launched in 2003 and briefly the most visited website in the United States before Facebook's open registration in 2006 drew its audience away within a few years.",
    ex: ["Ranking your Top 8 was a genuine source of social anxiety.", "MySpace let you code your own profile, which nothing since has really replaced."],
    rel: ["top-8", "geocities", "livejournal"], tags: ["social-media", "2000s", "history"],
  },
  {
    slug: "top-8", term: "Top 8", pron: "top ayt", pos: "noun", cat: "oldweb",
    year: 2003, pop: 34, trend: 2, status: "classic",
    def: "A public ranked list of a user's eight closest friends displayed on their MySpace profile, whose order was scrutinised and renegotiated constantly.",
    eli: "A public list of your eight best friends shown on your MySpace page, which people took very seriously.",
    org: "A core MySpace feature from launch in 2003, later expandable but always referred to by its original number, and a genuine source of friendship politics for millions of teenagers.",
    ex: ["Got dropped from the Top 8 and knew exactly what it meant.", "Renegotiating the Top 8 was a real diplomatic exercise."],
    rel: ["myspace", "away-message", "screen-name"], tags: ["myspace", "friendship", "2000s"],
  },
  {
    slug: "livejournal", term: "LiveJournal", pron: "lyv-JUR-nul", pos: "noun", cat: "oldweb",
    year: 1999, pop: 32, trend: 3, status: "niche",
    def: "An early blogging platform built around personal, often diary-style posts, friends-locked entries, and tightly knit fandom and roleplay communities.",
    eli: "An early blogging site known for personal diary-style posts and close-knit fan communities that locked posts to friends only.",
    org: "Launched in 1999 by a college student for his own friends, it became a major hub for confessional blogging and fan fiction long before Tumblr existed to inherit that role.",
    ex: ["Half of early 2000s fan fiction lived on LiveJournal.", "Friends-locked LiveJournal posts were the original private social feed."],
    rel: ["myspace", "fanfic", "blogroll"], tags: ["blogging", "fandom", "1999"],
  },
  {
    slug: "napster", term: "Napster", pron: "NAP-stur", pos: "noun", cat: "oldweb",
    year: 1999, pop: 44, trend: 1, status: "classic",
    def: "A peer-to-peer file-sharing service that let users trade music files directly, triggering the recording industry's first major legal fight against internet piracy.",
    eli: "An early service that let people share music files with each other for free, which led to huge lawsuits from the music industry.",
    org: "Launched by two teenagers in 1999, it grew to tens of millions of users within two years before a wave of lawsuits shut it down in 2001, reshaping how the music industry approached digital distribution ever after.",
    ex: ["An entire generation's music library came from Napster and nowhere else.", "The Napster lawsuits basically wrote the rulebook for online piracy law."],
    rel: ["torrent", "warez", "limewire"], tags: ["piracy", "music", "1999"],
  },
  {
    slug: "icq", term: "ICQ", pron: "eye-see-kyoo", pos: "noun", cat: "oldweb",
    year: 1996, pop: 30, trend: 1, status: "niche",
    def: "One of the first widely used instant messenger programs, identifying users by a numeric ICQ number rather than a name, and known for its distinctive incoming-message sound.",
    eli: "One of the first popular instant messaging programs, where you were identified by a number instead of a username.",
    org: "Released by an Israeli company in 1996, its name a phonetic play on I seek you, and it briefly dominated instant messaging before AOL Instant Messenger and MSN Messenger took over that role.",
    ex: ["Still remembers his six-digit ICQ number from 1998.", "That notification sound was universally recognised for a solid decade."],
    rel: ["away-message", "screen-name", "aol"], tags: ["messenger", "1996", "history"],
  },
  {
    slug: "sig-file", term: "Sig file", pron: "sig fyl", pos: "noun", cat: "oldweb",
    year: 1985, pop: 26, trend: 0, status: "classic",
    def: "A short block of text automatically appended to the end of every message a user sent, often containing a quote, ASCII art or a contact detail.",
    eli: "A short block of text, like a quote or your details, automatically added to the end of every message you send.",
    org: "Standard on Usenet and email from the mid-1980s, with etiquette guides eventually recommending a maximum of four lines to keep threads from bloating.",
    ex: ["His sig file was a longer read than most of his actual posts.", "The four-line sig file rule was routinely and enthusiastically broken."],
    rel: ["usenet", "netiquette", "ascii-art"], tags: ["email", "usenet", "etiquette"],
  },
  {
    slug: "faq", term: "FAQ", pron: "fak", pos: "abbreviation", cat: "oldweb",
    year: 1982, pop: 58, trend: 0, status: "classic",
    def: "Frequently asked questions: a compiled document answering a community's most common queries in advance, so the same questions do not have to be answered repeatedly.",
    eli: "A list of the questions people ask most often, answered ahead of time so nobody has to keep repeating themselves.",
    org: "Developed on Usenet in the early 1980s as newsgroups grew large enough that certain questions were asked constantly, and maintaining a shared FAQ became standard community practice.",
    ex: ["It is answered in the FAQ, pinned at the top for a reason.", "Writing a good FAQ is an underrated form of community service."],
    rel: ["usenet", "sticky", "rtfm"], tags: ["usenet", "documentation", "classic"],
  },
  {
    slug: "spam", term: "Spam", pron: "spam", pos: "noun", cat: "oldweb",
    year: 1993, pop: 64, trend: 0, status: "classic",
    def: "Unsolicited, repetitive or irrelevant messages sent in bulk, originally referring to disruptive Usenet posting and later generalised to unwanted email and messages of any kind.",
    eli: "Unwanted, repeated junk messages sent to lots of people at once, like junk email.",
    org: "Named in 1993 after a Monty Python sketch in which the word spam is repeated so often it drowns out actual conversation, applied to a Usenet post repeated across thousands of newsgroups the same year.",
    ex: ["The inbox is ninety percent spam most mornings.", "Spam filters remain an unglamorous but genuinely essential piece of infrastructure."],
    rel: ["phishing", "usenet", "bot"], tags: ["email", "usenet", "classic"],
  },
  {
    slug: "phishing", term: "Phishing", pron: "FISH-ing", pos: "noun", cat: "oldweb",
    year: 1996, pop: 60, trend: 2, status: "classic",
    def: "Sending fraudulent messages that impersonate a trustworthy source in order to trick the recipient into revealing passwords, financial details or other sensitive information.",
    eli: "Fake emails or messages pretending to be from someone trustworthy, designed to trick you into giving away passwords or bank details.",
    org: "The spelling with ph, echoing earlier phone-hacking phreaking, dates to the mid-1990s, when early scammers targeted AOL account credentials using messages disguised as official communications.",
    ex: ["The phishing email had the right logo and the wrong sender address.", "Never has anyone actually won a competition they never entered."],
    rel: ["spam", "sockpuppet", "astroturfing"], tags: ["security", "scams", "classic"],
  },
  {
    slug: "limewire", term: "LimeWire", pron: "LYM-wyr", pos: "noun", cat: "oldweb",
    year: 2000, pop: 34, trend: 1, status: "niche",
    def: "A peer-to-peer file-sharing program notorious both for making pirated music widely available and for the malware frequently bundled inside its downloads.",
    eli: "An old file-sharing program known for pirated music, and also for often accidentally installing viruses on your computer.",
    org: "Launched in 2000 in the wake of Napster's shutdown, it operated for a decade before a court injunction forced it to stop enabling unauthorised file sharing in 2010.",
    ex: ["Half the ringtones from that era came from LimeWire, viruses included.", "LimeWire is the answer whenever someone asks how their childhood computer died."],
    rel: ["napster", "torrent", "warez"], tags: ["piracy", "p2p", "2000s"],
  },
  {
    slug: "ascii-art", term: "ASCII art", pron: "AS-kee art", pos: "noun", cat: "oldweb",
    year: 1966, pop: 37, trend: 2, status: "classic",
    def: "Images composed entirely from standard text characters, arranged so that the pattern of letters and symbols forms a recognisable picture when viewed in a fixed-width font.",
    eli: "Pictures made entirely out of ordinary keyboard letters and symbols, arranged to look like an image.",
    org: "Predating the graphical web entirely, ASCII art thrived on printers, early bulletin boards and Usenet signatures, where it remained the only practical way to include images in plain text.",
    ex: ["The sig file included a surprisingly detailed ASCII art dragon.", "ASCII art never really died, it just moved into terminal splash screens."],
    rel: ["sig-file", "bbs", "usenet"], tags: ["art", "text", "classic"],
  },
];
