import type { RawTerm } from "../types";

export const slangTerms: RawTerm[] = [
  {
    slug: "aura", term: "Aura", pron: "OR-uh", pos: "noun", cat: "slang",
    year: 2023, pop: 81, trend: 24, status: "rising",
    def: "A running, invented score for how composed and impressive a person seems. Framed as points that can be gained or lost through small social moments.",
    eli: "Imaginary cool points. Do something smooth and you gain aura; trip over nothing in public and you lose a thousand.",
    org: "Grew out of gaming and anime commentary in 2023, where characters were described as having \"aura\". By 2024 the point-scoring version was everywhere on TikTok.",
    ex: ["Caught the glass before it hit the floor. Massive aura.", "Negative 10,000 aura for waving at someone who was waving past me."],
    rel: ["rizz", "ick", "sweaty"], tags: ["status", "gen-alpha", "anime"],
  },
  {
    slug: "based", term: "Based", pron: "bayst", pos: "adjective", cat: "slang",
    year: 2010, pop: 71, trend: -3, status: "classic",
    def: "Describing an opinion or action that is admirably independent - correct because the speaker means it rather than because it is popular. The opposite of pandering.",
    eli: "Saying what you actually think even when it is unpopular. Calling someone based means they were honest and did not care who agreed.",
    org: "Rapper Lil B reclaimed \"basehead\" as a compliment around 2010, meaning someone unapologetically themselves. Message boards adopted it, and by the late 2010s it was a general marker of approval.",
    ex: ["Refusing to install the app and just using the website is based.", "Based take, terrible timing."],
    rel: ["cringe", "mid", "ratio"], tags: ["approval", "opinion", "forums"],
  },
  {
    slug: "brainrot", term: "Brainrot", pron: "BRAYN-rot", pos: "noun", cat: "slang",
    year: 2023, pop: 90, trend: 18, status: "rising",
    def: "Low-quality, hyper-repetitive online content, or the mental state produced by consuming it. Also names a genre of deliberately incoherent humour built from stacked references.",
    eli: "Silly internet stuff that means nothing but is so catchy it gets stuck in your head and crowds out everything else.",
    org: "The word dates to Thoreau in 1854, but its modern sense took hold on TikTok in 2023-2024. Oxford chose it as word of the year in 2024.",
    ex: ["My little brother only speaks in brainrot now.", "Three hours of shorts and I can feel the brainrot setting in."],
    rel: ["doomscrolling", "ai-slop", "touch-grass"], tags: ["attention", "tiktok", "gen-alpha"],
  },
  {
    slug: "chronically-online", term: "Chronically online", pron: "KRON-ik-lee on-LYNE", pos: "adjective", cat: "slang",
    year: 2021, pop: 69, trend: 5, status: "mainstream",
    def: "Describing someone whose sense of what is normal has been distorted by heavy internet use, so that niche online disputes feel like mainstream concerns.",
    eli: "Someone who is online so much that they think internet arguments are what everybody in the world is talking about.",
    org: "Popularised on Twitter around 2021 as a diagnosis-shaped upgrade of \"terminally online\", which had circulated since roughly 2018.",
    ex: ["Only a chronically online person would treat that as a scandal.", "I said it out loud and realised how chronically online I sound."],
    rel: ["touch-grass", "doomscrolling", "parasocial"], tags: ["criticism", "internet-brain"],
  },
  {
    slug: "crash-out", term: "Crash out", pron: "krash owt", pos: "verb", cat: "slang",
    year: 2023, pop: 78, trend: 29, status: "rising",
    def: "To lose composure completely, acting on anger or stress in a way that damages your own position. Often used reflexively about a foreseeable breakdown.",
    eli: "Getting so upset that you do something reckless you will regret, instead of staying calm.",
    org: "Long present in US regional slang for a violent loss of control. Rap lyrics and TikTok narration softened and spread it from 2023 onward.",
    ex: ["One more merge conflict and I am going to crash out.", "She crashed out in the group chat at 2am and apologised by breakfast."],
    rel: ["lock-in", "tilt", "brainrot"], tags: ["emotion", "stress"],
  },
  {
    slug: "cringe", term: "Cringe", pron: "krinj", pos: "adjective", cat: "slang",
    year: 2011, pop: 79, trend: -8, status: "classic",
    def: "Producing secondhand embarrassment; earnest in a way an audience finds uncomfortable. Now used as an adjective far more often than as the original verb.",
    eli: "That squirmy feeling when someone tries too hard and you feel embarrassed for them, even though it is not happening to you.",
    org: "From the ordinary English verb, reframed as an adjective by the subreddit r/cringe in 2011. A counter-movement around 2021 argued that cringe is just the price of caring about something.",
    ex: ["The company account is cringe and I watch every single post.", "Being called cringe is the tax on being sincere."],
    rel: ["based", "normie", "brainrot"], tags: ["embarrassment", "reddit"],
  },
  {
    slug: "delulu", term: "Delulu", pron: "duh-LOO-loo", pos: "adjective", cat: "slang",
    year: 2018, pop: 84, trend: 11, status: "mainstream",
    def: "Holding a belief that is obviously untrue but pleasant, usually about a romantic prospect or an unlikely outcome. Almost always self-applied, and affectionate rather than cruel.",
    eli: "Believing something that probably is not true because believing it feels good, like being sure your crush likes you based on one emoji.",
    org: "A reduplicated shortening of \"delusional\" from K-pop fandom forums in the late 2010s, where it described fans convinced they had a real relationship with an idol. TikTok generalised it in 2023.",
    ex: ["I am being delulu about this job application and you cannot stop me.", "Slightly delulu, extremely happy. No notes."],
    rel: ["stan", "parasocial", "situationship"], tags: ["optimism", "kpop", "self-aware"],
  },
  {
    slug: "glazing", term: "Glazing", pron: "GLAY-zing", pos: "verb", cat: "slang",
    year: 2023, pop: 72, trend: 21, status: "rising",
    def: "Praising someone so excessively that the praise stops being credible, particularly a celebrity, streamer or brand.",
    eli: "Complimenting someone so much and so often that people stop believing you actually mean it.",
    org: "Rose through Twitch and NBA Twitter around 2023 as a blunter replacement for \"simping\" or \"riding for\" someone.",
    ex: ["Every reply under that post is pure glazing.", "I am not glazing, he genuinely played well."],
    rel: ["stan", "parasocial", "ratio"], tags: ["praise", "twitch", "sports"],
  },
  {
    slug: "ick", term: "The ick", pron: "thuh ik", pos: "noun", cat: "slang",
    year: 2017, pop: 76, trend: 3, status: "mainstream",
    def: "A sudden, usually irreversible loss of attraction triggered by a small and often trivial detail about someone.",
    eli: "When you liked someone, then saw them do one tiny awkward thing, and suddenly the feeling switched off.",
    org: "Used on British reality television as early as 2017 and carried worldwide by Love Island. TikTok turned listing your icks into a format around 2020.",
    ex: ["He ran for the bus and I caught the ick instantly.", "Naming your icks out loud makes them sound unforgivable and unserious at once."],
    rel: ["rizz", "situationship", "aura"], tags: ["dating", "reality-tv"],
  },
  {
    slug: "lock-in", term: "Lock in", pron: "lok in", pos: "verb", cat: "slang",
    year: 2023, pop: 80, trend: 26, status: "rising",
    def: "To enter a state of complete focus on a single task, deliberately shutting out distraction. Used as encouragement as often as description.",
    eli: "Deciding to concentrate hard on one thing and ignore everything else until it is finished.",
    org: "Sports and gaming shorthand for pre-match focus, which crossed into study and work culture on TikTok around 2023.",
    ex: ["Two weeks to the deadline. Time to lock in.", "He locked in and cleared the whole backlog in a day."],
    rel: ["crash-out", "grind", "sweaty"], tags: ["focus", "motivation", "study"],
  },
  {
    slug: "mid", term: "Mid", pron: "mid", pos: "adjective", cat: "slang",
    year: 2021, pop: 88, trend: 2, status: "mainstream",
    def: "Mediocre; average in a way that disappoints given the hype. Sharper than \"fine\" because it implies the thing was oversold.",
    eli: "Not bad, not good, just boring. People say it when something was talked up a lot and turned out okay at best.",
    org: "Long-standing shorthand for \"middling\" in hip-hop slang. Wrestling commentary and sports Twitter pushed it mainstream around 2021 as the default way to dismiss something.",
    ex: ["Great trailer, mid film.", "Calling it mid is the harshest thing you can do to a sequel."],
    rel: ["based", "cringe", "ratio"], tags: ["criticism", "reviews"],
  },
  {
    slug: "ratio", term: "Ratio", pron: "RAY-shee-oh", pos: "noun", cat: "slang",
    year: 2017, pop: 74, trend: -4, status: "classic",
    def: "A post whose replies vastly outnumber its likes, read as evidence that the audience disagrees. Also a verb: to bury a post under critical replies.",
    eli: "When far more people argue with a post than like it. It is the internet scoreboard showing that a bad take lost.",
    org: "Named on Twitter around 2017 after users noticed that reply-to-like imbalance reliably marked a disliked post. It outlived the platform rename and spread to every comment section.",
    ex: ["That announcement got ratioed within nine minutes.", "Ratio, plus you posted it from the brand account."],
    rel: ["ragebait", "based", "mid"], tags: ["twitter", "backlash", "metrics"],
  },
  {
    slug: "rizz", term: "Rizz", pron: "riz", pos: "noun", cat: "slang",
    year: 2021, pop: 92, trend: -6, status: "mainstream",
    def: "Charisma applied specifically to romantic or flirtatious situations; a person's ability to attract someone through conversation alone. Also used as a verb in the form \"rizz up\".",
    eli: "Being really good at talking to someone you like, so that they end up liking you back. It is charm, but the version you use on a crush.",
    org: "Coined by streamer Kai Cenat and his circle around 2021 as a clipped form of \"charisma\". It spread through Twitch clips to TikTok, and Oxford named it word of the year in 2023.",
    ex: ["He has unspoken rizz - he barely says anything and it still works.", "I tried to rizz her up and immediately forgot how sentences work."],
    rel: ["ick", "situationship", "aura"], tags: ["dating", "charisma", "twitch"],
  },
  {
    slug: "situationship", term: "Situationship", pron: "sit-choo-AY-shun-ship", pos: "noun", cat: "slang",
    year: 2014, pop: 83, trend: 6, status: "mainstream",
    def: "A romantic connection that functions like a relationship but has deliberately never been defined, leaving both people without agreed terms.",
    eli: "Two people who act like they are together but never actually said they are, so nobody knows the rules.",
    org: "Appeared in relationship columns around 2014 and spread widely after 2020 dating apps made undefined arrangements the default.",
    ex: ["Eight months into a situationship and I still cannot describe him to my friends.", "A situationship is a relationship with the paperwork missing."],
    rel: ["ick", "soft-launch", "delulu"], tags: ["dating", "relationships"],
  },
  {
    slug: "touch-grass", term: "Touch grass", pron: "tuhch gras", pos: "phrase", cat: "slang",
    year: 2020, pop: 77, trend: -2, status: "mainstream",
    def: "An instruction to go outside and reconnect with physical reality, aimed at someone whose intensity or worldview appears shaped entirely by being online.",
    eli: "A way of telling someone they have been on the internet too long and should go outside for a while.",
    org: "Emerged on Twitter and Discord around 2020, when lockdowns made the gap between arguing online and living outdoors unusually literal.",
    ex: ["Anyone with a 400-post opinion on this needs to touch grass.", "Logged off, touched grass, felt nothing. Back now."],
    rel: ["chronically-online", "doomscrolling", "brainrot"], tags: ["advice", "wellbeing"],
  },
  {
    slug: "bet", term: "Bet", pron: "bet", pos: "interjection", cat: "slang",
    year: 2017, pop: 79, trend: -2, status: "mainstream",
    def: "An affirmative: agreement, confirmation or acceptance of a plan. Depending on tone it ranges from a casual yes to a challenge meaning we will see about that.",
    eli: "A quick way of saying yes, agreed, or fine, I will prove it.",
    org: "African American Vernacular English, where it is short for you can bet on it. Spread nationally through hip-hop and then through group chats in the late 2010s.",
    ex: ["Meet at seven? Bet.", "You said you would never be late again. Bet."],
    rel: ["say-less", "facts", "word"], tags: ["agreement", "aave", "conversation"],
  },
  {
    slug: "cap", term: "Cap", pron: "kap", pos: "noun", cat: "slang",
    year: 2018, pop: 82, trend: -3, status: "mainstream",
    def: "A lie or an exaggeration. To cap is to lie, and the blue cap emoji often stands in for the word when calling out a false claim.",
    eli: "A lie. If someone says cap, they think you are making it up.",
    org: "Long-standing in African American Vernacular English, where capping meant boasting or lying. Migos brought it to a mass audience in 2018 and social media did the rest.",
    ex: ["He said he ran it in four minutes. That is cap.", "Stop capping, you were not even there."],
    rel: ["no-cap", "receipts", "bet"], tags: ["honesty", "aave", "accusation"],
  },
  {
    slug: "no-cap", term: "No cap", pron: "noh kap", pos: "phrase", cat: "slang",
    year: 2018, pop: 84, trend: -4, status: "mainstream",
    def: "A sincerity marker meaning no exaggeration, this is true. Placed before or after a claim the speaker expects to sound unbelievable.",
    eli: "A way of promising you are not exaggerating.",
    org: "The negation of cap, meaning a lie. Both entered wide circulation together around 2018 and function as a matched pair.",
    ex: ["No cap, that is the best thing I have eaten all year.", "I finished the whole thing in one sitting, no cap."],
    rel: ["cap", "deadass", "fr"], tags: ["honesty", "aave", "emphasis"],
  },
  {
    slug: "deadass", term: "Deadass", pron: "DED-ass", pos: "adverb", cat: "slang",
    year: 2016, pop: 71, trend: -1, status: "mainstream",
    def: "Seriously; genuinely. Used to insist a statement is not a joke, and as a standalone question meaning are you serious.",
    eli: "A way of saying I really mean it, no joking.",
    org: "New York City slang strongly associated with Brooklyn, documented from the 2000s and carried nationally by New York rappers and by Vine around 2016.",
    ex: ["I deadass forgot my own address.", "You got the job? Deadass?"],
    rel: ["no-cap", "fr", "istg"], tags: ["sincerity", "new-york", "emphasis"],
  },
  {
    slug: "lowkey", term: "Lowkey", pron: "LOH-kee", pos: "adverb", cat: "slang",
    year: 2015, pop: 86, trend: 0, status: "mainstream",
    def: "Somewhat, secretly, or slightly. A hedge that softens an admission the speaker is not fully committing to.",
    eli: "A way of admitting something quietly, like saying I kind of think this but do not make it a big deal.",
    org: "From the ordinary English sense of low-key, meaning restrained. Reanalysed as an intensity hedge in African American Vernacular English and mainstreamed by Twitter around 2015.",
    ex: ["Lowkey the sequel was better.", "I am lowkey nervous about tomorrow."],
    rel: ["highkey", "unserious", "mid"], tags: ["hedging", "aave", "conversation"],
  },
  {
    slug: "highkey", term: "Highkey", pron: "HY-kee", pos: "adverb", cat: "slang",
    year: 2016, pop: 63, trend: -2, status: "mainstream",
    def: "Openly and emphatically; the counterpart to lowkey. Signals that the speaker is not hedging at all.",
    eli: "The opposite of lowkey. It means you are saying something loudly and on purpose.",
    org: "Coined by analogy once lowkey had become common, following the usual pattern in which a hedge eventually produces its own intensifier.",
    ex: ["Highkey the best decision I made this year.", "I am highkey obsessed with this album."],
    rel: ["lowkey", "no-cap", "fr"], tags: ["emphasis", "conversation"],
  },
  {
    slug: "fr", term: "FR", pron: "ef-AR", pos: "abbreviation", cat: "slang",
    year: 2019, pop: 88, trend: 3, status: "mainstream",
    def: "Short for for real. Used to affirm a statement, to agree emphatically, or doubled as fr fr for extra insistence.",
    eli: "Short for for real. It means I agree, or I am not joking.",
    org: "Texting shorthand that hardened into speech, so that people now say the letters aloud. The doubled form fr fr appeared around 2020.",
    ex: ["Fr, that meeting could have been an email.", "It is genuinely that good, fr fr."],
    rel: ["ong", "no-cap", "facts"], tags: ["agreement", "texting", "abbreviation"],
  },
  {
    slug: "ong", term: "ONG", pron: "oh-en-JEE", pos: "abbreviation", cat: "slang",
    year: 2020, pop: 68, trend: 6, status: "mainstream",
    def: "Short for on God, a sincerity oath meaning I swear this is true. Functions as a stronger version of fr.",
    eli: "Short for on God. It is a way of swearing that what you said is true.",
    org: "A textual compression of the older spoken oath on God, itself from African American Vernacular English. The initialism spread through gaming chat and TikTok comments.",
    ex: ["ong that was the loudest room I have ever been in.", "I did not touch it, ong."],
    rel: ["fr", "deadass", "istg"], tags: ["sincerity", "texting", "abbreviation"],
  },
  {
    slug: "say-less", term: "Say less", pron: "say les", pos: "phrase", cat: "slang",
    year: 2017, pop: 61, trend: -1, status: "mainstream",
    def: "An acceptance meaning you have already convinced me, stop explaining. Warmer than a plain yes because it implies enthusiasm.",
    eli: "A way of saying I am already in, you do not need to keep persuading me.",
    org: "Toronto and New York slang carried outward by drill and by Drake-adjacent music in the mid-2010s.",
    ex: ["There is free food? Say less.", "Say less, I am already getting my coat."],
    rel: ["bet", "facts", "word"], tags: ["agreement", "enthusiasm"],
  },
  {
    slug: "facts", term: "Facts", pron: "fakts", pos: "interjection", cat: "slang",
    year: 2016, pop: 74, trend: -2, status: "mainstream",
    def: "A one-word agreement meaning that is correct and I have nothing to add. Often the entire reply.",
    eli: "A short way of saying you are right.",
    org: "African American Vernacular English usage that spread through comment sections, where a single-word reply carries more weight than a long one.",
    ex: ["Nobody actually reads the terms. Facts.", "Facts, and I will not be elaborating."],
    rel: ["bet", "word", "fr"], tags: ["agreement", "comments"],
  },
  {
    slug: "word", term: "Word", pron: "wurd", pos: "interjection", cat: "slang",
    year: 1985, pop: 55, trend: -3, status: "classic",
    def: "An affirmation meaning agreed, or genuinely. As a question, word? asks for confirmation that something surprising is true.",
    eli: "A short way of saying I agree, or really?",
    org: "Hip-hop vocabulary from early 1980s New York, clipped from the fuller phrases word up and word is bond. One of the oldest slang terms still in everyday online use.",
    ex: ["That place closed down. Word?", "Word, I felt the same way about it."],
    rel: ["facts", "bet", "say-less"], tags: ["agreement", "hip-hop", "classic"],
  },
  {
    slug: "bussin", term: "Bussin", pron: "BUS-in", pos: "adjective", cat: "slang",
    year: 2021, pop: 66, trend: -12, status: "fading",
    def: "Extremely good, used most often about food. The doubled bussin bussin is the intensified form.",
    eli: "Really, really tasty or good.",
    org: "African American Vernacular English, in use well before TikTok discovered it in 2021. Its rapid adoption by brand accounts is a standard example of how mainstream attention burns a word out.",
    ex: ["The chilli oil on that is bussin.", "Not bussin, and I am being generous."],
    rel: ["fire", "slaps", "mid"], tags: ["food", "praise", "aave", "tiktok"],
  },
  {
    slug: "fire", term: "Fire", pron: "FY-ur", pos: "adjective", cat: "slang",
    year: 2012, pop: 78, trend: -2, status: "classic",
    def: "Excellent, especially of music, food or clothing. Frequently written as the flame emoji alone.",
    eli: "Really good. People often just use the fire emoji instead of the word.",
    org: "Hip-hop vocabulary that predates social media by decades. The emoji shorthand made it one of the first slang terms to be commonly written as a picture.",
    ex: ["That whole record is fire.", "The fit is fire, the shoes are questionable."],
    rel: ["slaps", "bussin", "goes-hard"], tags: ["praise", "music", "emoji"],
  },
  {
    slug: "slaps", term: "Slaps", pron: "slaps", pos: "verb", cat: "slang",
    year: 2016, pop: 72, trend: -3, status: "mainstream",
    def: "Of a song, to be extremely good, particularly in a physical, bass-driven way. Extended to food and anything else that lands hard.",
    eli: "Used about a song that sounds so good it almost hits you.",
    org: "Bay Area hip-hop, where a slap was a track suited to car speakers. Generalised online from around 2016.",
    ex: ["This slaps and I will be playing it eleven more times.", "Cold water on a hot day just slaps."],
    rel: ["fire", "goes-hard", "hits-different"], tags: ["music", "praise", "bay-area"],
  },
  {
    slug: "hits-different", term: "Hits different", pron: "hits DIF-runt", pos: "phrase", cat: "slang",
    year: 2019, pop: 70, trend: -4, status: "mainstream",
    def: "Describes something whose effect is unusually strong in a particular context, often nostalgic or emotional, in a way the speaker cannot fully account for.",
    eli: "When something feels much more powerful than usual because of where or when you experience it.",
    org: "Spread on Twitter and Tumblr around 2019 as a way of naming an effect that depends on mood and setting rather than on the thing itself.",
    ex: ["That song hits different at 2am.", "Cereal hits different when someone else pours it."],
    rel: ["slaps", "sending-me", "big-mood"], tags: ["nostalgia", "feeling", "twitter"],
  },
  {
    slug: "goes-hard", term: "Goes hard", pron: "gohz hard", pos: "phrase", cat: "slang",
    year: 2018, pop: 69, trend: 2, status: "mainstream",
    def: "Commits fully and to impressive effect. Applied to music, writing, food and any effort that exceeds what the situation required.",
    eli: "Something that is much better or more intense than it needed to be.",
    org: "From going hard, meaning to give maximum effort, in hip-hop and sports. The detached phrase became a general compliment online in the late 2010s.",
    ex: ["The soundtrack for a supermarket advert goes unreasonably hard.", "Her cover letter goes hard."],
    rel: ["slaps", "fire", "peak"], tags: ["praise", "effort", "music"],
  },
  {
    slug: "sus", term: "Sus", pron: "sus", pos: "adjective", cat: "slang",
    year: 2020, pop: 76, trend: -6, status: "mainstream",
    def: "Suspicious; behaving in a way that suggests a hidden motive. Clipped from suspicious or suspect.",
    eli: "Someone or something that seems dodgy, like they are hiding what they are really doing.",
    org: "British and Caribbean English shorthand for suspect, used for decades. The 2020 game Among Us made it globally ubiquitous almost overnight.",
    ex: ["He volunteered to count the money. Slightly sus.", "That email is sus, do not click it."],
    rel: ["sussy", "cap", "receipts"], tags: ["suspicion", "among-us", "gaming"],
  },
  {
    slug: "sussy", term: "Sussy", pron: "SUS-ee", pos: "adjective", cat: "slang",
    year: 2021, pop: 44, trend: -18, status: "fading",
    def: "A deliberately childish elaboration of sus, used almost entirely in jest. Its silliness is the joke.",
    eli: "A sillier way of saying suspicious, said to be funny rather than serious.",
    org: "Grew out of Among Us commentary in 2021 and became a marker of ironic distance, then a marker of being late to the joke.",
    ex: ["Extremely sussy behaviour from the cat this morning.", "Nobody has said sussy sincerely since 2022."],
    rel: ["sus", "brainrot", "cringe"], tags: ["among-us", "irony", "gen-alpha"],
  },
  {
    slug: "slay", term: "Slay", pron: "slay", pos: "verb", cat: "slang",
    year: 2014, pop: 80, trend: -7, status: "mainstream",
    def: "To do something exceptionally well, particularly in a way that involves presence or style. Used as a standalone exclamation of approval.",
    eli: "To do something brilliantly, especially with confidence and style.",
    org: "Ballroom and Black queer vocabulary from the 1970s and 1980s, popularised through drag culture and then flattened by mass adoption after 2016.",
    ex: ["She slayed that presentation.", "New haircut? Slay."],
    rel: ["ate", "serving", "iconic"], tags: ["praise", "ballroom", "drag"],
  },
  {
    slug: "ate", term: "Ate", pron: "ayt", pos: "verb", cat: "slang",
    year: 2019, pop: 77, trend: 1, status: "mainstream",
    def: "Performed superbly. The full form, ate and left no crumbs, means the performance was so complete that nothing was left to criticise.",
    eli: "Did something so well there is nothing left to add.",
    org: "Ballroom and Black queer vocabulary, related to slay and serve, that reached general use through drag television and TikTok.",
    ex: ["She ate and left no crumbs.", "The bass player ate on that track."],
    rel: ["slay", "serving", "understood-the-assignment"], tags: ["praise", "ballroom", "performance"],
  },
  {
    slug: "serving", term: "Serving", pron: "SUR-ving", pos: "verb", cat: "slang",
    year: 2015, pop: 65, trend: -2, status: "mainstream",
    def: "Presenting a striking look or attitude, usually followed by what is being served: serving confidence, serving 1997.",
    eli: "Showing off a strong look or mood on purpose.",
    org: "Ballroom vocabulary, where to serve was to present yourself for judgement on the runway. Carried into wide use by drag culture.",
    ex: ["She is serving quiet menace in that coat.", "Serving looks in a supermarket car park."],
    rel: ["slay", "ate", "fit-check"], tags: ["fashion", "ballroom", "drag"],
  },
  {
    slug: "understood-the-assignment", term: "Understood the assignment", pron: "un-der-STOOD thee uh-SYNE-ment", pos: "phrase", cat: "slang",
    year: 2021, pop: 62, trend: -8, status: "fading",
    def: "Delivered exactly what the situation called for. Praise specifically for judgement and appropriateness rather than raw skill.",
    eli: "Did exactly the right thing for the occasion, not just something good.",
    org: "From a 2021 Twitter format praising red-carpet outfits that suited a film's theme, then generalised to any well-judged effort.",
    ex: ["Everyone at that wedding understood the assignment.", "The soundtrack understood the assignment."],
    rel: ["ate", "slay", "no-notes"], tags: ["praise", "judgement", "twitter"],
  },
  {
    slug: "its-giving", term: "It is giving", pron: "its GIV-ing", pos: "phrase", cat: "slang",
    year: 2021, pop: 73, trend: -3, status: "mainstream",
    def: "Introduces the impression something creates, usually followed by a noun rather than an adjective: it is giving autumn, it is giving unpaid intern.",
    eli: "A way of saying what something reminds you of or what mood it gives off.",
    org: "Black queer and ballroom vocabulary, where giving named the quality being presented. Amplified massively by TikTok from 2021.",
    ex: ["It is giving corporate away-day.", "The whole album is giving late-night bus ride."],
    rel: ["serving", "vibe", "coded"], tags: ["description", "ballroom", "tiktok"],
  },
  {
    slug: "periodt", term: "Periodt", pron: "PEER-ee-udt", pos: "interjection", cat: "slang",
    year: 2018, pop: 51, trend: -11, status: "fading",
    def: "An emphatic full stop placed after a statement to mark it as final and not open to discussion.",
    eli: "A way of saying that is final, end of conversation.",
    org: "An emphatic respelling of period in Black queer vernacular, where the added consonant lengthens the delivery. Spread through Twitter and drag culture.",
    ex: ["The original is better, periodt.", "She said what she said, periodt."],
    rel: ["facts", "slay", "no-notes"], tags: ["emphasis", "drag", "twitter"],
  },
  {
    slug: "tea", term: "Tea", pron: "tee", pos: "noun", cat: "slang",
    year: 2013, pop: 69, trend: -4, status: "mainstream",
    def: "Gossip, especially the specific and unflattering kind. To spill the tea is to share it; to sip tea is to observe without involvement.",
    eli: "Gossip. Spilling the tea means telling someone the story.",
    org: "Black drag culture, where T stood for truth. Documented in the 1990s and carried to a mass audience by reality television and Twitter.",
    ex: ["Sit down, I have tea about the group chat.", "No tea, no shade, but that was a disaster."],
    rel: ["shade", "receipts", "lore"], tags: ["gossip", "drag", "conversation"],
  },
  {
    slug: "shade", term: "Shade", pron: "shayd", pos: "noun", cat: "slang",
    year: 1990, pop: 67, trend: -2, status: "classic",
    def: "A subtle insult that works by implication rather than statement. Throwing shade requires that the target cannot easily object without seeming oversensitive.",
    eli: "An insult hidden inside something that sounds polite.",
    org: "Ballroom vocabulary documented in the 1990 film Paris Is Burning, which distinguished shade from a direct read. Entered general use through drag television.",
    ex: ["Saying it looks brave is pure shade.", "No shade, but nobody asked."],
    rel: ["tea", "read", "side-eye"], tags: ["insult", "ballroom", "subtlety"],
  },
  {
    slug: "receipts", term: "Receipts", pron: "ri-SEETS", pos: "noun", cat: "slang",
    year: 2016, pop: 75, trend: 2, status: "mainstream",
    def: "Screenshots or records produced as proof of what someone said or did. Demanded when a claim is disputed and deployed to end the dispute.",
    eli: "Screenshots that prove someone said or did something.",
    org: "Popularised after a 1991 interview in which Whitney Houston asked to see receipts for a rumour. Twitter turned it into standard argument vocabulary from 2016.",
    ex: ["Post the receipts or drop it.", "She had receipts going back four years."],
    rel: ["caught-in-4k", "cap", "tea"], tags: ["proof", "screenshots", "argument"],
  },
  {
    slug: "caught-in-4k", term: "Caught in 4K", pron: "kawt in for-KAY", pos: "phrase", cat: "slang",
    year: 2020, pop: 64, trend: -5, status: "mainstream",
    def: "Caught doing something with evidence so clear that denial is impossible. The resolution is the joke: not merely caught, but caught in high definition.",
    eli: "Caught doing something with proof so clear you cannot deny it.",
    org: "Twitter and TikTok around 2020, building on the older caught in 4K meme format about screenshots of deleted posts.",
    ex: ["Deleted it in ten seconds and still got caught in 4K.", "Caught in 4K liking a post from 2014."],
    rel: ["receipts", "cap", "sus"], tags: ["proof", "screenshots", "twitter"],
  },
  {
    slug: "side-eye", term: "Side eye", pron: "syde eye", pos: "noun", cat: "slang",
    year: 2011, pop: 58, trend: -1, status: "classic",
    def: "A sceptical or disapproving sideways glance, and by extension any expression of quiet doubt about what someone has said.",
    eli: "A look that says you do not believe or approve of what someone just did.",
    org: "Long-standing in spoken English, but reanimated online as a reaction-image genre and then as a written stage direction in replies.",
    ex: ["Massive side eye at that pricing change.", "I am giving this entire announcement side eye."],
    rel: ["shade", "sus", "unserious"], tags: ["reaction", "scepticism"],
  },
  {
    slug: "drip", term: "Drip", pron: "drip", pos: "noun", cat: "slang",
    year: 2018, pop: 73, trend: -3, status: "mainstream",
    def: "Notably good clothing and accessories, considered as a whole. To have drip is to dress with evident intent.",
    eli: "A really good outfit, especially one that looks expensive and deliberate.",
    org: "Atlanta hip-hop vocabulary from the mid-2010s that displaced the older term swag almost entirely by 2019.",
    ex: ["The drip is immaculate, the timekeeping is not.", "Where is that drip from?"],
    rel: ["fit-check", "serving", "clean-girl"], tags: ["fashion", "hip-hop", "style"],
  },
  {
    slug: "fit-check", term: "Fit check", pron: "fit chek", pos: "noun", cat: "slang",
    year: 2019, pop: 68, trend: 4, status: "mainstream",
    def: "A post or video presenting an outfit for appraisal, usually filmed in a mirror and narrated item by item.",
    eli: "Showing off what you are wearing and asking people what they think.",
    org: "Streetwear forums and Instagram, where fit is short for outfit. TikTok turned it into a standard short-video format from 2019.",
    ex: ["Fit check before the interview.", "The comments on that fit check were brutal."],
    rel: ["drip", "grwm", "serving"], tags: ["fashion", "tiktok", "format"],
  },
  {
    slug: "vibe", term: "Vibe", pron: "vybe", pos: "noun", cat: "slang",
    year: 2016, pop: 89, trend: -1, status: "classic",
    def: "The overall feeling a person, place or piece of media gives off, treated as a real and assessable property. A vibe check tests whether it is acceptable.",
    eli: "The general feeling something gives you, without being able to point at one reason.",
    org: "1960s counterculture shorthand for vibration, revived online in the mid-2010s and expanded into a whole family of terms including vibe check and immaculate vibes.",
    ex: ["Great food, strange vibe.", "Vibe check: how is everyone actually doing?"],
    rel: ["its-giving", "big-mood", "aesthetic"], tags: ["feeling", "atmosphere", "classic"],
  },
  {
    slug: "big-mood", term: "Big mood", pron: "big mood", pos: "phrase", cat: "slang",
    year: 2017, pop: 54, trend: -9, status: "fading",
    def: "An expression of total identification with something posted. Mood alone functions the same way; big is the intensifier.",
    eli: "A way of saying that is exactly how I feel right now.",
    org: "Tumblr and Twitter around 2017, part of a wider shift toward replying with a state of mind rather than an opinion.",
    ex: ["A dog refusing to leave the sofa. Big mood.", "That photo is a mood and a half."],
    rel: ["vibe", "same", "felt-that"], tags: ["reaction", "tumblr", "identification"],
  },
  {
    slug: "same", term: "Same", pron: "saym", pos: "interjection", cat: "slang",
    year: 2014, pop: 60, trend: -5, status: "classic",
    def: "A one-word reply expressing complete identification with what has just been described, especially a small failure or a strong preference.",
    eli: "A short way of saying me too.",
    org: "Tumblr reply culture of the early 2010s, where the shortest possible response became the most emphatic one.",
    ex: ["Cancelled plans and felt instant relief. Same.", "Same, unfortunately."],
    rel: ["big-mood", "felt-that", "facts"], tags: ["reaction", "tumblr", "empathy"],
  },
  {
    slug: "felt-that", term: "Felt that", pron: "felt that", pos: "phrase", cat: "slang",
    year: 2018, pop: 47, trend: -3, status: "niche",
    def: "Signals that a statement landed with physical force, usually because it described something uncomfortably accurate about the reader.",
    eli: "A way of saying that hit me right where it hurts, in a good way.",
    org: "Twitter reply vocabulary of the late 2010s, sitting alongside sending me and I am deceased as ways of reporting an involuntary reaction.",
    ex: ["Opening the fridge for the fourth time. I felt that.", "Felt that in my chest, honestly."],
    rel: ["same", "big-mood", "hits-different"], tags: ["reaction", "empathy", "twitter"],
  },
  {
    slug: "sending-me", term: "Sending me", pron: "SEND-ing mee", pos: "phrase", cat: "slang",
    year: 2018, pop: 56, trend: -4, status: "mainstream",
    def: "Causing helpless laughter. The implication is of being sent somewhere else by the force of the joke.",
    eli: "Something so funny it makes you lose it completely.",
    org: "Black Twitter vocabulary of the mid-2010s, part of a family of hyperbolic laughter reports that also includes screaming and deceased.",
    ex: ["The caption is sending me.", "That reply sent me, genuinely."],
    rel: ["im-deceased", "crying", "ijbol"], tags: ["laughter", "reaction", "twitter"],
  },
  {
    slug: "im-deceased", term: "I am deceased", pron: "eye am di-SEEST", pos: "phrase", cat: "slang",
    year: 2013, pop: 43, trend: -7, status: "fading",
    def: "A hyperbolic report of having been killed by something funny. Related forms include I am dead and I cannot breathe.",
    eli: "A joking way of saying something was so funny it finished you off.",
    org: "Black Twitter and Tumblr of the early 2010s, where mock-formal register was a reliable comic device.",
    ex: ["The cat photo caption. I am deceased.", "Deceased. Buried. Send flowers."],
    rel: ["sending-me", "crying", "screaming"], tags: ["laughter", "hyperbole", "tumblr"],
  },
  {
    slug: "crying", term: "Crying", pron: "KRY-ing", pos: "verb", cat: "slang",
    year: 2015, pop: 71, trend: -2, status: "mainstream",
    def: "Used almost exclusively to mean laughing very hard rather than actually weeping. Context does all the disambiguating work.",
    eli: "Usually means laughing so much your eyes water, not being sad.",
    org: "Emerged from the laughing-crying emoji, which became so common that the word itself flipped meaning in casual online use.",
    ex: ["Crying at the third slide of that deck.", "I am crying, who let him post this."],
    rel: ["screaming", "sending-me", "ijbol"], tags: ["laughter", "emoji", "reaction"],
  },
  {
    slug: "screaming", term: "Screaming", pron: "SKREEM-ing", pos: "verb", cat: "slang",
    year: 2016, pop: 66, trend: -1, status: "mainstream",
    def: "A report of an extreme reaction, usually delight or disbelief. Frequently stacked as screaming, crying, throwing up for comic escalation.",
    eli: "A way of saying you reacted very loudly, at least in your head.",
    org: "Twitter and Tumblr, where escalating physical claims replaced conventional laughter markers once those had lost their force.",
    ex: ["Screaming at the timing of that notification.", "Screaming, crying, throwing up, the usual."],
    rel: ["crying", "im-deceased", "sending-me"], tags: ["laughter", "hyperbole", "reaction"],
  },
  {
    slug: "ijbol", term: "IJBOL", pron: "IJ-bol", pos: "abbreviation", cat: "slang",
    year: 2023, pop: 41, trend: 9, status: "rising",
    def: "I just burst out laughing. Proposed as a successor to LOL on the grounds that it describes an actual event rather than a formality.",
    eli: "A newer way of saying you actually laughed out loud, because LOL stopped meaning that.",
    org: "Circulated in K-pop fan spaces before spreading on TikTok and Twitter in 2023, as part of the recurring search for a laughter marker that still means something.",
    ex: ["IJBOL at the delivery driver photo.", "Genuinely IJBOL, not the polite kind."],
    rel: ["lol", "crying", "sending-me"], tags: ["laughter", "abbreviation", "kpop"],
  },
  {
    slug: "yap", term: "Yap", pron: "yap", pos: "verb", cat: "slang",
    year: 2023, pop: 74, trend: 16, status: "rising",
    def: "To talk at length with little substance. A yapper does it habitually; yapping is the activity; yap session is a long unfocused conversation.",
    eli: "Talking a lot without saying much. A yapper is someone who never stops.",
    org: "The ordinary English word for a small dog barking, repurposed on TikTok around 2023 as the standard accusation against anyone speaking for too long.",
    ex: ["Sorry for the yapping, anyway, my point was this.", "Certified yapper, and I say that with love."],
    rel: ["glazing", "unserious", "brainrot"], tags: ["talking", "tiktok", "accusation"],
  },
  {
    slug: "unserious", term: "Unserious", pron: "un-SEER-ee-us", pos: "adjective", cat: "slang",
    year: 2021, pop: 64, trend: 5, status: "mainstream",
    def: "Not to be taken seriously, said of a person or a take. Often affectionate, marking someone as a source of nonsense rather than of harm.",
    eli: "Someone who is joking around and should not be taken seriously.",
    org: "Black Twitter usage that spread widely after 2021, filling a gap between calling something a joke and calling it stupid.",
    ex: ["This entire comment section is unserious.", "He is unserious and it is the best thing about him."],
    rel: ["side-eye", "yap", "lowkey"], tags: ["humour", "twitter", "judgement"],
  },
  {
    slug: "cope", term: "Cope", pron: "kohp", pos: "noun", cat: "slang",
    year: 2019, pop: 62, trend: 3, status: "mainstream",
    def: "A rationalisation offered to soften a defeat, and by extension the accusation that someone is producing one. Copium is the imagined drug that makes it possible.",
    eli: "An excuse people make so a loss feels less bad. Copium is the joke version, like a drug for coping.",
    org: "Imageboard vocabulary of the late 2010s, carried into gaming and sports argument by Twitch chat, where cope and seethe travel together.",
    ex: ["Calling it a moral victory is pure cope.", "Massive hit of copium in that post-match interview."],
    rel: ["skill-issue", "ratio", "malding"], tags: ["argument", "defeat", "imageboards"],
  },
  {
    slug: "skill-issue", term: "Skill issue", pron: "skil ISH-oo", pos: "phrase", cat: "slang",
    year: 2021, pop: 70, trend: 8, status: "rising",
    def: "A dismissal attributing someone's complaint to their own incompetence rather than to any real problem. Applied far outside games.",
    eli: "A way of saying the problem is not the game, it is that you are bad at it.",
    org: "Gaming chat, where it answered complaints about difficulty. Spread through Twitch and Discord from 2021 into general use as a catch-all deflection.",
    ex: ["The build takes nine minutes. Skill issue, apparently.", "Cannot parallel park. Genuine skill issue."],
    rel: ["cope", "git-gud", "ratio"], tags: ["gaming", "dismissal", "twitch"],
  },
  {
    slug: "rent-free", term: "Living rent free", pron: "LIV-ing rent free", pos: "phrase", cat: "slang",
    year: 2019, pop: 59, trend: -2, status: "mainstream",
    def: "Describes a thought or person occupying someone's mind without their consent, usually as an accusation that they are more bothered than they admit.",
    eli: "When something is stuck in your head all the time even though you wish it was not.",
    org: "From a much older business aphorism about not letting enemies live rent free in your head. Twitter reduced it to the punchline from around 2019.",
    ex: ["That advert jingle is living rent free in my head.", "One reply and you have been thinking about it all week. Rent free."],
    rel: ["cope", "ratio", "lore"], tags: ["obsession", "twitter", "accusation"],
  },
  {
    slug: "main-character", term: "Main character", pron: "mayn KAR-ik-tur", pos: "noun", cat: "slang",
    year: 2020, pop: 72, trend: -3, status: "mainstream",
    def: "Someone behaving as though the world is a story about them. Main character energy can be aspirational self-regard or an accusation of self-absorption.",
    eli: "Acting like you are the star of a film and everyone else is in the background.",
    org: "TikTok in 2020, where videos encouraged viewers to romanticise their own lives. Twitter simultaneously used main character of the day for whoever was being argued about.",
    ex: ["Walking to the shop with headphones on, full main character energy.", "Do not become the main character of Twitter today."],
    rel: ["npc", "villain-era", "era"], tags: ["identity", "tiktok", "self-image"],
  },
  {
    slug: "npc", term: "NPC", pron: "en-pee-SEE", pos: "noun", cat: "slang",
    year: 2018, pop: 68, trend: 4, status: "mainstream",
    def: "A person perceived as acting without independent thought, from the non-player characters who repeat fixed lines in games. Also a livestream genre imitating that behaviour.",
    eli: "Someone acting like a background character in a game who just repeats the same things.",
    org: "Borrowed from game design, where NPC is a neutral technical term. Used as an insult from 2018, then revived in 2023 as a TikTok livestream performance style.",
    ex: ["Every reply is the same sentence. Total NPC behaviour.", "The NPC streams were genuinely unsettling."],
    rel: ["main-character", "normie", "brainrot"], tags: ["gaming", "insult", "tiktok"],
  },
  {
    slug: "villain-era", term: "Villain era", pron: "VIL-un EER-uh", pos: "noun", cat: "slang",
    year: 2022, pop: 57, trend: -6, status: "mainstream",
    def: "A declared phase of prioritising yourself and refusing to accommodate others. Usually describes ordinary boundary-setting framed dramatically.",
    eli: "Deciding to stop being endlessly nice and put yourself first for a while.",
    org: "TikTok in 2022, part of a wider habit of narrating life in the vocabulary of television character arcs.",
    ex: ["Declined three invitations this week. Villain era.", "Her villain era mostly involves going to bed at nine."],
    rel: ["era", "main-character", "act-your-wage"], tags: ["identity", "tiktok", "boundaries"],
  },
  {
    slug: "clout", term: "Clout", pron: "klowt", pos: "noun", cat: "slang",
    year: 2017, pop: 66, trend: -4, status: "mainstream",
    def: "Online influence measured in attention rather than respect. Clout chasing is pursuing it through stunts, association or manufactured conflict.",
    eli: "Internet fame. Clout chasing means doing things just to get noticed.",
    org: "An old English word for a heavy blow, revived through hip-hop in the mid-2010s to describe reach and social pull.",
    ex: ["He started that argument purely for clout.", "All clout, no craft."],
    rel: ["ragebait", "glazing", "parasocial"], tags: ["fame", "hip-hop", "attention"],
  },
  {
    slug: "flex", term: "Flex", pron: "fleks", pos: "verb", cat: "slang",
    year: 2014, pop: 70, trend: -3, status: "classic",
    def: "To display wealth, skill or good fortune. A weird flex is a boast about something nobody considers impressive.",
    eli: "Showing off. A weird flex is bragging about something strange.",
    org: "Hip-hop vocabulary from the 1990s meaning to show strength, generalised online in the mid-2010s. The weird flex but ok format appeared in 2018.",
    ex: ["Weird flex, but fine.", "Not to flex, but I read the whole manual."],
    rel: ["clout", "humblebrag", "drip"], tags: ["boasting", "hip-hop", "status"],
  },
  {
    slug: "humblebrag", term: "Humblebrag", pron: "HUM-bul-brag", pos: "noun", cat: "slang",
    year: 2010, pop: 52, trend: -4, status: "classic",
    def: "A boast disguised as a complaint or as self-deprecation, so that the speaker gets the credit without appearing to seek it.",
    eli: "Bragging while pretending to complain, so it does not look like bragging.",
    org: "Coined by comedian Harris Wittels on Twitter in 2010 and documented in his account cataloguing examples. Entered dictionaries within five years.",
    ex: ["Exhausted from all this unexpected press. Classic humblebrag.", "So annoying when the upgrade is automatic."],
    rel: ["flex", "clout", "cringe"], tags: ["boasting", "twitter", "social"],
  },
  {
    slug: "salty", term: "Salty", pron: "SAWL-tee", pos: "adjective", cat: "slang",
    year: 2013, pop: 63, trend: -2, status: "classic",
    def: "Bitter or resentful about a defeat, in a way that is visible to everyone but denied by the person concerned.",
    eli: "Annoyed about losing and not hiding it very well.",
    org: "US Navy and later hip-hop slang for being irritable, adopted by fighting-game and shooter communities in the early 2010s.",
    ex: ["Still salty about a board game from 2019.", "Not salty, just factually correct and unhappy."],
    rel: ["pressed", "malding", "tilt"], tags: ["emotion", "gaming", "defeat"],
  },
  {
    slug: "pressed", term: "Pressed", pron: "prest", pos: "adjective", cat: "slang",
    year: 2015, pop: 55, trend: -1, status: "mainstream",
    def: "Unreasonably upset about something minor, with the implication that the reaction reveals more than the trigger warranted.",
    eli: "Getting way more worked up about something small than it deserves.",
    org: "African American Vernacular English, widespread on Twitter from the mid-2010s as a more precise alternative to salty.",
    ex: ["Why is everyone so pressed about a font change?", "He was pressed and it was beautiful to watch."],
    rel: ["salty", "big-mad", "cope"], tags: ["emotion", "aave", "argument"],
  },
  {
    slug: "big-mad", term: "Big mad", pron: "big mad", pos: "adjective", cat: "slang",
    year: 2018, pop: 49, trend: -3, status: "mainstream",
    def: "Extremely angry in a way that is disproportionate and therefore funny to observers. Distinguished from regular mad by visibility.",
    eli: "Really angry about something in a way other people find funny.",
    org: "Black Twitter usage in which big functions as an intensifier that also implies the anger is undignified.",
    ex: ["They are big mad about the referee decision.", "Big mad and posting through it."],
    rel: ["pressed", "salty", "crash-out"], tags: ["emotion", "twitter", "aave"],
  },
  {
    slug: "malding", term: "Malding", pron: "MAWL-ding", pos: "verb", cat: "slang",
    year: 2019, pop: 46, trend: -2, status: "niche",
    def: "Being so angry that you are going bald from the stress. A portmanteau of mad and balding, used almost entirely in Twitch chat.",
    eli: "A joking way of saying someone is so angry they are losing their hair over it.",
    org: "Twitch chat around 2019, originally aimed at specific streamers and then generalised to anyone visibly losing composure on stream.",
    ex: ["Third loss in a row and he is malding.", "Chat noticed the malding before he did."],
    rel: ["tilt", "salty", "cope"], tags: ["twitch", "anger", "gaming"],
  },
  {
    slug: "git-gud", term: "Git gud", pron: "git gud", pos: "phrase", cat: "slang",
    year: 2014, pop: 48, trend: -4, status: "classic",
    def: "A deliberately misspelled instruction to improve rather than complain, associated with punishing games and the communities around them.",
    eli: "A blunt way of telling someone to get better at the game instead of complaining.",
    org: "Dark Souls communities around 2014, where the misspelling signalled that the advice was not offered kindly. It predates and feeds into skill issue.",
    ex: ["Asked for a difficulty setting and got told to git gud.", "Git gud is not documentation."],
    rel: ["skill-issue", "cope", "sweaty"], tags: ["gaming", "dismissal", "souls"],
  },
  {
    slug: "goat", term: "GOAT", pron: "goht", pos: "abbreviation", cat: "slang",
    year: 2016, pop: 77, trend: 1, status: "mainstream",
    def: "Greatest of all time. Applied to athletes and artists, and increasingly to anything the speaker rates highly, often with the goat emoji.",
    eli: "Short for greatest of all time. The goat emoji is used the same way.",
    org: "Coined in boxing culture around Muhammad Ali, made an acronym by LL Cool J in 2000, and turned into everyday sports-internet vocabulary by Twitter.",
    ex: ["He is the GOAT and the argument bores me.", "Whoever invented the snooze button is a GOAT."],
    rel: ["peak", "dub", "based"], tags: ["sports", "praise", "abbreviation"],
  },
  {
    slug: "dub", term: "Dub", pron: "dub", pos: "noun", cat: "slang",
    year: 2015, pop: 61, trend: 2, status: "mainstream",
    def: "A win, from the letter W. To take the L is the counterpart, meaning to accept a loss with some grace.",
    eli: "A win. Taking the L means admitting you lost.",
    org: "Sports and gaming shorthand where W and L stand for win and loss on a record. Dub is simply how the letter W is pronounced.",
    ex: ["Got the last one in the shop. Massive dub.", "Just take the L and move on."],
    rel: ["goat", "take-the-l", "clutch"], tags: ["winning", "sports", "gaming"],
  },
  {
    slug: "take-the-l", term: "Take the L", pron: "tayk thuh EL", pos: "phrase", cat: "slang",
    year: 2015, pop: 58, trend: 0, status: "mainstream",
    def: "To accept a defeat rather than argue about it. The instruction is usually issued to someone visibly refusing to.",
    eli: "Admitting you lost instead of making excuses.",
    org: "From win-loss records in sport, where L marks a loss. Fortnite's Take the L emote in 2018 fixed the phrase in a much younger vocabulary.",
    ex: ["Wrong on the facts and the timing. Take the L.", "He will not take the L, he is still posting."],
    rel: ["dub", "cope", "ratio"], tags: ["defeat", "sports", "gaming"],
  },
  {
    slug: "glow-up", term: "Glow up", pron: "gloh up", pos: "noun", cat: "slang",
    year: 2016, pop: 71, trend: -2, status: "mainstream",
    def: "A dramatic improvement in appearance or circumstances over time, usually presented as a before-and-after pair of images.",
    eli: "Changing a lot for the better, and showing the old photo next to the new one.",
    org: "From Chief Keef's 2013 track Gotta Glo Up One Day, adopted as a transformation format on Twitter and Instagram from 2016.",
    ex: ["The glow up between first and final year is unreal.", "That whole neighbourhood had a glow up."],
    rel: ["era", "fit-check", "villain-era"], tags: ["transformation", "instagram", "format"],
  },
  {
    slug: "peak", term: "Peak", pron: "peek", pos: "adjective", cat: "slang",
    year: 2022, pop: 67, trend: 12, status: "rising",
    def: "The highest possible quality. Peak fiction is the fullest form, used about a story that has just delivered exactly what its audience wanted.",
    eli: "The best something can possibly be.",
    org: "Anime and manga discussion communities, where peak fiction began as sincere praise and survived heavy ironic use. Now general vocabulary among younger users.",
    ex: ["That episode was peak and I will hear nothing else.", "Peak fiction, no notes."],
    rel: ["goat", "cinema", "goes-hard"], tags: ["praise", "anime", "gen-alpha"],
  },
  {
    slug: "cinema", term: "Cinema", pron: "SIN-uh-muh", pos: "noun", cat: "slang",
    year: 2023, pop: 60, trend: 14, status: "rising",
    def: "Used of any moment with unearned cinematic weight, usually mundane footage that happens to be beautifully composed. Absolute cinema is the full form.",
    eli: "Calling something as dramatic and beautiful as a film, even when it is just ordinary life.",
    org: "From a widely shared image of Martin Scorsese with his arms raised, captioned absolute cinema, which became the standard reaction to accidentally dramatic footage in 2023.",
    ex: ["Security camera footage of a cat at 4am. Absolute cinema.", "The lighting on that goal replay is cinema."],
    rel: ["peak", "goes-hard", "aura"], tags: ["film", "praise", "meme"],
  },
  {
    slug: "diabolical", term: "Diabolical", pron: "dy-uh-BOL-ik-ul", pos: "adjective", cat: "slang",
    year: 2022, pop: 53, trend: 7, status: "rising",
    def: "Outrageous in a way that provokes admiration as much as disapproval, said of a joke, an insult or a decision that went much too far.",
    eli: "So bold and mean that you have to laugh even though you should not.",
    org: "Long-standing British English for wicked or terrible, reweighted by online use so that it now usually implies grudging respect.",
    ex: ["Replying with the receipt from 2016 is diabolical work.", "Diabolical pricing on those tickets."],
    rel: ["crazy-work", "shade", "unserious"], tags: ["humour", "british", "judgement"],
  },
  {
    slug: "crazy-work", term: "Crazy work", pron: "KRAY-zee wurk", pos: "phrase", cat: "slang",
    year: 2023, pop: 51, trend: 11, status: "rising",
    def: "An appraisal of an audacious act, sitting between admiration and disbelief. Wild work and diabolical work follow the same pattern.",
    eli: "A way of saying that was a bold and slightly outrageous thing to do.",
    org: "Black Twitter and TikTok comment sections around 2023, where work names the deed and the adjective supplies the verdict.",
    ex: ["Texting your ex on their birthday is crazy work.", "Crazy work from the person who scheduled this at 8am."],
    rel: ["diabolical", "unserious", "side-eye"], tags: ["judgement", "comments", "twitter"],
  },
  {
    slug: "iconic", term: "Iconic", pron: "eye-KON-ik", pos: "adjective", cat: "slang",
    year: 2014, pop: 64, trend: -5, status: "mainstream",
    def: "Memorable and definitive. Online the bar is set very low on purpose, so that trivial moments can be described in the vocabulary of cultural landmarks.",
    eli: "Calling something famous and unforgettable, often as a joke about something small.",
    org: "Standard English inflated by fan and stan vocabulary, where superlatives are the baseline register rather than the exception.",
    ex: ["Her one line in that scene is iconic.", "Iconic behaviour from a man buying six identical shirts."],
    rel: ["legend", "slay", "peak"], tags: ["praise", "fandom", "hyperbole"],
  },
  {
    slug: "legend", term: "Legend", pron: "LEJ-und", pos: "noun", cat: "slang",
    year: 2013, pop: 58, trend: -2, status: "classic",
    def: "Someone who has done a small favour or an admirable minor thing. The scale of the praise is deliberately out of proportion to the deed.",
    eli: "A big thank-you for a small favour.",
    org: "British and Australian English, where absolute legend has long been a standard compliment. Carried worldwide by football and gaming communities.",
    ex: ["Saved me a seat. Absolute legend.", "Whoever refilled the kettle is a legend."],
    rel: ["iconic", "goat", "based"], tags: ["praise", "british", "gratitude"],
  },
  {
    slug: "menty-b", term: "Menty B", pron: "MEN-tee bee", pos: "noun", cat: "slang",
    year: 2022, pop: 45, trend: 6, status: "rising",
    def: "A deliberately trivialising nickname for a mental breakdown, used to acknowledge distress while keeping the register light.",
    eli: "A joking short name for a meltdown, used so it feels less heavy to talk about.",
    org: "TikTok around 2022, part of a wider pattern of shortening clinical language into cute forms as a way of making it discussable.",
    ex: ["Small menty B in the stairwell, back in five.", "Scheduled my menty B for after the deadline."],
    rel: ["crash-out", "delulu", "brainrot"], tags: ["mental-health", "tiktok", "humour"],
  },
  {
    slug: "chat-is-this-real", term: "Chat, is this real?", pron: "chat iz this reel", pos: "phrase", cat: "slang",
    year: 2023, pop: 55, trend: 15, status: "rising",
    def: "An address to an imaginary livestream audience, used offline or in text to express disbelief. Treats everyday life as though it were being broadcast.",
    eli: "Talking to an imaginary stream chat, as if your life were being watched live.",
    org: "Twitch vocabulary, where streamers genuinely ask chat for confirmation. Gen Alpha adopted the address as a general exclamation from 2023.",
    ex: ["Chat, is this real? They cancelled the last train.", "Started saying chat out loud in an empty room. Concerning."],
    rel: ["npc", "brainrot", "aura"], tags: ["twitch", "gen-alpha", "disbelief"],
  },
  {
    slug: "no-notes", term: "No notes", pron: "noh nohts", pos: "phrase", cat: "slang",
    year: 2021, pop: 50, trend: 3, status: "mainstream",
    def: "Complete approval: there is nothing you would change. Borrowed from the editorial practice of returning feedback as notes.",
    eli: "A way of saying it was perfect and you would not change anything.",
    org: "Film and television production vocabulary, where notes are mandatory revisions. Twitter adopted the negative form as the highest available praise.",
    ex: ["Perfect sandwich. No notes.", "The whole set list, no notes."],
    rel: ["understood-the-assignment", "ate", "peak"], tags: ["praise", "film", "twitter"],
  },
  {
    slug: "nonchalant", term: "Nonchalant", pron: "non-shuh-LAHNT", pos: "adjective", cat: "slang",
    year: 2024, pop: 56, trend: 19, status: "rising",
    def: "Studied indifference presented as an ideal, particularly in dating. The nonchalant man became a 2024 archetype: unbothered, and possibly just uninterested.",
    eli: "Acting like you do not care about anything, on purpose, because it seems cool.",
    org: "The ordinary English word, elevated into an aspirational personality type by TikTok in 2024 and immediately parodied as a cover for emotional absence.",
    ex: ["He is not nonchalant, he is just not replying.", "Nonchalant until the football starts."],
    rel: ["aura", "ick", "situationship"], tags: ["dating", "tiktok", "persona"],
  },
  {
    slug: "sigma", term: "Sigma", pron: "SIG-muh", pos: "noun", cat: "slang",
    year: 2021, pop: 63, trend: -8, status: "fading",
    def: "A supposed personality type: successful but solitary, outside the usual social hierarchy. Almost always used ironically by the people who spread it most.",
    eli: "A made-up personality type meaning someone cool who does things alone. Mostly used as a joke now.",
    org: "Invented in 2010s manosphere writing as an addition to the alpha and beta scheme, which has no basis in animal behaviour research. Gen Alpha adopted it purely as a punchline.",
    ex: ["Eating lunch alone in the car. Sigma behaviour.", "What the sigma is going on in this group chat?"],
    rel: ["aura", "npc", "brainrot"], tags: ["gen-alpha", "irony", "personality"],
  },
  {
    slug: "skibidi", term: "Skibidi", pron: "SKIB-id-ee", pos: "adjective", cat: "slang",
    year: 2023, pop: 65, trend: -14, status: "fading",
    def: "A semantically empty intensifier that can mean good, bad or strange depending entirely on delivery. Its lack of meaning is the point.",
    eli: "A silly word with no fixed meaning, used because it sounds funny.",
    org: "From the Skibidi Toilet YouTube series that began in 2023 and became the defining Gen Alpha reference. Adults using it earnestly became a joke in itself.",
    ex: ["That was some skibidi behaviour.", "He said skibidi in a meeting and the room died."],
    rel: ["brainrot", "sigma", "ohio"], tags: ["gen-alpha", "brainrot", "youtube"],
  },
  {
    slug: "ohio", term: "Ohio", pron: "oh-HY-oh", pos: "adjective", cat: "slang",
    year: 2022, pop: 54, trend: -11, status: "fading",
    def: "Marks something as surreal or wrong, from a meme tradition treating the US state as a place where reality malfunctions. Only in Ohio is the standard caption.",
    eli: "A joking way of saying something is weird, as if it could only happen in one strange place.",
    org: "An imageboard joke of the mid-2010s that Gen Alpha adopted around 2022. The state itself is incidental; it simply became the agreed name for absurdity.",
    ex: ["A bus full of geese. Only in Ohio.", "This whole week has been extremely Ohio."],
    rel: ["skibidi", "brainrot", "cursed-image"], tags: ["gen-alpha", "surreal", "meme"],
  },
  {
    slug: "fanum-tax", term: "Fanum tax", pron: "FAY-num taks", pos: "noun", cat: "slang",
    year: 2023, pop: 48, trend: -13, status: "fading",
    def: "The act of taking a portion of a friend's food without asking, framed as a levy rather than a theft.",
    eli: "Taking a bit of your friend's food as if you were allowed to.",
    org: "Named after the streamer Fanum, who did it repeatedly on stream in 2023. Spread through the same Gen Alpha vocabulary wave as skibidi and rizz.",
    ex: ["He fanum taxed half my chips.", "Leave it unattended and expect the fanum tax."],
    rel: ["skibidi", "rizz", "aura"], tags: ["gen-alpha", "streaming", "food"],
  },
  {
    slug: "mewing", term: "Mewing", pron: "MYOO-ing", pos: "verb", cat: "slang",
    year: 2019, pop: 59, trend: 4, status: "mainstream",
    def: "Holding the tongue against the roof of the mouth in the belief that it sharpens the jawline. Online it doubles as a gesture meaning I am not speaking.",
    eli: "Pressing your tongue to the roof of your mouth to try to change your jaw shape. Also a hand signal meaning stay quiet.",
    org: "Named after orthodontist John Mew, whose claims are not supported by clinical evidence. Spread through looksmaxxing forums and then to schools via TikTok.",
    ex: ["Cannot answer, I am mewing.", "The mewing hand signal has taken over every classroom."],
    rel: ["looksmaxxing", "aura"], tags: ["appearance", "tiktok", "gen-alpha"],
  },
  {
    slug: "looksmaxxing", term: "Looksmaxxing", pron: "LOOKS-maks-ing", pos: "verb", cat: "slang",
    year: 2018, pop: 57, trend: 9, status: "rising",
    def: "Systematically optimising one's appearance, treating attractiveness as a stat to be raised. Ranges from grooming advice to genuinely harmful practice.",
    eli: "Trying to improve your looks in a very organised way, like levelling up a character.",
    org: "Manosphere and incel forums of the 2010s, where maxxing came from game vocabulary for maximising a stat. TikTok carried a softened version to a mass teenage audience after 2022.",
    ex: ["The whole channel is looksmaxxing content with a skincare label.", "Looksmaxxing is just grooming with a spreadsheet."],
    rel: ["mewing", "maxxing", "aura"], tags: ["appearance", "forums", "tiktok"],
  },
  {
    slug: "delusionship", term: "Delusionship", pron: "di-LOO-zhun-ship", pos: "noun", cat: "slang",
    year: 2023, pop: 42, trend: 8, status: "rising",
    def: "A relationship that exists mainly in one person's imagination, built from minimal evidence and considerable hope.",
    eli: "A relationship that is mostly happening in your head.",
    org: "A blend of delusion and relationship, coined on TikTok around 2023 alongside delulu as the situationship vocabulary continued to subdivide.",
    ex: ["Two liked stories and a delusionship was born.", "It is not a situationship, it is a delusionship."],
    rel: ["delulu", "situationship", "parasocial"], tags: ["dating", "tiktok", "humour"],
  },
  {
    slug: "beige-flag", term: "Beige flag", pron: "bayzh flag", pos: "noun", cat: "slang",
    year: 2023, pop: 53, trend: -7, status: "mainstream",
    def: "A quirk in a partner that is neither a warning nor a virtue, just distinctive. Completes the set alongside red and green flags.",
    eli: "A habit someone has that is not good or bad, just a bit odd.",
    org: "Coined on TikTok in 2023 by extending the existing red flag and green flag scheme to cover the large middle ground neither term described.",
    ex: ["His beige flag is narrating what the dog is thinking.", "Beige flag: alphabetises the spice rack, uses none of it."],
    rel: ["red-flag", "green-flag", "ick"], tags: ["dating", "tiktok", "relationships"],
  },
  {
    slug: "red-flag", term: "Red flag", pron: "red flag", pos: "noun", cat: "slang",
    year: 2020, pop: 79, trend: -3, status: "mainstream",
    def: "A warning sign about a person's character. Online the threshold has drifted so far that trivial preferences are now routinely listed as red flags.",
    eli: "A warning sign that someone might be trouble.",
    org: "Standard English for a danger signal, absorbed into dating vocabulary and then into a 2021 emoji format that reduced it to a punchline.",
    ex: ["Refuses to tip. Red flag.", "The red flag emoji format ruined the actual concept."],
    rel: ["green-flag", "beige-flag", "ick"], tags: ["dating", "warning", "relationships"],
  },
  {
    slug: "green-flag", term: "Green flag", pron: "green flag", pos: "noun", cat: "slang",
    year: 2021, pop: 66, trend: 2, status: "mainstream",
    def: "A sign of good character, coined as the necessary counterpart once red flags dominated the conversation.",
    eli: "A sign that someone is probably good news.",
    org: "Emerged on TikTok around 2021 in explicit reaction to red-flag content, as users noted that only listing warnings produced a distorted picture.",
    ex: ["Texts his mum back immediately. Green flag.", "Green flag energy: admits when he does not know something."],
    rel: ["red-flag", "beige-flag", "situationship"], tags: ["dating", "tiktok", "relationships"],
  },
  {
    slug: "girl-dinner", term: "Girl dinner", pron: "gurl DIN-ur", pos: "noun", cat: "slang",
    year: 2023, pop: 55, trend: -10, status: "fading",
    def: "A meal assembled from whatever is available rather than cooked, typically small unrelated items eaten standing up. Named affectionately rather than critically.",
    eli: "A dinner made of snacks and leftovers instead of a proper cooked meal.",
    org: "Coined on TikTok in 2023 in a video listing bread, cheese and pickles as a complete meal. Widely praised and then widely criticised for aestheticising undereating.",
    ex: ["Girl dinner: three olives, some crisps and half a lemon.", "Every evening this week has been girl dinner."],
    rel: ["girl-math", "soft-life", "clean-girl"], tags: ["food", "tiktok", "2023"],
  },
  {
    slug: "roman-empire", term: "Roman Empire", pron: "ROH-mun EM-py-ur", pos: "noun", cat: "slang",
    year: 2023, pop: 52, trend: -12, status: "fading",
    def: "A subject someone thinks about far more often than anyone expects. From a viral prompt asking men how often they think about ancient Rome.",
    eli: "The thing you think about all the time for no clear reason.",
    org: "A TikTok trend in September 2023 in which women asked their partners how often they thought about the Roman Empire, and were startled by the answers.",
    ex: ["The Betamax format war is my Roman Empire.", "Ask him about his Roman Empire and clear your afternoon."],
    rel: ["rent-free", "lore", "brainrot"], tags: ["tiktok", "obsession", "2023"],
  },
  {
    slug: "brat", term: "Brat", pron: "brat", pos: "adjective", cat: "slang",
    year: 2024, pop: 61, trend: -9, status: "fading",
    def: "A deliberately messy, confident and unpolished mode of self-presentation, defined against the tidy aspirational aesthetics that preceded it.",
    eli: "Being messy and confident on purpose instead of trying to look perfect.",
    org: "Named by Charli XCX's 2024 album Brat, whose lime-green cover became a whole summer's visual shorthand before being absorbed into advertising.",
    ex: ["A brat summer, allegedly.", "That lime green went from album cover to everything in six weeks."],
    rel: ["demure", "aesthetic", "era"], tags: ["music", "2024", "aesthetic"],
  },
  {
    slug: "demure", term: "Demure", pron: "di-MYOOR", pos: "adjective", cat: "slang",
    year: 2024, pop: 50, trend: -16, status: "fading",
    def: "Restrained and considerate, used ironically in the formula very demure, very mindful, very cutesy to describe behaviour that is none of those things.",
    eli: "A joking way of calling something polite and modest, usually when it is the opposite.",
    org: "From creator Jools Lebron's August 2024 videos describing workplace presentation. It saturated the internet within a fortnight and was exhausted almost as quickly.",
    ex: ["Very demure, very mindful, very late.", "Answering emails at midnight is not demure."],
    rel: ["brat", "unserious", "its-giving"], tags: ["tiktok", "irony", "2024"],
  },
  {
    slug: "mother", term: "Mother", pron: "MUTH-ur", pos: "noun", cat: "slang",
    year: 2022, pop: 51, trend: -6, status: "mainstream",
    def: "An honorific for a woman, usually a performer, considered to have set the standard others follow. Mothering is the act of doing so.",
    eli: "A way of praising a performer as the one everyone else copies.",
    org: "Ballroom culture, where a house mother leads and mentors. Stan Twitter adopted it as a superlative in the early 2020s and used it into near-meaninglessness.",
    ex: ["Mother is mothering on this record.", "She walked out and the whole arena said mother."],
    rel: ["slay", "iconic", "stan"], tags: ["ballroom", "fandom", "praise"],
  },
  {
    slug: "gagged", term: "Gagged", pron: "gagd", pos: "adjective", cat: "slang",
    year: 2019, pop: 44, trend: -2, status: "niche",
    def: "Rendered speechless by something impressive or shocking. To gag is to have that reaction; to gag someone is to cause it.",
    eli: "So shocked or impressed that you cannot speak.",
    org: "Ballroom and drag vocabulary, carried into wider use by drag television. The image is of being stopped mid-breath.",
    ex: ["The reveal gagged the entire room.", "Gagged, floored, unwell."],
    rel: ["slay", "snatched", "screaming"], tags: ["drag", "ballroom", "reaction"],
  },
  {
    slug: "snatched", term: "Snatched", pron: "snacht", pos: "adjective", cat: "slang",
    year: 2016, pop: 47, trend: -5, status: "fading",
    def: "Sharply and flatteringly styled, particularly of a silhouette, waistline or hairline. The older on point covers similar ground.",
    eli: "Looking really sharp and well put together.",
    org: "Black queer and ballroom vocabulary, where snatched described a wig sitting perfectly. Mainstream beauty marketing adopted it around 2016.",
    ex: ["Waist snatched, timeline unbothered.", "That tailoring is snatched."],
    rel: ["gagged", "serving", "drip"], tags: ["fashion", "ballroom", "beauty"],
  },
  {
    slug: "pick-me", term: "Pick me", pron: "pik mee", pos: "noun", cat: "slang",
    year: 2016, pop: 58, trend: 3, status: "mainstream",
    def: "Someone who seeks approval by distancing themselves from their own group, typically by claiming to be unlike other people in it.",
    eli: "Someone who puts down people like themselves so that others will like them more.",
    org: "From Black Twitter in the mid-2010s, originally the hashtag Tweet Like a Pick Me. Now used broadly, and often loosely, in relationship discourse.",
    ex: ["Not like other people is the whole pick me script.", "Calling every disagreement pick me behaviour is lazy."],
    rel: ["performative", "cringe"], tags: ["twitter", "identity", "criticism"],
  },
  {
    slug: "performative", term: "Performative", pron: "pur-FOR-muh-tiv", pos: "adjective", cat: "slang",
    year: 2020, pop: 62, trend: 13, status: "rising",
    def: "Done for an audience rather than from conviction. The performative male became a 2025 archetype: a set of tastes displayed as evidence of character.",
    eli: "Doing something so people see you doing it, not because you really mean it.",
    org: "Borrowed from linguistics, where a performative utterance does something by being said. Online it narrowed to mean insincere display, and spawned 2025 contests judging the archetype.",
    ex: ["Tote bag, obscure novel, single earphone. Deeply performative.", "Performative allyship is worse than silence, allegedly."],
    rel: ["pick-me", "clout", "cringe"], tags: ["identity", "criticism", "2025"],
  },
  {
    slug: "soft-life", term: "Soft life", pron: "soft lyfe", pos: "noun", cat: "slang",
    year: 2021, pop: 49, trend: 4, status: "mainstream",
    def: "A deliberately chosen life of ease and low stress, framed as a rejection of struggle as a source of virtue.",
    eli: "Choosing a calm, comfortable life instead of one full of hard work and stress.",
    org: "Popularised by Nigerian and diaspora creators on Instagram around 2021, explicitly answering the expectation that resilience should be endless.",
    ex: ["Soft life means never checking email before coffee.", "Entering my soft life era, budget permitting."],
    rel: ["villain-era", "hustle-culture", "girl-dinner"], tags: ["lifestyle", "instagram", "wellbeing"],
  },
  {
    slug: "cook", term: "Cook", pron: "kook", pos: "verb", cat: "slang",
    year: 2022, pop: 69, trend: 7, status: "rising",
    def: "To perform impressively, especially when given freedom to work. Let him cook asks that someone be left alone; he is not cooking means it is going badly.",
    eli: "Doing something really well. Let him cook means give them space to finish.",
    org: "Kitchen metaphor from hip-hop and sports commentary, generalised through Twitch and Twitter around 2022. The negative form arrived almost immediately.",
    ex: ["Let him cook, the second half is the good part.", "Six minutes in and he is not cooking."],
    rel: ["goes-hard", "peak", "cinema"], tags: ["praise", "twitch", "sports"],
  },
  {
    slug: "yapping-rights", term: "Yapping rights", pron: "YAP-ing rytes", pos: "noun", cat: "slang",
    year: 2024, pop: 34, trend: 12, status: "rising",
    def: "The informal entitlement to talk at length about a subject, granted by having been right about it before.",
    eli: "Having earned the right to go on about something because you were right the first time.",
    org: "Formed from yap, which became general vocabulary in 2023. The construction follows bragging rights and appeared once yapping had become a named activity.",
    ex: ["Called it in January, so I have yapping rights.", "Yapping rights expire faster than people think."],
    rel: ["yap", "receipts", "unserious"], tags: ["talking", "2024", "humour"],
  },
  {
    slug: "ragebait-pilled", term: "Ragebait-pilled", pron: "RAYJ-bayt pild", pos: "adjective", cat: "slang",
    year: 2024, pop: 31, trend: 8, status: "rising",
    def: "Describing someone whose posting has been reshaped by discovering that provocation outperforms substance.",
    eli: "Someone who learned that annoying people gets more attention, and now posts that way on purpose.",
    org: "A compound of ragebait and the -pilled suffix, both established by 2022. It names the moment a creator's incentives visibly change.",
    ex: ["He went ragebait-pilled around post four hundred.", "You can usually date the exact week it happened."],
    rel: ["ragebait", "pilled", "clout"], tags: ["posting", "incentives", "criticism"],
  },
  {
    slug: "side-quest", term: "Side quest", pron: "syde kwest", pos: "noun", cat: "slang",
    year: 2022, pop: 52, trend: 9, status: "rising",
    def: "An unplanned detour from what you meant to do, framed as an optional mission rather than a waste of an afternoon.",
    eli: "A random detour from your plans, described like an extra mission in a game.",
    org: "Game design vocabulary applied to daily life around 2022, part of the same habit that produced main character and NPC as descriptions of real behaviour.",
    ex: ["Went out for milk, came back four hours later. Side quest.", "The side quest is usually better than the main one."],
    rel: ["main-character", "npc", "arc"], tags: ["gaming", "identity", "detour"],
  },
  {
    slug: "clocked", term: "Clocked", pron: "klokt", pos: "verb", cat: "slang",
    year: 2018, pop: 48, trend: 4, status: "mainstream",
    def: "Noticed and correctly identified, particularly something the subject hoped would pass unremarked.",
    eli: "Spotted straight away, especially something someone hoped nobody would notice.",
    org: "Ballroom and drag vocabulary, where being clocked meant being read accurately. Wider adoption from around 2018 broadened it to any accurate perception.",
    ex: ["Clocked the stock photo immediately.", "She clocked the lie in about a second."],
    rel: ["read", "receipts", "caught-in-4k"], tags: ["ballroom", "perception", "drag"],
  },
  {
    slug: "ate-down", term: "Ate down", pron: "ayt down", pos: "phrase", cat: "slang",
    year: 2022, pop: 33, trend: 5, status: "niche",
    def: "An intensified form of ate, used when a performance was not merely good but decisive.",
    eli: "An even stronger way of saying someone did something brilliantly.",
    org: "Black queer vocabulary, where intensifiers stack productively. The pattern of adding a particle to strengthen an existing term is long established in the same register.",
    ex: ["She ate down and the crowd knew it.", "Ate, ate down, ate and left no crumbs: three grades of the same verdict."],
    rel: ["ate", "slay", "mother"], tags: ["praise", "ballroom", "intensifier"],
  },
  {
    slug: "unc", term: "Unc", pron: "unk", pos: "noun", cat: "slang",
    year: 2022, pop: 52, trend: 10, status: "rising",
    def: "An older man behaving in a dated or overly try-hard way, from uncle. Acting like an unc means clinging to outdated slang, music or opinions.",
    eli: "A joking way of calling an older guy out of touch, like an uncle trying too hard to seem current.",
    org: "African American Vernacular English, spread through basketball commentary and TikTok in 2022 as a gentler generational jab than boomer.",
    ex: ["Using slang from 2015 unironically is such unc behaviour.", "He is turning into an unc and he knows it."],
    rel: ["cooked", "npc", "based"], tags: ["age", "aave", "generational"],
  },
  {
    slug: "cooked", term: "Cooked", pron: "kookt", pos: "adjective", cat: "slang",
    year: 2023, pop: 71, trend: 20, status: "rising",
    def: "Finished, doomed, or beyond saving. Applied to a person, a plan or an entire situation with no hope of recovery.",
    eli: "A way of saying something is completely over or ruined, with no way to fix it.",
    org: "Gaming and sports commentary of the early 2020s, generalised on TikTok by 2023 as a blunter alternative to it's so over.",
    ex: ["Forgot the presentation is today. I am cooked.", "Missed the last train, we are cooked."],
    rel: ["its-so-over", "crash-out", "unc"], tags: ["defeat", "tiktok", "hyperbole"],
  },
  {
    slug: "bed-rotting", term: "Bed rotting", pron: "bed ROT-ing", pos: "noun", cat: "slang",
    year: 2023, pop: 49, trend: -8, status: "fading",
    def: "Spending an extended period in bed doing nothing productive, framed as a deliberate rest practice rather than a symptom of low mood.",
    eli: "Staying in bed all day on purpose, doing nothing, and calling it self-care instead of laziness.",
    org: "Coined on TikTok in 2023 as part of a wave of rebranding rest and inactivity as wellness practices, alongside soft life and quiet quitting.",
    ex: ["Weekend plans: bed rotting, nothing else.", "Bed rotting sounds better than what it actually is."],
    rel: ["soft-life", "doomscrolling", "menty-b"], tags: ["wellbeing", "tiktok", "rest"],
  },
  {
    slug: "six-seven", term: "6 7", pron: "siks SEV-un", pos: "interjection", cat: "slang",
    year: 2025, pop: 62, trend: 30, status: "rising",
    def: "A semantically empty catchphrase said with a hand-wobbling gesture, functioning purely as a callback and reaction, with no fixed meaning attached to the numbers themselves.",
    eli: "Two numbers people say as a joke, along with a hand-wiggling motion, mostly just because it caught on and became funny to repeat.",
    org: "Spread among younger schoolchildren in 2025 from a rap lyric referencing the numbers, then detached from its source entirely to become a pure reaction sound, echoing skibidi's earlier trajectory.",
    ex: ["He said 6 7 in the middle of class for no reason.", "The whole playground is doing the 6 7 hand thing."],
    rel: ["skibidi", "ohio", "brainrot"], tags: ["gen-alpha", "brainrot", "2025"],
  },
  {
    slug: "gyat", term: "Gyat", pron: "gee-AT", pos: "interjection", cat: "slang",
    year: 2022, pop: 60, trend: -5, status: "fading",
    def: "An exclamation of surprise at someone's physical appearance, typically shouted rather than written, functioning as a more explicit cousin of daaamn.",
    eli: "A loud exclamation people shout when they see someone they think looks good.",
    org: "A stylised elongation of the older exclamation goddamn, popularised by streamers reacting to gaming clips before spreading to general Gen Alpha slang around 2022.",
    ex: ["Someone yelled gyat across the cafeteria and got sent to the office.", "Gyat is mostly just a noise at this point."],
    rel: ["rizz", "sigma", "skibidi"], tags: ["gen-alpha", "exclamation", "streaming"],
  },
];
