import type { RawTerm } from "../types";

export const socialTerms: RawTerm[] = [
  {
    slug: "algorithm", term: "The algorithm", pron: "thee AL-guh-rith-um", pos: "noun", cat: "social",
    year: 2016, pop: 91, trend: 2, status: "mainstream",
    def: "The recommendation system that decides what a feed shows, treated in everyday speech as a single wilful entity with moods and preferences.",
    eli: "The computer program that picks what you see online. People talk about it like a person who has to be kept happy.",
    org: "Became folk vocabulary after 2016, when chronological feeds were replaced by ranked ones and creators began reasoning about an invisible audience of one.",
    ex: ["Posting at eight because the algorithm apparently prefers it.", "The algorithm buried it and nobody can tell me why."],
    rel: ["fyp", "shadowban", "algospeak"], tags: ["platforms", "ranking", "creators"],
  },
  {
    slug: "algospeak", term: "Algospeak", pron: "AL-goh-speek", pos: "noun", cat: "social",
    year: 2022, pop: 65, trend: 16, status: "rising",
    def: "Deliberately altered vocabulary used to discuss moderated topics without triggering automated enforcement, such as writing \"unalive\" in place of a banned word.",
    eli: "Changing words on purpose so a filter does not block your post, like spelling something wrong so the computer misses it.",
    org: "Named in reporting around 2022, though the practice is much older. Substitutions spread so widely that some now appear in ordinary speech offline.",
    ex: ["Half the comments are algospeak and the other half are confused.", "Children use algospeak at school now, which was not the plan."],
    rel: ["shadowban", "algorithm", "fyp"], tags: ["moderation", "language-change", "tiktok"],
  },
  {
    slug: "deinfluencing", term: "Deinfluencing", pron: "dee-IN-floo-un-sing", pos: "noun", cat: "social",
    year: 2023, pop: 57, trend: -6, status: "niche",
    def: "Content that advises viewers against buying popular products. Sometimes genuine consumer scepticism, sometimes a rebranded route to recommending an alternative.",
    eli: "Videos telling you not to buy something popular, either to be honest or to sell you a different thing instead.",
    org: "Trended on TikTok in early 2023 as a response to relentless product recommendation, then was quickly absorbed by the same marketing it criticised.",
    ex: ["The deinfluencing video ended with a discount code, which rather made the point.", "Genuine deinfluencing saved me two hundred pounds this year."],
    rel: ["loud-budgeting", "algorithm", "thirst-trap"], tags: ["consumer", "tiktok", "marketing"],
  },
  {
    slug: "doomscrolling", term: "Doomscrolling", pron: "DOOM-skroh-ling", pos: "noun", cat: "social",
    year: 2018, pop: 79, trend: -3, status: "mainstream",
    def: "Compulsively reading distressing news long past the point of usefulness, driven by the feeling that stopping would mean missing something worse.",
    eli: "Scrolling through bad news for ages even though it makes you feel awful, because you cannot make yourself stop.",
    org: "Coined on Twitter around 2018 and adopted widely in 2020, when infinite feeds and a continuous news cycle made the behaviour close to universal.",
    ex: ["Two hours of doomscrolling and no new information.", "I moved the phone to the other room to stop doomscrolling at midnight."],
    rel: ["brainrot", "touch-grass", "chronically-online"], tags: ["attention", "news", "wellbeing"],
  },
  {
    slug: "fyp", term: "FYP", pron: "ef-why-PEE", pos: "abbreviation", cat: "social",
    year: 2018, pop: 88, trend: 3, status: "mainstream",
    def: "TikTok's For You Page, the algorithmically assembled main feed. Used generally for any recommendation feed that seems to know the viewer unusually well.",
    eli: "The main TikTok feed that guesses what you want to watch. People say it is spying when it guesses right.",
    org: "Named by TikTok at launch in 2018. Users tagged posts with #fyp hoping to be promoted, which is largely superstition but became a ritual anyway.",
    ex: ["My FYP has decided I am a woodworker now.", "Three videos about the same obscure hobby. The FYP knows."],
    rel: ["algorithm", "shadowban", "doomscrolling"], tags: ["tiktok", "feeds", "recommendation"],
  },
  {
    slug: "parasocial", term: "Parasocial", pron: "pa-ruh-SOH-shul", pos: "adjective", cat: "social",
    year: 1956, pop: 74, trend: 10, status: "mainstream",
    def: "Describing a one-sided bond in which an audience member feels they know a creator personally, while the creator has no awareness of them at all.",
    eli: "Feeling like a person you watch online is your friend, even though they have never heard of you.",
    org: "Coined by sociologists Horton and Wohl in 1956 to describe television audiences. Streaming and daily vlogs made the idea common vocabulary after 2020.",
    ex: ["Streaming makes parasocial attachment almost the business model.", "I had to admit the feeling was parasocial and log off."],
    rel: ["stan", "glazing", "chronically-online"], tags: ["psychology", "streaming", "creators"],
  },
  {
    slug: "shadowban", term: "Shadowban", pron: "SHAD-oh-ban", pos: "noun", cat: "social",
    year: 1986, pop: 70, trend: 6, status: "mainstream",
    def: "Suppression of an account's reach without notification, so the user continues posting normally while their audience quietly disappears.",
    eli: "When a site hides your posts from other people but does not tell you, so you keep posting to nobody.",
    org: "Used on bulletin boards in the 1980s as a quiet moderation tool. Platforms usually deny doing it; reduced-distribution systems make the distinction largely academic.",
    ex: ["Views dropped 95 percent overnight and support says nothing is wrong.", "Every creator believes in shadowbans and every platform denies them."],
    rel: ["algorithm", "algospeak", "fyp"], tags: ["moderation", "reach", "platforms"],
  },
  {
    slug: "soft-launch", term: "Soft launch", pron: "soft lawnch", pos: "noun", cat: "social",
    year: 2020, pop: 73, trend: 4, status: "mainstream",
    def: "Hinting at a new relationship online without identifying the person, typically through a hand, a shoulder or a second coffee cup in frame.",
    eli: "Posting a hint that you are dating someone without showing their face, so only close friends work it out.",
    org: "Borrowed from product marketing and applied to relationships on Instagram around 2020, as a hedge against having to announce a breakup later.",
    ex: ["Two elbows and a sunset. Classic soft launch.", "She soft launched in March and hard launched in July."],
    rel: ["situationship", "thirst-trap", "parasocial"], tags: ["instagram", "relationships"],
  },
  {
    slug: "thirst-trap", term: "Thirst trap", pron: "thurst trap", pos: "noun", cat: "social",
    year: 2013, pop: 71, trend: -2, status: "mainstream",
    def: "A photograph posted primarily to attract admiring attention, presented under a casual pretext such as a caption about the weather.",
    eli: "A picture posted to get compliments, with an excuse in the caption so it looks accidental.",
    org: "Formed from \"thirsty\", meaning desperate for attention, and current on Twitter and Instagram by 2013.",
    ex: ["The caption is about the gym. The photo is a thirst trap.", "Posted a thirst trap, got career advice from an aunt."],
    rel: ["soft-launch", "glazing", "algorithm"], tags: ["instagram", "attention"],
  },
  {
    slug: "influencer", term: "Influencer", pron: "IN-floo-un-sur", pos: "noun", cat: "social",
    year: 2015, pop: 82, trend: -2, status: "mainstream",
    def: "Someone whose audience is their product, monetised through brand partnerships. Nano, micro and macro tiers describe audience size, with engagement often inversely related.",
    eli: "Someone with a big online following who gets paid to recommend things.",
    org: "Marketing vocabulary that became a job title around 2015. Disclosure rules from the FTC and equivalent regulators arrived several years after the practice.",
    ex: ["Micro-influencers convert better than the famous ones.", "Undisclosed ads are the enforcement problem, not the ads."],
    rel: ["brand-deal", "creator-economy", "deinfluencing"], tags: ["marketing", "career", "disclosure"],
  },
  {
    slug: "brand-deal", term: "Brand deal", pron: "brand deel", pos: "noun", cat: "social",
    year: 2016, pop: 63, trend: 0, status: "mainstream",
    def: "A paid arrangement to feature a product in content. Legally required to be disclosed in most jurisdictions, and frequently disclosed in the least visible way possible.",
    eli: "When a company pays a creator to mention their product in a video or post.",
    org: "Formalised as the creator economy professionalised after 2016. Disclosure standards vary, and buried hashtags remain the most common form of technical compliance.",
    ex: ["The disclosure was the ninth hashtag in the caption.", "Brand deals fund most of the content people watch free."],
    rel: ["influencer", "creator-economy", "deinfluencing"], tags: ["money", "advertising", "disclosure"],
  },
  {
    slug: "creator-economy", term: "Creator economy", pron: "kree-AY-tur i-KON-uh-mee", pos: "noun", cat: "social",
    year: 2020, pop: 60, trend: 3, status: "mainstream",
    def: "The market in which individuals earn directly from audiences through subscriptions, tips and sponsorship rather than through employers.",
    eli: "People making a living directly from their audience instead of from a company.",
    org: "Named around 2020 as subscription and tipping tools matured. The economics are heavily concentrated: a small fraction of creators earn the large majority of the money.",
    ex: ["The creator economy is a power law wearing a friendly name.", "Platform dependency is the structural risk nobody prices in."],
    rel: ["influencer", "brand-deal", "streamer"], tags: ["economics", "labour", "platforms"],
  },
  {
    slug: "grwm", term: "GRWM", pron: "jee-ar-dub-em", pos: "abbreviation", cat: "social",
    year: 2018, pop: 64, trend: 4, status: "mainstream",
    def: "Get ready with me: a video in which a creator prepares to go out while talking, so the routine provides structure for the conversation.",
    eli: "A video where someone gets ready while chatting to the camera.",
    org: "A YouTube beauty format that TikTok compressed and generalised. The genius of it is that the task supplies pacing, so the talking never has to justify itself.",
    ex: ["GRWM for a wedding I am dreading.", "The makeup is the excuse; the monologue is the content."],
    rel: ["fit-check", "pov-format", "influencer"], tags: ["format", "beauty", "tiktok"],
  },
  {
    slug: "pov-format", term: "POV", pron: "pee-oh-VEE", pos: "abbreviation", cat: "social",
    year: 2019, pop: 71, trend: -3, status: "mainstream",
    def: "Point of view. Labels a video that casts the viewer as a participant in a scenario, though it is frequently used for videos with no point of view at all.",
    eli: "A video that puts you in a scene as if it were happening to you.",
    org: "Borrowed from film vocabulary, adopted by TikTok around 2019. Its misuse became a running joke, since most POV videos are simply captioned scenes.",
    ex: ["POV: you are the only one who read the document.", "Half of POV videos are not POV anything."],
    rel: ["grwm", "duet", "going-viral"], tags: ["format", "tiktok", "video"],
  },
  {
    slug: "duet", term: "Duet", pron: "doo-ET", pos: "noun", cat: "social",
    year: 2019, pop: 55, trend: 0, status: "mainstream",
    def: "A TikTok feature placing your video beside someone else's, playing in sync. Stitch is the related feature that splices a clip into the start of your own.",
    eli: "A TikTok feature that puts your video next to someone else's so they play together.",
    org: "Introduced by TikTok in 2019. Duet and stitch made response a native format rather than a repost, which is why the platform's remix culture is unusually dense.",
    ex: ["The duet chain ran to eleven people.", "Stitching the first two seconds and answering is a whole genre."],
    rel: ["pov-format", "going-viral", "grwm"], tags: ["tiktok", "remix", "feature"],
  },
  {
    slug: "going-viral", term: "Going viral", pron: "GOH-ing VY-rul", pos: "phrase", cat: "social",
    year: 2009, pop: 79, trend: -1, status: "classic",
    def: "Spreading rapidly through sharing and recommendation. On algorithmic platforms it is less person-to-person contagion than a system deciding to promote something.",
    eli: "When something online is suddenly seen by huge numbers of people.",
    org: "From viral marketing vocabulary of the 1990s. The mechanism changed completely: early virality was forwarding, modern virality is a recommendation system's choice.",
    ex: ["Went viral overnight and the account was suspended by Friday.", "You do not go viral so much as get selected."],
    rel: ["algorithm", "fyp", "clout"], tags: ["distribution", "algorithms", "marketing"],
  },
  {
    slug: "finsta", term: "Finsta", pron: "FIN-stuh", pos: "noun", cat: "social",
    year: 2015, pop: 44, trend: -4, status: "mainstream",
    def: "A second, private Instagram account for a small trusted audience, where the posting is unpolished. The real account, despite the name meaning fake.",
    eli: "A private second Instagram for close friends, where you post the unflattering stuff.",
    org: "Named around 2015, from fake plus Instagram. The naming is backwards: the finsta is usually where people are honest and the main account is the performance.",
    ex: ["The finsta has forty followers and all the actual news.", "Close Friends was Instagram admitting the finsta was right."],
    rel: ["close-friends", "soft-launch", "influencer"], tags: ["instagram", "privacy", "authenticity"],
  },
  {
    slug: "close-friends", term: "Close Friends", pron: "klohs frendz", pos: "noun", cat: "social",
    year: 2018, pop: 52, trend: 4, status: "mainstream",
    def: "A restricted audience list on Instagram, marked with a green ring. Being added to someone's list is a legible social event with real weight.",
    eli: "A private list on Instagram for stories only certain people can see.",
    org: "Introduced by Instagram in 2018, effectively conceding what finstas had already proved: people want a small audience more often than a large one.",
    ex: ["Demoted from Close Friends without discussion.", "The green ring did more social work than any feature that year."],
    rel: ["finsta", "soft-launch", "influencer"], tags: ["instagram", "privacy", "audience"],
  },
  {
    slug: "engagement", term: "Engagement", pron: "en-GAYJ-munt", pos: "noun", cat: "social",
    year: 2010, pop: 69, trend: 1, status: "classic",
    def: "Measurable interaction with a post. Because systems optimise for it and outrage produces it reliably, engagement is the mechanism behind most complaints about feeds.",
    eli: "How much people click, like and comment. Since sites try to maximise it, angry posts often win.",
    org: "Advertising vocabulary that became the governing metric of social platforms around 2010. Goodhart's law applies with unusual clarity: it stopped being a good measure once it became the target.",
    ex: ["The post did well on engagement and badly on being true.", "Optimising for engagement selects for whatever provokes."],
    rel: ["algorithm", "ragebait", "going-viral"], tags: ["metrics", "advertising", "incentives"],
  },
  {
    slug: "engagement-bait", term: "Engagement bait", pron: "en-GAYJ-munt bayt", pos: "noun", cat: "social",
    year: 2017, pop: 57, trend: 5, status: "mainstream",
    def: "Content whose only purpose is to provoke interaction: comment your birth month, name a film without the letter A. Explicitly against most platform policies.",
    eli: "Posts that exist only to make you comment or share, not to say anything.",
    org: "Named by Facebook in 2017 when it announced demotion of the practice. It never stopped, because the incentive that produces it was never changed.",
    ex: ["Ninety thousand comments and not one of them about the post.", "Every anti-bait policy is followed by a new bait format."],
    rel: ["ragebait", "engagement", "algorithm"], tags: ["manipulation", "facebook", "policy"],
  },
  {
    slug: "reach", term: "Reach", pron: "reech", pos: "noun", cat: "social",
    year: 2012, pop: 62, trend: 2, status: "classic",
    def: "How many accounts actually saw a post, as opposed to how many follow you. Organic reach has fallen steadily across every major platform for a decade.",
    eli: "How many people actually saw your post, which is far fewer than the number who follow you.",
    org: "Advertising vocabulary that became a creator obsession as platforms reduced unpaid distribution. The decline in organic reach is the commercial engine behind the whole complaint.",
    ex: ["Two hundred thousand followers, four thousand reach.", "Reach is rented, not owned."],
    rel: ["shadowban", "algorithm", "engagement"], tags: ["metrics", "advertising", "creators"],
  },
  {
    slug: "ugc", term: "UGC", pron: "yoo-jee-SEE", pos: "abbreviation", cat: "social",
    year: 2005, pop: 48, trend: 4, status: "mainstream",
    def: "User-generated content. In marketing it now names a paid job: making advertising that deliberately looks like an ordinary person's unpaid post.",
    eli: "Content made by ordinary users. In advertising it means ads made to look like ordinary posts.",
    org: "Coined in the mid-2000s to describe the shift from broadcast to participation. Its current commercial sense inverts the original meaning almost completely.",
    ex: ["UGC creator is a job title with a rate card.", "The whole point is that it should not look produced."],
    rel: ["influencer", "brand-deal", "creator-economy"], tags: ["marketing", "advertising", "authenticity"],
  },
  {
    slug: "story", term: "Story", pron: "STOR-ee", pos: "noun", cat: "social",
    year: 2013, pop: 74, trend: 0, status: "classic",
    def: "A post that expires after twenty-four hours. The format changed posting behaviour more than almost any other feature, by removing the permanence that made people hesitate.",
    eli: "A post that disappears after a day.",
    org: "Introduced by Snapchat in 2013 and copied by Instagram in 2016, then by everyone. Ephemerality lowered the stakes of posting, which is exactly why volume rose.",
    ex: ["Posted it to a story so it would be gone by morning.", "Snapchat invented it and Instagram monetised it."],
    rel: ["close-friends", "finsta", "soft-launch"], tags: ["format", "snapchat", "ephemeral"],
  },
  {
    slug: "quote-post", term: "Quote post", pron: "kwoht pohst", pos: "noun", cat: "social",
    year: 2015, pop: 55, trend: -2, status: "mainstream",
    def: "Reposting someone with your own commentary above it. Designed for adding context and used overwhelmingly for public disagreement.",
    eli: "Sharing someone else's post with your own comment on top, usually to argue with it.",
    org: "Introduced by Twitter in 2015 as quote tweeting. It made dogpiling frictionless, since criticism now travels to your own audience rather than staying in the replies.",
    ex: ["Four thousand quote posts and none of them agreeing.", "The feature that made pile-ons structural."],
    rel: ["dogpiling", "ratio", "subtweet"], tags: ["twitter", "conflict", "feature"],
  },
  {
    slug: "mutuals", term: "Mutuals", pron: "MYOO-choo-ulz", pos: "noun", cat: "social",
    year: 2014, pop: 51, trend: 3, status: "mainstream",
    def: "People who follow you and whom you follow back. A recognised relationship category with real social weight, often abbreviated to moots.",
    eli: "People who follow you while you follow them back.",
    org: "Tumblr and Twitter vocabulary of the mid-2010s. It names a genuine tier between stranger and friend that platforms never designed but everyone understands.",
    ex: ["We have been mutuals for six years and never spoken.", "Losing a moot is a real if minor grief."],
    rel: ["close-friends", "parasocial", "finsta"], tags: ["tumblr", "relationships", "twitter"],
  },
  {
    slug: "feed", term: "Feed", pron: "feed", pos: "noun", cat: "social",
    year: 2006, pop: 78, trend: 0, status: "classic",
    def: "The endless scrolling stream of posts a platform assembles for you. Its shift from chronological to ranked is the single most consequential design change in social media.",
    eli: "The endless list of posts an app shows you, chosen by the app rather than by time.",
    org: "Facebook launched the News Feed in 2006 to widespread user protest. Ranking replaced chronology from around 2009, and almost every argument about social media since dates from that change.",
    ex: ["The feed decided I wanted woodworking and it was right.", "Chronological was a choice, and it was removed."],
    rel: ["algorithm", "fyp", "doomscrolling"], tags: ["facebook", "design", "history"],
  },
  {
    slug: "photo-dump", term: "Photo dump", pron: "FOH-toh dump", pos: "noun", cat: "social",
    year: 2021, pop: 68, trend: 6, status: "mainstream",
    def: "An Instagram post combining several unrelated photos from a period of time, deliberately looser and less curated than a single posed shot.",
    eli: "A post with a bunch of random photos from the last few weeks, instead of one perfect picture.",
    org: "Rose on Instagram around 2021 as a reaction against the over-curated single-photo grid, part of a wider shift toward looking less staged online.",
    ex: ["Monthly photo dump, mostly food and the dog.", "The photo dump format killed the perfectly matching grid."],
    rel: ["grwm", "story", "close-friends"], tags: ["instagram", "format", "authenticity"],
  },
  {
    slug: "instagram-official", term: "Instagram official", pron: "IN-stuh-gram uh-FISH-ul", pos: "adjective", cat: "social",
    year: 2012, pop: 54, trend: -2, status: "classic",
    def: "The moment a relationship is confirmed publicly through a joint post, treated as more binding than a private admission.",
    eli: "When a couple posts about each other publicly, making the relationship feel officially confirmed.",
    org: "Emerged alongside Instagram and Facebook relationship statuses in the early 2010s, formalising the idea that a relationship was not fully real until it was public.",
    ex: ["Three months in and still not Instagram official.", "They went Instagram official on Valentine's Day, on schedule."],
    rel: ["soft-launch", "situationship", "close-friends"], tags: ["instagram", "dating", "relationships"],
  },
  {
    slug: "add-yours", term: "Add Yours", pron: "add yorz", pos: "noun", cat: "social",
    year: 2021, pop: 39, trend: -5, status: "fading",
    def: "An Instagram Stories sticker that chains a prompt from user to user, each adding their own response to the same theme.",
    eli: "A story sticker that asks a question and passes it to your friends to answer too.",
    org: "Launched by Instagram in 2021 as a built-in Stories feature explicitly designed to manufacture the kind of chain participation that used to spread organically.",
    ex: ["An Add Yours about first concerts went round the whole group.", "Add Yours chains die out within about a day."],
    rel: ["story", "close-friends", "photo-dump"], tags: ["instagram", "format", "feature"],
  },
  {
    slug: "community-notes", term: "Community Notes", pron: "kuh-MYOO-nit-ee nohts", pos: "noun", cat: "social",
    year: 2021, pop: 65, trend: 14, status: "rising",
    def: "A crowdsourced fact-check appended beneath a post on X, written and rated by ordinary users rather than the platform itself. Getting one attached is treated as a public correction.",
    eli: "A note added under a post by other users to correct or add context to it, instead of the company doing it.",
    org: "Launched as Birdwatch in 2021 and renamed Community Notes after Elon Musk's 2022 acquisition of Twitter, replacing most of the platform's own fact-checking system.",
    ex: ["The post is still up but the Community Note tells the real story.", "Getting community-noted is the modern version of the ratio."],
    rel: ["ratio", "x-the-everything-app", "bad-faith"], tags: ["x", "fact-check", "moderation"],
  },
  {
    slug: "x-the-everything-app", term: "The everything app", pron: "thee EV-ree-thing ap", pos: "noun", cat: "social",
    year: 2023, pop: 33, trend: 4, status: "niche",
    def: "The stated ambition for X to combine social media, payments and messaging into one platform, invoked online mostly to mock how far the reality lags the pitch.",
    eli: "The plan for X to do everything, like chatting, paying and posting, in one app. People mostly joke that it does not.",
    org: "Stated repeatedly by Elon Musk after acquiring Twitter and rebranding it X in 2023, modelled explicitly on China's WeChat.",
    ex: ["Still waiting on the everything app to do the one thing.", "The everything app cannot reliably load images."],
    rel: ["community-notes", "blue-check", "algorithm"], tags: ["x", "rebrand", "criticism"],
  },
  {
    slug: "blue-check", term: "Blue check", pron: "bloo chek", pos: "noun", cat: "social",
    year: 2009, pop: 58, trend: -3, status: "mainstream",
    def: "The verification badge on X, originally free and reserved for confirmed notable accounts, now purchasable by anyone. Its meaning inverted almost completely after 2022.",
    eli: "The blue tick next to a name, which used to mean the account was verified as real and important, but now can just be bought.",
    org: "Introduced by Twitter in 2009 to stop impersonation of public figures. A 2022 paid-subscription model let anyone buy one, and the badge became a punchline rather than a credential.",
    ex: ["The blue check used to mean something.", "Reply guys with blue checks are their own genre now."],
    rel: ["x-the-everything-app", "reply-guy", "clout"], tags: ["x", "verification", "status"],
  },
  {
    slug: "reply-guy", term: "Reply guy", pron: "ri-PLY gy", pos: "noun", cat: "social",
    year: 2018, pop: 49, trend: 5, status: "mainstream",
    def: "A man who replies to a specific woman's posts constantly and predictably, usually with unsolicited opinions or flattery, regardless of the topic.",
    eli: "A guy who always replies to the same woman's posts, whether or not she wants him to.",
    org: "Named on Twitter around 2018 to describe a recurring pattern users had all noticed independently but had no shared word for.",
    ex: ["Every post has the same three reply guys within a minute.", "Being a reply guy is a lifestyle, not an accident."],
    rel: ["blue-check", "parasocial", "glazing"], tags: ["x", "behaviour", "criticism"],
  },
  {
    slug: "snap-streak", term: "Snap streak", pron: "snap streek", pos: "noun", cat: "social",
    year: 2015, pop: 61, trend: -1, status: "mainstream",
    def: "A running count of consecutive days two Snapchat users have exchanged snaps, visible as a number that resets to zero if either side misses a day.",
    eli: "A count of how many days in a row you and a friend have sent each other Snapchat photos without missing one.",
    org: "Added by Snapchat in 2015. Losing a years-long streak is treated as a genuine minor grief event, and streak-restoring became a small paid feature for exactly that reason.",
    ex: ["Lost a 900-day streak because the app crashed.", "He asked a friend to keep his streaks alive during a phone repair."],
    rel: ["snap-score", "streak-freeze", "fyp"], tags: ["snapchat", "gamification", "friendship"],
  },
  {
    slug: "streak-freeze", term: "Streak freeze", pron: "streek freez", pos: "noun", cat: "social",
    year: 2018, pop: 30, trend: 2, status: "niche",
    def: "A feature or favour that protects a snap streak from resetting despite a missed day, either purchased in-app or granted informally by a friend covering for you.",
    eli: "A way to save your Snapchat streak even if you forget to send something one day.",
    org: "Snapchat added a paid streak-restore option after streak loss became one of its most common support complaints and a genuine source of user distress.",
    ex: ["Bought a streak freeze rather than admit I forgot.", "A good friend sends the streak freeze snap without being asked."],
    rel: ["snap-streak", "snap-score", "close-friends"], tags: ["snapchat", "gamification"],
  },
  {
    slug: "snap-score", term: "Snap score", pron: "snap skor", pos: "noun", cat: "social",
    year: 2016, pop: 42, trend: 0, status: "mainstream",
    def: "A cumulative number on Snapchat based on snaps sent and received, whose exact formula is undisclosed and treated as mildly mysterious status by users.",
    eli: "A number on your Snapchat profile that goes up the more you use the app, though nobody is quite sure exactly how it is calculated.",
    org: "Introduced by Snapchat in 2016. The company has never published the formula, which is itself part of why users treat the number as a small status symbol.",
    ex: ["His snap score is in six figures and nobody knows why.", "Snap score means nothing and everyone still checks it."],
    rel: ["snap-streak", "clout", "aura"], tags: ["snapchat", "status", "gamification"],
  },
  {
    slug: "snapchat-dysmorphia", term: "Snapchat dysmorphia", pron: "SNAP-chat dis-MOR-fee-uh", pos: "noun", cat: "social",
    year: 2018, pop: 40, trend: 7, status: "rising",
    def: "A documented pattern in which people seek cosmetic procedures to resemble their own beautifying filters, rather than any real public figure.",
    eli: "Wanting cosmetic changes to look like your own filtered selfie instead of your real face.",
    org: "Named in a 2018 medical journal describing a pattern doctors were newly seeing once selfie filters became photorealistic enough to set an achievable-seeming standard.",
    ex: ["Surgeons now regularly cite Snapchat dysmorphia as a reason patients give.", "The filter is the reference photo now, not a celebrity."],
    rel: ["clean-girl", "looksmaxxing", "facetune"], tags: ["snapchat", "beauty", "psychology"],
  },
  {
    slug: "facetune", term: "Facetune", pron: "FAYSS-toon", pos: "noun", cat: "social",
    year: 2013, pop: 47, trend: -3, status: "mainstream",
    def: "A photo-editing app for smoothing skin and reshaping features, and by extension any visibly over-edited photo, used as a verb meaning to edit unnaturally.",
    eli: "An app for smoothing and adjusting faces in photos. People also use the name as a verb for an over-edited picture.",
    org: "Released in 2013 and adopted so widely by influencers that the brand name became the generic term for the effect, similar to how Photoshop did for an earlier generation.",
    ex: ["Facetuned within an inch of recognition.", "You can spot the facetune around the jawline."],
    rel: ["snapchat-dysmorphia", "clean-girl", "looksmaxxing"], tags: ["editing", "beauty", "instagram"],
  },
  {
    slug: "were-so-back", term: "We're so back", pron: "weer soh bak", pos: "phrase", cat: "social",
    year: 2022, pop: 63, trend: 9, status: "rising",
    def: "A declaration of sudden optimism after a setback, almost always paired ironically with its opposite, it's so over, to narrate the smallest fluctuations as dramatic swings.",
    eli: "A joking way of saying things are looking good again after they seemed bad, often followed a minute later by the opposite.",
    org: "Grew from sports and gaming commentary in the early 2020s into a general-purpose reaction format for any minor reversal of fortune, treated with mock seriousness.",
    ex: ["The bug got fixed. We're so back.", "So over five minutes ago, so back now."],
    rel: ["its-so-over", "cinema", "npc"], tags: ["format", "irony", "twitter"],
  },
  {
    slug: "its-so-over", term: "It's so over", pron: "its soh OH-vur", pos: "phrase", cat: "social",
    year: 2022, pop: 58, trend: 5, status: "rising",
    def: "A declaration of dramatic defeat after a minor setback, functioning as the pessimistic half of a pair with we're so back.",
    eli: "A joking way of saying everything is ruined, usually about something small.",
    org: "Circulated alongside we're so back from the early 2020s as sports and gaming communities began narrating tiny fluctuations in the vocabulary of total collapse.",
    ex: ["Missed the bus. It's so over.", "It's so over, we're so back, repeat every ninety seconds."],
    rel: ["were-so-back", "crash-out", "cope"], tags: ["format", "irony", "twitter"],
  },
  {
    slug: "threads-app", term: "Threads", pron: "thredz", pos: "noun", cat: "social",
    year: 2023, pop: 44, trend: -6, status: "mainstream",
    def: "Meta's text-based app launched as a direct rival to Twitter, notable for its record-setting first-day signups and the immediate wave of jokes about whether anyone would stay.",
    eli: "A Meta app for short text posts, made to compete with Twitter/X.",
    org: "Launched by Instagram's parent company in July 2023, gaining 100 million signups in five days, then a widely mocked drop-off in daily use once the novelty wore off.",
    ex: ["Made a Threads account, posted twice, forgot about it.", "Threads is where the exodus from X actually went."],
    rel: ["x-the-everything-app", "were-so-back", "community-notes"], tags: ["threads", "meta", "platforms"],
  },
];
