import type { RawTerm } from "../types";

export const streamTerms: RawTerm[] = [
  {
    slug: "emote", term: "Emote", pron: "i-MOHT", pos: "noun", cat: "stream",
    year: 2011, pop: 66, trend: 3, status: "classic",
    def: "A small custom image used in place of a word in chat. Unlike emoji, emotes are platform-specific and often channel-specific, which makes them dialect markers.",
    eli: "A little picture used as a word in stream chat. Different channels have different ones.",
    org: "Twitch inherited the concept from its parent Justin.tv and turned it into an economy, where subscribing to a channel unlocks its emotes. Third-party extensions expanded the vocabulary enormously.",
    ex: ["The whole chat replied in one emote.", "Half of Twitch English cannot be typed on a normal keyboard."],
    rel: ["kappa", "poggers", "emote-spam"], tags: ["twitch", "chat", "vocabulary"],
  },
  {
    slug: "kappa", term: "Kappa", pron: "KAP-uh", pos: "noun", cat: "stream",
    year: 2011, pop: 52, trend: -6, status: "classic",
    def: "The sarcasm emote, functioning exactly as a tone indicator. Appending it marks the preceding statement as not meant seriously.",
    eli: "An emote that means the message before it was a joke.",
    org: "The face is Josh DeSeno, a Justin.tv employee, hidden in the client as an easter egg in 2011. It became Twitch's most-used emote and its de facto punctuation mark.",
    ex: ["Great patch notes, really thoughtful Kappa", "Kappa is a tone indicator that predates the term."],
    rel: ["emote", "tone-indicator", "poggers"], tags: ["twitch", "sarcasm", "history"],
  },
  {
    slug: "poggers", term: "Poggers", pron: "POG-urz", pos: "interjection", cat: "stream",
    year: 2017, pop: 61, trend: -8, status: "fading",
    def: "An expression of excitement at something impressive. Pog and PogChamp are the related forms; to pog is to react with delight.",
    eli: "A way of saying that was amazing, used when something exciting happens on stream.",
    org: "Descended from the PogChamp emote, taken from a 2010 blooper reel of gamer Ryan Gutierrez. The original was retired by Twitch in 2021 and replaced repeatedly.",
    ex: ["Clutch at one health. POGGERS", "Poggers has escaped Twitch and now appears in offices."],
    rel: ["kappa", "emote", "clutch"], tags: ["twitch", "excitement", "emote"],
  },
  {
    slug: "kekw", term: "KEKW", pron: "kek-DUB", pos: "interjection", cat: "stream",
    year: 2019, pop: 49, trend: -3, status: "mainstream",
    def: "The standard laughter emote on Twitch, showing Spanish comedian Juan Joya Borja mid-laugh. Kek alone is an older laughter marker.",
    eli: "The Twitch way of saying something was hilarious.",
    org: "Kek came from World of Warcraft, where a Horde player typing lol appeared to Alliance players as kek. The KEKW emote added the face in 2019.",
    ex: ["KEKW he walked straight off the map", "Chat is nothing but KEKW right now."],
    rel: ["emote", "lol", "omegalul"], tags: ["twitch", "laughter", "warcraft"],
  },
  {
    slug: "monkas", term: "MonkaS", pron: "MON-kuh-es", pos: "interjection", cat: "stream",
    year: 2017, pop: 41, trend: -2, status: "niche",
    def: "Marks tension or anxiety, posted when something on stream is about to go badly. A sweating frog face.",
    eli: "An emote meaning this is stressful and I am nervous watching it.",
    org: "A Pepe variant that spread through Twitch chat around 2017. It fills a genuine gap: no standard emoji conveys anxious anticipation as precisely.",
    ex: ["One hit left monkaS", "The whole chat went monkaS during the last round."],
    rel: ["emote", "poggers", "sadge"], tags: ["twitch", "anxiety", "emote"],
  },
  {
    slug: "sadge", term: "Sadge", pron: "SAJ", pos: "adjective", cat: "stream",
    year: 2019, pop: 44, trend: -1, status: "niche",
    def: "A marker of mild disappointment, deliberately too small a word for real grief. Used when something minor does not go your way.",
    eli: "A way of saying that is a shame, about something small.",
    org: "A Twitch emote of a downcast Pepe, which escaped chat and became a spoken word among younger users, usually with ironic distance.",
    ex: ["Sold out already. Sadge.", "Cancelled the only good flavour, sadge."],
    rel: ["monkas", "emote", "copium"], tags: ["twitch", "disappointment", "emote"],
  },
  {
    slug: "vtuber", term: "VTuber", pron: "VEE-too-bur", pos: "noun", cat: "stream",
    year: 2016, pop: 63, trend: 14, status: "rising",
    def: "A streamer who performs as an animated avatar driven by motion capture, so the persona rather than the person is the public identity.",
    eli: "A streamer who appears as a cartoon character that moves when they move.",
    org: "Kizuna AI began in 2016 and defined the format. Agencies such as Hololive and Nijisanji industrialised it, and by the 2020s VTubers regularly topped global streaming earnings.",
    ex: ["The VTuber debut had eight hundred thousand concurrent viewers.", "Separating persona from person is the whole appeal."],
    rel: ["streamer", "parasocial"], tags: ["japan", "avatar", "streaming"],
  },
  {
    slug: "just-chatting", term: "Just Chatting", pron: "just CHAT-ing", pos: "noun", cat: "stream",
    year: 2018, pop: 55, trend: 6, status: "mainstream",
    def: "A Twitch category for streams with no game, where the content is conversation, reactions and presence. Consistently among the platform's most watched.",
    eli: "A stream where someone just talks to their audience instead of playing a game.",
    org: "Introduced by Twitch in 2018 to accommodate what was already happening. Its rise marked the platform's shift from a games site to a general live-video one.",
    ex: ["Nine hours in Just Chatting and not one game launched.", "The category nobody planned for became the biggest one."],
    rel: ["streamer", "parasocial", "vtuber"], tags: ["twitch", "format", "category"],
  },
  {
    slug: "streamer", term: "Streamer", pron: "STREE-mur", pos: "noun", cat: "stream",
    year: 2013, pop: 78, trend: 4, status: "mainstream",
    def: "Someone who broadcasts live to an audience as an occupation. The job combines performance, moderation, scheduling and small-business administration.",
    eli: "Someone whose job is broadcasting themselves live to an audience.",
    org: "Twitch launched in 2011 and made full-time live broadcasting viable. The role has since split into dozens of specialisms, from speedrunning to cooking.",
    ex: ["Full-time streamer, part-time everything else.", "The unglamorous part of streaming is the schedule."],
    rel: ["just-chatting", "vtuber", "parasocial"], tags: ["twitch", "career", "creator"],
  },
  {
    slug: "raid", term: "Raid", pron: "rayd", pos: "noun", cat: "stream",
    year: 2017, pop: 47, trend: 2, status: "mainstream",
    def: "Sending your entire audience to another channel at the end of a broadcast. A native feature and the main way small streamers are discovered.",
    eli: "When a streamer finishes and sends all their viewers to watch someone else.",
    org: "A community practice that Twitch formalised as a feature in 2017. It is one of the few genuinely cooperative mechanics on any platform.",
    ex: ["Raided out to four hundred viewers and made her night.", "Raid trains can run for hours."],
    rel: ["streamer", "emote-spam", "sub"], tags: ["twitch", "community", "discovery"],
  },
  {
    slug: "sub", term: "Sub", pron: "sub", pos: "noun", cat: "stream",
    year: 2011, pop: 60, trend: 1, status: "classic",
    def: "A paid monthly subscription to a channel, granting emotes and badges. Gifted subs are bought in bulk for other viewers, often anonymously.",
    eli: "A paid monthly membership to a streamer's channel that unlocks emotes.",
    org: "Twitch's core revenue model. Sub badges showing tenure created a visible status hierarchy in chat, which turned out to matter more than the emotes.",
    ex: ["Resub at forty-eight months.", "Someone dropped a hundred gifted subs and chat lost its mind."],
    rel: ["bits", "raid", "streamer"], tags: ["twitch", "money", "status"],
  },
  {
    slug: "bits", term: "Bits", pron: "bits", pos: "noun", cat: "stream",
    year: 2016, pop: 42, trend: -1, status: "mainstream",
    def: "Twitch's purchasable currency, spent on animated cheer messages that highlight a comment in chat. A way of paying to be seen.",
    eli: "Money you buy on Twitch to make your chat message stand out.",
    org: "Introduced in 2016 to let viewers pay without leaving the platform. The underlying mechanic, paying for message prominence, was later copied widely.",
    ex: ["A thousand bits to ask a question that was already answered.", "Cheering is buying attention, plainly."],
    rel: ["sub", "dono", "streamer"], tags: ["twitch", "money", "chat"],
  },
  {
    slug: "dono", term: "Dono", pron: "DOH-noh", pos: "noun", cat: "stream",
    year: 2015, pop: 40, trend: 0, status: "mainstream",
    def: "A donation to a streamer, usually accompanied by a message read aloud by text-to-speech. The TTS voice is a genre of its own.",
    eli: "Money sent to a streamer, usually with a message the computer reads out loud.",
    org: "Third-party donation services predate Twitch's own tools, which is why donos and bits coexist. The robotic TTS voice became a comic instrument in its own right.",
    ex: ["Five pound dono to make him read a shopping list.", "The TTS voice has ruined more serious moments than anything else."],
    rel: ["bits", "sub", "streamer"], tags: ["twitch", "money", "tts"],
  },
  {
    slug: "subathon", term: "Subathon", pron: "SUB-uh-thon", pos: "noun", cat: "stream",
    year: 2021, pop: 38, trend: 3, status: "niche",
    def: "A stream whose end time is extended by each new subscription, so the audience collectively decides how long the broadcaster stays awake.",
    eli: "A stream that gets longer every time someone subscribes, so it can run for days.",
    org: "Popularised in 2021 when several streamers ran month-long subathons. It made explicit the exchange between audience payment and performer endurance.",
    ex: ["Day nineteen of the subathon and he has stopped forming sentences.", "Subathons are a study in incentive design."],
    rel: ["sub", "streamer", "just-chatting"], tags: ["twitch", "endurance", "format"],
  },
  {
    slug: "clip", term: "Clip", pron: "klip", pos: "noun", cat: "stream",
    year: 2016, pop: 71, trend: 7, status: "mainstream",
    def: "A short excerpt captured from a live broadcast. Clips are how streams reach people who were not watching, and how moments outlive their context.",
    eli: "A short saved bit of a stream that people share afterwards.",
    org: "Twitch shipped clipping in 2016. It changed streamer behaviour permanently: anything said live may be extracted, and clip chasing became a recognised failure mode.",
    ex: ["The clip has more views than the stream had viewers.", "Clipped out of context and posted with a new caption."],
    rel: ["vod", "streamer", "ragebait"], tags: ["twitch", "video", "virality"],
  },
  {
    slug: "vod", term: "VOD", pron: "vod", pos: "abbreviation", cat: "stream",
    year: 2012, pop: 45, trend: 0, status: "classic",
    def: "Video on demand: the recording of a live broadcast, available afterwards. VOD review is the practice of studying your own footage to improve.",
    eli: "The saved recording of a stream that you can watch later.",
    org: "Standard broadcast vocabulary adopted by streaming platforms. In competitive gaming, VOD review is a formal coaching method borrowed directly from sport.",
    ex: ["It is in the VOD at about four hours in.", "VOD review is where improvement actually happens."],
    rel: ["clip", "streamer", "speedrun"], tags: ["twitch", "video", "coaching"],
  },
  {
    slug: "emote-spam", term: "Emote spam", pron: "i-MOHT spam", pos: "noun", cat: "stream",
    year: 2014, pop: 39, trend: 0, status: "mainstream",
    def: "Hundreds of viewers posting the same emote simultaneously, turning chat into a single collective reaction rather than a conversation.",
    eli: "When everyone in chat posts the same picture at once as one big reaction.",
    org: "An emergent property of large chats, where individual messages scroll past too fast to read. Spam is the only legible signal at scale, which is a genuine design insight.",
    ex: ["The play landed and chat became one column of the same emote.", "Above ten thousand viewers, chat stops being text."],
    rel: ["emote", "poggers", "kekw"], tags: ["twitch", "chat", "scale"],
  },
  {
    slug: "backseat-gaming", term: "Backseat gaming", pron: "BAK-seet GAY-ming", pos: "noun", cat: "stream",
    year: 2015, pop: 43, trend: 1, status: "mainstream",
    def: "Telling a streamer how to play when they have not asked. Many channels ban it outright, since watching someone work it out is often the point.",
    eli: "Telling a streamer what to do when they did not ask for help.",
    org: "From backseat driving. It became a formal chat rule as first-playthrough streams grew, because unsolicited hints destroy the thing the audience came for.",
    ex: ["No backseating, he wants to find it himself.", "Timed out for backseating within nine seconds."],
    rel: ["stream-sniping", "mod", "streamer"], tags: ["twitch", "etiquette", "moderation"],
  },
  {
    slug: "stream-sniping", term: "Stream sniping", pron: "STREEM SNY-ping", pos: "noun", cat: "stream",
    year: 2017, pop: 37, trend: 0, status: "niche",
    def: "Watching a broadcast to gain an unfair advantage against that player in a live match, using their own screen as intelligence.",
    eli: "Cheating by watching a streamer's screen while playing against them.",
    org: "A structural problem for competitive streaming. Countermeasures include stream delay and hidden lobbies, neither of which fully solves it.",
    ex: ["Added a two-minute delay to stop stream sniping.", "Being sniped every game is why some pros stopped streaming ranked."],
    rel: ["backseat-gaming", "streamer", "smurf"], tags: ["twitch", "cheating", "competitive"],
  },
  {
    slug: "mod", term: "Mod", pron: "mod", pos: "noun", cat: "stream",
    year: 2003, pop: 68, trend: 1, status: "classic",
    def: "A moderator: an unpaid volunteer enforcing a community's rules. On streams they hold a sword icon; on forums, the power to lock and delete.",
    eli: "A volunteer who keeps a chat or forum in order and can remove people who break the rules.",
    org: "Forum vocabulary carried into every platform since. Almost all internet moderation is done free by people with no training and considerable exposure to abuse.",
    ex: ["The mods deleted it before most people saw it.", "Unpaid mods hold up an enormous share of the internet."],
    rel: ["sysop", "backseat-gaming", "timeout"], tags: ["moderation", "community", "labour"],
  },
  {
    slug: "timeout", term: "Timeout", pron: "TYME-owt", pos: "noun", cat: "stream",
    year: 2012, pop: 41, trend: 0, status: "mainstream",
    def: "A temporary chat ban lasting seconds to hours, used as a warning rather than a punishment. Distinct from a permanent ban.",
    eli: "Being muted in chat for a short while as a warning.",
    org: "Twitch's graduated moderation model, which recognised that most rule-breaking needs a nudge rather than removal. Widely copied by Discord and others.",
    ex: ["Ten-minute timeout for backseating.", "A timeout is a conversation, a ban is a verdict."],
    rel: ["mod", "backseat-gaming", "shadowban"], tags: ["moderation", "twitch", "discipline"],
  },
  {
    slug: "first-time-chatter", term: "First-time chatter", pron: "furst-tyme CHAT-ur", pos: "noun", cat: "stream",
    year: 2020, pop: 33, trend: 2, status: "niche",
    def: "A viewer sending their first message in a channel, highlighted by the platform so the streamer can acknowledge them.",
    eli: "Someone posting in a chat for the very first time, marked so the streamer can say hello.",
    org: "A Twitch feature designed to convert lurkers into participants. It quantified a moment that had always mattered informally in small communities.",
    ex: ["Welcome, first-time chatter.", "The highlight exists because the first message is the hardest."],
    rel: ["lurker", "streamer", "mod"], tags: ["twitch", "community", "onboarding"],
  },
  {
    slug: "content-farm", term: "Content farm", pron: "KON-tent farm", pos: "noun", cat: "stream",
    year: 2009, pop: 51, trend: 11, status: "rising",
    def: "An operation producing high volumes of low-value media purely to capture search or recommendation traffic, with quality irrelevant to the business model.",
    eli: "A company that makes huge amounts of cheap content just to get clicks.",
    org: "Named around 2009 for websites gaming search results. Generative tools lowered the cost of production to nearly zero, which is why the term resurfaced after 2023.",
    ex: ["The channel posts forty videos a day. Content farm.", "Content farms were a search problem before they were a video problem."],
    rel: ["ai-slop", "clip", "algorithm"], tags: ["seo", "volume", "quality"],
  },
  {
    slug: "no-life", term: "No-life", pron: "noh-LYFE", pos: "verb", cat: "stream",
    year: 2004, pop: 32, trend: -3, status: "fading",
    def: "To play or grind something to the exclusion of everything else. As a noun it was an insult; as a verb it is closer to a boast.",
    eli: "Spending almost all your time on one game.",
    org: "Massively multiplayer game communities of the early 2000s, where the time required to compete genuinely did crowd out other activity.",
    ex: ["He no-lifed the expansion in four days.", "The verb survived long after the insult stopped landing."],
    rel: ["grind", "sweaty", "streamer"], tags: ["gaming", "time", "mmo"],
  },
  {
    slug: "copium", term: "Copium", pron: "KOH-pee-um", pos: "noun", cat: "stream",
    year: 2020, pop: 53, trend: 6, status: "rising",
    def: "An imaginary drug taken to make a loss bearable, from cope plus opium. Posted when someone is visibly rationalising a defeat.",
    eli: "A pretend drug that makes losing feel okay, used to tease someone making excuses.",
    org: "The word appeared in a 2017 image and spread through Twitch chat and esports communities around 2020, where it became a standard emote and then everyday vocabulary.",
    ex: ["Huge hit of copium in the post-match interview.", "Hopium is the forward-looking version."],
    rel: ["cope", "malding", "sadge"], tags: ["twitch", "esports", "emote"],
  },
  {
    slug: "omegalul", term: "OMEGALUL", pron: "oh-MEG-uh-lul", pos: "interjection", cat: "stream",
    year: 2018, pop: 36, trend: -2, status: "niche",
    def: "The maximum-intensity laughter emote, an enlarged distortion of the LUL face. Sits at the top of a graded scale from LUL to LULW to OMEGALUL.",
    eli: "The strongest way of saying something was hilarious in Twitch chat.",
    org: "Built from the LUL emote, itself a photograph of the late streamer TotalBiscuit. Twitch chat maintains a genuine intensity scale across the variants.",
    ex: ["OMEGALUL he did it again", "The emote scale is finer grained than most punctuation."],
    rel: ["kekw", "emote", "emote-spam"], tags: ["twitch", "laughter", "emote"],
  },
  {
    slug: "patch-notes", term: "Patch notes", pron: "pach nohts", pos: "noun", cat: "stream",
    year: 2004, pop: 47, trend: 1, status: "classic",
    def: "The published list of changes in a game update. Read with the intensity of legal documents, because a single number can invalidate a whole strategy.",
    eli: "The list of what changed in a game update, which players read very carefully.",
    org: "Standard software practice that competitive gaming turned into an event. Patch note days reorganise entire communities, and the vocabulary of buff and nerf comes from reading them.",
    ex: ["Patch notes dropped and the meta is unrecognisable.", "One decimal point in the patch notes ended a whole playstyle."],
    rel: ["nerf", "buff", "meta"], tags: ["gaming", "updates", "balance"],
  },
  {
    slug: "bait", term: "Bait", pron: "bayt", pos: "noun", cat: "stream",
    year: 2015, pop: 58, trend: 3, status: "mainstream",
    def: "Content posted to provoke a predictable response. Obvious bait is bait so transparent that replying is the joke; taking the bait is falling for it sincerely.",
    eli: "Something posted on purpose to make people react, usually angrily.",
    org: "From fishing, via the older sense in trolling. The modern vocabulary distinguishes carefully between bait, ragebait and engagement bait by what reaction is being farmed.",
    ex: ["Obvious bait, nine thousand quote posts.", "Bait used to be believable."],
    rel: ["ragebait", "troll", "clip"], tags: ["provocation", "engagement", "twitch"],
  },
];
