import type { RawTerm } from "../types";

export const techTerms: RawTerm[] = [
  {
    slug: "open-source", term: "Open source", pron: "OH-pun sors", pos: "noun", cat: "tech",
    year: 1998, pop: 74, trend: 1, status: "classic",
    def: "Software whose source code is published under a licence permitting inspection, modification and redistribution. A licensing fact first, and a culture second.",
    eli: "Software whose recipe is public, so anyone can read it, change it and share it.",
    org: "The term was chosen at a 1998 meeting in Palo Alto as a business-friendly alternative to free software, whose ambiguity between price and liberty had hampered adoption.",
    ex: ["The whole stack is open source and nobody maintains half of it.", "Open source is a licence, not a promise of support."],
    rel: ["fork", "pull-request", "bus-factor"], tags: ["licensing", "software", "community"],
  },
  {
    slug: "fork", term: "Fork", pron: "fork", pos: "noun", cat: "tech",
    year: 1995, pop: 62, trend: 0, status: "classic",
    def: "A copy of a project taken in a new direction. Technically routine on modern platforms, but a hard fork of a community usually follows a governance dispute.",
    eli: "Making your own copy of a project and taking it somewhere different.",
    org: "Unix vocabulary, where fork creates a duplicate process. GitHub made forking a one-click social gesture, which changed the word from a threat into a compliment.",
    ex: ["They forked it after the licence change.", "Forking is cheap; maintaining a fork is not."],
    rel: ["open-source", "pull-request", "merge-conflict"], tags: ["git", "governance", "software"],
  },
  {
    slug: "pull-request", term: "Pull request", pron: "pool ri-KWEST", pos: "noun", cat: "tech",
    year: 2008, pop: 66, trend: 1, status: "classic",
    def: "A proposal to merge changes into a project, bundled with discussion and review. The unit of collaboration in modern software, and of a great deal of social friction.",
    eli: "Asking a project to accept your changes, so others can check them first.",
    org: "Introduced by GitHub in 2008. It turned code contribution into something resembling a conversation thread, which is why software argument now looks like forum argument.",
    ex: ["The pull request has been open for fourteen months.", "Nine approving reviews and one blocking comment about naming."],
    rel: ["fork", "code-review", "bikeshedding"], tags: ["git", "github", "collaboration"],
  },
  {
    slug: "merge-conflict", term: "Merge conflict", pron: "murj KON-flikt", pos: "noun", cat: "tech",
    year: 2005, pop: 58, trend: 0, status: "classic",
    def: "What happens when two people change the same lines and the version control system refuses to guess which one is right.",
    eli: "When two people edit the same part of a file and the computer asks a human to decide.",
    org: "As old as version control, but named into everyday speech by Git after 2005. Now used metaphorically for any two-party disagreement over the same detail.",
    ex: ["Three-way merge conflict in a file nobody has touched since 2019.", "Our holiday plans have a merge conflict."],
    rel: ["fork", "pull-request", "rebase"], tags: ["git", "collaboration", "frustration"],
  },
  {
    slug: "rubber-duck-debugging", term: "Rubber duck debugging", pron: "RUB-ur duk dee-BUG-ing", pos: "noun", cat: "tech",
    year: 1999, pop: 47, trend: 2, status: "classic",
    def: "Solving a problem by explaining it aloud, line by line, to an inanimate object. The explanation, not the listener, does the work.",
    eli: "Fixing a problem by explaining it out loud to a toy duck, because saying it clearly makes the mistake obvious.",
    org: "Named in The Pragmatic Programmer in 1999, describing a developer who carried an actual duck. The technique long predates the name and is now standard advice.",
    ex: ["Found it halfway through explaining it to the duck.", "Ask a colleague, or ask the duck first."],
    rel: ["yak-shaving", "heisenbug", "code-review"], tags: ["debugging", "practice", "folklore"],
  },
  {
    slug: "yak-shaving", term: "Yak shaving", pron: "yak SHAY-ving", pos: "noun", cat: "tech",
    year: 2000, pop: 43, trend: 1, status: "classic",
    def: "A chain of prerequisite tasks that leads ever further from the original goal, so that you end up doing something absurd for a defensible reason.",
    eli: "When fixing one small thing means fixing five other things first, until you forget what you started on.",
    org: "Coined at the MIT Media Lab around 2000 by Carlin Vieri, from a Ren and Stimpy episode. It names something every practitioner recognises immediately.",
    ex: ["Wanted to change a colour, currently upgrading the build system. Yak shaving.", "Four hours of yak shaving and the original ticket is untouched."],
    rel: ["bikeshedding", "tech-debt", "rubber-duck-debugging"], tags: ["procrastination", "mit", "folklore"],
  },
  {
    slug: "bikeshedding", term: "Bikeshedding", pron: "BYKE-shed-ing", pos: "noun", cat: "tech",
    year: 1999, pop: 51, trend: 2, status: "classic",
    def: "Spending disproportionate discussion on a trivial detail because everyone understands it, while the difficult substance passes unexamined.",
    eli: "Arguing for hours about something small and easy instead of the hard thing that actually matters.",
    org: "From C. Northcote Parkinson's 1957 law of triviality, in which a committee approves a nuclear reactor quickly and then debates a bicycle shed for an hour. Named for software by Poul-Henning Kamp in 1999.",
    ex: ["Forty comments on the button label, none on the data model.", "Classic bikeshedding: everyone has an opinion on names."],
    rel: ["yak-shaving", "pull-request", "code-review"], tags: ["meetings", "process", "parkinson"],
  },
  {
    slug: "tech-debt", term: "Technical debt", pron: "TEK-nik-ul det", pos: "noun", cat: "tech",
    year: 1992, pop: 69, trend: 3, status: "classic",
    def: "The accumulated cost of shortcuts taken to ship sooner, which must be repaid later with interest in the form of slower work.",
    eli: "Rushed work that saves time now but makes everything slower later, like borrowing time you have to pay back.",
    org: "Coined by Ward Cunningham in 1992 as a way of explaining refactoring to non-technical stakeholders. He later stressed that the metaphor covers deliberate trade-offs, not sloppiness.",
    ex: ["The estimate is three days plus a decade of tech debt.", "Every quarter we agree to pay down tech debt and every quarter we do not."],
    rel: ["refactor", "spaghetti-code", "legacy-code"], tags: ["metaphor", "process", "maintenance"],
  },
  {
    slug: "works-on-my-machine", term: "Works on my machine", pron: "wurks on my muh-SHEEN", pos: "phrase", cat: "tech",
    year: 2005, pop: 55, trend: 0, status: "classic",
    def: "A defence offered when code fails elsewhere, and the standard illustration of why reproducible environments matter.",
    eli: "Saying the program works fine on your own computer, so the problem must be someone else's.",
    org: "Long-standing developer folklore, formalised as a joke certification badge in the late 2000s. Containers were sold largely as the answer to this exact sentence.",
    ex: ["Works on my machine, which is not a deployment strategy.", "The whole reason Docker sold was this phrase."],
    rel: ["heisenbug", "flaky-test", "tech-debt"], tags: ["debugging", "folklore", "devops"],
  },
  {
    slug: "heisenbug", term: "Heisenbug", pron: "HY-zun-bug", pos: "noun", cat: "tech",
    year: 1985, pop: 38, trend: 1, status: "classic",
    def: "A defect that changes behaviour or disappears when you try to observe it, typically because the act of debugging alters timing or memory layout.",
    eli: "A bug that vanishes as soon as you try to look at it closely.",
    org: "Named after Heisenberg's uncertainty principle, in use among programmers from the 1980s. Related coinages include the Bohrbug, which is reliably reproducible.",
    ex: ["Added one log line and the heisenbug went away.", "It only fails in production and only on Tuesdays."],
    rel: ["works-on-my-machine", "flaky-test", "race-condition"], tags: ["debugging", "folklore", "physics"],
  },
  {
    slug: "spaghetti-code", term: "Spaghetti code", pron: "spuh-GET-ee kohd", pos: "noun", cat: "tech",
    year: 1977, pop: 52, trend: 0, status: "classic",
    def: "Code whose control flow is so tangled that following it requires tracing every strand. Usually the result of many small reasonable changes over years.",
    eli: "Code so tangled that following what it does is like pulling one strand out of a bowl of spaghetti.",
    org: "In use by the late 1970s, when the structured programming movement argued against unrestricted jumps. The image outlived the specific argument that produced it.",
    ex: ["Six hundred lines and four exit points. Spaghetti code.", "Nobody writes spaghetti code deliberately."],
    rel: ["tech-debt", "legacy-code", "refactor"], tags: ["quality", "maintenance", "history"],
  },
  {
    slug: "legacy-code", term: "Legacy code", pron: "LEG-uh-see kohd", pos: "noun", cat: "tech",
    year: 1990, pop: 60, trend: 1, status: "classic",
    def: "Code inherited rather than written, usually critical and poorly understood. One influential definition is simply code without tests.",
    eli: "Old code you did not write, that everything depends on, and that nobody fully understands.",
    org: "Michael Feathers reframed the term in 2004 as code without tests, shifting it from an insult about age to a statement about how safely it can be changed.",
    ex: ["It is legacy code the moment the author leaves.", "Working effectively with legacy code is an entire discipline."],
    rel: ["tech-debt", "spaghetti-code", "bus-factor"], tags: ["maintenance", "testing", "inheritance"],
  },
  {
    slug: "refactor", term: "Refactor", pron: "ree-FAK-tur", pos: "verb", cat: "tech",
    year: 1990, pop: 63, trend: 0, status: "classic",
    def: "To restructure code without changing what it does. Strictly, behaviour must be preserved; loosely, it now covers any rewrite anyone feels like doing.",
    eli: "Tidying up code so it is easier to work with, without changing what it actually does.",
    org: "Formalised by William Opdyke's 1992 thesis and popularised by Martin Fowler's 1999 book. The precise meaning erodes constantly in casual use.",
    ex: ["It is not a refactor if the output changed.", "Two weeks to refactor, three days to explain why."],
    rel: ["tech-debt", "legacy-code", "code-smell"], tags: ["practice", "quality", "fowler"],
  },
  {
    slug: "code-smell", term: "Code smell", pron: "kohd smel", pos: "noun", cat: "tech",
    year: 1999, pop: 46, trend: 0, status: "classic",
    def: "A surface indication that something deeper may be wrong. Not a defect in itself, but a prompt to look harder.",
    eli: "Something in the code that looks off and suggests a bigger problem underneath.",
    org: "Attributed to Kent Beck and popularised in Fowler's Refactoring in 1999. The metaphor is deliberately imprecise: a smell is a reason to investigate, not a verdict.",
    ex: ["Five boolean parameters is a code smell.", "It is a smell, not a rule. Look before rewriting."],
    rel: ["refactor", "spaghetti-code", "tech-debt"], tags: ["quality", "heuristic", "fowler"],
  },
  {
    slug: "cargo-cult", term: "Cargo cult programming", pron: "KAR-goh kult", pos: "noun", cat: "tech",
    year: 1974, pop: 41, trend: 0, status: "classic",
    def: "Copying the form of a practice without understanding why it works, so the ritual is preserved and the benefit is not.",
    eli: "Copying what experts do without understanding why, so it looks right but does nothing.",
    org: "From Richard Feynman's 1974 Caltech address on cargo cult science. Applied to programming for code copied without comprehension, and to process for rituals kept after their purpose is gone.",
    ex: ["The config has four settings nobody can justify. Cargo cult.", "Daily standups with no decisions are cargo cult agile."],
    rel: ["bikeshedding", "dogfooding", "tech-debt"], tags: ["practice", "feynman", "process"],
  },
  {
    slug: "footgun", term: "Footgun", pron: "FOOT-gun", pos: "noun", cat: "tech",
    year: 2005, pop: 39, trend: 6, status: "rising",
    def: "A feature that works as designed while making it easy to cause serious harm to yourself. Not a bug, but an invitation.",
    eli: "A feature that works properly but makes it very easy to break something badly by accident.",
    org: "From the older phrase about shooting yourself in the foot, long applied to C++. The compressed noun spread through language design discussion in the 2010s.",
    ex: ["Silent type coercion is a footgun.", "The API is powerful and the safety catch is optional."],
    rel: ["code-smell", "dark-pattern", "tech-debt"], tags: ["design", "api", "safety"],
  },
  {
    slug: "enshittification", term: "Enshittification", pron: "en-shit-if-i-KAY-shun", pos: "noun", cat: "tech",
    year: 2022, pop: 71, trend: 24, status: "rising",
    def: "The predictable decay of a platform: first it is good to users, then it abuses users to favour business customers, then it abuses those too, then it dies.",
    eli: "The way apps start out great, then get worse on purpose to make more money, until everyone leaves.",
    org: "Coined by Cory Doctorow in November 2022. The American Dialect Society named it word of the year for 2023, and it now appears in regulatory and academic writing.",
    ex: ["Search results are ninety percent ads. Textbook enshittification.", "The enshittification curve is remarkably consistent across platforms."],
    rel: ["dark-pattern", "walled-garden", "ai-slop"], tags: ["platforms", "doctorow", "2023"],
  },
  {
    slug: "dark-pattern", term: "Dark pattern", pron: "dark PAT-urn", pos: "noun", cat: "tech",
    year: 2010, pop: 64, trend: 8, status: "mainstream",
    def: "An interface designed to trick users into choices they would not knowingly make, such as buried unsubscribe links or pre-ticked consent boxes.",
    eli: "A design made on purpose to trick you into clicking something you did not want.",
    org: "Coined by user-experience researcher Harry Brignull in 2010, who catalogued the taxonomy. The term now appears in EU and US regulation, sometimes as deceptive design.",
    ex: ["Cancelling takes six screens and a phone call. Dark pattern.", "Confirmshaming the decline button is a named pattern."],
    rel: ["enshittification", "footgun", "walled-garden"], tags: ["ux", "regulation", "deception"],
  },
  {
    slug: "walled-garden", term: "Walled garden", pron: "wawld GAR-dun", pos: "noun", cat: "tech",
    year: 1995, pop: 53, trend: 3, status: "classic",
    def: "A platform that keeps users inside its own ecosystem by limiting what can be exported, linked to or interoperated with.",
    eli: "A service that makes it hard to take your stuff somewhere else, so you stay.",
    org: "Telecoms vocabulary applied to AOL in the 1990s, when its content was easier to reach than the open web. The argument recurs with every dominant platform.",
    ex: ["No export, no API, no links out. Walled garden.", "AOL was the walled garden, then app stores were."],
    rel: ["enshittification", "aol", "api"], tags: ["platforms", "lock-in", "history"],
  },
  {
    slug: "move-fast", term: "Move fast and break things", pron: "moov fast", pos: "phrase", cat: "tech",
    year: 2009, pop: 57, trend: -4, status: "classic",
    def: "A development philosophy prioritising speed over stability, on the argument that the cost of being slow exceeds the cost of breakage.",
    eli: "The idea that it is better to build quickly and fix mistakes later than to be careful and slow.",
    org: "Facebook's internal motto, made public around 2009 and quietly retired in 2014 for move fast with stable infrastructure. The original is now used mostly as criticism.",
    ex: ["Move fast and break things, then spend four years in hearings.", "The motto outlived the company that abandoned it."],
    rel: ["tech-debt", "mvp", "pivot"], tags: ["startups", "facebook", "philosophy"],
  },
  {
    slug: "mvp", term: "MVP", pron: "em-vee-PEE", pos: "abbreviation", cat: "tech",
    year: 2001, pop: 61, trend: -2, status: "classic",
    def: "Minimum viable product: the smallest version that tests whether an idea works. In practice frequently used to justify shipping something unfinished.",
    eli: "The smallest version of a product you can build to find out whether anyone wants it.",
    org: "Coined by Frank Robinson in 2001 and popularised by Eric Ries in The Lean Startup. Ries stressed the learning goal, which is the part most often dropped.",
    ex: ["The MVP has been in production for three years.", "Minimum was achieved, viable is contested."],
    rel: ["move-fast", "pivot", "tech-debt"], tags: ["startups", "lean", "product"],
  },
  {
    slug: "pivot", term: "Pivot", pron: "PIV-ut", pos: "verb", cat: "tech",
    year: 2009, pop: 58, trend: -1, status: "classic",
    def: "A structured change of business direction while keeping something learned from the previous attempt. Colloquially, any change of plan announced confidently.",
    eli: "Changing what your company does, while keeping what you learned from the last idea.",
    org: "Formalised by Eric Ries around 2009 as a specific manoeuvre with criteria. It quickly became a general euphemism for abandoning a plan.",
    ex: ["They pivoted from dog food to enterprise software.", "It is a pivot if you learned something, otherwise it is a restart."],
    rel: ["mvp", "move-fast", "unicorn"], tags: ["startups", "lean", "business"],
  },
  {
    slug: "unicorn", term: "Unicorn", pron: "YOO-nik-orn", pos: "noun", cat: "tech",
    year: 2013, pop: 55, trend: -3, status: "classic",
    def: "A private company valued at over one billion dollars. Named for rarity, at a time when the status was genuinely unusual.",
    eli: "A startup worth more than a billion dollars before it is publicly listed.",
    org: "Coined by investor Aileen Lee in a 2013 article counting thirty-nine such companies. There are now over a thousand, which has rather undermined the metaphor.",
    ex: ["Unicorn status, negative margins, enormous burn.", "When there are a thousand unicorns, the word has stopped working."],
    rel: ["pivot", "mvp", "burn-rate"], tags: ["startups", "funding", "valuation"],
  },
  {
    slug: "bus-factor", term: "Bus factor", pron: "bus FAK-tur", pos: "noun", cat: "tech",
    year: 1994, pop: 42, trend: 4, status: "classic",
    def: "The number of people who would have to be hit by a bus before a project became unmaintainable. A bus factor of one is extremely common and rarely acknowledged.",
    eli: "How many people would have to disappear before nobody knows how something works.",
    org: "Discussed on programming mailing lists from the mid-1990s. Sometimes softened to lottery factor, which describes the same risk more cheerfully.",
    ex: ["Bus factor of one on the billing system.", "Half the internet depends on packages with a bus factor of one."],
    rel: ["legacy-code", "open-source", "tech-debt"], tags: ["risk", "maintenance", "teams"],
  },
  {
    slug: "404", term: "404", pron: "for-oh-FOR", pos: "noun", cat: "tech",
    year: 1992, pop: 76, trend: 0, status: "classic",
    def: "The HTTP status code for a resource that does not exist. Used figuratively for anything or anyone absent when needed.",
    eli: "The error you get when a web page is not there.",
    org: "Defined in the original HTTP specification. It escaped into general speech faster than any other status code, largely because everyone eventually sees one.",
    ex: ["Every link in the footer is a 404.", "Asked him for the file and got a 404."],
    rel: ["500", "link-rot", "dead-link"], tags: ["http", "error", "web"],
  },
  {
    slug: "500", term: "500", pron: "fyve HUN-drud", pos: "noun", cat: "tech",
    year: 1992, pop: 44, trend: 0, status: "classic",
    def: "Internal server error: the server failed and cannot say why. Where a 404 blames the request, a 500 admits the fault is at home.",
    eli: "An error meaning the website itself broke, not your link.",
    org: "Part of the original HTTP status code specification. The distinction between four hundred and five hundred codes, client fault versus server fault, is the useful part.",
    ex: ["Checkout is throwing 500s.", "A 404 is your problem, a 500 is theirs."],
    rel: ["404", "incident", "postmortem"], tags: ["http", "error", "operations"],
  },
  {
    slug: "link-rot", term: "Link rot", pron: "link rot", pos: "noun", cat: "tech",
    year: 1996, pop: 40, trend: 7, status: "mainstream",
    def: "The steady decay of hyperlinks as the pages they point to move or vanish, quietly destroying the web's citation graph.",
    eli: "The way old links slowly stop working as pages disappear.",
    org: "Studied since the mid-1990s. Research has repeatedly found that a large share of links in news articles and even court opinions break within a decade.",
    ex: ["Half the citations in that 2011 post are link rot.", "Archive it now or lose it."],
    rel: ["404", "wayback-machine", "dead-link"], tags: ["preservation", "web", "archives"],
  },
  {
    slug: "wayback-machine", term: "Wayback Machine", pron: "WAY-bak muh-SHEEN", pos: "noun", cat: "tech",
    year: 2001, pop: 58, trend: 5, status: "classic",
    def: "The Internet Archive's public store of historical web page snapshots, and the closest thing the web has to a memory.",
    eli: "A website that saves old copies of web pages so you can see what they used to say.",
    org: "Launched publicly in 2001 by the Internet Archive, founded by Brewster Kahle in 1996. It is now routinely cited as evidence of what a page said before it was edited.",
    ex: ["The original wording is on the Wayback Machine.", "Deleted, but archived. The internet does forget, just unevenly."],
    rel: ["link-rot", "receipts", "geocities"], tags: ["archives", "preservation", "evidence"],
  },
  {
    slug: "dogfooding", term: "Dogfooding", pron: "DOG-food-ing", pos: "verb", cat: "tech",
    year: 1988, pop: 45, trend: 1, status: "classic",
    def: "Using your own product internally, on the theory that you will notice problems your users would otherwise have to report.",
    eli: "Using the thing you built yourself, so you find the problems before customers do.",
    org: "From eating your own dog food, popularised at Microsoft in 1988 by a manager who challenged a team to run on their own software. Now standard practice with a slightly unpleasant name.",
    ex: ["We dogfood the beta for a fortnight before release.", "Nobody on the team actually uses it, which explains a lot."],
    rel: ["mvp", "cargo-cult", "feature-flag"], tags: ["practice", "microsoft", "quality"],
  },
  {
    slug: "feature-flag", term: "Feature flag", pron: "FEE-chur flag", pos: "noun", cat: "tech",
    year: 2010, pop: 48, trend: 3, status: "mainstream",
    def: "A switch that turns functionality on or off without a new release, letting code ship dark and be enabled gradually or reverted instantly.",
    eli: "A switch that turns a feature on or off without releasing new code.",
    org: "Popularised by Flickr and Facebook engineering writing around 2009 and 2010, as continuous deployment made separating release from launch essential.",
    ex: ["Ship it behind a flag and enable for one percent.", "The flag has been at one hundred percent since 2021 and nobody has removed it."],
    rel: ["canary", "rollback", "dogfooding"], tags: ["deployment", "practice", "risk"],
  },
  {
    slug: "postmortem", term: "Postmortem", pron: "pohst-MOR-tum", pos: "noun", cat: "tech",
    year: 2003, pop: 50, trend: 2, status: "classic",
    def: "A written review of an incident covering what happened, why, and what will change. Blameless postmortems deliberately exclude individual fault to keep the account honest.",
    eli: "A write-up after something breaks, explaining what went wrong so it does not happen again.",
    org: "Adopted from aviation and medicine into software operations, and codified by Google's site reliability engineering practice. The blameless framing is the load-bearing part.",
    ex: ["The postmortem found four contributing causes and no villain.", "If people are hiding facts, the postmortem is not blameless."],
    rel: ["incident", "500", "rollback"], tags: ["operations", "sre", "process"],
  },
  {
    slug: "incident", term: "Incident", pron: "IN-sid-unt", pos: "noun", cat: "tech",
    year: 2005, pop: 47, trend: 2, status: "classic",
    def: "An unplanned service disruption, graded by severity. Sev-1 typically means everything is down and everybody is awake.",
    eli: "When a service breaks badly enough that a team has to drop everything and fix it.",
    org: "Operations vocabulary borrowed from emergency services, with named roles such as incident commander taken almost directly from firefighting practice.",
    ex: ["Sev-1 at 3am, resolved by 6, postmortem on Thursday.", "Declaring an incident early is cheaper than declaring one late."],
    rel: ["postmortem", "500", "oncall"], tags: ["operations", "sre", "reliability"],
  },
  {
    slug: "code-review", term: "Code review", pron: "kohd ri-VYOO", pos: "noun", cat: "tech",
    year: 2000, pop: 57, trend: 1, status: "classic",
    def: "Reading a colleague's changes before they are merged. Nominally about defects, in practice about shared understanding and, frequently, about naming.",
    eli: "Someone else reading your code before it goes live, to catch problems.",
    org: "Formalised by Michael Fagan at IBM in 1976 as a heavyweight inspection process. Pull requests made the lightweight version universal after 2008.",
    ex: ["Approved with one comment about a variable name.", "Reviews catch design problems more often than bugs."],
    rel: ["pull-request", "bikeshedding", "code-smell"], tags: ["practice", "collaboration", "quality"],
  },
  {
    slug: "flaky-test", term: "Flaky test", pron: "FLAY-kee test", pos: "noun", cat: "tech",
    year: 2012, pop: 44, trend: 3, status: "mainstream",
    def: "A test that passes and fails without any change to the code, usually because of timing or shared state. Corrosive because it teaches people to ignore failures.",
    eli: "A test that sometimes passes and sometimes fails for no reason, so people stop trusting it.",
    org: "Named as continuous integration became standard. Google published influential data showing a substantial fraction of its test failures were flakes rather than real defects.",
    ex: ["Rerun it, it is just the flaky one.", "A flaky test is worse than no test, because it trains you to click retry."],
    rel: ["heisenbug", "race-condition", "works-on-my-machine"], tags: ["testing", "ci", "reliability"],
  },
  {
    slug: "race-condition", term: "Race condition", pron: "rays kun-DISH-un", pos: "noun", cat: "tech",
    year: 1954, pop: 48, trend: 0, status: "classic",
    def: "A defect where the outcome depends on the unpredictable order of concurrent operations, so the same input can produce different results.",
    eli: "A bug where two things happen at once and the result depends on which finishes first.",
    org: "Electronics vocabulary from the 1950s, describing signals racing through a circuit. It transferred directly to concurrent software and remains one of the hardest bug classes to reproduce.",
    ex: ["Two requests, one row, and the balance went negative.", "Race conditions are why the bug only appears under load."],
    rel: ["heisenbug", "flaky-test", "deadlock"], tags: ["concurrency", "debugging", "history"],
  },
  {
    slug: "rollback", term: "Rollback", pron: "ROHL-bak", pos: "noun", cat: "tech",
    year: 2005, pop: 51, trend: 1, status: "classic",
    def: "Reverting a deployment to the previous working version. The first question in most incidents is whether a rollback is possible.",
    eli: "Putting the old version back after a new one breaks something.",
    org: "Database vocabulary, where a transaction rolls back on failure, generalised to deployment. Database migrations are the usual reason a rollback turns out not to be possible.",
    ex: ["Rolled back in ninety seconds, investigated for three days.", "You cannot roll back a migration that dropped a column."],
    rel: ["incident", "feature-flag", "canary"], tags: ["deployment", "operations", "recovery"],
  },
  {
    slug: "canary", term: "Canary release", pron: "kuh-NAIR-ee ri-LEES", pos: "noun", cat: "tech",
    year: 2010, pop: 42, trend: 2, status: "mainstream",
    def: "Releasing a change to a small fraction of traffic first, so failures are detected on a limited blast radius before a full rollout.",
    eli: "Giving a new version to a few users first, to see if anything breaks.",
    org: "Named after the canary in a coal mine. It became standard practice as continuous deployment made large simultaneous releases unnecessarily risky.",
    ex: ["Canary at one percent caught the memory leak.", "Canarying only works if you are actually watching the metrics."],
    rel: ["rollback", "feature-flag", "incident"], tags: ["deployment", "risk", "practice"],
  },
  {
    slug: "oncall", term: "On-call", pron: "ON-kawl", pos: "noun", cat: "tech",
    year: 2008, pop: 49, trend: 2, status: "classic",
    def: "A rotation in which an engineer carries responsibility for responding to alerts outside working hours. Alert fatigue is the standard failure mode.",
    eli: "Taking turns being the person who gets woken up if something breaks at night.",
    org: "Borrowed wholesale from medicine, including the vocabulary of rotations and handovers. Google's site reliability engineering book made the practice explicit and widely copied.",
    ex: ["Third page before 4am and none of them actionable.", "If on-call is miserable, the alerts are wrong, not the people."],
    rel: ["incident", "postmortem", "rollback"], tags: ["operations", "sre", "labour"],
  },
  {
    slug: "rebase", term: "Rebase", pron: "ree-BAYS", pos: "verb", cat: "tech",
    year: 2005, pop: 45, trend: 0, status: "classic",
    def: "To replay your commits on top of a newer base, producing a linear history. Rewriting shared history this way is the source of a permanent team argument.",
    eli: "Rewriting your changes so they look like they were made after everyone else's.",
    org: "A Git operation from 2005. Whether to rebase or merge is a genuine trade-off between a readable history and an accurate one, which is why it never gets settled.",
    ex: ["Rebase before opening the pull request.", "Never rebase a branch someone else has pulled."],
    rel: ["merge-conflict", "pull-request", "fork"], tags: ["git", "history", "workflow"],
  },
  {
    slug: "api", term: "API", pron: "ay-pee-EYE", pos: "abbreviation", cat: "tech",
    year: 2000, pop: 76, trend: 1, status: "classic",
    def: "Application programming interface: the defined way one piece of software talks to another. In platform politics, whether an API exists at all is usually the whole story.",
    eli: "The agreed way one program can ask another program for something.",
    org: "The concept dates to the 1940s; the modern web sense arrives with Salesforce and eBay around 2000. API access has since become the main lever platforms use to control what third parties can build.",
    ex: ["The API closed and forty apps died in a week.", "An API is a promise, and promises get withdrawn."],
    rel: ["walled-garden", "enshittification", "webhook"], tags: ["platforms", "integration", "power"],
  },
  {
    slug: "deadlock", term: "Deadlock", pron: "DED-lok", pos: "noun", cat: "tech",
    year: 1965, pop: 38, trend: 0, status: "classic",
    def: "A standstill where two or more processes each hold a resource the other needs, so none can proceed and none will release.",
    eli: "When two programs each wait for something the other is holding, so both wait forever.",
    org: "Formalised by Edsger Dijkstra in 1965 through the dining philosophers problem, which remains the standard teaching illustration sixty years later.",
    ex: ["Two transactions, opposite lock order, permanent deadlock.", "The database detects it and kills one at random, which is its own problem."],
    rel: ["race-condition", "heisenbug", "incident"], tags: ["concurrency", "dijkstra", "theory"],
  },
  {
    slug: "webhook", term: "Webhook", pron: "WEB-hook", pos: "noun", cat: "tech",
    year: 2007, pop: 41, trend: 2, status: "classic",
    def: "A callback that pushes data to a URL when something happens, so a service can notify you rather than being repeatedly asked.",
    eli: "A way for one service to tell another that something happened, instead of being asked over and over.",
    org: "Coined by Jeff Lindsay in 2007. The design inverts polling, which is why it became the default integration mechanism for almost every platform.",
    ex: ["The webhook fires on merge and posts to the channel.", "Retries and duplicate delivery are the part everyone forgets."],
    rel: ["api", "walled-garden", "incident"], tags: ["integration", "events", "platforms"],
  },
  {
    slug: "burn-rate", term: "Burn rate", pron: "burn rayt", pos: "noun", cat: "tech",
    year: 2000, pop: 43, trend: 1, status: "classic",
    def: "How quickly a company spends its cash reserves, usually quoted monthly. Divided into cash on hand it gives runway, the months remaining before the money runs out.",
    eli: "How fast a company is spending its money, and how long it has left before it runs out.",
    org: "Venture capital vocabulary that entered general use during the dot-com era. Runway is the number that actually determines behaviour, since it sets the fundraising deadline.",
    ex: ["Nine months of runway at the current burn rate.", "Every layoff announcement is a runway calculation."],
    rel: ["unicorn", "pivot", "mvp"], tags: ["startups", "finance", "funding"],
  },
  {
    slug: "monorepo", term: "Monorepo", pron: "MON-oh-ree-poh", pos: "noun", cat: "tech",
    year: 2015, pop: 44, trend: 3, status: "niche",
    def: "A single version-controlled repository holding the code for multiple projects or services, as opposed to splitting each into its own separate repository.",
    eli: "Keeping the code for many different projects together in one big shared folder instead of many separate ones.",
    org: "Practised internally at large tech companies for years before the term spread publicly around 2015, as tooling matured enough to make the approach viable outside a handful of giants.",
    ex: ["Moved everything into a monorepo and the shared tooling finally made sense.", "The monorepo versus many-repos debate resurfaces every few years."],
    rel: ["fork", "merge-conflict", "code-review"], tags: ["architecture", "tooling", "workflow"],
  },
  {
    slug: "microservices", term: "Microservices", pron: "MY-kroh-sur-vis-iz", pos: "noun", cat: "tech",
    year: 2011, pop: 52, trend: -2, status: "mainstream",
    def: "An architecture splitting an application into many small, independently deployable services, each responsible for one function, communicating over a network.",
    eli: "Building an app as lots of small separate pieces that each do one job and talk to each other, instead of one big combined program.",
    org: "The term was popularised around 2011 to 2014, promising easier scaling and independent deployment, though critics note it trades one set of problems for a different, more distributed set.",
    ex: ["Split the monolith into microservices and immediately gained a distributed systems problem.", "Microservices solve organisational problems as much as technical ones."],
    rel: ["monorepo", "webhook", "legacy-code"], tags: ["architecture", "backend", "2010s"],
  },
  {
    slug: "serverless", term: "Serverless", pron: "SUR-vur-les", pos: "adjective", cat: "tech",
    year: 2014, pop: 46, trend: 1, status: "mainstream",
    def: "A cloud computing model where code runs in response to events without the developer managing any underlying server, despite servers obviously still existing somewhere.",
    eli: "Running code in the cloud without having to manage a server yourself, even though a server is still doing the work behind the scenes.",
    org: "Named around 2014 as cloud providers launched function-as-a-service products, and immediately mocked for the name being technically inaccurate, since servers are still very much involved.",
    ex: ["Serverless just means someone else's server, as the joke goes.", "Billing per request made serverless genuinely cheap for spiky traffic."],
    rel: ["webhook", "microservices", "canary"], tags: ["cloud", "architecture", "2014"],
  },
  {
    slug: "devops", term: "DevOps", pron: "DEV-ops", pos: "noun", cat: "tech",
    year: 2009, pop: 55, trend: 0, status: "mainstream",
    def: "A set of practices and culture merging software development and IT operations, aiming to ship changes faster and more reliably through automation and shared responsibility.",
    eli: "A way of working that blends building software and running it in production, so releases happen faster and more smoothly.",
    org: "Named at a 2009 conference blending development and operations, in reaction to the older model where developers wrote code and a separate team deployed it, often slowly and with friction.",
    ex: ["A real DevOps culture means developers carry the pager too.", "DevOps became a job title almost as often as it stayed a philosophy."],
    rel: ["oncall", "incident", "postmortem"], tags: ["culture", "operations", "2009"],
  },
  {
    slug: "ci-cd", term: "CI/CD", pron: "see-eye see-DEE", pos: "noun", cat: "tech",
    year: 2010, pop: 48, trend: 1, status: "mainstream",
    def: "Continuous integration and continuous deployment: automated pipelines that test code changes as they are made and, when they pass, ship them to production without manual steps.",
    eli: "An automatic system that tests your code changes and then releases them, without a person having to manually do each step.",
    org: "Building on continuous integration practices from the 2000s, the combined pipeline became standard vocabulary through the 2010s as automated testing and deployment tooling matured.",
    ex: ["The CI/CD pipeline caught the bug before it ever reached production.", "A red CI/CD build blocks the merge, no exceptions."],
    rel: ["pull-request", "canary", "rollback"], tags: ["automation", "workflow", "deployment"],
  },
  {
    slug: "hotfix", term: "Hotfix", pron: "HOT-fiks", pos: "noun", cat: "tech",
    year: 1998, pop: 51, trend: 0, status: "classic",
    def: "A quick, narrowly scoped code change deployed urgently outside the normal release schedule to fix a critical bug already affecting users.",
    eli: "A quick emergency fix pushed out immediately to solve a serious problem, without waiting for the next planned update.",
    org: "Standard software vocabulary since the late 1990s, describing the small, urgent, high-risk deployment that skips the usual careful review in favour of speed.",
    ex: ["Shipped a hotfix at midnight once the outage started.", "Hotfixes are the ones most likely to introduce a second bug."],
    rel: ["incident", "rollback", "postmortem"], tags: ["deployment", "urgency", "classic"],
  },
  {
    slug: "sre", term: "SRE", pron: "es-ar-EE", pos: "abbreviation", cat: "tech",
    year: 2003, pop: 40, trend: 4, status: "niche",
    def: "Site reliability engineering: a discipline applying software engineering practices to operations, using measurable reliability targets to decide how much risk a system can absorb.",
    eli: "A job and approach focused on keeping software running reliably, using clear numerical targets to decide how careful to be.",
    org: "Developed internally at Google starting in 2003 and made public through a widely read 2016 book, introducing concepts like error budgets that formalised the trade-off between speed and stability.",
    ex: ["The SRE team owns the uptime target, not just the on-call rotation.", "Error budgets are the most useful idea SRE culture introduced."],
    rel: ["devops", "oncall", "incident"], tags: ["operations", "reliability", "google"],
  },
  {
    slug: "feature-creep", term: "Feature creep", pron: "FEE-chur kreep", pos: "noun", cat: "tech",
    year: 1994, pop: 49, trend: 2, status: "classic",
    def: "The gradual, often unplanned expansion of a product's features over time, eventually making it more complex and harder to use than originally intended.",
    eli: "When a product slowly gains more and more features over time until it becomes bloated and confusing.",
    org: "Standard software engineering vocabulary since the mid-1990s, naming a failure mode that predates computing entirely but became especially visible once software made adding features cheap.",
    ex: ["The app started simple and feature creep turned it into a maze of settings.", "Every roadmap meeting is a small negotiation against feature creep."],
    rel: ["scope-creep", "mvp", "tech-debt"], tags: ["product", "design", "classic"],
  },
  {
    slug: "sprint", term: "Sprint", pron: "sprint", pos: "noun", cat: "tech",
    year: 1995, pop: 57, trend: -1, status: "classic",
    def: "A fixed, short time period, typically one to four weeks, during which a development team commits to completing a defined set of work.",
    eli: "A short, set period of time, like two weeks, where a team focuses on finishing a specific list of tasks.",
    org: "Introduced as part of the Scrum framework in the mid-1990s, borrowing the running metaphor to signal a burst of focused effort with a hard deadline.",
    ex: ["That feature slipped to the next sprint again.", "Sprint planning always runs long, ironically."],
    rel: ["standup", "agile", "mvp"], tags: ["agile", "scrum", "workflow"],
  },
  {
    slug: "standup", term: "Standup", pron: "STAND-up", pos: "noun", cat: "tech",
    year: 1996, pop: 54, trend: -2, status: "classic",
    def: "A brief daily team meeting where each person states what they did, what they plan to do, and any blockers, traditionally held standing up to keep it short.",
    eli: "A quick daily team meeting where everyone shares what they are working on and if anything is blocking them.",
    org: "Part of the Scrum agile framework from the mid-1990s, the standing requirement was meant literally, as a physical incentive to keep the meeting under fifteen minutes.",
    ex: ["Standup ran forty minutes today, which defeats the entire point.", "Async standups replaced the live version for most remote teams."],
    rel: ["sprint", "agile", "wfh"], tags: ["agile", "scrum", "meetings"],
  },
  {
    slug: "agile", term: "Agile", pron: "AJ-uyl", pos: "noun", cat: "tech",
    year: 2001, pop: 58, trend: -3, status: "classic",
    def: "A family of iterative software development approaches favouring short cycles, frequent feedback and adaptability over rigid upfront planning.",
    eli: "A way of building software in short cycles with lots of feedback, instead of planning everything out perfectly at the start.",
    org: "Formalised in a 2001 manifesto written by seventeen software developers, reacting against slower, heavily documented planning-first methods that struggled to adapt to changing requirements.",
    ex: ["Called it agile, ran it exactly like the old process with extra meetings.", "Real agile and agile in name only look very different in practice."],
    rel: ["sprint", "standup", "waterfall"], tags: ["methodology", "2001", "workflow"],
  },
  {
    slug: "waterfall", term: "Waterfall", pron: "WAW-tur-fawl", pos: "noun", cat: "tech",
    year: 1970, pop: 44, trend: -4, status: "classic",
    def: "A linear development approach in which each phase, such as design, building and testing, must fully complete before the next begins, with little room for revisiting earlier decisions.",
    eli: "An old way of building software where each stage has to be fully finished before the next one starts, in strict order.",
    org: "Described in a 1970 paper, ironically as an example of a flawed approach the author was cautioning against, though the name stuck as the default label for sequential, upfront-planned development.",
    ex: ["Still running waterfall, and the six-month spec is already outdated.", "Waterfall works fine when requirements genuinely will not change."],
    rel: ["agile", "sprint", "mvp"], tags: ["methodology", "classic", "planning"],
  },
  {
    slug: "greenfield", term: "Greenfield", pron: "GREEN-feeld", pos: "adjective", cat: "tech",
    year: 1990, pop: 42, trend: 0, status: "classic",
    def: "Describing a project built from scratch with no existing code, constraints or legacy systems to work around.",
    eli: "Starting a project completely from scratch, with no old code or systems to deal with.",
    org: "Borrowed from construction and urban planning, where a greenfield site has never been built on, applied to software from around 1990 onward.",
    ex: ["A rare greenfield project, no legacy code in sight.", "Greenfield work is the closest thing to a clean slate this job offers."],
    rel: ["legacy-code", "tech-debt", "mvp"], tags: ["projects", "classic", "planning"],
  },
  {
    slug: "brownfield", term: "Brownfield", pron: "BROWN-feeld", pos: "adjective", cat: "tech",
    year: 1995, pop: 38, trend: 1, status: "classic",
    def: "Describing a project that must build on or integrate with existing systems, code and constraints, the opposite of greenfield.",
    eli: "Building something new that has to work with old existing systems and code already in place.",
    org: "Also borrowed from construction, where a brownfield site has prior development to work around, applied to software from the mid-1990s.",
    ex: ["Brownfield migration, and the old system has no documentation.", "Almost all real engineering work is brownfield, whatever the job posting implies."],
    rel: ["greenfield", "legacy-code", "tech-debt"], tags: ["projects", "classic", "legacy"],
  },
  {
    slug: "toil", term: "Toil", pron: "toyl", pos: "noun", cat: "tech",
    year: 2016, pop: 33, trend: 3, status: "niche",
    def: "Manual, repetitive operational work that scales linearly with system growth and provides no lasting engineering value, a concept formalised to justify automating it away.",
    eli: "Boring, repetitive manual work that has to be redone constantly and does not actually improve anything long-term.",
    org: "Defined precisely in a 2016 site reliability engineering book to distinguish genuinely valuable operational work from work that should be automated instead.",
    ex: ["Half the on-call rotation is pure toil that a script could handle.", "Reducing toil is treated as a real engineering deliverable on that team."],
    rel: ["sre", "oncall", "devops"], tags: ["operations", "sre", "workflow"],
  },
  {
    slug: "scope-creep", term: "Scope creep", pron: "skohp kreep", pos: "noun", cat: "tech",
    year: 1980, pop: 51, trend: 1, status: "classic",
    def: "The gradual expansion of a project's requirements beyond what was originally agreed, usually through a series of individually small, reasonable-seeming additions.",
    eli: "When a project slowly grows bigger and bigger than originally planned, one small extra request at a time.",
    org: "Project management vocabulary since around 1980, describing a failure that rarely arrives as one dramatic decision but rather as an accumulation of many small ones.",
    ex: ["Scope creep turned a two-week project into a two-month one.", "Every requirements document needs a defence against scope creep."],
    rel: ["feature-creep", "mvp", "tech-debt"], tags: ["project-management", "planning", "classic"],
  },
];
