import type { RawTerm } from "../types";

export const textTerms: RawTerm[] = [
  {
    slug: "lol", term: "LOL", pron: "el-oh-EL", pos: "abbreviation", cat: "text",
    year: 1989, pop: 91, trend: -2, status: "classic",
    def: "Laughing out loud. Long since detached from actual laughter, it now functions as a softener that marks a message as non-hostile.",
    eli: "It used to mean you laughed. Now it mostly means the message is friendly and not serious.",
    org: "Attested on Usenet and BBS chat from the late 1980s, credited to Wayne Pearson in 1989. Its drift from description to tone marker is the most studied change in internet English.",
    ex: ["sorry im late lol", "lol no"],
    rel: ["lmao", "ijbol", "tone-indicator"], tags: ["abbreviation", "laughter", "usenet"],
  },
  {
    slug: "lmao", term: "LMAO", pron: "luh-MOW", pos: "abbreviation", cat: "text",
    year: 1990, pop: 84, trend: -1, status: "classic",
    def: "A stronger laughter marker than LOL, which by the 2010s had lost most of its force. Extended forms add letters for further emphasis.",
    eli: "A stronger version of LOL, used when something is actually funny.",
    org: "Emerged on BBSes shortly after LOL and took over its original job once LOL had softened into politeness. The same cycle later produced IJBOL.",
    ex: ["lmao he actually did it", "lmaooo the timing"],
    rel: ["lol", "rofl", "ijbol"], tags: ["abbreviation", "laughter", "bbs"],
  },
  {
    slug: "rofl", term: "ROFL", pron: "ROF-ul", pos: "abbreviation", cat: "text",
    year: 1993, pop: 38, trend: -6, status: "fading",
    def: "Rolling on the floor laughing. Now dated enough that using it sincerely reads as a generational marker.",
    eli: "An old way of saying something was very funny.",
    org: "Usenet and IRC of the early 1990s. The extended ROFLMAO stacked two markers together, which was already a joke about escalation by 1996.",
    ex: ["rofl, that takes me back", "Nobody has typed ROFL unironically since about 2009."],
    rel: ["lol", "lmao", "ijbol"], tags: ["abbreviation", "laughter", "irc"],
  },
  {
    slug: "brb", term: "BRB", pron: "bee-ar-BEE", pos: "abbreviation", cat: "text",
    year: 1990, pop: 62, trend: -3, status: "classic",
    def: "Be right back. A courtesy notice that you are leaving a live conversation briefly, from an era when presence was ambiguous.",
    eli: "Be right back. You type it before stepping away from a chat.",
    org: "IRC and instant messenger convention. It mattered most when there was no other way to tell whether someone was still at the keyboard.",
    ex: ["brb, doorbell", "He said brb in 2011 and the conversation never resumed."],
    rel: ["afk", "gtg", "irc"], tags: ["abbreviation", "chat", "irc"],
  },
  {
    slug: "afk", term: "AFK", pron: "ay-ef-KAY", pos: "abbreviation", cat: "text",
    year: 1994, pop: 68, trend: 0, status: "classic",
    def: "Away from keyboard. In games it also names the offence of occupying a slot while contributing nothing.",
    eli: "Away from keyboard. In games it also means someone who is there but not playing.",
    org: "IRC and MUD convention that hardened into a formal game state, with automatic AFK detection and penalties in most multiplayer titles.",
    ex: ["afk two minutes", "One player went afk in the first round and stayed there."],
    rel: ["brb", "gtg", "griefing"], tags: ["abbreviation", "gaming", "irc"],
  },
  {
    slug: "gtg", term: "GTG", pron: "jee-tee-JEE", pos: "abbreviation", cat: "text",
    year: 1997, pop: 41, trend: -4, status: "fading",
    def: "Got to go. The standard sign-off of instant messenger conversations, often paired with a promise to continue later.",
    eli: "Got to go. A quick way of ending a chat.",
    org: "AOL Instant Messenger and MSN Messenger vocabulary, where conversations were sessions with clear beginnings and endings rather than open threads.",
    ex: ["gtg, dinner, ttyl", "gtg but send it anyway"],
    rel: ["brb", "afk", "ttyl"], tags: ["abbreviation", "messenger", "chat"],
  },
  {
    slug: "ttyl", term: "TTYL", pron: "tee-tee-why-EL", pos: "abbreviation", cat: "text",
    year: 1998, pop: 33, trend: -7, status: "fading",
    def: "Talk to you later. A closing formula from the era when chat had explicit endings rather than trailing off.",
    eli: "Talk to you later. A way of saying goodbye in a chat.",
    org: "Instant messenger vocabulary of the late 1990s. Its decline tracks the shift from session-based chat to always-on messaging.",
    ex: ["ttyl, good luck tomorrow", "Nobody says ttyl now because no conversation ever formally ends."],
    rel: ["gtg", "brb", "lol"], tags: ["abbreviation", "messenger", "farewell"],
  },
  {
    slug: "tldr", term: "TL;DR", pron: "tee-el-dee-AR", pos: "abbreviation", cat: "text",
    year: 2003, pop: 78, trend: 1, status: "classic",
    def: "Too long; didn't read. Used both as a complaint about length and, more often now, as a heading introducing an author's own summary.",
    eli: "Too long, did not read. Now mostly used as a label for a short summary at the top.",
    org: "Something Awful forums in the early 2000s as a dismissal. Reddit inverted it into a courtesy, which is how it is almost always used today.",
    ex: ["TL;DR: the update broke logins and they know.", "Four thousand words and no tldr."],
    rel: ["op", "eli5", "til"], tags: ["abbreviation", "forums", "reddit"],
  },
  {
    slug: "imo", term: "IMO", pron: "eye-em-OH", pos: "abbreviation", cat: "text",
    year: 1990, pop: 64, trend: -2, status: "classic",
    def: "In my opinion. IMHO adds humble, which online usually signals the opposite of humility.",
    eli: "In my opinion. IMHO means in my humble opinion, often not humbly.",
    org: "Usenet convention, where marking a claim as opinion was a genuine courtesy in threads that otherwise assumed you were stating fact.",
    ex: ["IMO the first season is the only one that works.", "IMHO, and I do mean humbly, this is a bad idea."],
    rel: ["afaik", "ymmv", "tbh"], tags: ["abbreviation", "usenet", "opinion"],
  },
  {
    slug: "tbh", term: "TBH", pron: "tee-bee-AYCH", pos: "abbreviation", cat: "text",
    year: 2003, pop: 76, trend: -1, status: "classic",
    def: "To be honest. A hedge that prepares the reader for a mild admission, and briefly a social format in which users solicited candid assessments.",
    eli: "To be honest. It warns that something a bit blunt is coming.",
    org: "Forum and messenger shorthand that became a teenage social ritual on Facebook and Instagram around 2015, where a like earned you a tbh in return.",
    ex: ["tbh I never finished it", "Like for a tbh was the entire content strategy of 2015."],
    rel: ["ngl", "imo", "fwiw"], tags: ["abbreviation", "honesty", "instagram"],
  },
  {
    slug: "ngl", term: "NGL", pron: "en-jee-EL", pos: "abbreviation", cat: "text",
    year: 2015, pop: 80, trend: 4, status: "mainstream",
    def: "Not gonna lie. A hedge that introduces a mild confession, usually one the speaker expects to be slightly unpopular.",
    eli: "Not going to lie. It warns that you are about to admit something.",
    org: "Texting shorthand that displaced TBH among younger users during the 2010s, following the same softening pattern as every other honesty marker.",
    ex: ["ngl the remake is better", "ngl I have no idea what that meeting was for"],
    rel: ["tbh", "imo", "fr"], tags: ["abbreviation", "honesty", "texting"],
  },
  {
    slug: "smh", term: "SMH", pron: "es-em-AYCH", pos: "abbreviation", cat: "text",
    year: 2010, pop: 72, trend: -2, status: "classic",
    def: "Shaking my head. Registers disappointment or disbelief without argument, standing in for a gesture rather than a statement.",
    eli: "Shaking my head. It shows you are disappointed without saying why.",
    org: "Black Twitter and forum vocabulary of the late 2000s. Part of a family of typed gestures that also includes facepalm and side eye.",
    ex: ["Cancelled the only good line. smh", "smh at the entire comment section"],
    rel: ["side-eye", "facepalm", "bruh"], tags: ["abbreviation", "reaction", "twitter"],
  },
  {
    slug: "iirc", term: "IIRC", pron: "eye-eye-ar-SEE", pos: "abbreviation", cat: "text",
    year: 1992, pop: 44, trend: 0, status: "classic",
    def: "If I recall correctly. A hedge that flags a claim as remembered rather than checked, and invites correction.",
    eli: "If I remember right. It admits you might be slightly wrong.",
    org: "Usenet convention from a culture where being corrected was expected and pre-empting it was considered good manners.",
    ex: ["IIRC that feature shipped and was pulled a month later.", "IIRC, though do check."],
    rel: ["afaik", "imo", "ymmv"], tags: ["abbreviation", "usenet", "hedging"],
  },
  {
    slug: "afaik", term: "AFAIK", pron: "ay-fayk", pos: "abbreviation", cat: "text",
    year: 1991, pop: 40, trend: -1, status: "classic",
    def: "As far as I know. Marks the limits of the speaker's information rather than the strength of their opinion.",
    eli: "As far as I know. It means this is true unless someone knows better.",
    org: "Usenet and mailing-list vocabulary, part of the same hedging toolkit as IIRC and YMMV that early technical communities built to keep threads civil.",
    ex: ["AFAIK the API has not changed since March.", "AFAIK nobody has tried it on that hardware."],
    rel: ["iirc", "ymmv", "imo"], tags: ["abbreviation", "usenet", "hedging"],
  },
  {
    slug: "ymmv", term: "YMMV", pron: "why-em-em-VEE", pos: "abbreviation", cat: "text",
    year: 1993, pop: 36, trend: 0, status: "classic",
    def: "Your mileage may vary. Warns that a recommendation is personal and may not transfer, borrowed from American fuel-economy disclaimers.",
    eli: "What worked for me might not work for you.",
    org: "Taken from car advertising, where it was a legal disclaimer. Usenet adopted it in the early 1990s as a general caveat and it never left.",
    ex: ["It fixed it for me, YMMV.", "Great in a quiet room. YMMV on a train."],
    rel: ["afaik", "iirc", "imo"], tags: ["abbreviation", "usenet", "caveat"],
  },
  {
    slug: "op", term: "OP", pron: "oh-PEE", pos: "abbreviation", cat: "text",
    year: 2004, pop: 74, trend: 1, status: "classic",
    def: "Original poster, or original post. Names the person who started a thread, and by extension the obligation to answer them rather than each other.",
    eli: "The person who started the thread, or the first message in it.",
    org: "Forum vocabulary formalised by Reddit and imageboards, where thread structure made the distinction between OP and everyone else load-bearing.",
    ex: ["OP never came back to explain.", "Answering the question OP actually asked would be novel."],
    rel: ["tldr", "ama", "thread"], tags: ["abbreviation", "forums", "reddit"],
  },
  {
    slug: "eli5", term: "ELI5", pron: "ee-el-eye-FYVE", pos: "abbreviation", cat: "text",
    year: 2011, pop: 58, trend: 2, status: "classic",
    def: "Explain like I am five. A request for an explanation stripped of jargon, with the understanding that some precision will be lost.",
    eli: "Asking someone to explain something in the simplest possible way.",
    org: "The subreddit r/explainlikeimfive, created in 2011, whose rules explicitly asked for simplified rather than literally childish answers.",
    ex: ["ELI5 how interest rates actually reach my rent.", "The ELI5 version is that nobody knows."],
    rel: ["tldr", "til", "ama"], tags: ["abbreviation", "reddit", "explanation"],
  },
  {
    slug: "til", term: "TIL", pron: "tee-eye-EL", pos: "abbreviation", cat: "text",
    year: 2008, pop: 55, trend: 0, status: "classic",
    def: "Today I learned. Introduces a fact the poster has just discovered, with the implication that others may not know it either.",
    eli: "Today I learned. Used to share something you just found out.",
    org: "Reddit's r/todayilearned, founded in 2008, which turned the phrase into a whole content genre and then into general shorthand.",
    ex: ["TIL the shipping forecast has a fixed running order.", "TIL I have been pronouncing it wrong for a decade."],
    rel: ["eli5", "ama", "op"], tags: ["abbreviation", "reddit", "facts"],
  },
  {
    slug: "ama", term: "AMA", pron: "ay-em-AY", pos: "abbreviation", cat: "text",
    year: 2009, pop: 60, trend: -2, status: "classic",
    def: "Ask me anything. A question-and-answer format in which someone with unusual access or experience takes open questions from a crowd.",
    eli: "A session where someone answers whatever questions people ask them.",
    org: "Reddit's r/IAmA, founded in 2009, which formalised the structure and the proof requirement. The format has since been copied by nearly every platform.",
    ex: ["I run the night shift at a lighthouse, AMA.", "The AMA lasted nine minutes and answered two questions."],
    rel: ["til", "op", "eli5"], tags: ["abbreviation", "reddit", "format"],
  },
  {
    slug: "fyi", term: "FYI", pron: "ef-why-EYE", pos: "abbreviation", cat: "text",
    year: 1980, pop: 66, trend: 0, status: "classic",
    def: "For your information. Neutral in origin, but in workplace email it now frequently carries an edge, marking something the reader should already have known.",
    eli: "For your information. In work emails it often means you should have known this already.",
    org: "Office memo shorthand that predates the internet, carried into email and then absorbed into chat, where its passive-aggressive reading became dominant.",
    ex: ["FYI, the deadline moved on Tuesday.", "An FYI with three people cc'd is never an FYI."],
    rel: ["psa", "op", "period-full-stop"], tags: ["abbreviation", "email", "work"],
  },
  {
    slug: "nsfw", term: "NSFW", pron: "en-es-ef-DUB", pos: "abbreviation", cat: "text",
    year: 2000, pop: 71, trend: 0, status: "classic",
    def: "Not safe for work. A courtesy tag warning that a link should not be opened where a screen is visible to colleagues.",
    eli: "A warning that a link is not something to open at work or around other people.",
    org: "Email forwarding culture around 2000, then formalised as a tag by forums and Reddit. NSFL, not safe for life, marks genuinely disturbing material.",
    ex: ["Great thread, one image is NSFW.", "Tag it NSFW or do not post it."],
    rel: ["tone-indicator", "content-warning", "spoiler-tag"], tags: ["abbreviation", "moderation", "courtesy"],
  },
  {
    slug: "tone-indicator", term: "Tone indicator", pron: "tohn IN-dik-ay-tur", pos: "noun", cat: "text",
    year: 2019, pop: 47, trend: 6, status: "rising",
    def: "A suffix marking the intent behind a message, such as /s for sarcasm, /j for joking or /srs for serious. Text carries no prosody, so the tag supplies it.",
    eli: "A little tag at the end of a message that tells you if it is a joke or serious.",
    org: "Reddit used /s for sarcasm from the late 2000s. The wider system was formalised on Twitter and TikTok around 2019, driven substantially by autistic and neurodivergent users.",
    ex: ["Wonderful, another meeting /s", "Your cooking is a war crime /j"],
    rel: ["lol", "content-warning", "keysmash"], tags: ["tone", "accessibility", "punctuation"],
  },
  {
    slug: "content-warning", term: "Content warning", pron: "KON-tent WOR-ning", pos: "noun", cat: "text",
    year: 2013, pop: 52, trend: 2, status: "mainstream",
    def: "A note placed before material that some readers may wish to approach carefully or skip. Abbreviated CW; TW for trigger warning is the older and narrower form.",
    eli: "A note at the top warning you what a post is about, so you can decide whether to read it.",
    org: "Feminist blogging and LiveJournal communities in the 2000s, generalised by Tumblr in the 2010s and now built into most platforms as a native feature.",
    ex: ["CW: discussion of hospitals in the second half.", "The tag exists so people can choose, not so nobody can post."],
    rel: ["nsfw", "spoiler-tag", "tone-indicator"], tags: ["moderation", "tumblr", "courtesy"],
  },
  {
    slug: "spoiler-tag", term: "Spoiler tag", pron: "SPOY-lur tag", pos: "noun", cat: "text",
    year: 1994, pop: 56, trend: 0, status: "classic",
    def: "Markup that hides plot details until deliberately revealed. On Usenet this was achieved by blank lines; modern platforms blur or collapse the text.",
    eli: "Hidden text that only shows a story detail if you choose to reveal it.",
    org: "Usenet groups devised spoiler space and rot13 encoding in the early 1990s. Every forum and chat platform since has reinvented the same courtesy in its own markup.",
    ex: ["Put the ending behind a spoiler tag.", "Untagged spoilers in the thread title is a hostile act."],
    rel: ["content-warning", "rot13", "nsfw"], tags: ["usenet", "courtesy", "markup"],
  },
  {
    slug: "keysmash", term: "Keysmash", pron: "KEE-smash", pos: "noun", cat: "text",
    year: 2010, pop: 49, trend: 3, status: "mainstream",
    def: "A run of random letters representing speechless excitement or distress. Conventions have hardened: it usually begins with a and favours the home row.",
    eli: "Mashing the keyboard to show you are too excited or overwhelmed for words.",
    org: "Tumblr and LiveJournal fandom, where emotional intensity outran vocabulary. Studies of the form show surprisingly consistent unwritten rules about what a valid keysmash looks like.",
    ex: ["asdfghjkl they announced the tour", "The keysmash said more than a paragraph would have"],
    rel: ["screaming", "tone-indicator", "letter-stretching"], tags: ["tumblr", "fandom", "expression"],
  },
  {
    slug: "letter-stretching", term: "Letter stretching", pron: "LET-ur STRECH-ing", pos: "noun", cat: "text",
    year: 2005, pop: 53, trend: 1, status: "classic",
    def: "Repeating a letter to lengthen a word and signal intensity or duration, as in noooo or heyyy. Vowel count maps roughly to feeling.",
    eli: "Repeating letters to show how strongly you mean something.",
    org: "An early and durable solution to the problem that typed text has no volume or pitch. Instant messenger culture set the conventions still in use.",
    ex: ["nooooo not the good bakery", "heyyy, quick favour"],
    rel: ["keysmash", "all-caps", "tone-indicator"], tags: ["expression", "chat", "prosody"],
  },
  {
    slug: "all-caps", term: "All caps", pron: "awl kaps", pos: "noun", cat: "text",
    year: 1984, pop: 61, trend: 0, status: "classic",
    def: "Capitalising an entire message, read as shouting. One of the oldest and most stable conventions in online writing.",
    eli: "Typing in capitals, which reads as shouting.",
    org: "Documented on Usenet and BBSes by the mid-1980s, with etiquette guides warning against it years before the web existed. The reading has never meaningfully changed.",
    ex: ["I AM NOT SHOUTING, THIS IS EXCITEMENT", "Please stop replying in all caps."],
    rel: ["lowercase", "letter-stretching", "period-full-stop"], tags: ["etiquette", "usenet", "prosody"],
  },
  {
    slug: "lowercase", term: "Lowercase", pron: "LOH-ur-kays", pos: "noun", cat: "text",
    year: 2012, pop: 58, trend: 4, status: "mainstream",
    def: "Writing without capitals as a deliberate register, signalling casualness, intimacy or a flattened affect rather than carelessness.",
    eli: "Typing with no capital letters on purpose, to sound relaxed rather than formal.",
    org: "Tumblr and Twitter in the early 2010s, where dropping capitals distinguished personal writing from institutional writing. Now a recognised marker of sincerity among younger users.",
    ex: ["anyway i think about this a lot", "The brand account switched to lowercase and fooled nobody."],
    rel: ["all-caps", "period-full-stop", "tone-indicator"], tags: ["register", "tumblr", "style"],
  },
  {
    slug: "period-full-stop", term: "The full stop", pron: "thuh FOOL stop", pos: "noun", cat: "text",
    year: 2013, pop: 57, trend: 2, status: "mainstream",
    def: "In short messages, ending a sentence with a full stop reads as cold or annoyed, because the line break already ends the thought and the punctuation must mean something else.",
    eli: "In a text, a full stop can make a message sound angry, because it is not needed to end the sentence.",
    org: "Documented by linguists including Gretchen McCulloch from the early 2010s. Studies found readers consistently rated full-stopped one-word replies as less sincere.",
    ex: ["He replied fine. and I have not recovered.", "ok vs ok. is the entire difference"],
    rel: ["lowercase", "all-caps", "tone-indicator"], tags: ["punctuation", "tone", "linguistics"],
  },
  {
    slug: "skull-emoji", term: "Skull emoji", pron: "skul i-MOH-jee", pos: "noun", cat: "text",
    year: 2020, pop: 74, trend: 5, status: "mainstream",
    def: "Marks something as extremely funny, on the logic that it killed you. It displaced the laughing-crying emoji, which younger users came to read as dated.",
    eli: "The skull means something was so funny it killed you. It replaced the laughing-crying face.",
    org: "Gen Z convention that hardened around 2020, part of the same escalation cycle that produced deceased and screaming as laughter markers.",
    ex: ["the caption on that one, skull", "Using the crying-laughing face now marks you as over thirty."],
    rel: ["crying", "im-deceased", "emoji"], tags: ["emoji", "laughter", "gen-z"],
  },
  {
    slug: "emoji", term: "Emoji", pron: "i-MOH-jee", pos: "noun", cat: "text",
    year: 1999, pop: 87, trend: 0, status: "classic",
    def: "Standardised pictographic characters encoded in Unicode. Distinct from emoticons, which are built from ordinary punctuation.",
    eli: "The little pictures you can type, like faces and animals. They are real characters, not images.",
    org: "Created by Shigetaka Kurita for NTT DoCoMo in 1999. Unicode adoption in 2010 made them universal, and the name comes from Japanese for picture character, not from emotion.",
    ex: ["The whole reply was three emoji and it was devastating.", "Emoji meanings drift by platform and by generation."],
    rel: ["emoticon", "skull-emoji", "kaomoji"], tags: ["unicode", "japan", "pictograph"],
  },
  {
    slug: "emoticon", term: "Emoticon", pron: "i-MOH-tik-on", pos: "noun", cat: "text",
    year: 1982, pop: 44, trend: -3, status: "classic",
    def: "A facial expression built from punctuation, read sideways in the Western tradition. The direct ancestor of emoji, and still in use.",
    eli: "A face made out of punctuation marks, like a colon and a bracket.",
    org: "Proposed by Scott Fahlman on a Carnegie Mellon bulletin board in September 1982, to mark jokes in text. The problem he was solving is the same one tone indicators solve today.",
    ex: [":) still does a job no emoji quite matches", "The 1982 post proposing it is still archived."],
    rel: ["emoji", "kaomoji", "tone-indicator"], tags: ["bbs", "history", "punctuation"],
  },
  {
    slug: "kaomoji", term: "Kaomoji", pron: "kah-oh-MOH-jee", pos: "noun", cat: "text",
    year: 1986, pop: 38, trend: 1, status: "niche",
    def: "Japanese-style emoticons read upright rather than sideways, using a wide character set to build expressive faces such as shrugs and blushes.",
    eli: "Japanese-style text faces that you read the right way up instead of sideways.",
    org: "Developed on Japanese BBSes from the mid-1980s, independently of Western emoticons. The shrug became one of the most copied strings on the internet.",
    ex: ["Sent the shrug and closed the laptop.", "Kaomoji do more with characters than most emoji manage with colour."],
    rel: ["emoticon", "emoji", "uwu"], tags: ["japan", "bbs", "expression"],
  },
  {
    slug: "uwu", term: "UwU", pron: "OO-woo", pos: "interjection", cat: "text",
    year: 2005, pop: 46, trend: -5, status: "niche",
    def: "A kaomoji depicting a contented face, and by extension a whole cutesy register in which words are softened, as in owo and hewwo.",
    eli: "A little text face showing happiness, and a very cute way of typing that goes with it.",
    org: "Anime forums and DeviantArt in the mid-2000s. Later adopted ironically far beyond its origins, to the point where sincere use is now the marked case.",
    ex: ["uwu", "The entire changelog was written in uwu speak and nobody could stop them."],
    rel: ["kaomoji", "emoticon", "weeb"], tags: ["anime", "cute", "register"],
  },
  {
    slug: "irl", term: "IRL", pron: "eye-ar-EL", pos: "abbreviation", cat: "text",
    year: 1990, pop: 70, trend: -4, status: "classic",
    def: "In real life. Distinguishes offline events from online ones, a division that has become progressively harder to maintain.",
    eli: "In real life, meaning offline rather than on the internet.",
    org: "Usenet and MUD vocabulary, from an era when the two spheres genuinely were separate. Some users now prefer AFK or offline, on the grounds that online life is also real.",
    ex: ["We finally met IRL after nine years of replies.", "The IRL and online distinction stopped working around 2015."],
    rel: ["afk", "meatspace"], tags: ["abbreviation", "usenet", "offline"],
  },
  {
    slug: "dm", term: "DM", pron: "dee-EM", pos: "noun", cat: "text",
    year: 2007, pop: 83, trend: 1, status: "classic",
    def: "Direct message. A private message inside a public platform, and as a verb the act of sending one. Sliding into someone's DMs implies romantic intent.",
    eli: "A private message on a social app. Sliding into the DMs means messaging someone you fancy.",
    org: "Named by Twitter at launch in 2006 to distinguish private messages from public replies. The term spread to every platform regardless of what each one calls the feature.",
    ex: ["DM me the address.", "He slid into the DMs with a spelling mistake and no follow-up."],
    rel: ["op", "subtweet", "thirst-trap"], tags: ["abbreviation", "twitter", "messaging"],
  },
  {
    slug: "omg", term: "OMG", pron: "oh-em-JEE", pos: "abbreviation", cat: "text",
    year: 1917, pop: 79, trend: -2, status: "classic",
    def: "Oh my God. A surprise marker that has softened over a century of use into general emphasis.",
    eli: "Oh my God. Used to show surprise or excitement.",
    org: "First attested in a 1917 letter from Admiral John Fisher to Winston Churchill, decades before computers. Chat culture rediscovered it independently in the 1990s.",
    ex: ["omg the tickets are already gone", "A First World War admiral got there before Messenger did."],
    rel: ["wtf", "lol", "istg"], tags: ["abbreviation", "history", "surprise"],
  },
  {
    slug: "wtf", term: "WTF", pron: "dub-tee-EF", pos: "abbreviation", cat: "text",
    year: 1985, pop: 81, trend: 0, status: "classic",
    def: "An expression of blunt confusion or disbelief. Softened considerably by decades of use, and now common in contexts that would once have refused it.",
    eli: "A rude way of saying what on earth is going on.",
    org: "Attested on Usenet from the mid-1980s. Its gradual acceptability is a standard example of how taboo strength decays under high-frequency use.",
    ex: ["wtf is this pricing page", "wtf, genuinely, how did that ship"],
    rel: ["omg", "smh", "bruh"], tags: ["abbreviation", "usenet", "disbelief"],
  },
  {
    slug: "jk", term: "JK", pron: "jay-KAY", pos: "abbreviation", cat: "text",
    year: 1994, pop: 52, trend: -5, status: "classic",
    def: "Just kidding. A retroactive marker converting a statement into a joke, and frequently a way of testing a reaction before committing to it.",
    eli: "Just kidding. Added after something to show it was a joke.",
    org: "Instant messenger shorthand of the 1990s. The modern /j tone indicator does the same job, but is placed as a tag rather than as a retraction.",
    ex: ["you should quit. jk. unless?", "jk did a lot of work in that sentence"],
    rel: ["tone-indicator", "lol", "unserious"], tags: ["abbreviation", "humour", "chat"],
  },
  {
    slug: "psa", term: "PSA", pron: "pee-es-AY", pos: "abbreviation", cat: "text",
    year: 2009, pop: 48, trend: 0, status: "classic",
    def: "Public service announcement. Introduces information the poster considers generally useful, often with a hint of exasperation that it needs saying.",
    eli: "A notice telling everyone something useful they probably did not know.",
    org: "Borrowed from broadcast regulation, where PSAs were mandated free airtime. Forums adopted the framing to lend weight to unsolicited advice.",
    ex: ["PSA: the clocks change on Sunday.", "PSA to whoever keeps microwaving fish."],
    rel: ["fyi", "til", "op"], tags: ["abbreviation", "announcement", "forums"],
  },
  {
    slug: "istg", term: "ISTG", pron: "eye-es-tee-JEE", pos: "abbreviation", cat: "text",
    year: 2013, pop: 51, trend: 2, status: "mainstream",
    def: "I swear to God. An intensifier expressing exasperation or insistence, usually about something trivial.",
    eli: "I swear to God. Used when you are annoyed or really mean something.",
    org: "Texting shorthand of the early 2010s, part of the same family as ONG and FR. The oath form long predates any of them.",
    ex: ["istg if the train is delayed again", "istg I put it down right here"],
    rel: ["ong", "deadass", "fr"], tags: ["abbreviation", "texting", "exasperation"],
  },
  {
    slug: "bruh", term: "Bruh", pron: "bruh", pos: "interjection", cat: "text",
    year: 2010, pop: 78, trend: 1, status: "classic",
    def: "A single-word reaction expressing disbelief, disappointment or resignation. Carries no content; the whole message is the tone.",
    eli: "A one-word way of showing you cannot believe what just happened.",
    org: "A clipped form of brother in African American Vernacular English, in use for decades. Vine made it a punchline in the mid-2010s and it has functioned as pure interjection ever since.",
    ex: ["Bruh.", "The reply was one word and it said everything."],
    rel: ["smh", "facepalm", "wtf"], tags: ["aave", "reaction", "vine"],
  },
  {
    slug: "facepalm", term: "Facepalm", pron: "FAYS-pahm", pos: "noun", cat: "text",
    year: 2001, pop: 54, trend: -2, status: "classic",
    def: "The gesture of putting a hand to your face in exasperation, written as a stage direction or posted as an image before an emoji existed for it.",
    eli: "Covering your face with your hand because something was so silly.",
    org: "Named on forums in the early 2000s and carried by a Star Trek screenshot of Picard that became the definitive reaction image. Unicode added the gesture in 2016.",
    ex: ["Read the error message. Facepalm.", "Picard did more for this word than anyone."],
    rel: ["smh", "bruh", "reaction-image"], tags: ["reaction", "star-trek", "gesture"],
  },
  {
    slug: "fwiw", term: "FWIW", pron: "ef-dub-eye-DUB", pos: "abbreviation", cat: "text",
    year: 1993, pop: 33, trend: 0, status: "classic",
    def: "For what it is worth. Marks a contribution as offered rather than insisted upon, and occasionally as a polite prelude to disagreement.",
    eli: "For what it is worth. A way of offering an opinion without pushing it.",
    org: "Usenet hedging vocabulary, alongside IMO, AFAIK and YMMV. Its survival in professional email is largely due to how much softening one small acronym can do.",
    ex: ["FWIW, we tried that in 2019 and it did not hold.", "FWIW is doing a lot of diplomacy in that sentence."],
    rel: ["imo", "afaik", "ymmv"], tags: ["abbreviation", "usenet", "hedging"],
  },
  {
    slug: "coded", term: "-coded", pron: "KOH-did", pos: "suffix", cat: "text",
    year: 2020, pop: 58, trend: 9, status: "rising",
    def: "A suffix meaning giving off the qualities of, without literally being: sibling-coded, villain-coded, Tuesday-coded. Attaches to almost anything.",
    eli: "An ending meaning something gives off the feeling of a thing, without actually being it.",
    org: "Adapted from queer-coding in film criticism, where a character signals an identity without it being stated. Fandom generalised it around 2020 into a productive suffix.",
    ex: ["That jacket is deeply villain-coded.", "The whole album is autumn-coded."],
    rel: ["core-suffix", "its-giving", "pilled"], tags: ["morphology", "fandom", "suffix"],
  },
  {
    slug: "pilled", term: "-pilled", pron: "pild", pos: "suffix", cat: "text",
    year: 2016, pop: 46, trend: 4, status: "mainstream",
    def: "A suffix meaning converted to a belief: blackpilled, cottagecore-pilled, whitepilled. Signals a conversion experience rather than a mere opinion.",
    eli: "An ending meaning someone has been won over to an idea, as if they swallowed a pill.",
    org: "From the red pill in The Matrix, adopted by online political subcultures from around 2016 and then defused by ironic and trivial uses like sleep-pilled.",
    ex: ["Fully sleep-pilled, in bed by nine.", "The suffix escaped its politics by being applied to everything."],
    rel: ["coded", "maxxing", "core-suffix"], tags: ["morphology", "matrix", "suffix"],
  },
  {
    slug: "maxxing", term: "-maxxing", pron: "MAKS-ing", pos: "suffix", cat: "text",
    year: 2015, pop: 49, trend: 11, status: "rising",
    def: "A suffix meaning optimising one thing to the exclusion of others: looksmaxxing, sleepmaxxing, moneymaxxing. Treats life as a character sheet.",
    eli: "An ending meaning you are trying to max out one part of your life, like a stat in a game.",
    org: "From role-playing game vocabulary for maximising a stat, adopted by incel and bodybuilding forums in the 2010s and softened into general wellness content on TikTok.",
    ex: ["Sleepmaxxing is just going to bed on time with better branding.", "Everything is a stat now."],
    rel: ["looksmaxxing", "pilled", "mewing"], tags: ["morphology", "gaming", "suffix"],
  },
  {
    slug: "rot13", term: "ROT13", pron: "rot-thur-TEEN", pos: "noun", cat: "text",
    year: 1982, pop: 22, trend: 0, status: "classic",
    def: "A cipher rotating each letter thirteen places, used on Usenet to hide spoilers and punchlines. Trivially reversible, which was the point.",
    eli: "A simple code that shifts letters so text is hidden until you decode it.",
    org: "A Usenet convention from the early 1980s. It offered no security whatsoever, only a deliberate pause before reading, which made it the first spoiler tag.",
    ex: ["Punchline in ROT13 so nobody reads it by accident.", "Applying ROT13 twice returns the original, which is a standing joke."],
    rel: ["spoiler-tag", "usenet", "netiquette"], tags: ["usenet", "cipher", "spoilers"],
  },
];
