import type { RawTerm } from "../types";

export const textTerms: RawTerm[] = [
  {
    slug: "lol", term: "LOL", pron: "el-oh-EL", pos: "abbreviation", cat: "text",
    year: 1989, pop: 91, trend: -2, status: "classic",
    def: "Laughing out loud. Long since detached from actual laughter, it now functions as a softener that marks a message as non-hostile.",
    eli: "It used to mean you laughed. Now it mostly means the message is friendly and not serious.",
    org: "Attested on Usenet and BBS chat from the late 1980s, credited to Wayne Pearson in 1989. Its drift from description to tone marker is the most studied change in internet English.",
    ex: ["sorry im late lol", "lol no"],
    rel: ["lmao", "ijbol", "tone-indicator"], tags: ["abbreviation", "laughter", "usenet"],
  },
  {
    slug: "lmao", term: "LMAO", pron: "luh-MOW", pos: "abbreviation", cat: "text",
    year: 1990, pop: 84, trend: -1, status: "classic",
    def: "A stronger laughter marker than LOL, which by the 2010s had lost most of its force. Extended forms add letters for further emphasis.",
    eli: "A stronger version of LOL, used when something is actually funny.",
    org: "Emerged on BBSes shortly after LOL and took over its original job once LOL had softened into politeness. The same cycle later produced IJBOL.",
    ex: ["lmao he actually did it", "lmaooo the timing"],
    rel: ["lol", "rofl", "ijbol"], tags: ["abbreviation", "laughter", "bbs"],
  },
  {
    slug: "rofl", term: "ROFL", pron: "ROF-ul", pos: "abbreviation", cat: "text",
    year: 1993, pop: 38, trend: -6, status: "fading",
    def: "Rolling on the floor laughing. Now dated enough that using it sincerely reads as a generational marker.",
    eli: "An old way of saying something was very funny.",
    org: "Usenet and IRC of the early 1990s. The extended ROFLMAO stacked two markers together, which was already a joke about escalation by 1996.",
    ex: ["rofl, that takes me back", "Nobody has typed ROFL unironically since about 2009."],
    rel: ["lol", "lmao", "ijbol"], tags: ["abbreviation", "laughter", "irc"],
  },
  {
    slug: "brb", term: "BRB", pron: "bee-ar-BEE", pos: "abbreviation", cat: "text",
    year: 1990, pop: 62, trend: -3, status: "classic",
    def: "Be right back. A courtesy notice that you are leaving a live conversation briefly, from an era when presence was ambiguous.",
    eli: "Be right back. You type it before stepping away from a chat.",
    org: "IRC and instant messenger convention. It mattered most when there was no other way to tell whether someone was still at the keyboard.",
    ex: ["brb, doorbell", "He said brb in 2011 and the conversation never resumed."],
    rel: ["afk", "gtg", "irc"], tags: ["abbreviation", "chat", "irc"],
  },
  {
    slug: "afk", term: "AFK", pron: "ay-ef-KAY", pos: "abbreviation", cat: "text",
    year: 1994, pop: 68, trend: 0, status: "classic",
    def: "Away from keyboard. In games it also names the offence of occupying a slot while contributing nothing.",
    eli: "Away from keyboard. In games it also means someone who is there but not playing.",
    org: "IRC and MUD convention that hardened into a formal game state, with automatic AFK detection and penalties in most multiplayer titles.",
    ex: ["afk two minutes", "One player went afk in the first round and stayed there."],
    rel: ["brb", "gtg", "griefing"], tags: ["abbreviation", "gaming", "irc"],
  },
  {
    slug: "gtg", term: "GTG", pron: "jee-tee-JEE", pos: "abbreviation", cat: "text",
    year: 1997, pop: 41, trend: -4, status: "fading",
    def: "Got to go. The standard sign-off of instant messenger conversations, often paired with a promise to continue later.",
    eli: "Got to go. A quick way of ending a chat.",
    org: "AOL Instant Messenger and MSN Messenger vocabulary, where conversations were sessions with clear beginnings and endings rather than open threads.",
    ex: ["gtg, dinner, ttyl", "gtg but send it anyway"],
    rel: ["brb", "afk", "ttyl"], tags: ["abbreviation", "messenger", "chat"],
  },
  {
    slug: "ttyl", term: "TTYL", pron: "tee-tee-why-EL", pos: "abbreviation", cat: "text",
    year: 1998, pop: 33, trend: -7, status: "fading",
    def: "Talk to you later. A closing formula from the era when chat had explicit endings rather than trailing off.",
    eli: "Talk to you later. A way of saying goodbye in a chat.",
    org: "Instant messenger vocabulary of the late 1990s. Its decline tracks the shift from session-based chat to always-on messaging.",
    ex: ["ttyl, good luck tomorrow", "Nobody says ttyl now because no conversation ever formally ends."],
    rel: ["gtg", "brb", "lol"], tags: ["abbreviation", "messenger", "farewell"],
  },
  {
    slug: "tldr", term: "TL;DR", pron: "tee-el-dee-AR", pos: "abbreviation", cat: "text",
    year: 2003, pop: 78, trend: 1, status: "classic",
    def: "Too long; didn't read. Used both as a complaint about length and, more often now, as a heading introducing an author's own summary.",
    eli: "Too long, did not read. Now mostly used as a label for a short summary at the top.",
    org: "Something Awful forums in the early 2000s as a dismissal. Reddit inverted it into a courtesy, which is how it is almost always used today.",
    ex: ["TL;DR: the update broke logins and they know.", "Four thousand words and no tldr."],
    rel: ["op", "eli5", "til"], tags: ["abbreviation", "forums", "reddit"],
  },
  {
    slug: "imo", term: "IMO", pron: "eye-em-OH", pos: "abbreviation", cat: "text",
    year: 1990, pop: 64, trend: -2, status: "classic",
    def: "In my opinion. IMHO adds humble, which online usually signals the opposite of humility.",
    eli: "In my opinion. IMHO means in my humble opinion, often not humbly.",
    org: "Usenet convention, where marking a claim as opinion was a genuine courtesy in threads that otherwise assumed you were stating fact.",
    ex: ["IMO the first season is the only one that works.", "IMHO, and I do mean humbly, this is a bad idea."],
    rel: ["afaik", "ymmv", "tbh"], tags: ["abbreviation", "usenet", "opinion"],
  },
  {
    slug: "tbh", term: "TBH", pron: "tee-bee-AYCH", pos: "abbreviation", cat: "text",
    year: 2003, pop: 76, trend: -1, status: "classic",
    def: "To be honest. A hedge that prepares the reader for a mild admission, and briefly a social format in which users solicited candid assessments.",
    eli: "To be honest. It warns that something a bit blunt is coming.",
    org: "Forum and messenger shorthand that became a teenage social ritual on Facebook and Instagram around 2015, where a like earned you a tbh in return.",
    ex: ["tbh I never finished it", "Like for a tbh was the entire content strategy of 2015."],
    rel: ["ngl", "imo", "fwiw"], tags: ["abbreviation", "honesty", "instagram"],
  },
  {
    slug: "ngl", term: "NGL", pron: "en-jee-EL", pos: "abbreviation", cat: "text",
    year: 2015, pop: 80, trend: 4, status: "mainstream",
    def: "Not gonna lie. A hedge that introduces a mild confession, usually one the speaker expects to be slightly unpopular.",
    eli: "Not going to lie. It warns that you are about to admit something.",
    org: "Texting shorthand that displaced TBH among younger users during the 2010s, following the same softening pattern as every other honesty marker.",
    ex: ["ngl the remake is better", "ngl I have no idea what that meeting was for"],
    rel: ["tbh", "imo", "fr"], tags: ["abbreviation", "honesty", "texting"],
  },
  {
    slug: "smh", term: "SMH", pron: "es-em-AYCH", pos: "abbreviation", cat: "text",
    year: 2010, pop: 72, trend: -2, status: "classic",
    def: "Shaking my head. Registers disappointment or disbelief without argument, standing in for a gesture rather than a statement.",
    eli: "Shaking my head. It shows you are disappointed without saying why.",
    org: "Black Twitter and forum vocabulary of the late 2000s. Part of a family of typed gestures that also includes facepalm and side eye.",
    ex: ["Cancelled the only good line. smh", "smh at the entire comment section"],
    rel: ["side-eye", "facepalm", "bruh"], tags: ["abbreviation", "reaction", "twitter"],
  },
  {
    slug: "iirc", term: "IIRC", pron: "eye-eye-ar-SEE", pos: "abbreviation", cat: "text",
    year: 1992, pop: 44, trend: 0, status: "classic",
    def: "If I recall correctly. A hedge that flags a claim as remembered rather than checked, and invites correction.",
    eli: "If I remember right. It admits you might be slightly wrong.",
    org: "Usenet convention from a culture where being corrected was expected and pre-empting it was considered good manners.",
    ex: ["IIRC that feature shipped and was pulled a month later.", "IIRC, though do check."],
    rel: ["afaik", "imo", "ymmv"], tags: ["abbreviation", "usenet", "hedging"],
  },
  {
    slug: "afaik", term: "AFAIK", pron: "ay-fayk", pos: "abbreviation", cat: "text",
    year: 1991, pop: 40, trend: -1, status: "classic",
    def: "As far as I know. Marks the limits of the speaker's information rather than the strength of their opinion.",
    eli: "As far as I know. It means this is true unless someone knows better.",
    org: "Usenet and mailing-list vocabulary, part of the same hedging toolkit as IIRC and YMMV that early technical communities built to keep threads civil.",
    ex: ["AFAIK the API has not changed since March.", "AFAIK nobody has tried it on that hardware."],
    rel: ["iirc", "ymmv", "imo"], tags: ["abbreviation", "usenet", "hedging"],
  },
  {
    slug: "ymmv", term: "YMMV", pron: "why-em-em-VEE", pos: "abbreviation", cat: "text",
    year: 1993, pop: 36, trend: 0, status: "classic",
    def: "Your mileage may vary. Warns that a recommendation is personal and may not transfer, borrowed from American fuel-economy disclaimers.",
    eli: "What worked for me might not work for you.",
    org: "Taken from car advertising, where it was a legal disclaimer. Usenet adopted it in the early 1990s as a general caveat and it never left.",
    ex: ["It fixed it for me, YMMV.", "Great in a quiet room. YMMV on a train."],
    rel: ["afaik", "iirc", "imo"], tags: ["abbreviation", "usenet", "caveat"],
  },
  {
    slug: "op", term: "OP", pron: "oh-PEE", pos: "abbreviation", cat: "text",
    year: 2004, pop: 74, trend: 1, status: "classic",
    def: "Original poster, or original post. Names the person who started a thread, and by extension the obligation to answer them rather than each other.",
    eli: "The person who started the thread, or the first message in it.",
    org: "Forum vocabulary formalised by Reddit and imageboards, where thread structure made the distinction between OP and everyone else load-bearing.",
    ex: ["OP never came back to explain.", "Answering the question OP actually asked would be novel."],
    rel: ["tldr", "ama", "thread"], tags: ["abbreviation", "forums", "reddit"],
  },
  {
    slug: "eli5", term: "ELI5", pron: "ee-el-eye-FYVE", pos: "abbreviation", cat: "text",
    year: 2011, pop: 58, trend: 2, status: "classic",
    def: "Explain like I am five. A request for an explanation stripped of jargon, with the understanding that some precision will be lost.",
    eli: "Asking someone to explain something in the simplest possible way.",
    org: "The subreddit r/explainlikeimfive, created in 2011, whose rules explicitly asked for simplified rather than literally childish answers.",
    ex: ["ELI5 how interest rates actually reach my rent.", "The ELI5 version is that nobody knows."],
    rel: ["tldr", "til", "ama"], tags: ["abbreviation", "reddit", "explanation"],
  },
  {
    slug: "til", term: "TIL", pron: "tee-eye-EL", pos: "abbreviation", cat: "text",
    year: 2008, pop: 55, trend: 0, status: "classic",
    def: "Today I learned. Introduces a fact the poster has just discovered, with the implication that others may not know it either.",
    eli: "Today I learned. Used to share something you just found out.",
    org: "Reddit's r/todayilearned, founded in 2008, which turned the phrase into a whole content genre and then into general shorthand.",
    ex: ["TIL the shipping forecast has a fixed running order.", "TIL I have been pronouncing it wrong for a decade."],
    rel: ["eli5", "ama", "op"], tags: ["abbreviation", "reddit", "facts"],
  },
  {
    slug: "ama", term: "AMA", pron: "ay-em-AY", pos: "abbreviation", cat: "text",
    year: 2009, pop: 60, trend: -2, status: "classic",
    def: "Ask me anything. A question-and-answer format in which someone with unusual access or experience takes open questions from a crowd.",
    eli: "A session where someone answers whatever questions people ask them.",
    org: "Reddit's r/IAmA, founded in 2009, which formalised the structure and the proof requirement. The format has since been copied by nearly every platform.",
    ex: ["I run the night shift at a lighthouse, AMA.", "The AMA lasted nine minutes and answered two questions."],
    rel: ["til", "op", "eli5"], tags: ["abbreviation", "reddit", "format"],
  },
  {
    slug: "fyi", term: "FYI", pron: "ef-why-EYE", pos: "abbreviation", cat: "text",
    year: 1980, pop: 66, trend: 0, status: "classic",
    def: "For your information. Neutral in origin, but in workplace email it now frequently carries an edge, marking something the reader should already have known.",
    eli: "For your information. In work emails it often means you should have known this already.",
    org: "Office memo shorthand that predates the internet, carried into email and then absorbed into chat, where its passive-aggressive reading became dominant.",
    ex: ["FYI, the deadline moved on Tuesday.", "An FYI with three people cc'd is never an FYI."],
    rel: ["psa", "op", "period-full-stop"], tags: ["abbreviation", "email", "work"],
  },
  {
    slug: "nsfw", term: "NSFW", pron: "en-es-ef-DUB", pos: "abbreviation", cat: "text",
    year: 2000, pop: 71, trend: 0, status: "classic",
    def: "Not safe for work. A courtesy tag warning that a link should not be opened where a screen is visible to colleagues.",
    eli: "A warning that a link is not something to open at work or around other people.",
    org: "Email forwarding culture around 2000, then formalised as a tag by forums and Reddit. NSFL, not safe for life, marks genuinely disturbing material.",
    ex: ["Great thread, one image is NSFW.", "Tag it NSFW or do not post it."],
    rel: ["tone-indicator", "content-warning", "spoiler-tag"], tags: ["abbreviation", "moderation", "courtesy"],
  },
  {
    slug: "tone-indicator", term: "Tone indicator", pron: "tohn IN-dik-ay-tur", pos: "noun", cat: "text",
    year: 2019, pop: 47, trend: 6, status: "rising",
    def: "A suffix marking the intent behind a message, such as /s for sarcasm, /j for joking or /srs for serious. Text carries no prosody, so the tag supplies it.",
    eli: "A little tag at the end of a message that tells you if it is a joke or serious.",
    org: "Reddit used /s for sarcasm from the late 2000s. The wider system was formalised on Twitter and TikTok around 2019, driven substantially by autistic and neurodivergent users.",
    ex: ["Wonderful, another meeting /s", "Your cooking is a war crime /j"],
    rel: ["lol", "content-warning", "keysmash"], tags: ["tone", "accessibility", "punctuation"],
  },
  {
    slug: "content-warning", term: "Content warning", pron: "KON-tent WOR-ning", pos: "noun", cat: "text",
    year: 2013, pop: 52, trend: 2, status: "mainstream",
    def: "A note placed before material that some readers may wish to approach carefully or skip. Abbreviated CW; TW for trigger warning is the older and narrower form.",
    eli: "A note at the top warning you what a post is about, so you can decide whether to read it.",
    org: "Feminist blogging and LiveJournal communities in the 2000s, generalised by Tumblr in the 2010s and now built into most platforms as a native feature.",
    ex: ["CW: discussion of hospitals in the second half.", "The tag exists so people can choose, not so nobody can post."],
    rel: ["nsfw", "spoiler-tag", "tone-indicator"], tags: ["moderation", "tumblr", "courtesy"],
  },
  {
    slug: "spoiler-tag", term: "Spoiler tag", pron: "SPOY-lur tag", pos: "noun", cat: "text",
    year: 1994, pop: 56, trend: 0, status: "classic",
    def: "Markup that hides plot details until deliberately revealed. On Usenet this was achieved by blank lines; modern platforms blur or collapse the text.",
    eli: "Hidden text that only shows a story detail if you choose to reveal it.",
    org: "Usenet groups devised spoiler space and rot13 encoding in the early 1990s. Every forum and chat platform since has reinvented the same courtesy in its own markup.",
    ex: ["Put the ending behind a spoiler tag.", "Untagged spoilers in the thread title is a hostile act."],
    rel: ["content-warning", "rot13", "nsfw"], tags: ["usenet", "courtesy", "markup"],
  },
  {
    slug: "keysmash", term: "Keysmash", pron: "KEE-smash", pos: "noun", cat: "text",
    year: 2010, pop: 49, trend: 3, status: "mainstream",
    def: "A run of random letters representing speechless excitement or distress. Conventions have hardened: it usually begins with a and favours the home row.",
    eli: "Mashing the keyboard to show you are too excited or overwhelmed for words.",
    org: "Tumblr and LiveJournal fandom, where emotional intensity outran vocabulary. Studies of the form show surprisingly consistent unwritten rules about what a valid keysmash looks like.",
    ex: ["asdfghjkl they announced the tour", "The keysmash said more than a paragraph would have"],
    rel: ["screaming", "tone-indicator", "letter-stretching"], tags: ["tumblr", "fandom", "expression"],
  },
  {
    slug: "letter-stretching", term: "Letter stretching", pron: "LET-ur STRECH-ing", pos: "noun", cat: "text",
    year: 2005, pop: 53, trend: 1, status: "classic",
    def: "Repeating a letter to lengthen a word and signal intensity or duration, as in noooo or heyyy. Vowel count maps roughly to feeling.",
    eli: "Repeating letters to show how strongly you mean something.",
    org: "An early and durable solution to the problem that typed text has no volume or pitch. Instant messenger culture set the conventions still in use.",
    ex: ["nooooo not the good bakery", "heyyy, quick favour"],
    rel: ["keysmash", "all-caps", "tone-indicator"], tags: ["expression", "chat", "prosody"],
  },
  {
    slug: "all-caps", term: "All caps", pron: "awl kaps", pos: "noun", cat: "text",
    year: 1984, pop: 61, trend: 0, status: "classic",
    def: "Capitalising an entire message, read as shouting. One of the oldest and most stable conventions in online writing.",
    eli: "Typing in capitals, which reads as shouting.",
    org: "Documented on Usenet and BBSes by the mid-1980s, with etiquette guides warning against it years before the web existed. The reading has never meaningfully changed.",
    ex: ["I AM NOT SHOUTING, THIS IS EXCITEMENT", "Please stop replying in all caps."],
    rel: ["lowercase", "letter-stretching", "period-full-stop"], tags: ["etiquette", "usenet", "prosody"],
  },
  {
    slug: "lowercase", term: "Lowercase", pron: "LOH-ur-kays", pos: "noun", cat: "text",
    year: 2012, pop: 58, trend: 4, status: "mainstream",
    def: "Writing without capitals as a deliberate register, signalling casualness, intimacy or a flattened affect rather than carelessness.",
    eli: "Typing with no capital letters on purpose, to sound relaxed rather than formal.",
    org: "Tumblr and Twitter in the early 2010s, where dropping capitals distinguished personal writing from institutional writing. Now a recognised marker of sincerity among younger users.",
    ex: ["anyway i think about this a lot", "The brand account switched to lowercase and fooled nobody."],
    rel: ["all-caps", "period-full-stop", "tone-indicator"], tags: ["register", "tumblr", "style"],
  },
  {
    slug: "period-full-stop", term: "The full stop", pron: "thuh FOOL stop", pos: "noun", cat: "text",
    year: 2013, pop: 57, trend: 2, status: "mainstream",
    def: "In short messages, ending a sentence with a full stop reads as cold or annoyed, because the line break already ends the thought and the punctuation must mean something else.",
    eli: "In a text, a full stop can make a message sound angry, because it is not needed to end the sentence.",
    org: "Documented by linguists including Gretchen McCulloch from the early 2010s. Studies found readers consistently rated full-stopped one-word replies as less sincere.",
    ex: ["He replied fine. and I have not recovered.", "ok vs ok. is the entire difference"],
    rel: ["lowercase", "all-caps", "tone-indicator"], tags: ["punctuation", "tone", "linguistics"],
  },
  {
    slug: "skull-emoji", term: "Skull emoji", pron: "skul i-MOH-jee", pos: "noun", cat: "text",
    year: 2020, pop: 74, trend: 5, status: "mainstream",
    def: "Marks something as extremely funny, on the logic that it killed you. It displaced the laughing-crying emoji, which younger users came to read as dated.",
    eli: "The skull means something was so funny it killed you. It replaced the laughing-crying face.",
    org: "Gen Z convention that hardened around 2020, part of the same escalation cycle that produced deceased and screaming as laughter markers.",
    ex: ["the caption on that one, skull", "Using the crying-laughing face now marks you as over thirty."],
    rel: ["crying", "im-deceased", "emoji"], tags: ["emoji", "laughter", "gen-z"],
  },
  {
    slug: "emoji", term: "Emoji", pron: "i-MOH-jee", pos: "noun", cat: "text",
    year: 1999, pop: 87, trend: 0, status: "classic",
    def: "Standardised pictographic characters encoded in Unicode. Distinct from emoticons, which are built from ordinary punctuation.",
    eli: "The little pictures you can type, like faces and animals. They are real characters, not images.",
    org: "Created by Shigetaka Kurita for NTT DoCoMo in 1999. Unicode adoption in 2010 made them universal, and the name comes from Japanese for picture character, not from emotion.",
    ex: ["The whole reply was three emoji and it was devastating.", "Emoji meanings drift by platform and by generation."],
    rel: ["emoticon", "skull-emoji", "kaomoji"], tags: ["unicode", "japan", "pictograph"],
  },
  {
    slug: "emoticon", term: "Emoticon", pron: "i-MOH-tik-on", pos: "noun", cat: "text",
    year: 1982, pop: 44, trend: -3, status: "classic",
    def: "A facial expression built from punctuation, read sideways in the Western tradition. The direct ancestor of emoji, and still in use.",
    eli: "A face made out of punctuation marks, like a colon and a bracket.",
    org: "Proposed by Scott Fahlman on a Carnegie Mellon bulletin board in September 1982, to mark jokes in text. The problem he was solving is the same one tone indicators solve today.",
    ex: [":) still does a job no emoji quite matches", "The 1982 post proposing it is still archived."],
    rel: ["emoji", "kaomoji", "tone-indicator"], tags: ["bbs", "history", "punctuation"],
  },
  {
    slug: "kaomoji", term: "Kaomoji", pron: "kah-oh-MOH-jee", pos: "noun", cat: "text",
    year: 1986, pop: 38, trend: 1, status: "niche",
    def: "Japanese-style emoticons read upright rather than sideways, using a wide character set to build expressive faces such as shrugs and blushes.",
    eli: "Japanese-style text faces that you read the right way up instead of sideways.",
    org: "Developed on Japanese BBSes from the mid-1980s, independently of Western emoticons. The shrug became one of the most copied strings on the internet.",
    ex: ["Sent the shrug and closed the laptop.", "Kaomoji do more with characters than most emoji manage with colour."],
    rel: ["emoticon", "emoji", "uwu"], tags: ["japan", "bbs", "expression"],
  },
  {
    slug: "uwu", term: "UwU", pron: "OO-woo", pos: "interjection", cat: "text",
    year: 2005, pop: 46, trend: -5, status: "niche",
    def: "A kaomoji depicting a contented face, and by extension a whole cutesy register in which words are softened, as in owo and hewwo.",
    eli: "A little text face showing happiness, and a very cute way of typing that goes with it.",
    org: "Anime forums and DeviantArt in the mid-2000s. Later adopted ironically far beyond its origins, to the point where sincere use is now the marked case.",
    ex: ["uwu", "The entire changelog was written in uwu speak and nobody could stop them."],
    rel: ["kaomoji", "emoticon", "weeb"], tags: ["anime", "cute", "register"],
  },
  {
    slug: "irl", term: "IRL", pron: "eye-ar-EL", pos: "abbreviation", cat: "text",
    year: 1990, pop: 70, trend: -4, status: "classic",
    def: "In real life. Distinguishes offline events from online ones, a division that has become progressively harder to maintain.",
    eli: "In real life, meaning offline rather than on the internet.",
    org: "Usenet and MUD vocabulary, from an era when the two spheres genuinely were separate. Some users now prefer AFK or offline, on the grounds that online life is also real.",
    ex: ["We finally met IRL after nine years of replies.", "The IRL and online distinction stopped working around 2015."],
    rel: ["afk", "meatspace"], tags: ["abbreviation", "usenet", "offline"],
  },
  {
    slug: "dm", term: "DM", pron: "dee-EM", pos: "noun", cat: "text",
    year: 2007, pop: 83, trend: 1, status: "classic",
    def: "Direct message. A private message inside a public platform, and as a verb the act of sending one. Sliding into someone's DMs implies romantic intent.",
    eli: "A private message on a social app. Sliding into the DMs means messaging someone you fancy.",
    org: "Named by Twitter at launch in 2006 to distinguish private messages from public replies. The term spread to every platform regardless of what each one calls the feature.",
    ex: ["DM me the address.", "He slid into the DMs with a spelling mistake and no follow-up."],
    rel: ["op", "subtweet", "thirst-trap"], tags: ["abbreviation", "twitter", "messaging"],
  },
  {
    slug: "omg", term: "OMG", pron: "oh-em-JEE", pos: "abbreviation", cat: "text",
    year: 1917, pop: 79, trend: -2, status: "classic",
    def: "Oh my God. A surprise marker that has softened over a century of use into general emphasis.",
    eli: "Oh my God. Used to show surprise or excitement.",
    org: "First attested in a 1917 letter from Admiral John Fisher to Winston Churchill, decades before computers. Chat culture rediscovered it independently in the 1990s.",
    ex: ["omg the tickets are already gone", "A First World War admiral got there before Messenger did."],
    rel: ["wtf", "lol", "istg"], tags: ["abbreviation", "history", "surprise"],
  },
  {
    slug: "wtf", term: "WTF", pron: "dub-tee-EF", pos: "abbreviation", cat: "text",
    year: 1985, pop: 81, trend: 0, status: "classic",
    def: "An expression of blunt confusion or disbelief. Softened considerably by decades of use, and now common in contexts that would once have refused it.",
    eli: "A rude way of saying what on earth is going on.",
    org: "Attested on Usenet from the mid-1980s. Its gradual acceptability is a standard example of how taboo strength decays under high-frequency use.",
    ex: ["wtf is this pricing page", "wtf, genuinely, how did that ship"],
    rel: ["omg", "smh", "bruh"], tags: ["abbreviation", "usenet", "disbelief"],
  },
  {
    slug: "jk", term: "JK", pron: "jay-KAY", pos: "abbreviation", cat: "text",
    year: 1994, pop: 52, trend: -5, status: "classic",
    def: "Just kidding. A retroactive marker converting a statement into a joke, and frequently a way of testing a reaction before committing to it.",
    eli: "Just kidding. Added after something to show it was a joke.",
    org: "Instant messenger shorthand of the 1990s. The modern /j tone indicator does the same job, but is placed as a tag rather than as a retraction.",
    ex: ["you should quit. jk. unless?", "jk did a lot of work in that sentence"],
    rel: ["tone-indicator", "lol", "unserious"], tags: ["abbreviation", "humour", "chat"],
  },
  {
    slug: "psa", term: "PSA", pron: "pee-es-AY", pos: "abbreviation", cat: "text",
    year: 2009, pop: 48, trend: 0, status: "classic",
    def: "Public service announcement. Introduces information the poster considers generally useful, often with a hint of exasperation that it needs saying.",
    eli: "A notice telling everyone something useful they probably did not know.",
    org: "Borrowed from broadcast regulation, where PSAs were mandated free airtime. Forums adopted the framing to lend weight to unsolicited advice.",
    ex: ["PSA: the clocks change on Sunday.", "PSA to whoever keeps microwaving fish."],
    rel: ["fyi", "til", "op"], tags: ["abbreviation", "announcement", "forums"],
  },
  {
    slug: "istg", term: "ISTG", pron: "eye-es-tee-JEE", pos: "abbreviation", cat: "text",
    year: 2013, pop: 51, trend: 2, status: "mainstream",
    def: "I swear to God. An intensifier expressing exasperation or insistence, usually about something trivial.",
    eli: "I swear to God. Used when you are annoyed or really mean something.",
    org: "Texting shorthand of the early 2010s, part of the same family as ONG and FR. The oath form long predates any of them.",
    ex: ["istg if the train is delayed again", "istg I put it down right here"],
    rel: ["ong", "deadass", "fr"], tags: ["abbreviation", "texting", "exasperation"],
  },
  {
    slug: "bruh", term: "Bruh", pron: "bruh", pos: "interjection", cat: "text",
    year: 2010, pop: 78, trend: 1, status: "classic",
    def: "A single-word reaction expressing disbelief, disappointment or resignation. Carries no content; the whole message is the tone.",
    eli: "A one-word way of showing you cannot believe what just happened.",
    org: "A clipped form of brother in African American Vernacular English, in use for decades. Vine made it a punchline in the mid-2010s and it has functioned as pure interjection ever since.",
    ex: ["Bruh.", "The reply was one word and it said everything."],
    rel: ["smh", "facepalm", "wtf"], tags: ["aave", "reaction", "vine"],
  },
  {
    slug: "facepalm", term: "Facepalm", pron: "FAYS-pahm", pos: "noun", cat: "text",
    year: 2001, pop: 54, trend: -2, status: "classic",
    def: "The gesture of putting a hand to your face in exasperation, written as a stage direction or posted as an image before an emoji existed for it.",
    eli: "Covering your face with your hand because something was so silly.",
    org: "Named on forums in the early 2000s and carried by a Star Trek screenshot of Picard that became the definitive reaction image. Unicode added the gesture in 2016.",
    ex: ["Read the error message. Facepalm.", "Picard did more for this word than anyone."],
    rel: ["smh", "bruh", "reaction-image"], tags: ["reaction", "star-trek", "gesture"],
  },
  {
    slug: "fwiw", term: "FWIW", pron: "ef-dub-eye-DUB", pos: "abbreviation", cat: "text",
    year: 1993, pop: 33, trend: 0, status: "classic",
    def: "For what it is worth. Marks a contribution as offered rather than insisted upon, and occasionally as a polite prelude to disagreement.",
    eli: "For what it is worth. A way of offering an opinion without pushing it.",
    org: "Usenet hedging vocabulary, alongside IMO, AFAIK and YMMV. Its survival in professional email is largely due to how much softening one small acronym can do.",
    ex: ["FWIW, we tried that in 2019 and it did not hold.", "FWIW is doing a lot of diplomacy in that sentence."],
    rel: ["imo", "afaik", "ymmv"], tags: ["abbreviation", "usenet", "hedging"],
  },
  {
    slug: "coded", term: "-coded", pron: "KOH-did", pos: "suffix", cat: "text",
    year: 2020, pop: 58, trend: 9, status: "rising",
    def: "A suffix meaning giving off the qualities of, without literally being: sibling-coded, villain-coded, Tuesday-coded. Attaches to almost anything.",
    eli: "An ending meaning something gives off the feeling of a thing, without actually being it.",
    org: "Adapted from queer-coding in film criticism, where a character signals an identity without it being stated. Fandom generalised it around 2020 into a productive suffix.",
    ex: ["That jacket is deeply villain-coded.", "The whole album is autumn-coded."],
    rel: ["core-suffix", "its-giving", "pilled"], tags: ["morphology", "fandom", "suffix"],
  },
  {
    slug: "pilled", term: "-pilled", pron: "pild", pos: "suffix", cat: "text",
    year: 2016, pop: 46, trend: 4, status: "mainstream",
    def: "A suffix meaning converted to a belief: blackpilled, cottagecore-pilled, whitepilled. Signals a conversion experience rather than a mere opinion.",
    eli: "An ending meaning someone has been won over to an idea, as if they swallowed a pill.",
    org: "From the red pill in The Matrix, adopted by online political subcultures from around 2016 and then defused by ironic and trivial uses like sleep-pilled.",
    ex: ["Fully sleep-pilled, in bed by nine.", "The suffix escaped its politics by being applied to everything."],
    rel: ["coded", "maxxing", "core-suffix"], tags: ["morphology", "matrix", "suffix"],
  },
  {
    slug: "maxxing", term: "-maxxing", pron: "MAKS-ing", pos: "suffix", cat: "text",
    year: 2015, pop: 49, trend: 11, status: "rising",
    def: "A suffix meaning optimising one thing to the exclusion of others: looksmaxxing, sleepmaxxing, moneymaxxing. Treats life as a character sheet.",
    eli: "An ending meaning you are trying to max out one part of your life, like a stat in a game.",
    org: "From role-playing game vocabulary for maximising a stat, adopted by incel and bodybuilding forums in the 2010s and softened into general wellness content on TikTok.",
    ex: ["Sleepmaxxing is just going to bed on time with better branding.", "Everything is a stat now."],
    rel: ["looksmaxxing", "pilled", "mewing"], tags: ["morphology", "gaming", "suffix"],
  },
  {
    slug: "rot13", term: "ROT13", pron: "rot-thur-TEEN", pos: "noun", cat: "text",
    year: 1982, pop: 22, trend: 0, status: "classic",
    def: "A cipher rotating each letter thirteen places, used on Usenet to hide spoilers and punchlines. Trivially reversible, which was the point.",
    eli: "A simple code that shifts letters so text is hidden until you decode it.",
    org: "A Usenet convention from the early 1980s. It offered no security whatsoever, only a deliberate pause before reading, which made it the first spoiler tag.",
    ex: ["Punchline in ROT13 so nobody reads it by accident.", "Applying ROT13 twice returns the original, which is a standing joke."],
    rel: ["spoiler-tag", "usenet", "netiquette"], tags: ["usenet", "cipher", "spoilers"],
  },
  {
    slug: "lmk", term: "LMK", pron: "el-em-KAY", pos: "abbreviation", cat: "text",
    year: 1998, pop: 74, trend: 1, status: "classic",
    def: "Let me know. A closing request for a reply once the sender has finished laying out information or options.",
    eli: "Short for let me know, used to ask someone to reply once they have decided something.",
    org: "Instant-messenger and early texting shorthand from the late 1990s, carried forward largely unchanged because it saves exactly the amount of typing worth saving.",
    ex: ["Sent three options, LMK which works.", "LMK if the time needs to change."],
    rel: ["hmu", "wyd", "brb"], tags: ["texting", "abbreviation", "classic"],
  },
  {
    slug: "idk", term: "IDK", pron: "eye-dee-KAY", pos: "abbreviation", cat: "text",
    year: 1995, pop: 78, trend: 0, status: "classic",
    def: "I don't know. One of the oldest and most stable texting abbreviations, used as a full sentence on its own.",
    eli: "Short for I don't know.",
    org: "Chat-room shorthand from the mid-1990s, old enough to predate SMS and simply carried into every texting platform since.",
    ex: ["IDK, ask him yourself.", "IDK why that took so long to load."],
    rel: ["idc", "ig", "nvm"], tags: ["texting", "abbreviation", "classic"],
  },
  {
    slug: "idc", term: "IDC", pron: "eye-dee-SEE", pos: "abbreviation", cat: "text",
    year: 1999, pop: 61, trend: 0, status: "classic",
    def: "I don't care. States indifference, and depending on tone can be genuinely neutral or a pointed way of ending a discussion.",
    eli: "Short for I don't care.",
    org: "Texting shorthand from the same generation as IDK, following the same pattern of compressing a stance into four letters.",
    ex: ["IDC which restaurant, you pick.", "Said IDC three times, clearly did care."],
    rel: ["idk", "nvm", "unserious"], tags: ["texting", "abbreviation", "classic"],
  },
  {
    slug: "hbu", term: "HBU", pron: "aych-bee-YOO", pos: "abbreviation", cat: "text",
    year: 2000, pop: 55, trend: -1, status: "classic",
    def: "How about you. Turns a question back on the person who was just asked it, usually to close a small-talk exchange politely.",
    eli: "Short for how about you, used to ask someone the same question back.",
    org: "Instant-messenger shorthand from the early 2000s, alongside the equivalent WBU, both compressing the reciprocal question into a single word-shaped unit.",
    ex: ["Good, tired. HBU?", "Nothing much, HBU?"],
    rel: ["wyd", "lmk", "rn"], tags: ["texting", "abbreviation", "classic"],
  },
  {
    slug: "rn", term: "RN", pron: "ar-EN", pos: "abbreviation", cat: "text",
    year: 2005, pop: 76, trend: 2, status: "classic",
    def: "Right now. Specifies that a statement describes the current moment rather than a general or future state.",
    eli: "Short for right now.",
    org: "Texting shorthand from the mid-2000s, standard once SMS character limits made abbreviating high-frequency words worthwhile.",
    ex: ["Busy RN, call you later.", "I am not okay RN, honestly."],
    rel: ["hbu", "nvm", "omw"], tags: ["texting", "abbreviation", "classic"],
  },
  {
    slug: "nvm", term: "NVM", pron: "en-vee-EM", pos: "abbreviation", cat: "text",
    year: 2003, pop: 70, trend: 0, status: "classic",
    def: "Never mind. Withdraws a question or statement, usually because the answer arrived, the point stopped mattering, or the sender lost their nerve.",
    eli: "Short for never mind, used to take back something you just said or asked.",
    org: "Texting and instant-messenger shorthand from the early 2000s, one of the most reliable ways to end a thread without further explanation.",
    ex: ["Wait, NVM, found it.", "NVM, figured it out myself."],
    rel: ["idk", "rn", "lmk"], tags: ["texting", "abbreviation", "classic"],
  },
  {
    slug: "omw", term: "OMW", pron: "oh-em-DUB-ul-yoo", pos: "abbreviation", cat: "text",
    year: 2004, pop: 65, trend: 0, status: "classic",
    def: "On my way. Confirms that travel toward an agreed destination has actually started, as distinct from merely intending to leave.",
    eli: "Short for on my way, used to say you have already left.",
    org: "Texting shorthand from the mid-2000s, notable for being one of the abbreviations most commonly sent before the trip has actually begun.",
    ex: ["OMW, fifteen minutes.", "Said OMW twenty minutes ago, still at home."],
    rel: ["rn", "lmk", "hmu"], tags: ["texting", "abbreviation", "classic"],
  },
  {
    slug: "wyd", term: "WYD", pron: "wy-dee", pos: "abbreviation", cat: "text",
    year: 2010, pop: 62, trend: 1, status: "mainstream",
    def: "What you doing. A low-commitment opener that checks availability or interest without stating a purpose outright.",
    eli: "Short for what you doing, often used to casually check if someone is free or interested in talking.",
    org: "African American Vernacular English texting shorthand that became standard across group chats by the early 2010s.",
    ex: ["WYD tonight?", "WYD is doing a lot of work in that opening text."],
    rel: ["hmu", "hbu", "rn"], tags: ["texting", "abbreviation", "aave"],
  },
  {
    slug: "hmu", term: "HMU", pron: "aych-em-YOO", pos: "abbreviation", cat: "text",
    year: 2008, pop: 68, trend: -1, status: "mainstream",
    def: "Hit me up. An invitation to be contacted, either generally or when a specific condition is met.",
    eli: "Short for hit me up, meaning contact me.",
    org: "African American Vernacular English texting shorthand from the late 2000s, borrowing hit up from earlier phone-call slang.",
    ex: ["HMU if you need a ride.", "HMU when you land."],
    rel: ["wyd", "lmk", "dm"], tags: ["texting", "abbreviation", "aave"],
  },
  {
    slug: "ily", term: "ILY", pron: "eye-el-WY", pos: "abbreviation", cat: "text",
    year: 2002, pop: 58, trend: 0, status: "classic",
    def: "I love you. A shortened version used often enough between friends and family that it carries less weight than the full phrase, reserved for smaller, more frequent affection.",
    eli: "Short for I love you, used casually and often.",
    org: "Early SMS shorthand from the 2000s, when character limits made every word worth abbreviating, including the most sincere ones.",
    ex: ["ILY, drive safe.", "Ended the call with an ILY, as usual."],
    rel: ["ilysm", "gn", "thx"], tags: ["texting", "abbreviation", "affection"],
  },
  {
    slug: "ilysm", term: "ILYSM", pron: "eye-el-why-es-EM", pos: "abbreviation", cat: "text",
    year: 2010, pop: 46, trend: 0, status: "mainstream",
    def: "I love you so much. The intensified form of ILY, used when the plain version feels insufficient.",
    eli: "Short for I love you so much.",
    org: "A natural extension of ILY once texting culture matured enough to need a stronger version of an already-shortened phrase.",
    ex: ["Thank you for that, ILYSM.", "ILYSM, see you tomorrow."],
    rel: ["ily", "gn", "thx"], tags: ["texting", "abbreviation", "affection"],
  },
  {
    slug: "thx", term: "Thx", pron: "thanks", pos: "abbreviation", cat: "text",
    year: 1997, pop: 72, trend: -1, status: "classic",
    def: "Thanks, shortened. One of the earliest and most durable texting contractions, still in constant use decades on.",
    eli: "A short way of writing thanks.",
    org: "Present since the earliest days of SMS and instant messaging, when every saved character mattered on a numeric keypad.",
    ex: ["Thx for the ride.", "Thx, appreciate it."],
    rel: ["ty", "np", "yw"], tags: ["texting", "abbreviation", "classic"],
  },
  {
    slug: "ty", term: "TY", pron: "tee-WY", pos: "abbreviation", cat: "text",
    year: 1996, pop: 66, trend: -2, status: "classic",
    def: "Thank you, reduced to its two initials. Shorter and blunter than thx, common in fast-paced chat and gaming.",
    eli: "A very short way of writing thank you.",
    org: "Chat and gaming shorthand from the mid-1990s, favoured where speed matters more than warmth, such as mid-match voice-free coordination.",
    ex: ["ty for the assist", "ty, that answers it"],
    rel: ["thx", "np", "yw"], tags: ["texting", "abbreviation", "gaming"],
  },
  {
    slug: "yw", term: "YW", pron: "why-DUB-ul-yoo", pos: "abbreviation", cat: "text",
    year: 1997, pop: 51, trend: -1, status: "classic",
    def: "You're welcome, shortened. The standard reply to thx or ty, completing the smallest possible exchange of courtesy.",
    eli: "A short way of writing you're welcome.",
    org: "Chat shorthand from the same period as thx and ty, forming a matched set for closing out a brief exchange with minimal typing.",
    ex: ["ty! - yw", "yw, anytime"],
    rel: ["thx", "ty", "np"], tags: ["texting", "abbreviation", "classic"],
  },
  {
    slug: "np", term: "NP", pron: "en-PEE", pos: "abbreviation", cat: "text",
    year: 1996, pop: 63, trend: -1, status: "classic",
    def: "No problem. Downplays a favour or apology, signalling that no debt or grievance remains.",
    eli: "A short way of writing no problem.",
    org: "Chat and gaming shorthand from the mid-1990s, used interchangeably with yw as a low-effort close to a thanks or a sorry.",
    ex: ["np, glad it worked", "sorry! - np"],
    rel: ["yw", "ty", "thx"], tags: ["texting", "abbreviation", "classic"],
  },
  {
    slug: "icymi", term: "ICYMI", pron: "eye-see-why-em-EYE", pos: "abbreviation", cat: "text",
    year: 2009, pop: 57, trend: 1, status: "mainstream",
    def: "In case you missed it. Flags a repost or a resurfaced piece of information, softening the fact that it is not new.",
    eli: "Short for in case you missed it, used when sharing something again for people who did not see it the first time.",
    org: "Twitter shorthand from around 2009, when the platform's chronological feed meant a genuinely important post could easily scroll past unseen.",
    ex: ["ICYMI, the deadline moved to Friday.", "ICYMI is doing the algorithm's job for it."],
    rel: ["tldr", "psa", "op"], tags: ["texting", "abbreviation", "twitter"],
  },
  {
    slug: "fomo", term: "FOMO", pron: "FOH-moh", pos: "abbreviation", cat: "text",
    year: 2004, pop: 81, trend: 3, status: "mainstream",
    def: "Fear of missing out. Anxiety that others are having a better or more meaningful experience somewhere you are not.",
    eli: "Short for fear of missing out, the worried feeling that something good is happening without you.",
    org: "Coined in a 2004 Harvard Business School paper about status anxiety, then popularised by tech writer Patrick McGinnis, who later added the counter-term JOMO.",
    ex: ["Skipped the trip and the FOMO was real.", "Social media runs almost entirely on manufactured FOMO."],
    rel: ["jomo", "doomscrolling", "parasocial"], tags: ["abbreviation", "psychology", "social-media"],
  },
  {
    slug: "jomo", term: "JOMO", pron: "JOH-moh", pos: "abbreviation", cat: "text",
    year: 2012, pop: 38, trend: 5, status: "niche",
    def: "Joy of missing out. The deliberate satisfaction of opting out of an event or trend rather than the anxious version, FOMO.",
    eli: "The opposite of FOMO: feeling good about missing out on something instead of anxious.",
    org: "Coined by Anil Dash in 2012 as a direct counter-term to FOMO, gaining wider use as digital-wellbeing and slow-living framing grew more common.",
    ex: ["Turned the phone off for the weekend, pure JOMO.", "JOMO is FOMO's much calmer sibling."],
    rel: ["fomo", "soft-life", "doomscrolling"], tags: ["abbreviation", "wellbeing", "psychology"],
  },
  {
    slug: "yolo", term: "YOLO", pron: "YOH-loh", pos: "abbreviation", cat: "text",
    year: 2011, pop: 55, trend: -5, status: "fading",
    def: "You only live once. Used to justify an impulsive or risky decision, often ironically once the phrase itself became a punchline.",
    eli: "Short for you only live once, said to justify doing something a bit reckless.",
    org: "Popularised by Drake's 2011 track The Motto, after which it spread so fast and so widely that Oxford named it a word of the year contender within months.",
    ex: ["Bought the ticket, YOLO.", "YOLO stopped being sincere around 2014."],
    rel: ["fomo", "delulu", "unserious"], tags: ["abbreviation", "2010s", "risk"],
  },
  {
    slug: "ftw", term: "FTW", pron: "ef-tee-DUB-ul-yoo", pos: "abbreviation", cat: "text",
    year: 1996, pop: 44, trend: -1, status: "classic",
    def: "For the win. Attached to something being praised, framing it as the deciding factor in an implied contest.",
    eli: "Short for for the win, added after something you are praising.",
    org: "Gaming and forum shorthand from the mid-1990s, borrowed from game-show vocabulary where the phrase preceded a final, decisive answer.",
    ex: ["Coffee before anything else, coffee FTW.", "Public libraries FTW."],
    rel: ["goat", "based", "dub"], tags: ["abbreviation", "gaming", "praise"],
  },
  {
    slug: "bffr", term: "BFFR", pron: "bee-ef-ef-AR", pos: "abbreviation", cat: "text",
    year: 2023, pop: 47, trend: 12, status: "rising",
    def: "Be for real. An impatient instruction to stop exaggerating or being dramatic, sharper than the plain for real it is built from.",
    eli: "Short for be for real, a way of telling someone to stop being dramatic or ridiculous.",
    org: "TikTok comment-section shorthand from 2023, built on the existing fr as an intensified, slightly exasperated version.",
    ex: ["You cried over a font change? BFFR.", "BFFR, it was one comment."],
    rel: ["fr", "cap", "unserious"], tags: ["abbreviation", "tiktok", "2023"],
  },
  {
    slug: "iykyk", term: "IYKYK", pron: "eye-why-kay-why-KAY", pos: "abbreviation", cat: "text",
    year: 2015, pop: 60, trend: 6, status: "mainstream",
    def: "If you know, you know. Marks a reference as intentionally exclusive, signalling an in-joke without explaining it to outsiders.",
    eli: "Short for if you know, you know, used for jokes or references only some people will understand.",
    org: "Spread through Instagram captions and Twitter in the mid-2010s as a way of posting a niche reference while openly acknowledging that most readers would not get it.",
    ex: ["The playlist title makes no sense unless you were there. IYKYK.", "Caption was just IYKYK and three emoji."],
    rel: ["lore", "coded", "inside-joke"], tags: ["abbreviation", "instagram", "reference"],
  },
  {
    slug: "rq", term: "RQ", pron: "ar-KYOO", pos: "abbreviation", cat: "text",
    year: 2016, pop: 34, trend: 1, status: "niche",
    def: "Real quick. Frames a request or action as brief, often used to make an interruption sound smaller than it is.",
    eli: "Short for real quick.",
    org: "Texting shorthand from the mid-2010s, following the same clipping pattern as rn and fr once vowel-dropping became standard practice.",
    ex: ["Can you call me rq?", "Just checking rq, ignore if busy."],
    rel: ["rn", "fr", "lmk"], tags: ["texting", "abbreviation"],
  },
  {
    slug: "obvi", term: "Obvi", pron: "OB-vee", pos: "adverb", cat: "text",
    year: 2004, pop: 41, trend: -3, status: "fading",
    def: "Obviously, clipped. Part of a small family of cutesy abbreviations, alongside totes and adorbs, that peaked in the early 2010s.",
    eli: "A short, casual way of saying obviously.",
    org: "Valley-girl-adjacent clipping from the mid-2000s, popularised further by reality television before falling out of frequent use.",
    ex: ["Obvi I am coming, why would you ask.", "Obvi has not aged as well as fr."],
    rel: ["totes", "deadass", "fr"], tags: ["abbreviation", "clipping", "2000s"],
  },
  {
    slug: "totes", term: "Totes", pron: "tohts", pos: "adverb", cat: "text",
    year: 2003, pop: 36, trend: -4, status: "fading",
    def: "Totally, clipped. Part of the same cutesy-abbreviation family as obvi and adorbs, most associated with mid-2000s and early-2010s texting.",
    eli: "A short, casual way of saying totally.",
    org: "British and Australian clipping from the early 2000s that spread through reality television and teen texting culture before fading against newer intensifiers.",
    ex: ["Totes coming, wouldn't miss it.", "Totes forgot that was today."],
    rel: ["obvi", "deadass", "fr"], tags: ["abbreviation", "clipping", "2000s"],
  },
  {
    slug: "inside-joke", term: "Inside joke", pron: "IN-syde johk", pos: "noun", cat: "text",
    year: 1970, pop: 62, trend: 2, status: "classic",
    def: "A joke whose humour depends entirely on shared context known only to a specific group, meaningless or confusing to anyone outside it.",
    eli: "A joke that only makes sense to people who already know the story behind it.",
    org: "Standard English long before the internet, but the internet turned inside jokes into a scalable format: a whole fandom or server can share one built from a single screenshot.",
    ex: ["The whole server still references that one typo from 2019.", "Explaining an inside joke always kills it."],
    rel: ["iykyk", "lore", "copypasta"], tags: ["humour", "community", "reference"],
  },
  {
    slug: "wbu", term: "WBU", pron: "dub-ul-yoo-bee-YOO", pos: "abbreviation", cat: "text",
    year: 2000, pop: 40, trend: -2, status: "classic",
    def: "What about you. A near-exact equivalent of HBU, returning a question to the person who asked it.",
    eli: "Short for what about you, used to ask someone the same thing back.",
    org: "Instant-messenger shorthand from the early 2000s, coexisting with HBU as one of two competing abbreviations for the same reciprocal question.",
    ex: ["Good thanks, WBU?", "Tired but fine, WBU?"],
    rel: ["hbu", "rn", "lmk"], tags: ["texting", "abbreviation", "classic"],
  },
  {
    slug: "def", term: "Def", pron: "def", pos: "adverb", cat: "text",
    year: 1998, pop: 58, trend: -1, status: "classic",
    def: "Definitely, clipped. One of the earliest and least controversial texting abbreviations, largely unchanged in meaning or tone since the 1990s.",
    eli: "A short way of saying definitely.",
    org: "Standard SMS-era clipping from the late 1990s, part of the first wave of abbreviations built simply by dropping the end of a common word.",
    ex: ["Def coming this time.", "That is def the better option."],
    rel: ["probs", "obvi", "fr"], tags: ["abbreviation", "clipping", "classic"],
  },
  {
    slug: "probs", term: "Probs", pron: "probz", pos: "adverb", cat: "text",
    year: 2005, pop: 49, trend: -2, status: "classic",
    def: "Probably, clipped. A hedge softened by informality, common in casual planning messages.",
    eli: "A short, casual way of saying probably.",
    org: "Texting shorthand from the mid-2000s, following the same end-clipping pattern as def and obvi.",
    ex: ["Probs not going, feeling rough.", "Probs the best one on the menu."],
    rel: ["def", "ig", "obvi"], tags: ["abbreviation", "clipping", "classic"],
  },
  {
    slug: "ig", term: "IG", pron: "eye-JEE", pos: "abbreviation", cat: "text",
    year: 2008, pop: 53, trend: 0, status: "classic",
    def: "I guess. A reluctant or half-hearted agreement, weaker than a plain yes and often signalling mild resignation.",
    eli: "Short for I guess, used when agreeing without much enthusiasm.",
    org: "Texting shorthand from the late 2000s. Context usually disambiguates it from the unrelated abbreviation for Instagram.",
    ex: ["Sure, IG.", "IG that works, not thrilled about it."],
    rel: ["probs", "unserious", "idc"], tags: ["abbreviation", "texting"],
  },
  {
    slug: "sry", term: "Sry", pron: "SOR-ee", pos: "interjection", cat: "text",
    year: 1997, pop: 52, trend: -1, status: "classic",
    def: "Sorry, clipped. Common enough to read as a genuine apology in casual contexts, though its brevity can also read as offhand.",
    eli: "A short way of writing sorry.",
    org: "Early SMS-era clipping, old enough to predate smartphone autocorrect, which now frequently expands it back to the full word.",
    ex: ["sry, missed your call", "sry sry, on my way"],
    rel: ["nvm", "my-bad", "gtg"], tags: ["abbreviation", "texting", "classic"],
  },
  {
    slug: "my-bad", term: "My bad", pron: "my bad", pos: "phrase", cat: "text",
    year: 1970, pop: 61, trend: 0, status: "classic",
    def: "A casual admission of fault, lighter in tone than a formal apology and often used for genuinely minor mistakes.",
    eli: "A casual way of saying that was my mistake.",
    org: "US basketball slang from the 1970s, credited partly to Manute Bol's imperfect English becoming a beloved catchphrase among teammates, then generalised well beyond sport.",
    ex: ["My bad, wrong thread.", "My bad, I will fix it now."],
    rel: ["sry", "nvm", "oop"], tags: ["apology", "sports", "classic"],
  },
  {
    slug: "oop", term: "Oop", pron: "oop", pos: "interjection", cat: "text",
    year: 2018, pop: 39, trend: -3, status: "niche",
    def: "A short exclamation of mild surprise or self-correction, often typed as oop or the extended sksksk-adjacent and I oop, marking an awkward or unexpected moment.",
    eli: "A short sound people write when something surprising or slightly embarrassing just happened.",
    org: "Popularised by drag performer Jasmine Masters, whose clip saying and I oop was widely repurposed as a reaction sound on Vine and then TikTok from 2018.",
    ex: ["And I oop, wrong group chat.", "Oop, did not mean to send that."],
    rel: ["my-bad", "keysmash", "screaming"], tags: ["interjection", "tiktok", "drag"],
  },
  {
    slug: "gn", term: "GN", pron: "jee-EN", pos: "abbreviation", cat: "text",
    year: 1996, pop: 56, trend: -1, status: "classic",
    def: "Good night, shortened. A closing message before ending contact for the evening, sometimes doubled as gngn for extra warmth.",
    eli: "A short way of writing good night.",
    org: "Chat and texting shorthand present since the earliest days of SMS, one of the most consistently used abbreviations across every generation of texters.",
    ex: ["GN, talk tomorrow.", "GN, love you."],
    rel: ["ily", "ilysm", "ttyl"], tags: ["texting", "abbreviation", "classic"],
  },
  {
    slug: "sksksk", term: "Sksksk", pron: "SKUH-skuh-skuh", pos: "interjection", cat: "text",
    year: 2019, pop: 38, trend: -8, status: "fading",
    def: "A vocalisation typed to represent shocked or excited laughter, without spelling out actual words, often paired with and I oop as a matched exclamation pair.",
    eli: "A typed sound representing excited or shocked laughing, without using real words.",
    org: "Associated with the VSCO girl aesthetic of 2019, spreading through TikTok as a recognisable vocal tic before becoming a punchline about the trend itself.",
    ex: ["sksksk I cannot believe that actually worked", "Nobody has typed sksksk unironically in years."],
    rel: ["vsco-girl", "oop", "keysmash"], tags: ["tiktok", "2019", "vocalisation"],
  },
];
