import type { RawTerm } from "../types";

export const web3Terms: RawTerm[] = [
  {
    slug: "degen", term: "Degen", pron: "DEE-jen", pos: "noun", cat: "web3",
    year: 2020, pop: 58, trend: 3, status: "niche",
    def: "A trader who knowingly takes reckless positions for entertainment as much as profit. Worn as a badge rather than accepted as criticism.",
    eli: "Someone who makes very risky bets for fun and jokes about how bad an idea it is.",
    org: "Clipped from \"degenerate gambler\" in sports-betting communities, then adopted across crypto around 2020 as self-deprecating identity.",
    ex: ["Full degen behaviour at three in the morning.", "The degen play was correct exactly once and he has not stopped mentioning it."],
    rel: ["memecoin", "hodl", "diamond-hands"], tags: ["risk", "identity", "trading"],
  },
  {
    slug: "diamond-hands", term: "Diamond hands", pron: "DY-mund handz", pos: "noun", cat: "web3",
    year: 2021, pop: 59, trend: -8, status: "fading",
    def: "The disposition to hold a volatile position without selling under pressure. Its opposite, paper hands, describes someone who sells at the first sign of trouble.",
    eli: "Being brave enough to keep something valuable while its price drops, instead of panicking and selling.",
    org: "Spread from the WallStreetBets forum during the 2021 meme-stock episode and moved straight into crypto vocabulary.",
    ex: ["Diamond hands until the mortgage was due.", "He called it conviction, the chart called it diamond hands."],
    rel: ["hodl", "degen", "memecoin"], tags: ["trading", "wallstreetbets"],
  },
  {
    slug: "dyor", term: "DYOR", pron: "dee-why-oh-AR", pos: "abbreviation", cat: "web3",
    year: 2017, pop: 61, trend: -2, status: "classic",
    def: "\"Do your own research\": a disclaimer appended to investment talk, functioning both as sincere advice and as a shield against responsibility for bad tips.",
    eli: "A warning that means look it up yourself, because if you lose money it is not my fault.",
    org: "Standard on crypto forums and Twitter by 2017, borrowed from earlier retail-investing communities.",
    ex: ["Not financial advice, DYOR.", "DYOR is doing a great deal of work in that thread."],
    rel: ["rug-pull", "hodl", "degen"], tags: ["disclaimer", "investing"],
  },
  {
    slug: "gm", term: "gm", pron: "jee-EM", pos: "interjection", cat: "web3",
    year: 2021, pop: 54, trend: -5, status: "niche",
    def: "\"Good morning\": a greeting posted regardless of local time, used in crypto communities as a low-effort signal of continued presence and optimism.",
    eli: "Saying good morning online to your community, even at midnight, just to show you are still around.",
    org: "Became ritual on crypto Twitter and Discord around 2021, when constant cheerful posting doubled as proof a project was still alive.",
    ex: ["gm to everyone still building.", "Four hundred replies, all of them gm."],
    rel: ["memecoin", "degen", "hodl"], tags: ["greeting", "community", "twitter"],
  },
  {
    slug: "hodl", term: "HODL", pron: "HOD-ul", pos: "verb", cat: "web3",
    year: 2013, pop: 66, trend: -4, status: "classic",
    def: "To keep holding an asset through severe price falls rather than selling. Backronymed as \"hold on for dear life\".",
    eli: "Refusing to sell something even when its price crashes, because you believe it will go back up.",
    org: "A misspelling of \"holding\" in a 2013 Bitcointalk forum post written by someone who admitted they were drunk. The typo became doctrine.",
    ex: ["Down 60 percent and still hodling.", "The whole strategy is hodl and hope."],
    rel: ["diamond-hands", "degen", "dyor"], tags: ["bitcoin", "trading", "forums"],
  },
  {
    slug: "memecoin", term: "Memecoin", pron: "MEEM-koyn", pos: "noun", cat: "web3",
    year: 2013, pop: 72, trend: 9, status: "mainstream",
    def: "A cryptocurrency with no stated utility, whose value depends entirely on attention and community momentum. Honest about being a bet on virality.",
    eli: "A coin created as a joke that is worth something only while lots of people find the joke funny.",
    org: "Dogecoin began as satire in 2013 and unexpectedly persisted. Cheap token creation after 2021 turned the category into a permanent feature of the market.",
    ex: ["The memecoin outperformed the serious project, as usual.", "Every cycle produces a memecoin nobody can explain later."],
    rel: ["degen", "rug-pull", "gm"], tags: ["tokens", "speculation", "dogecoin"],
  },
  {
    slug: "rug-pull", term: "Rug pull", pron: "rug pool", pos: "noun", cat: "web3",
    year: 2020, pop: 68, trend: 5, status: "mainstream",
    def: "A scam in which the creators of a token or project withdraw the pooled funds and disappear, leaving holders with something worthless.",
    eli: "When the people who made a coin take everyone's money and vanish, so what you bought is suddenly worth nothing.",
    org: "From the phrase \"pull the rug out\", standard vocabulary by 2020 as automated token launches made the manoeuvre trivially easy to execute.",
    ex: ["Liquidity was gone in four minutes. Textbook rug pull.", "Anonymous team, locked comments, no audit. It was always a rug pull."],
    rel: ["dyor", "memecoin", "degen"], tags: ["scams", "risk", "tokens"],
  },
  {
    slug: "nft", term: "NFT", pron: "en-ef-TEE", pos: "abbreviation", cat: "web3",
    year: 2017, pop: 68, trend: -14, status: "fading",
    def: "Non-fungible token: a blockchain record asserting ownership of a unique item. Usually the token points at an image stored elsewhere rather than containing it.",
    eli: "A blockchain receipt saying you own a particular digital item, usually a picture stored somewhere else.",
    org: "CryptoKitties in 2017 demonstrated the format and congested Ethereum doing it. The 2021 boom and subsequent collapse in trading volume were both extraordinary.",
    ex: ["The token survived; the server hosting the image did not.", "Trading volume fell by well over ninety percent from the peak."],
    rel: ["smart-contract", "memecoin", "floor-price"], tags: ["ethereum", "2021", "ownership"],
  },
  {
    slug: "smart-contract", term: "Smart contract", pron: "smart KON-trakt", pos: "noun", cat: "web3",
    year: 2015, pop: 52, trend: 0, status: "mainstream",
    def: "Code deployed to a blockchain that executes automatically when conditions are met. Neither smart nor a contract in the legal sense.",
    eli: "A program on a blockchain that runs by itself when certain conditions happen.",
    org: "The term was coined by Nick Szabo in 1994; Ethereum made it practical in 2015. Because deployed code is usually immutable, bugs are permanent and expensive.",
    ex: ["The bug was unfixable because the contract was immutable.", "Audits are the whole industry that immutability created."],
    rel: ["nft", "dao", "gas-fee"], tags: ["ethereum", "code", "automation"],
  },
  {
    slug: "gas-fee", term: "Gas fee", pron: "gas fee", pos: "noun", cat: "web3",
    year: 2015, pop: 49, trend: -3, status: "mainstream",
    def: "The cost of executing a transaction on a blockchain, priced by demand for block space rather than by the value being moved.",
    eli: "The fee you pay to make a blockchain transaction happen, which rises when the network is busy.",
    org: "Ethereum vocabulary from 2015, using gas as a metaphor for computational fuel. Fees exceeding the value of the transaction became a standard complaint during congestion.",
    ex: ["Ninety dollars in gas to move forty dollars of tokens.", "Layer twos exist largely because of this line item."],
    rel: ["smart-contract", "nft", "dao"], tags: ["ethereum", "fees", "congestion"],
  },
  {
    slug: "dao", term: "DAO", pron: "dow", pos: "abbreviation", cat: "web3",
    year: 2016, pop: 43, trend: -6, status: "fading",
    def: "Decentralised autonomous organisation: a group governed by token-weighted voting and smart contracts rather than by conventional corporate structure.",
    eli: "A group that makes decisions by token holders voting, with the rules enforced by code.",
    org: "The original DAO launched in 2016 and was drained of a third of its funds within weeks, causing the Ethereum hard fork. Governance in practice tends to concentrate among large holders.",
    ex: ["The DAO vote passed with four wallets deciding it.", "Token-weighted voting is one-dollar-one-vote, not one-person-one-vote."],
    rel: ["smart-contract", "whale", "gas-fee"], tags: ["governance", "ethereum", "2016"],
  },
  {
    slug: "whale", term: "Whale", pron: "wayl", pos: "noun", cat: "web3",
    year: 2013, pop: 47, trend: 1, status: "classic",
    def: "A holder large enough to move a market by trading. Whale watching, tracking large wallets on public ledgers, is a whole analytical subgenre.",
    eli: "Someone holding so much of something that their buying or selling changes the price.",
    org: "Casino vocabulary for a high-roller, adopted by crypto and by free-to-play game economics, where a small number of whales generate most revenue.",
    ex: ["One whale moved and the chart fell eleven percent.", "Public ledgers make whale watching possible in a way stock markets do not."],
    rel: ["dao", "pump-and-dump", "degen"], tags: ["markets", "casino", "wallets"],
  },
  {
    slug: "pump-and-dump", term: "Pump and dump", pron: "pump and dump", pos: "noun", cat: "web3",
    year: 2017, pop: 56, trend: 2, status: "classic",
    def: "Inflating an asset's price through coordinated promotion, then selling into the demand created. Illegal in regulated securities markets and endemic where enforcement is thin.",
    eli: "Hyping something up so the price rises, then selling it all before it crashes.",
    org: "A securities fraud pattern dating to the 1700s. Coordinated groups made it routine in crypto after 2017, sometimes advertising the schedule openly.",
    ex: ["Coordinated buy at eight, dumped by ten past.", "The pattern is centuries old; only the venue changed."],
    rel: ["rug-pull", "whale", "memecoin"], tags: ["fraud", "markets", "regulation"],
  },
  {
    slug: "wagmi", term: "WAGMI", pron: "WAG-mee", pos: "abbreviation", cat: "web3",
    year: 2021, pop: 38, trend: -9, status: "fading",
    def: "We are all going to make it. A solidarity chant during downturns. NGMI, not going to make it, is the dismissal aimed at those who sold or doubted.",
    eli: "A way of saying we will all succeed eventually, used to keep spirits up when prices fall.",
    org: "Crypto Twitter around 2021. The pairing with NGMI turned belief into a group identity marker, which is much of why the vocabulary spread so fast.",
    ex: ["Down eighty percent. WAGMI, apparently.", "NGMI was aimed at anyone who took profits."],
    rel: ["hodl", "gm", "diamond-hands"], tags: ["twitter", "community", "2021"],
  },
  {
    slug: "floor-price", term: "Floor price", pron: "flor prys", pos: "noun", cat: "web3",
    year: 2021, pop: 35, trend: -11, status: "fading",
    def: "The lowest asking price in a collection, used as the headline measure of its value despite being set by whoever is most desperate to sell.",
    eli: "The cheapest price anyone is currently asking for an item in a collection.",
    org: "Became the standard NFT valuation metric during the 2021 boom, largely because it was the easiest number to display. It is a poor proxy for what a collection is worth.",
    ex: ["Floor is down ninety-four percent from the peak.", "A floor set by one panicked seller is not a valuation."],
    rel: ["nft", "whale", "pump-and-dump"], tags: ["nft", "valuation", "markets"],
  },
  {
    slug: "seed-phrase", term: "Seed phrase", pron: "seed frayz", pos: "noun", cat: "web3",
    year: 2013, pop: 44, trend: 1, status: "mainstream",
    def: "A sequence of twelve or twenty-four words that regenerates a wallet's private keys. Anyone with the phrase has the funds, and losing it loses them permanently.",
    eli: "A list of words that is the only way back into your crypto wallet. Lose it and the money is gone forever.",
    org: "Standardised in 2013 as BIP-39, which made backups human-readable. It also made the single most effective scam in the space: asking people for the phrase.",
    ex: ["Nobody legitimate will ever ask for your seed phrase.", "Written on paper in a safe, or it is not backed up."],
    rel: ["cold-storage", "rug-pull", "hodl"], tags: ["security", "wallets", "scams"],
  },
  {
    slug: "cold-storage", term: "Cold storage", pron: "kohld STOR-ij", pos: "noun", cat: "web3",
    year: 2013, pop: 36, trend: 0, status: "mainstream",
    def: "Keeping keys on a device never connected to the internet. Slower to use and dramatically harder to steal from remotely.",
    eli: "Storing crypto keys on something not connected to the internet, so hackers cannot reach them.",
    org: "Standard practice after a series of exchange collapses demonstrated that leaving assets with a custodian carried its own risk. Not your keys, not your coins is the associated slogan.",
    ex: ["Moved it to cold storage after the third exchange failure.", "Convenience and custody are the trade-off."],
    rel: ["seed-phrase", "hodl", "whale"], tags: ["security", "custody", "practice"],
  },
  {
    slug: "airdrop", term: "Airdrop", pron: "AIR-drop", pos: "noun", cat: "web3",
    year: 2017, pop: 39, trend: -2, status: "mainstream",
    def: "A free distribution of tokens to existing wallets, used for marketing or to reward early users. Airdrop farming is the practice of gaming eligibility across many wallets.",
    eli: "Free tokens given out to wallets, often to promote a new project.",
    org: "Became common in 2017 and industrialised afterwards, with farmers operating thousands of wallets to qualify. Several projects now design specifically against this.",
    ex: ["Farmed the airdrop across four hundred wallets.", "Free tokens are a customer acquisition cost with extra steps."],
    rel: ["memecoin", "degen", "whale"], tags: ["marketing", "tokens", "farming"],
  },
  {
    slug: "staking", term: "Staking", pron: "STAY-king", pos: "noun", cat: "web3",
    year: 2020, pop: 41, trend: 0, status: "mainstream",
    def: "Locking tokens to help secure a proof-of-stake network in return for rewards. Distinct from lending schemes that borrow the vocabulary to sound safer.",
    eli: "Locking up your tokens to help run the network, and being paid for it.",
    org: "Central to proof-of-stake designs and mainstream after Ethereum's 2022 transition. Several collapsed platforms marketed lending as staking, which regulators later treated as a material misstatement.",
    ex: ["Staking rewards are not interest, whatever the app says.", "The word got borrowed by products that were doing something else entirely."],
    rel: ["smart-contract", "gas-fee", "dao"], tags: ["ethereum", "yield", "regulation"],
  },
  {
    slug: "ape-in", term: "Ape in", pron: "AYP in", pos: "verb", cat: "web3",
    year: 2020, pop: 35, trend: -4, status: "niche",
    def: "To buy heavily on impulse without research, self-consciously named as unwise. The opposite of the advice contained in DYOR.",
    eli: "Buying a lot of something quickly without checking whether it is a good idea.",
    org: "Crypto and meme-stock communities around 2020, where apes also became a collective self-description. The knowing recklessness is part of the identity.",
    ex: ["Aped in at the top, as tradition demands.", "The word admits the mistake in advance."],
    rel: ["degen", "dyor", "memecoin"], tags: ["trading", "risk", "identity"],
  },
  {
    slug: "moon", term: "Moon", pron: "moon", pos: "verb", cat: "web3",
    year: 2017, pop: 42, trend: -3, status: "classic",
    def: "To rise sharply in price. When moon, asked with practised impatience, is the standard question in any project's chat during a downturn.",
    eli: "When a price goes up very fast. Asking when moon means asking when you will get rich.",
    org: "From to the moon, in circulation on Bitcoin forums well before 2017. It functions as a shibboleth: asking it marks you as a particular kind of holder.",
    ex: ["ser when moon", "Three years of when moon and no moon."],
    rel: ["hodl", "wagmi", "memecoin"], tags: ["price", "community", "humour"],
  },
  {
    slug: "layer-two", term: "Layer 2", pron: "LAY-ur too", pos: "noun", cat: "web3",
    year: 2021, pop: 33, trend: 3, status: "niche",
    def: "A secondary network that batches transactions and settles them on a main chain, reducing cost and congestion at the price of added complexity.",
    eli: "A faster, cheaper network built on top of a slower one, which sends the results back to the main chain.",
    org: "Became the dominant scaling approach after 2021, when Ethereum gas fees made ordinary transactions uneconomic. The trade-offs between designs are still actively argued.",
    ex: ["Moved to a layer two and the fee dropped by two orders of magnitude.", "Scaling by moving the work somewhere else and settling later."],
    rel: ["gas-fee", "smart-contract", "staking"], tags: ["scaling", "ethereum", "infrastructure"],
  },
  {
    slug: "not-your-keys", term: "Not your keys, not your coins", pron: "not yor keez", pos: "phrase", cat: "web3",
    year: 2016, pop: 40, trend: 2, status: "classic",
    def: "A warning that assets held by an exchange belong to the exchange in practice, whatever the balance screen says.",
    eli: "If someone else controls your crypto keys, the crypto is not really yours.",
    org: "A long-standing slogan attributed to Andreas Antonopoulos, repeatedly vindicated by exchange failures from Mt. Gox onward, and most spectacularly in 2022.",
    ex: ["Everyone repeats it and most people still use an exchange.", "Custody risk is not a theoretical concern."],
    rel: ["cold-storage", "seed-phrase", "rug-pull"], tags: ["custody", "risk", "slogan"],
  },
];
