import type { RawTerm } from "../types";

export const workTerms: RawTerm[] = [
  {
    slug: "act-your-wage", term: "Act your wage", pron: "akt yor wayj", pos: "phrase", cat: "work",
    year: 2022, pop: 62, trend: 4, status: "mainstream",
    def: "An instruction to match your effort to your pay, refusing responsibilities that belong to a more senior and better-paid role.",
    eli: "Only doing the amount of work you are actually being paid for.",
    org: "A pun on \"act your age\" that spread through workplace TikTok in 2022 alongside quiet quitting, framing the same idea as arithmetic rather than rebellion.",
    ex: ["They want director output on a coordinator salary. Act your wage.", "Acting my wage has been excellent for my sleep."],
    rel: ["quiet-quitting", "hustle-culture", "rto"], tags: ["labour", "pay", "boundaries"],
  },
  {
    slug: "coffee-badging", term: "Coffee badging", pron: "KOF-ee BAJ-ing", pos: "noun", cat: "work",
    year: 2023, pop: 51, trend: 17, status: "rising",
    def: "Appearing at the office briefly enough to register attendance, then leaving to work elsewhere. A direct response to presence-based policies.",
    eli: "Going into the office just long enough to be seen and swipe your card, then going home to work.",
    org: "Named in workplace surveys around 2023 as return-to-office rules began measuring badge swipes rather than output.",
    ex: ["Badge in, one coffee, gone by ten. Coffee badging.", "Attendance is up and nobody is in the building after eleven."],
    rel: ["rto", "quiet-quitting", "act-your-wage"], tags: ["remote-work", "office", "metrics"],
  },
  {
    slug: "ghost-job", term: "Ghost job", pron: "gohst job", pos: "noun", cat: "work",
    year: 2022, pop: 58, trend: 22, status: "rising",
    def: "A job advertisement for a role the employer has no intention of filling, posted to collect applications, signal growth or keep a talent pipeline warm.",
    eli: "A job advert for a job that does not really exist, so nobody who applies will ever get hired.",
    org: "Named around 2022 as candidates compared notes on postings that stayed open for months and never closed with a hire.",
    ex: ["Reposted every 30 days for a year. Ghost job.", "Forty applications, six ghost jobs, two real interviews."],
    rel: ["rage-applying", "rto", "quiet-quitting"], tags: ["hiring", "job-search"],
  },
  {
    slug: "hustle-culture", term: "Hustle culture", pron: "HUS-ul KUL-chur", pos: "noun", cat: "work",
    year: 2015, pop: 66, trend: -9, status: "fading",
    def: "The belief that constant work is a moral virtue and that rest must be earned. Promoted heavily online in the 2010s and widely rejected since.",
    eli: "The idea that you should always be working and that resting means you are lazy.",
    org: "Built through startup blogging and motivational Instagram from around 2015, then criticised sharply after 2020 as burnout research caught up with it.",
    ex: ["Hustle culture rebranded exhaustion as ambition.", "The five a.m. routine posts are hustle culture in a new font."],
    rel: ["grind", "quiet-quitting", "loud-budgeting"], tags: ["burnout", "startups", "instagram"],
  },
  {
    slug: "loud-budgeting", term: "Loud budgeting", pron: "lowd BUJ-it-ing", pos: "noun", cat: "work",
    year: 2024, pop: 60, trend: 12, status: "rising",
    def: "Openly stating that you are declining something because of cost, removing the social pressure to pretend money was not the reason.",
    eli: "Saying out loud that something is too expensive instead of making up an excuse for not going.",
    org: "Coined by comedian Lukas Battle on TikTok in January 2024 and adopted quickly as a counterweight to years of quiet aspirational spending.",
    ex: ["I am not skipping dinner because I am busy. Loud budgeting.", "Loud budgeting made the group chat honest for the first time."],
    rel: ["deinfluencing", "hustle-culture", "act-your-wage"], tags: ["money", "honesty", "tiktok"],
  },
  {
    slug: "quiet-quitting", term: "Quiet quitting", pron: "KWY-ut KWIT-ing", pos: "noun", cat: "work",
    year: 2022, pop: 75, trend: -11, status: "fading",
    def: "Doing exactly what a job description requires and no more. Despite the name it involves no resignation, only the withdrawal of unpaid extra effort.",
    eli: "Doing your job properly but stopping the extra unpaid work, without actually leaving.",
    org: "Went viral on TikTok in mid-2022. Critics noted the phrase mislabels ordinary boundary-setting as a form of quitting.",
    ex: ["Quiet quitting is just the contract, read out loud.", "The article called it quiet quitting. My colleague called it Tuesday."],
    rel: ["act-your-wage", "hustle-culture", "coffee-badging"], tags: ["labour", "boundaries", "tiktok"],
  },
  {
    slug: "rage-applying", term: "Rage applying", pron: "rayj uh-PLY-ing", pos: "noun", cat: "work",
    year: 2023, pop: 55, trend: 8, status: "niche",
    def: "Sending a burst of job applications immediately after a frustrating incident at work, driven by anger rather than by a considered plan.",
    eli: "Applying for lots of new jobs in one go right after something at work made you furious.",
    org: "Named on TikTok in early 2023, alongside a wave of vocabulary describing job-hunting as an emotional response to management.",
    ex: ["One meeting, eleven applications. Rage applying works sometimes.", "She rage applied on Friday and had an offer by the end of the month."],
    rel: ["ghost-job", "quiet-quitting", "act-your-wage"], tags: ["job-search", "emotion"],
  },
  {
    slug: "rto", term: "RTO", pron: "ar-tee-OH", pos: "abbreviation", cat: "work",
    year: 2022, pop: 69, trend: 13, status: "rising",
    def: "Return to office: a mandate requiring staff to work on site for a set number of days. Frequently described by employees as restructuring conducted without redundancy costs.",
    eli: "A rule saying workers have to come back to the office instead of working from home.",
    org: "Entered general vocabulary from 2022 onward as pandemic remote arrangements were rolled back, usually accompanied by claims about collaboration.",
    ex: ["Three-day RTO announced by email, which everyone read from home.", "RTO attrition is a strategy, not a side effect."],
    rel: ["coffee-badging", "act-your-wage", "quiet-quitting"], tags: ["labour", "remote-work", "policy"],
  },
  {
    slug: "girl-math", term: "Girl math", pron: "gurl math", pos: "noun", cat: "work",
    year: 2023, pop: 57, trend: -8, status: "fading",
    def: "Deliberately absurd reasoning that reclassifies spending as saving: cash is free, a return is income, cost per wear approaches zero.",
    eli: "Joke reasoning that makes spending money sound like saving it.",
    org: "A New Zealand radio segment in 2023 that spread on TikTok. Boy math followed as a mirror format. Both were criticised for the gendered framing of ordinary rationalisation.",
    ex: ["Paid cash, so it was free. Girl math.", "The joke is that everyone does this and only some of it gets named."],
    rel: ["loud-budgeting", "doom-spending", "dupe"], tags: ["money", "tiktok", "humour"],
  },
  {
    slug: "great-resignation", term: "Great Resignation", pron: "grayt rez-ig-NAY-shun", pos: "noun", cat: "work",
    year: 2021, pop: 55, trend: -7, status: "fading",
    def: "The period from 2021 when workers left jobs at unusually high rates, driven by pandemic reassessment, wage competition and delayed moves finally being made.",
    eli: "The time after the pandemic when huge numbers of people quit their jobs at once.",
    org: "Coined by organisational psychologist Anthony Klotz in May 2021. Later analysis showed much of it was pent-up turnover concentrated in lower-paid sectors rather than a general revolt.",
    ex: ["The Great Resignation was mostly hospitality and retail.", "Quit rates returned to trend within about two years."],
    rel: ["quiet-quitting", "rage-applying", "rto"], tags: ["labour", "pandemic", "economics"],
  },
  {
    slug: "quiet-firing", term: "Quiet firing", pron: "KWY-ut FY-ur-ing", pos: "noun", cat: "work",
    year: 2022, pop: 48, trend: 5, status: "mainstream",
    def: "Making conditions unpleasant enough that an employee leaves voluntarily, avoiding redundancy costs and process. The employer counterpart to quiet quitting.",
    eli: "Making someone's job so bad that they quit, instead of firing them.",
    org: "Named in 2022 as an explicit response to quiet quitting discourse, pointing out that the same withdrawal of effort runs in both directions.",
    ex: ["No projects, no reviews, no meetings. Quiet firing.", "Constructive dismissal is the legal name for the extreme version."],
    rel: ["quiet-quitting", "rto", "ghost-job"], tags: ["labour", "management", "2022"],
  },
  {
    slug: "productivity-theatre", term: "Productivity theatre", pron: "pro-duk-TIV-it-ee THEE-uh-tur", pos: "noun", cat: "work",
    year: 2021, pop: 46, trend: 6, status: "rising",
    def: "Visible activity performed to appear busy rather than to accomplish anything: mouse jigglers, green status dots, replies sent at conspicuous hours.",
    eli: "Doing things that make you look busy rather than things that actually get work done.",
    org: "Named as remote work made presence unobservable and employers reached for monitoring software. Mouse-jiggler sales are a genuinely tracked economic indicator.",
    ex: ["Green dot at 11pm is productivity theatre.", "Monitoring produces theatre; it does not produce output."],
    rel: ["coffee-badging", "rto", "quiet-quitting"], tags: ["remote-work", "monitoring", "performance"],
  },
  {
    slug: "career-cushioning", term: "Career cushioning", pron: "kuh-REER KUSH-un-ing", pos: "noun", cat: "work",
    year: 2022, pop: 41, trend: 4, status: "mainstream",
    def: "Quietly maintaining employability while employed: updating a profile, taking calls, keeping a network warm, without actively job hunting.",
    eli: "Keeping your options open at work in case you lose your job.",
    org: "Named in 2022 during a wave of technology redundancies, borrowing the cushioning metaphor from dating vocabulary. It describes prudence rather than disloyalty.",
    ex: ["Everyone started career cushioning after the third round of cuts.", "It is insurance, and employers read it as betrayal."],
    rel: ["rage-applying", "ghost-job", "quiet-firing"], tags: ["labour", "job-search", "security"],
  },
  {
    slug: "side-hustle", term: "Side hustle", pron: "syde HUS-ul", pos: "noun", cat: "work",
    year: 2014, pop: 64, trend: -5, status: "mainstream",
    def: "Income-generating work done alongside a main job. Framed as entrepreneurial ambition, and frequently a response to wages not covering costs.",
    eli: "A second job or small business you run alongside your main job.",
    org: "Older American vocabulary revived by 2010s gig platforms and hustle-culture blogging. Critics note the framing turns a wage problem into a personal-initiative story.",
    ex: ["Three side hustles and still checking the rent date.", "It is a second job with better branding."],
    rel: ["hustle-culture", "creator-economy", "fire-movement"], tags: ["gig-economy", "money", "labour"],
  },
  {
    slug: "fire-movement", term: "FIRE", pron: "FY-ur", pos: "abbreviation", cat: "work",
    year: 2011, pop: 44, trend: 1, status: "mainstream",
    def: "Financial independence, retire early: saving an extreme share of income to stop working decades ahead of schedule. LeanFIRE and CoastFIRE are the softer variants.",
    eli: "Saving a huge amount of your income so you can stop working long before retirement age.",
    org: "Built on Vicki Robin and Joe Dominguez's 1992 book Your Money or Your Life, formalised on blogs and Reddit from around 2011. The maths depends heavily on income level.",
    ex: ["Saving seventy percent of income to reach FIRE by forty.", "CoastFIRE is the version most people can actually reach."],
    rel: ["side-hustle", "loud-budgeting", "soft-life"], tags: ["money", "reddit", "retirement"],
  },
  {
    slug: "dupe", term: "Dupe", pron: "dyoop", pos: "noun", cat: "work",
    year: 2022, pop: 59, trend: 7, status: "rising",
    def: "A cheaper product closely resembling an expensive one. Distinct from a counterfeit, since a dupe copies the design without claiming to be the brand.",
    eli: "A cheap version of an expensive product that looks and works almost the same.",
    org: "Beauty vocabulary that TikTok generalised after 2022. Retailers now market dupes openly, which has produced a steady stream of design-right litigation.",
    ex: ["The eight-pound dupe outperformed the fifty-pound original.", "A dupe copies the design, a fake copies the label."],
    rel: ["deinfluencing", "girl-math", "loud-budgeting"], tags: ["shopping", "tiktok", "value"],
  },
  {
    slug: "doom-spending", term: "Doom spending", pron: "doom SPEND-ing", pos: "noun", cat: "work",
    year: 2023, pop: 45, trend: 9, status: "rising",
    def: "Spending money as a response to pessimism about the future, on the reasoning that saving toward goals which feel unreachable is pointless.",
    eli: "Spending money because the future feels hopeless anyway, so saving seems pointless.",
    org: "Named around 2023 alongside doomscrolling. Surveys consistently link it to a belief that conventional milestones such as home ownership are out of reach.",
    ex: ["Doom spending is a rational response to an irrational housing market.", "It is not bad budgeting, it is a forecast."],
    rel: ["loud-budgeting", "girl-math", "soft-life"], tags: ["money", "pessimism", "2023"],
  },
  {
    slug: "bare-minimum-monday", term: "Bare minimum Monday", pron: "bair MIN-im-um MUN-day", pos: "noun", cat: "work",
    year: 2023, pop: 39, trend: -4, status: "mainstream",
    def: "Deliberately starting the week with low-demand tasks, on the argument that a gentle Monday produces a more productive rest of the week.",
    eli: "Doing only easy work on Mondays so the week starts calmly.",
    org: "Coined by Marisa Jo Mayes on TikTok in 2023, describing her own practice after burnout. It spread as a scheduling idea rather than as an act of resistance.",
    ex: ["Bare minimum Monday, catastrophic Thursday.", "It is a workload distribution argument, not a laziness one."],
    rel: ["quiet-quitting", "act-your-wage", "productivity-theatre"], tags: ["scheduling", "burnout", "tiktok"],
  },
  {
    slug: "lazy-girl-job", term: "Lazy girl job", pron: "LAY-zee gurl job", pos: "noun", cat: "work",
    year: 2023, pop: 42, trend: -6, status: "fading",
    def: "A comfortable, predictable role with decent pay and no expectation of overwork. The name is ironic: such jobs are neither lazy nor easy to get.",
    eli: "A steady job that pays reasonably and does not take over your life.",
    org: "Coined by Gabrielle Judge on TikTok in 2023 as an explicit rejection of girlboss ambition. Criticised for framing wanting reasonable hours as laziness.",
    ex: ["The lazy girl job is just a job with boundaries.", "It got named because it had become unusual."],
    rel: ["act-your-wage", "soft-life", "quiet-quitting"], tags: ["labour", "tiktok", "boundaries"],
  },
  {
    slug: "shrinkflation", term: "Shrinkflation", pron: "SHRINK-flay-shun", pos: "noun", cat: "work",
    year: 2009, pop: 63, trend: 8, status: "rising",
    def: "Reducing product size while holding the price, so an increase is hidden rather than announced. Skimpflation is the version that cuts quality instead.",
    eli: "When a packet gets smaller but costs the same, so the price rise is hidden.",
    org: "Credited to economist Pippa Malmgren around 2009 and widely used after 2021. Several countries now require unit pricing on shelf labels specifically to make it visible.",
    ex: ["Same box, two fewer biscuits, same price.", "Unit pricing exists to defeat exactly this."],
    rel: ["dupe", "doom-spending", "loud-budgeting"], tags: ["economics", "retail", "prices"],
  },
  {
    slug: "presenteeism", term: "Presenteeism", pron: "prez-un-TEE-iz-um", pos: "noun", cat: "work",
    year: 2010, pop: 44, trend: 4, status: "mainstream",
    def: "Being present without being effective, whether through illness or through the belief that visible hours are what is actually measured.",
    eli: "Being at work when you are not really able to work, because being seen matters more.",
    org: "Occupational health vocabulary from the 2000s. Research consistently finds it costs more than absenteeism, which is the metric organisations actually track.",
    ex: ["Nine hours at the desk, ninety minutes of work.", "The thing being measured is attendance, so attendance is what you get."],
    rel: ["productivity-theatre", "coffee-badging", "rto"], tags: ["health", "management", "measurement"],
  },
  {
    slug: "boreout", term: "Boreout", pron: "BOR-owt", pos: "noun", cat: "work",
    year: 2007, pop: 31, trend: 5, status: "niche",
    def: "Chronic disengagement caused by work that is too undemanding, producing symptoms that resemble burnout despite the opposite cause.",
    eli: "Feeling exhausted and miserable at work because there is nothing meaningful to do.",
    org: "Named in a 2007 book by Peter Werder and Philippe Rothlin. Less studied than burnout, and frequently misdiagnosed as it, since the presentation is similar.",
    ex: ["Not burnout, boreout. Three tasks a week and none of them matter.", "Underload is a workload problem too."],
    rel: ["quiet-quitting", "ghost-job", "productivity-theatre"], tags: ["burnout", "psychology", "engagement"],
  },
  {
    slug: "overemployment", term: "Overemployment", pron: "OH-vur-em-ploy-munt", pos: "noun", cat: "work",
    year: 2021, pop: 37, trend: 6, status: "rising",
    def: "Holding two or more full-time remote jobs simultaneously without informing either employer. Usually a contractual breach rather than an illegal act.",
    eli: "Secretly working two full-time jobs at once from home.",
    org: "Named around 2021 as remote work made overlapping schedules feasible. Dedicated communities share tactics; employers responded with activity monitoring and clearer contract terms.",
    ex: ["Two salaries, four standups, one calendar.", "It is a contract question before it is an ethics one."],
    rel: ["productivity-theatre", "side-hustle", "career-cushioning"], tags: ["remote-work", "contracts", "money"],
  },
  {
    slug: "burnout", term: "Burnout", pron: "BURN-owt", pos: "noun", cat: "work",
    year: 1974, pop: 78, trend: 5, status: "mainstream",
    def: "A state of chronic physical and emotional exhaustion caused by prolonged workplace stress, formally recognised by the World Health Organization as an occupational phenomenon rather than a medical condition.",
    eli: "Feeling completely worn out and empty from work stress that has built up over a long time.",
    org: "Coined by psychologist Herbert Freudenberger in 1974 to describe what he observed in health workers, and given a formal definition by the World Health Organization in 2019.",
    ex: ["Full burnout by March, and the year had barely started.", "Burnout is a workplace problem, not a personal failing, according to the official definition."],
    rel: ["boreout", "quiet-quitting", "presenteeism"], tags: ["mental-health", "workplace", "who"],
  },
  {
    slug: "imposter-syndrome", term: "Imposter syndrome", pron: "im-POS-tur SIN-drohm", pos: "noun", cat: "work",
    year: 1978, pop: 71, trend: 3, status: "mainstream",
    def: "Persistent doubt about one's own competence despite clear external evidence of success, accompanied by fear of being exposed as a fraud.",
    eli: "Feeling like a fake at your job even when you are actually doing well, and worrying people will find out.",
    org: "Identified in a 1978 psychology paper studying high-achieving women, and generalised in internet workplace culture as a widely shared, named experience rather than a rare condition.",
    ex: ["Promoted twice and still convinced it was a mistake. Imposter syndrome.", "Naming it as imposter syndrome at least makes it easier to talk about."],
    rel: ["burnout", "career-cushioning", "productivity-theatre"], tags: ["psychology", "workplace", "confidence"],
  },
  {
    slug: "wfh", term: "WFH", pron: "dub-ul-yoo-ef-AYCH", pos: "abbreviation", cat: "work",
    year: 1995, pop: 66, trend: -2, status: "classic",
    def: "Working from home, as opposed to a commuted office setting, in wide casual use since long before it became the default for millions during the pandemic.",
    eli: "Short for working from home instead of going into an office.",
    org: "In occasional use since the mid-1990s, the abbreviation became universal vocabulary in 2020 once remote work shifted from an occasional privilege to a mass default.",
    ex: ["WFH Fridays are the one policy nobody complains about.", "Still WFH, four years and counting."],
    rel: ["hybrid-work", "rto", "digital-nomad"], tags: ["remote-work", "abbreviation", "classic"],
  },
  {
    slug: "hybrid-work", term: "Hybrid work", pron: "HY-brid wurk", pos: "noun", cat: "work",
    year: 2021, pop: 58, trend: 4, status: "mainstream",
    def: "A work arrangement splitting time between an office and a remote location on a set or flexible schedule, positioned as a compromise between full remote and full office mandates.",
    eli: "A work setup where you split your time between the office and home instead of doing either one fully.",
    org: "Formalised as a named policy category from 2021 onward, as employers negotiated a middle ground between pandemic-era full remote work and pre-pandemic full office attendance.",
    ex: ["Hybrid work means three specific days in the office, chosen by nobody who has to commute.", "Hybrid work satisfies almost no one completely, which may be the point."],
    rel: ["wfh", "rto", "coffee-badging"], tags: ["remote-work", "policy", "2020s"],
  },
  {
    slug: "toxic-positivity", term: "Toxic positivity", pron: "TOK-sik poz-i-TIV-it-ee", pos: "noun", cat: "work",
    year: 2019, pop: 55, trend: 4, status: "mainstream",
    def: "The pressure to maintain a relentlessly upbeat attitude in the workplace regardless of genuine circumstances, which dismisses legitimate concerns rather than addressing them.",
    eli: "Being forced to act happy and positive at work all the time, even when things are genuinely going badly, instead of actually fixing the problem.",
    org: "Named in workplace psychology writing around 2019, describing a culture where relentless positivity becomes its own form of dismissal rather than genuine support.",
    ex: ["Layoffs announced as an exciting new chapter is toxic positivity in its purest form.", "Toxic positivity treats every complaint as a mindset problem."],
    rel: ["productivity-theatre", "burnout", "quiet-quitting"], tags: ["culture", "psychology", "criticism"],
  },
  {
    slug: "sunday-scaries", term: "Sunday scaries", pron: "SUN-day SKAIR-eez", pos: "noun", cat: "work",
    year: 2016, pop: 63, trend: 2, status: "mainstream",
    def: "Rising anxiety experienced on Sunday evenings in anticipation of the coming work week, sitting somewhere between mild dread and genuine distress.",
    eli: "The anxious, dreading feeling you get on Sunday night knowing work starts again the next day.",
    org: "Named around 2016 as workplace wellbeing writing began giving specific, shareable names to widely felt but previously unlabelled patterns of low-grade dread.",
    ex: ["Sunday scaries hit right on schedule at six pm.", "The Sunday scaries got worse once the commute got longer."],
    rel: ["burnout", "wfh", "boreout"], tags: ["anxiety", "workplace", "wellbeing"],
  },
  {
    slug: "zoom-fatigue", term: "Zoom fatigue", pron: "zoom fuh-TEEG", pos: "noun", cat: "work",
    year: 2020, pop: 60, trend: -3, status: "classic",
    def: "Exhaustion caused by back-to-back video calls, attributed partly to the unnatural cognitive load of maintaining eye contact with a grid of faces, including one's own.",
    eli: "Feeling drained from too many video calls in a row, partly because staring at faces on a screen, including your own, is more tiring than it seems.",
    org: "Named and studied seriously from 2020 onward once video calls became the default meeting format, with researchers specifically examining the effect of constantly seeing your own face.",
    ex: ["Six back-to-back calls and the zoom fatigue is real.", "Turning the camera off is the standard zoom fatigue defence."],
    rel: ["wfh", "hybrid-work", "burnout"], tags: ["remote-work", "wellbeing", "2020"],
  },
  {
    slug: "loud-quitting", term: "Loud quitting", pron: "lowd KWIT-ing", pos: "noun", cat: "work",
    year: 2023, pop: 47, trend: 6, status: "rising",
    def: "Actively expressing dissatisfaction and disengagement at work in a visible, public way, positioned as the confrontational counterpart to quiet quitting's withdrawal.",
    eli: "Being openly and loudly unhappy and checked out at work, instead of quietly doing the bare minimum.",
    org: "Named by workplace research firm Gallup in 2023 as a distinct category from quiet quitting, describing employees who actively undermine morale rather than passively disengage.",
    ex: ["Quiet quitting was last year, this team has moved on to loud quitting.", "Loud quitting is a lot harder for management to ignore."],
    rel: ["quiet-quitting", "act-your-wage", "great-resignation"], tags: ["labour", "2023", "gallup"],
  },
  {
    slug: "gig-economy", term: "Gig economy", pron: "gig ee-KON-uh-mee", pos: "noun", cat: "work",
    year: 2009, pop: 65, trend: 1, status: "classic",
    def: "A labour market built on short-term, freelance or app-mediated tasks rather than stable ongoing employment, offering flexibility at the cost of benefits and job security.",
    eli: "Work made up of lots of short jobs or gigs, often booked through an app, instead of one steady full-time job.",
    org: "Named around 2009 as ride-hailing and delivery apps built entire business models on independent contractors, generalising an older musicians' term for a single paid engagement.",
    ex: ["The gig economy promised flexibility and mostly delivered unpredictability.", "Multiple gig economy apps just to cover one month's rent."],
    rel: ["side-hustle", "overemployment", "digital-nomad"], tags: ["labour", "apps", "economics"],
  },
  {
    slug: "glass-ceiling", term: "Glass ceiling", pron: "glas SEEL-ing", pos: "noun", cat: "work",
    year: 1978, pop: 62, trend: 0, status: "classic",
    def: "An invisible but real barrier preventing women and other underrepresented groups from advancing beyond a certain level in an organisation, despite equal or superior qualifications.",
    eli: "An invisible barrier that stops certain groups of people, especially women, from being promoted past a certain point at work, even when they deserve it.",
    org: "The metaphor entered wide use through workplace equity writing in the late 1970s and 1980s, becoming standard vocabulary for a well-documented, persistent pattern in corporate leadership data.",
    ex: ["The company's own diversity report shows the glass ceiling clearly in the numbers.", "Cracking the glass ceiling made headlines; the second and third cracks rarely do."],
    rel: ["glass-cliff", "burnout", "great-resignation"], tags: ["equity", "labour", "classic"],
  },
  {
    slug: "glass-cliff", term: "Glass cliff", pron: "glas klif", pos: "noun", cat: "work",
    year: 2005, pop: 42, trend: 3, status: "niche",
    def: "The pattern in which women and minority leaders are disproportionately promoted into precarious, high-risk leadership roles during a crisis, then blamed when the outcome is poor.",
    eli: "A pattern where underrepresented leaders get put in charge mainly during a crisis, when the job is riskiest and most likely to end badly through no fault of their own.",
    org: "Identified by researchers at the University of Exeter in 2005, who found that companies were statistically more likely to appoint women to leadership right before or during a downturn.",
    ex: ["Promoted the week before the layoffs. Textbook glass cliff.", "The glass cliff explains a pattern the glass ceiling metaphor alone missed."],
    rel: ["glass-ceiling", "burnout", "quiet-firing"], tags: ["equity", "research", "leadership"],
  },
  {
    slug: "digital-nomad", term: "Digital nomad", pron: "DIJ-it-ul NOH-mad", pos: "noun", cat: "work",
    year: 2007, pop: 61, trend: 3, status: "mainstream",
    def: "Someone who works remotely while travelling continuously rather than maintaining a fixed home base, often moving between countries offering favourable visas or lower living costs.",
    eli: "Someone who works online while constantly travelling instead of living in one place.",
    org: "Named in a 2007 book of the same title, the lifestyle remained a minority pursuit until remote work became widespread after 2020, prompting many countries to create dedicated digital nomad visas.",
    ex: ["Digital nomad visas turned into a genuine competitive category between countries.", "Being a digital nomad mostly means a great view and a mediocre internet connection."],
    rel: ["wfh", "gig-economy", "hybrid-work"], tags: ["remote-work", "lifestyle", "travel"],
  },
];
